### ISSUE TITLE
Verify Sleep Works with Async/Await Node.js

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1002]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-34?filter=allopenissues

This is complete when:

- [x] Async/Await Node.js function is tested is verified to allow for sleep

**Comment by c3bryant** [comment]
Sleep by itself in an async loop delays all requests, which all fire off at the same time after the sleep duration.

Adjusting the sleep time by means of an incremental multiplier value is providing the results we are looking for, which we can leverage for throttling.
