### ISSUE TITLE
Verify Parking Lot API

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1005]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-84

This is complete when:

- [x] The following API for the following parking lots is confirmed to be correct and accessible
- [x] The following lots display data on the card

,
    {
        "LocationId":"P782",
        "LocationName":"Athena Circle & Athena Way",
        "LocationContext":"Lot 782",
        "LocationEndpoint":"https://api.streetsoncloud.com/pl1/location-info",
        "LocationProvider":"Parking Logix",
        "AvailabilityType":"aggregate",
        "LocationSpotTypes":[
            "S"
        ]
    },
    {
        "LocationId":"P386",
        "LocationName":"Gliderport",
        "LocationContext":"Lot 386",
        "LocationEndpoint":"https://api.streetsoncloud.com/pl1/location-info",
        "LocationProvider":"Parking Logix",
        "AvailabilityType":"aggregate",
        "LocationSpotTypes":[
            "S"
        ]
    },
    {
        "LocationId":"P704",
        "LocationName":"P704",
        "LocationContext":"Gliderport",
        "LocationEndpoint":"https://api.streetsoncloud.com/pl1/location-info",
        "LocationProvider":"Parking Logix",
        "AvailabilityType":"aggregate",
        "LocationSpotTypes":[
            "S"
        ]
    },
    {
        "LocationId":"P705",
        "LocationName":"P705",
        "LocationContext":"Gliderport",
        "LocationEndpoint":"https://api.streetsoncloud.com/pl1/location-info",
        "LocationProvider":"Parking Logix",
        "AvailabilityType":"aggregate",
        "LocationSpotTypes":[
            "S"
        ]
    }

**Comment by p8gonzal** [comment]
This has been verified within parking_service.dart pulling from endpoint:       "https://mobile.ucsd.edu/replatform/v1/qa/webview/parking/parking_lots.json";
