### ISSUE TITLE
Weather Card: Error seen loading weather data for some users

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1009]
Time Entry: MA-34

This is done when:
- [ ] The weather card loads weather data as expected, without returning an error response to users

<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/27b6495a-b06c-4e40-81cb-2bce8cfba7c7" width="300">

**Comment by c3bryant** [comment]
The FetchCompactWeatherForecastService AWS API field weather.currently.visibility can now return a double rather than int, which is causing campus mobile to throw an `invalid data type` error.

Lambda update required:
- Lambda: [fetchWeatherForecastCompact](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/fetchWeatherForecastCompact?tab=configuration)
- Repo: https://sourcecode.ucsd.edu/projects/WTS/repos/weather-service-compact/browse
- Branch: `master`

Ready to deploy

**Comment by a6wu** [comment]
Deployed
