### ISSUE TITLE
Availability Card Location Selection

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1021]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-83

This is complete when:

- [ ] A mockup for how a user would select among 100 locations for the Availability card

**Comment by a6wu** [comment]
Neighborhood names:

1. Campus Services Complex
2. Marshall
3. Muir
4. North Campus
5. North Torrey Pines Living and Learning
6. Pepper Canyon
7. Revelle
8. Roosevelt
9. Scripps Institution of Oceanography
10. Torrey Pines
11. University Center
12. Warren

Within each neighborhoods will be specific buildings. Within each building could be multiple floors.

**Comment by a6wu** [comment]
@woznaut Is the list of neighborhood names above what you're looking for?

**Comment by a6wu** [comment]
API at https://api-qa.ucsd.edu/store/apis/info?name=FIM-Portfolio&version=v0.0.3#/default/get_Neighborhood__id_

**Comment by woznaut** [comment]
see Parking Lot selection mockup for interaction design. we'd use this same scheme:

https://xd.adobe.com/view/48b708f3-3e75-4100-b302-f17ba837e213-1de4/
