### ISSUE TITLE
Duplicate Scan Message

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1024]
ITS-Pro time category: “Submission failed due to barcode already scanned. Scan another barcode.”

This is complete when:

- [x] The following message displays when a user scans a barcode that has been scanned by another user, "Submission failed due to barcode already scanned. Please scan another barcode.”
- [x] This screen displays for 5 seconds before returning to the scanning view
- [x] This screen has a yellow alert icon

**Comment by p8gonzal** [comment]
Duplicate error screen and behavior done. Handed off to Mihir for integration with update scanData api.
