### ISSUE TITLE
At Home Testing UI Flow

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1027]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-42?filter=allissues

This is complete when:

- [ ] A mockup with user flow is implemented to support at home testing

**Comment by a6wu** [comment]
Example process from NYU: https://www.nyu.edu/life/safety-health-wellness/coronavirus-information/safety-and-health/coronavirus-testing/ongoing-testing/step-1-pick-up-your-kit.html

**Comment by sramcode** [comment]
Link to at home testing flow doc:

https://docs.google.com/document/d/1bOERVURE5bHfX_4wEl1w5QLhECyRW0cn72c5n-KQvEM/edit?usp=sharing

**Comment by a6wu** [comment]
Holding off as the students are getting familiar with the process of testing.
