### ISSUE TITLE
Barcode Generation Tool

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1028]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-33?filter=allopenissues

This is complete when:

- [ ] A tool is created that generates a random barcode with the value prefix: "UCSD-Test-<random>"

**Comment by kevdesilva01** [comment]
v1 - https://mobile.ucsd.edu/replatform/v1/qa/webview/barcode-generator/barcode-generator.html
