### ISSUE TITLE
Add Timeout to Network Requests

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#103]
Add timeout handling for network requests.

**Comment by c3bryant** [comment]
https://github.com/robinpowered/react-native-fetch-polyfill

**Comment by c3bryant** [comment]
This task can be streamlined by coinciding with the change manager implementation

**Comment by Gulci** [comment]
A new method for keeping track of network requests is being introduced in v5.6 inspired by [this post](https://medium.com/stashaway-engineering/react-redux-tips-better-way-to-handle-loading-flags-in-your-reducers-afda42a804c6).

The main gist of this is that when we begin a network service request in a saga, we dispatch an action as follows:
`{HTTP_METHOD}_{SERVICE_NAME}_REQUEST / SUCCESS / FAILURE`

So for example, let's say we are submitting feedback in the app. The action would be: `POST_FEEDBACK_REQUEST`

Once we indicate that we have started the request, the exact datetime that request was started is stored. Then, within the same saga, we start a race between the HTTP request and a timeout function.

Here's an example of all this in action. This can be found in `feedbackSaga.js`.
```
// We need to indicate that we're loading
try {
	const { response, timeout } = yield race({
		response: call(FeedbackService.FetchFeedback, action.feedback),
		timeout: call(delay, HTTP_REQUEST_TTL)
	})

	if (timeout) {
		const e = new Error('Request timed out.')
		throw e
	}
	else if (response.status !== 200) {
		const e = new Error('Invalid server response.')
		throw e
	}
	else {
		yield put({ type: 'SET_FEEDBACK_RESPONSE', response })
		yield put({ type: 'POST_FEEDBACK_SUCCESS' })
	}
} catch (error) {
	logger.log(error)
	yield put({ type: 'POST_FEEDBACK_FAILURE', error })
}
```
`HTTP_REQUEST_TTL` is defined in `AppSettings.js` and is currently set to 10 seconds. After those ten seconds, if the request has failed to return a response, the saga will stop waiting for a response. We can then check if `timeout` is `true`. If it is, we throw a time out error and we dispatch a `POST_FEEDBACK_FAILURE` action. This will notify our view that an error has a occurred, and an error can be displayed to the user.

The same applies for `POST_FEEDBACK_SUCCESS`: if that action is dispatched after the successful network request, the view can display a success message to the user.

And finally, while all this is happening and `POST_FEEDBACK_REQUEST` contains a datetime, we can display feedback that indicates to the user that their request is pending / loading. `POST_FEEDBACK_REQUEST` and its datetime value will be cleared upon `SUCCESS` or `FAILURE`.

Thus, we can handle timeouts gracefully and give useful feedback to the user _and_ make network request statuses easily accessible.

**Comment by Gulci** [comment]
So far, the following sagas and components have been updated to use these new actions:
+ `feedbackSaga.js`
+ `FeedbackView.js`
+ `DiningSaga.js` (Only for dining menus)
+ `DiningMenu.js`

**Comment by Gulci** [comment]
SSO operations have been updated to use these new actions as of d760234

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
