### ISSUE TITLE
Database Connection Cleanup

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1031]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-34?filter=allopenissues

This is complete when:

- [x] The database connection is created within the handler function
- [x] The database connection is explicitly disconnected for all execution paths

- [x] 1. https://sourcecode.ucsd.edu/scm/wts/qr-scanner-api.git
- [x] 2. https://sourcecode.ucsd.edu/scm/wts/my-staff-profile.git
- [x] 3. https://sourcecode.ucsd.edu/scm/wts/my-student-profile.git

**Comment by lukedutta9** [comment]
I made a new branch for each repo called "database-cleanup-1031" that handles creation of the connection inside the handler and explicitly disconnects for all paths.
