### ISSUE TITLE
Parking Lots Selection

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1032]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-42?filter=allissues

This is complete when:

- [x] A UI concept is created for selecting among 61 parking lots, currently live in the production app

**Comment by a6wu** [comment]
List of parking lots at http://mobile.ucsd.edu/replatform/v1/prod/webview/parking/parking_lots.json

**Comment by kennytrand** [comment]
Link to first design iteration: https://xd.adobe.com/view/48b708f3-3e75-4100-b302-f17ba837e213-1de4/

Breaking up parking into two sections, parking structures and parking lots. Parking lots are further broken up into subsections. Here are the subsections: 

1) Campus Services Complex
2) North Campus
3) North Torrey Pines & Glider Port
4) Regents Lots
5) School of Medicine
6) Science Research Park
7) Scripps Oceanography
8) The Preuss School
9) UCSD Medical Center La Jolla
10) University Center
11) The 7 colleges

**Comment by a6wu** [comment]
API at https://api-qa.ucsd.edu/store/apis/info?name=FIM-Portfolio&version=v0.0.3#/default/get_Neighborhood__id_
