### ISSUE TITLE
Shuttle card - Unable to add a stop for some users

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1036]
Time tracking: MA-78

This is done when:
- [x] Users are able to add new shuttle stops reliably, without infinite loading

* Could possibly be related to fetching arrival information

**Comment by p8gonzal** [comment]
Issue identified: 
Try-catch logic failed when exception caused by anything other than invalid token. Creating a cycle.
Type exception when api returned double rather than an int. 
Fix: 
Added cast to double
