### ISSUE TITLE
Update naming convention for Dev and Prod APIs

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#104]
For Dev APIs in AWS, use "dev" exclusively in the URL.
For Prod APIs in AWS, use "prod" exclusively in the URL.

Wait until "dev" is no longer in use in the production release(s).

**Comment by i8wu** [comment]
@a6wu review for March release?

**Comment by a6wu** [comment]
The AppSettings file looks good on "prod" vs "dev" in the API endpoints. There are two "dev" endpoints in use, which are the new APIs you created.

**Comment by i8wu** [comment]
Can close this issue after migrating to prod lambda?

**Comment by a6wu** [comment]
Yes.

**Comment by c3bryant** [comment]
All APIs should now be using the correct dev/prod naming convention, closing
