### ISSUE TITLE
Duplicate Barcode Scan by the Same Person

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1042]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The user receives a message about the previously scanned barcode, if the same user is submitting the same barcode

Scenario:

1. Student A scans the barcode XYZ
2. Two weeks later, student A scans another testkit with the barcode XYZ

Current implementation shows a success message which is misleading.

**Comment by gmihir** [comment]
Update pushed to duplicate-status-409 branch on sourcecode. In this update, all duplicate scans will be treated as failures and will return a custom status code of 409. There is no update required on the client-side.

**Comment by a6wu** [comment]
@gmihir Can you implement the following:

1. If it's the same day, multiple scans of the same barcode by the same person returns success, but does not write a new entry
2. If it's a different day, duplicate scans of the barcode by the same person returns the duplicate scan message

**Comment by gmihir** [comment]
@a6wu This implementation is done (pending QA testing) and has been pushed to same-day-success branch in sourcecode.

**Comment by a6wu** [comment]
@gmihir Uploaded to QA. Scanning the same code twice by the same person on the same day gives a duplicate error message. I made an update and pushed to the branch - however, still not correct. Could use additional help on this.
