### ISSUE TITLE
Add Check for Scanned Barcode Value

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1045]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [ ] The API for submitting the scan allows only alphanumeric values, underscore, hyphen

**Comment by gmihir** [comment]
This change is on the barcode-check branch on sourcecode. Returns a 415 error if the check fails, as per HTTP/1.1 specification.
