### ISSUE TITLE
Parking web card cutoff when in landscape mode on iPad

### ISSUE THREAD

**Issue by p8gonzal** [UCSD/campus-mobile#1051]
The parking web card appears cutoff at the bottom when in landscape orientation on iPad.
Reported when testing TestFlight 7.2.13 (102).

This is done when:

- [ ] The parking web card renders correctly on iPad landscape orientation.

Note: Occurred on a physical 12.9 in. iPad Pro

![IMG_0047](https://user-images.githubusercontent.com/42155702/97025137-8334d280-150c-11eb-86a1-848446c451ae.PNG)

**Comment by c3bryant** [comment]
Consolidating to #1071
