### ISSUE TITLE
Migrate flutter_scandit_plugin fork

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1056]
Time Tracking: MA-74

This is done when:
- [x] https://github.com/gmihir/flutter_scandit.git has been migrated to https://github.com/UCSD/flutter_scandit
- [x] PR #1053 pubspec updated to point to the UCSD/flutter_scandit fork

**Comment by gmihir** [comment]
This has been completed and the PR has been updated.
