### ISSUE TITLE
Standalone Web Scanner Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1057]
ITS-Pro time category: https://sourcecode.ucsd.edu/projects/WTS/repos/web-barcode-scanner/

This is complete when:

- [x] The standalone web scanner is updated to display the duplicate scan message

https://sourcecode.ucsd.edu/projects/WTS/repos/web-barcode-scanner/

**Comment by p8gonzal** [comment]
Done.

**Comment by a6wu** [comment]
@a6wu Build and deploy to CMS QA.
