### ISSUE TITLE
Implement NTPLLN Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1058]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-109

This is complete when:
- [x] Set up VPN access to NTPLLN API from AWS Lambda (avail on WTS Sandbox and UCSDTest)
- [x] API on WSO2 that wraps NTPLLN API
- [x] API cached at 5 minute interval
- [x] Log API errors
- [x] Metasys API added to heartbeat monitor in QA

- [x] Refactor detailed API to not do series of call, use cached access token and then call to the valve endpoint directly
- [x] The following mockup has been implemented, https://xd.adobe.com/view/c6f05884-3dee-4a90-8243-afc5b3d1bc5d-93a3/

- [x] PR 1543 requested changes completed

- [x] [PR 1543 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1543-Test-Plan-7.12.0-QA-1705.xlsx?web=1) PASS on iOS
- [x] [PR 1543 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1543-Test-Plan-7.12.0-QA-1706.xlsx?web=1) PASS on Android

**Comment by a6wu** [comment]
https://collab.ucsd.edu/display/WTS/NTPLLN+API

**Comment by a6wu** [comment]
Waiting on username/password to access APIs

**Comment by a6wu** [comment]
We have access to the APIs

**Comment by gmihir** [comment]
APIs seem to be down -- getting a 500 with a HTML error in the console with Postman

Will try the APIs later, but stuck for now

`<!DOCTYPE html>
<html>

<head>
	<title>Runtime Error</title>
	<meta name="viewport" content="width=device-width" />
	<style>
		body {
			font-family: "Verdana";
			font-weight: normal;
			font-size: .7em;
			color: black;
		}

		p {
			font-family: "Verdana";
			font-weight: normal;
			color: black;
			margin-top: -5px
		}

		b {
			font-family: "Verdana";
			font-weight: bold;
			color: black;
			margin-top: -5px
		}

		H1 {
			font-family: "Verdana";
			font-weight: normal;
			font-size: 18pt;
			color: red
		}

		H2 {
			font-family: "Verdana";
			font-weight: normal;
			font-size: 14pt;
			color: maroon
		}

		pre {
			font-family: "Consolas", "Lucida Console", Monospace;
			font-size: 11pt;
			margin: 0;
			padding: 0.5em;
			line-height: 14pt
		}

		.marker {
			font-weight: bold;
			color: black;
			text-decoration: none;
		}

		.version {
			color: gray;
		}

		.error {
			margin-bottom: 10px;
		}

		.expandable {
			text-decoration: underline;
			font-weight: bold;
			color: navy;
			cursor: hand;
		}

		@media screen and (max-width: 639px) {
			pre {
				width: 440px;
				overflow: auto;
				white-space: pre-wrap;
				word-wrap: break-word;
			}
		}

		@media screen and (max-width: 479px) {
			pre {
				width: 280px;
			}
		}
	</style>
</head>

<body bgcolor="white">

	<span><H1>Server Error in '/API' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

	<font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

		<b> Description: </b>An exception occurred while processing your request. Additionally, another exception
		occurred while executing the custom error page for the first exception. The request has been terminated.
		<br><br>

    </body>

</html>`
