### ISSUE TITLE
Barcode Scan Confirmation Screen Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1061]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The confirmation screen displays the barcode value that was scanned

**Comment by p8gonzal** [comment]
Updated changes, waiting on authorization to push to source code. 
![IMG_6728](https://user-images.githubusercontent.com/42155702/97670100-bd3d3180-1a42-11eb-812d-2d8944e46458.PNG)

**Comment by p8gonzal** [comment]
Done.

**Comment by a6wu** [comment]
@a6wu Build and push to CMS QA for testing.
