### ISSUE TITLE
Mobile Authentication

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1064]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-59

This is complete when:

- [x] ~~The authentication process checks that a user has a valid Student ID or Employee ID~~
- [x] ~~The authentication process denies authentication if the above is not true~~

**Comment by c3bryant** [comment]
Done in QA

Repo: https://sourcecode.ucsd.edu/projects/WTS/repos/mobile-authentication-service/browse
Branch: master

Notes:
- Non-breaking change
- Student ID valid starting characters supported: [A, U]
- QA API v2
- Deploy to PROD API v1.1

**Comment by c3bryant** [comment]
Recent conversation regarding this update from Dec '20 discussed reverting this change in QA.

@a6wu sending your way for direction/review.

**Comment by a6wu** [comment]
@c3bryant  Please revert in QA

**Comment by c3bryant** [comment]
Reverted in QA
