### ISSUE TITLE
WiFi Connection Stats

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1069]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-99

This is complete when:

- [x] Android logs the WiFi stats to the device
- [x] iOS logs the WiFi stats to the device

The following attributes are logged:

- [x] Device MAC address
- [x] Device IP Address
- [x] WiFi access point name
- [x] WiFi access point IP address
- [x] WiFi connection strength
- [x] WiFi channel
- [x] Network ID
- [x] BSSID
- [x] SSID
- [x] Link speed
- [x] Frequency
- [x] Lat/Lon
- [x] Timestamp

- [x] Logs are sent to the WiFi logging API at application launch

**Comment by a6wu** [comment]
@i8wu  https://sourcecode.ucsd.edu/projects/WTS/repos/msm-wifianalyzer

**Comment by p8gonzal** [comment]
Update: Built native Swift app to collect most listed above. (Possible privacy limitations specific to iOS) Will meet with Ivan to discuss path forward.
![IMG_6853](https://user-images.githubusercontent.com/42155702/97933719-6aa49380-1d28-11eb-8a0b-75beea339f17.PNG)

**Comment by g9singh** [comment]
here is the source code for the WifiBuddy app with the speed test implemented:
https://sourcecode.ucsd.edu/projects/WTS/repos/ucsd-wifi-analyzer/browse

**Comment by i8wu** [comment]
Created a flutter plugin: https://github.com/i8wu/WifiConnection
Will need to add in iOS implementation w/ Peter and we can test with campus-mobile

**Comment by p8gonzal** [comment]
For iOS the following attributes are logged:

- [ ] BSSID

- [ ] SSID

- [ ] WiFi access point IP address

- [ ] Vendor facing MAC address

- [ ] Lat/Lon

- [ ] Time Stamp

**Comment by i8wu** [comment]
Released the initial version of the plugin and verified it's working in the campus mobile app.
Link:
https://pub.dev/packages/wifi_connection

**Comment by p8gonzal** [comment]
0.0.2-dev.1 released on pub.dev with refactored iOS implementation. Verified on campus mobile app.

**Comment by a6wu** [comment]
@woznaut  Need a UI for students to submit this information.

**Comment by a6wu** [comment]
Included in #1257.
