### ISSUE TITLE
Tabbed Views

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#107]
Implement Tabbed view navigation for Top-level views
e.g...
- Home
- Map
- Calendar
- Settings
- Etc

There are probably tons of modules out there but this one looks pretty nice: https://github.com/react-native-community/react-native-tab-view

We might even want to implement our own. @c3bryant thoughts?

**Comment by i8wu** [comment]
@srkirkland Brought up a good point about possibly implementing a menu/drawer if we don't have enough useful tab views yet. Worth considering since we don't really have useful tabs yet. 

I think @c3bryant was looking into [react-native-router-flux](https://github.com/aksonov/react-native-router-flux)? We could put in the underlying implementation and just hide tabs for now?

**Comment by c3bryant** [comment]
react-native-router-flux is working really well so far

we will be merging it into dev soon and doing away with Navigator and NavigatorIOS

it includes support for a number of things, here are a few:
- Tabbar
- Drawer (side-menu)
- Modals
- Custom navbar
- Switch
- Splitting Scenes
- Sub-Scenes

@srkirkland we will be meeting sometime this week to discuss tabs/drawer options again and will loop you in on that

**Comment by c3bryant** [comment]
Tabs are in, closing
