### ISSUE TITLE
WebCard Performance and Reload Issue

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1070]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-66

Issue: WebCard reloads when coming back into the viewport during scrolling, causing frames to be dropped (<10 fps on most devices). 

This is complete when:

- [x] The WebCard does not reload after initially loading and then scrolling up and down the Home view
- [x] [PR 1148 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BEC5CCF5A-65C1-42EA-A118-B764B193A763%7D&file=PR-1148-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (@gmihir)
- [x] [PR 1148 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BEC5CCF5A-65C1-42EA-A118-B764B193A763%7D&file=PR-1148-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (@g9singh)

References:
https://gist.github.com/iapicca/1ce2fd13658a88c28fb72facd5491bf7

**Comment by g9singh** [comment]
Unfortunately, this is a well-known issue: https://stackoverflow.com/questions/55587918/web-view-is-too-slow
The answer to this post explains why the issue can't be resolved.

**Comment by kevdesilva01** [comment]
@g9singh even though we cant have it reload faster we can still prevent it from reloading every time it comes into the viewport right?

**Comment by kevdesilva01** [comment]
Update: keepAlive Mixin works and webcard no longer reloads after scrolling, will continue refining & testing

**Comment by g9singh** [comment]
Android test [results](https://ucsdcloud.sharepoint.com/:x:/s/WorkplaceTechnologyServices-CampusMobileBuilds/EVrPXOzBZepCoRi3ZLGTp2MBQmYCUw3l3FfacrcCUhIAOA?e=7Zn1Vo)

**Comment by gmihir** [comment]
passes on iOS
