### ISSUE TITLE
Parking Card Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1071]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-84

Issues:
- Parking card is slow when switch lots
- Parking card is slowing down the entire app
- Parking card jolts the entire home view scroll position when going in and out of the viewport
- Parking card may be reloading all the pages for each pageview rendering
- Parking card rendering artifacts on iOS <13
- Parking card does not load for a subset of users
- Parking card appears cutoff at the bottom when in landscape orientation on iPad

This complete when:
- [x] The Parking card has been reimplemented natively
- [x] The Parking card fetches data for all user-selected lots asynchronously so the user does not have to wait for results when scrolling horizontally between lots

- [x] Enlarge percentage circle to provide more space for the percentage number inside. Support `100%` availability text
- [x] Ensure spot type selection is limited to 3 spot types
- [x] Test on iPhone 6s and iPad 12.9" devices, report or resolve any issues

- [x] "Accessible" spot type is rendering the text "Accessibl" in the small spot types circle on Parking card lot availability. Use Accessible icon if feasible
- [x] SR spot type shown for Residential Students - change spot type code to RS

- [x] [PR 1487 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B02619430-75BD-4476-B998-777D1A20498F%7D&file=PR-1487-Test-Plan-7.10.0-QA-1621.xlsx&action=default&mobileredirect=true) PASS on iOS
- [x] [PR 1487 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1487-Test-Plan-7.10.0-QA-1598.xlsx?web=1) PASS on Android

**Comment by g9singh** [comment]
Made updates to parking card on following branch: https://github.com/g9singh/campus-mobile/tree/bugs/native-parking-card

- updated parking model
- updated parking service to point to https://b2waxbcovi.execute-api.us-west-2.amazonaws.com/prod/parking/v1.1/status
- updated data provider to use new parking model
- updated UI to use native code
- removed web card

This issue still needs some UI work and general code clean up.

**Comment by gmihir** [comment]
Current work is at the following branch: https://github.com/gmihir/campus-mobile/tree/native-parking-card-mg
 

The previous code has been updated to comply with Flutter 2. However, the work is not complete as there are still significant issues with the progression of the native parking card feature. The correct data is being made available to campus-mobile, but the UI is not presenting and is not complete.

**Comment by c3bryant** [comment]
Thanks for the update, gmihir.

Working branch is now on [UCSD/campus-mobile/parking-card-update](https://github.com/UCSD/campus-mobile/tree/parking-card-update)
