### ISSUE TITLE
Standalone Web Scanner: Barcode Value on Confirm Screen

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1076]
ITS-Pro time category: https://mobile.ucsd.edu/replatform/v1/qa/webview/scanner-standalone/index.html

This is complete when:

- [x] The barcode scanned is displayed on the confirmation screen

**Comment by gmihir** [comment]
Change has been pushed to sourcecode (web-barcode-scanner: master). I wasn't able to test it in mihir-test on the CMS due to API not recognizing the URL and I wasn't sure if it was ok to mess with qa or not. Should work, but needs to be verified.
