### ISSUE TITLE
Standardizing Cards/Components

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#108]
I would like to start refactoring and making our cards less specific and more black box-ish.

For example:
EventDetail.js is relying on an image url, a text title, text description, and some sort of date text.
The image url is checked and math is done to set the height in componentWillMount().
The date is reformatted in renderScene() to meet the component's needs. 

I think it'd be best if we could outline what data/feed structure a component wants and put any transformations that are required inside a specific function. We can then outline when that function is expected to output so that if someone were to put in their own Events Feed, they could do any transformations inside that one function, to match expected formatting, without having to touch anything else.

**Comment by c3bryant** [comment]
Revisit again for the first post-transition release

**Comment by i8wu** [comment]
#23

**Comment by i8wu** [comment]
Added DataListCard component d5dcde06e44388d39d3aa1234244aa3fd20d4ede

Example Usage:
```
<DataListCard
	title="Links"
	data={this.props.linksData}
	item={'QuicklinksItem'} // this needs to be defined in DataListView.js
	rows={4}
/>```

**Comment by c3bryant** [comment]
Significant work has been done around standardization/commonization of components since this issue was added. Closing, will review this again should the need arise in the future
