### ISSUE TITLE
Native Scanner Error Screen Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1081]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [ ] The following specific error message for invalid barcodes that do not begin with "EXC" or are not in the expected format is added: "Submission failed. Barcode is not valid. Please scan another barcode."

**Comment by gmihir** [comment]
Completed and is on scandit-native-integration branch. If it is more convenient to create a separate branch and submit PR, please let me know.
