### ISSUE TITLE
Shuttle Does not Retain Added Stops

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1082]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-34?filter=allopenissues

This is complete when:
- [x] The added shuttle stops remain after an app relaunch
- [x] [PR 1163 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B8313C433-D02B-4BA3-9864-2EF126C0B2B6%7D&file=PR-1163-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (@sramcode) 
- [x] [PR 1163 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B8313C433-D02B-4BA3-9864-2EF126C0B2B6%7D&file=PR-1163-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (@asg003)

To reproduce on 7.2.13 production build:

1. Tap on Manage Shuttle Stops
2. Add a stop
3. Confirm stop is added on the Home view
4. Completely close out the app
5. Launch the app
6. Home view does not show the added shuttle stop
7. Manage Shuttle Stops view does not show the added stop

**Comment by c3bryant** [comment]
PR #1096 has failed regression testing for some users. The issue of hard reset erasing added stops persists on Android and iOS.
