### ISSUE TITLE
Deploy UCSD Scan 1.0.2

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1083]
ITS-Pro time tracking: https://its-pro.ucsd.edu/projects/MA/issues/MA-31?filter=allopenissues

This is complete when:
- [x] v1.0.2 has gone through regression testing
- [x] v1.0.2 is awaiting App Store review
- [ ] v1.0.2 has been approved by Apple for store release
- [ ] v1.0.2 has been deployed to the App Store

**Comment by c3bryant** [comment]
Update
1.0.2 rejected by Apple Review citing the need for a SSO account login to fully review the app.

Next Steps
- [ ] Update demo video showing barcode submission success, failure, duplicate
- [ ] Appeal the decision using verbiage from Campus Mobile app submissions and updated demo video

**Comment by a6wu** [comment]
Holding off on this enhancement update. Native scanner on the campus mobile app has reduced the need of the iPads.
