### ISSUE TITLE
Scanner Hardware for Tablets

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1089]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [ ] A list of hardware options is provided that works with the UCSD Scan app

**Comment by gmihir** [comment]
I looked a little bit, couldn't find anything that will work with Flutter and iPads...

Here are some options I found:

- Honeywell Captuvo SL22/42 (https://pub.dev/packages/flutter_honeywell_captuvo_plugin)  [iPhone/iPod]

- A bunch of custom scanner handheld computers by Honeywell (https://pub.dev/packages/honeywell_scanner)
CN51
CK75
CN75
CN75e
CN80
CN85 
Dolphin 75e 
Dolphin CT40 
Dolphin CT50 
Dolphin CT60 
EDA50 
EDA51
EDA50K 
EDA70
Thor VM1A

- Zebra DataWedge API (https://developer.zebra.com/blog/creating-flutter-applications-zebra-android-devices-datawedge) [Android]
