### ISSUE TITLE
Implement Events Card Mockup

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1107]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-113

This is done when:

- [x] Limit event list title to 2 lines ([1](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/f9503c5c-4d9b-4918-ae41-5ea0c9f9784c))
- [x] Remove event list up arrow ([2](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/f9503c5c-4d9b-4918-ae41-5ea0c9f9784c))
- [x] Fix event list vertical spacing (Android) ([3](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/f9503c5c-4d9b-4918-ae41-5ea0c9f9784c))

- [x] [PR 1662 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1662-Test-Plan-7.19.0-QA-2104.xlsx?web=1) PASS on iOS
- [x] [PR 1662 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1662-Test-Plan-7.19.0-QA-2105.xlsx?web=1) PASS on Android

Notes:
- `tags` attribute is available via Events API for `Category` filtering
- `college` attribute is not available via Events API for `College` filtering. Omit `College` filter from implementation
- Mock: https://xd.adobe.com/view/5f69745a-1bcd-4b0e-8785-eb1df9a72c2e-0a3a/

Previously Completed Tasks:
- [x] Events card redesign integrated to campus mobile
- [x] If event has no image, then use student placeholder image
- [x] Event detail text renders (both light mode and dark mode) on physical device

- [x] Event tile widget file reimplementation (to fix the alignment and container size issue, try to avoid magic numbers)
- [x] Clip thumbnail images to one shape such that the width fits the container
- [x] Dark mode theme is supported
- [x] New placeholder image for the event tile widget (no white border)
- [x] Resolve rendering issue for detail view seen on TestFlight

**Comment by gmihir** [comment]
Failed on iOS, saw a lot of the same issues Kevin reported on Android.

**Comment by xxwwyytt1** [comment]
The rendering issue is not caused by dark mode/brightness. When I switched to light mode, the text still won't show up. Investigating if it's a data fetching issue or caused by something else.

**Comment by p8gonzal** [comment]
iOS and Android testing complete from me. Provided notes in both spreadsheets. Android build may not be a pass. Formatting issue, requires further investigation.

**Comment by kevdesilva01** [comment]
Same results as peter, they functioned properly, but I noticed some formatting errors on Android. There are some design choices that might need to be followed up on (the arrow on each tile and the spacing between each card)
