### ISSUE TITLE
Rotate Student ID Photo

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1108]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/SVCOPS-408

This is complete when:

- [x] The student photo is rotated automatically at schedule intervals (https://mobile.ucsd.edu/)

**Comment by c3bryant** [comment]
Student photo loads Jane Smith or John Smith initially (random), and rotates every 12sec after an initial 6sec first rotation
