### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#111]
Possible calendar view containing:

- school calendar (holidays/addclass/dropclass)
- class schedule
- school events
- reminders?

Resources:
http://blink.ucsd.edu/instructors/resources/academic/calendars/2016.html
https://github.com/mozilla-comm/ical.js/

**Comment by i8wu** [comment]
http://blink.ucsd.edu/instructors/resources/academic/calendars/2016.html

**Comment by c3bryant** [comment]
We will be revisiting this issue internally to flesh out the details before development work begins.
