### ISSUE TITLE
Events Card: Student events API returning Error 401

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1110]
Time Tracking: MA-34

This is done when:
- [x] Feed errors resolved by Tockify
- [x] CORS/rss-parser related issue resolved in getCampusEvents Lambda
- [x] Student Events API verified in QA
- [x] Student Events API deployed to PROD

**Comment by lukedutta9** [comment]
Other RSS verification sites showed the issues in the RSS format here in the response:

```xml
<atom:link href="https://tockify.com/api/feeds/rss/${cal.name}" rel="self" type="application/rss+xml"/>
<link>https://tockify.com/$
    ucenevents
</link>
```

The links for each of these elements contain unsafe characters ( '$', '{', and '}' ), we probably need to request a fix for this from the feed verifier.

**Comment by c3bryant** [comment]
Thanks Luke. This information has been forwarded to the sponsor and feed provider.

**Comment by c3bryant** [comment]
getCampusEvents:v3 ready to deploy

Source: https://sourcecode.ucsd.edu/projects/WTS/repos/grab-events/browse
Branch: `master`
API Gateway: https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/r6xnvicltl/resources/dzr2z0/methods/GET

**Comment by a6wu** [comment]
@c3bryant  Deployed.
