### ISSUE TITLE
Parking Card: Content not loading for some users (An error occurred)

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1115]
Time Tracking: MA-34

This is done when: 
- [ ] Parking card lots and availability load as expected

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/9f05b825-861e-4ca9-b616-a8840e2b4d81)

**Comment by a6wu** [comment]
Logging exception with Google Analytics, https://developers.google.com/analytics/devguides/collection/ga4/exceptions

**Comment by a6wu** [comment]
Added Google Analytics to https://mobile.ucsd.edu/replatform/v1/prod/webview/parking/index.html, and tag event for "exception".

**Comment by a6wu** [comment]
Could it be the template literals? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by a6wu** [comment]
Analytics running for a few days. No exceptions logged.

**Comment by c3bryant** [comment]
Closing in favor of #1071
