### ISSUE TITLE
Locate a COVID Test Vending Location Ideas

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1116]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-99

Ideas for displaying COVID test vending machine locations.

1. List as a category in the Maps tab
2. Link from the COVID information card
3. A separate card

**Comment by sramcode** [comment]
Here's a doc with some quick mockups of the ideas listed to show how to display the COVID test vending machine locations.

https://docs.google.com/document/d/1I6jcNGakpaaby5ajeJhpQ6jsF8v5KLRLBmr46VrzRUM/edit?usp=sharing

**Comment by a6wu** [comment]
@woznaut Can you review the doc above?

**Comment by c3bryant** [comment]
Implementations 1a (#1164) and 2a (#1165) selected for V1
