### ISSUE TITLE
Podcast Feature

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1117]
ITS-Pro time category:

Podcasts:
1. https://shows.acast.com/triton-tools-tidbits/episodes

**Comment by a6wu** [comment]
@woznaut 

![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/1f75e026-e2a5-4b97-8b43-de3f398bb254)

**Comment by kevdesilva01** [comment]
@a6wu is this screenshot from a prototype or a webcard that was added? is this how we want the podcast feature to be?

**Comment by woznaut** [comment]
I think at a minimum we'd like to be able to style the content from the feed to be more in brand if that's an option

**Comment by a6wu** [comment]
@kevdesilva01  @woznaut  This is something I threw up quickly. Completely open to making this more flexible. There are a handful of podcasts from UCSD.

**Comment by a6wu** [comment]
https://podcast.ucsd.edu/
https://ksdt.ucsd.edu/
(video) https://www.ucsd.tv/

**Comment by kevdesilva01** [comment]
@a6wu are all of these links things that should be made available through this feature?

**Comment by a6wu** [comment]
@kevdesilva01 not necessarily. Sharing a list of various media content for design/implementation ideas.

**Comment by kevdesilva01** [comment]
@a6wu okay thank you. Would it necessarily be a bad thing if the feature included a way to access all of these resources? Or is the main focus https://shows.acast.com/triton-tools-tidbits/episodes ?

**Comment by kevdesilva01** [comment]
@a6wu @woznaut here is a prototype w/ lock screen (only Triton Tools and Tidbits): https://xd.adobe.com/view/3ea50eab-e2ce-4057-a2c4-1c7a898eedd7-6bf6/
