### ISSUE TITLE
shuttle_routes_master.json is out of date

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#112]
shuttle_routes_master.json is out of date. Needs to be refreshed with new data.

**Comment by c3bryant** [comment]
This has been updated in dev. I will queue this to get pushed out via CodePush pending internal discussion.

I will be adding an issue for us to move to a dynamic replacement for this going forward.

**Comment by c3bryant** [comment]
shuttle json files are being reworked, this file will be removed - closing
