### ISSUE TITLE
WiFi Speed Test Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1125]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-99

This is done when:
- [x] WiFi speed test card displays for on-campus students
- [x] Card displays a button 
- [x] Student presses button to start speed test 
- [x] Card shows progress of test 
- [x] At end of test, card shows stats (upload speed/download speed) 
- [x] Card displays a Thank You with Rerun Test button 
- [x] At end of test, data is sent to API
- [x] File upload goes to S3 bucket
- [x] Use provider model setup
- [x] Report Issue button submits a Service Desk ticket

Regression Testing Round 1:
- [ ] ~~[PR 1302 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B0C1D65BC-1748-4593-AE98-DF90D2033701%7D&file=PR-1302-Test-Plan-7.8.0-QA-1319.xlsx&action=default&mobileredirect=true) PASS on iOS~~ (@gmihir) (FAILED, see notes)
- [ ] ~~[PR 1302 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B0C1D65BC-1748-4593-AE98-DF90D2033701%7D&file=PR-1302-Test-Plan-7.8.0-QA-1319.xlsx&action=default&mobileredirect=true) PASS on Android~~

Regression Testing Round 1 issues resolved when:
- [x] Users cannot begin a speed test unless connected to campus wifi
- [x] Speed test card does not infinitely load on or off of campus wifi
- [x] Speed test card does not degrade app performance or cause unresponsiveness
- [x] Speed test can be performed when the user loads app off campus wifi, and then connects to campus wifi
  - reloading card after connecting to campus wifi shows 'Looks like you aren't on a UCSD network'
  - scrolling down and up on Home view reloads the speed test card, resolving the issue

Supplemental Testing (WiFi Speed Test Card Only):
- iOS: @sramcode 
- Android: TBD

Testing round 2 issues resolved when:
- [x] iOS simulator does not crash on app startup
  - Goal is to prevent sim users from crashing while running the app
  - When clicking the button to start a speed test, print a debug message 'This feature is only available on physical devices.'
- [x] S3 object encoding resolved for wifi_logs and wifireport_logs (`[object Object]`)
- [x] Testing PASS on iOS
- [x] Testing PASS on Android

Remaining for 7.8:
- [ ] WiFiTest API deployed to PROD (#1333)

Additional documentation at: https://go.ucsd.edu/3lukJtE

**Comment by woznaut** [comment]
https://xd.adobe.com/view/3227f50c-cda0-48d9-8b40-b91379fc0b3f-6774/

**Comment by vesp56** [comment]
Justin Clow opened ticket CS0365851 to get an API connection from app to Service Desk, for the "Report Issue" button to translate into a Service Desk ticket. Our contact (on Justin's team) is Earl Duque - he can provide documentation for the API.

**Comment by p8gonzal** [comment]
@woznaut The functionality of the WiFi download and upload tests are done. However due to the implementation of dio.post(), call back function is less frequent for upload. This results in a less smooth progress bar and a jump after hitting 50%. I have attached a video for reference. Let me know if there is something you would suggest to make it less confusing to the user. 
[WiFi Speed Test Download and Upload.zip](https://github.com/UCSD/campus-mobile/files/5783335/WiFi.Speed.Test.Download.and.Upload.zip)

**Comment by woznaut** [comment]
I don't think the progress needs to be linear in it's progression necessarily. if we were getting stuck at a certain percentage for a long time that would be frustrating for the user but I don't know if what you're showing me here is problematic enough to spend a bunch of time on it

**Comment by p8gonzal** [comment]
@woznaut Here is a current implementation for a blocking message when the user is not connected to a UCSD WiFi. It prevents the user from using the WiFi Speed Card. Please let me know if this is good to go or if you have other suggestions for wording and/or user flow.
![Speed Test Unavailable](https://user-images.githubusercontent.com/42155702/108745405-e1d88000-74ef-11eb-938c-75ae8ad5bddd.PNG)

**Comment by p8gonzal** [comment]
JSON structure:
{
    "Platform": "iOS",
    "SSID": "gonzalezfamily",
    "BSSID": "44:d4:53:88:1d:27",
    "IPAddress": "192.168.1.77",
    "MacAddress": "622AAE95-5CD4-4F78-812D-DF43BDFDB6B5",
    "LinkSpeed": "",
    "SignalStrength": "",
    "Frequency": "",
    "NetworkID": "",
    "IsHiddenSSID": "",
    "RouterIP": "",
    "Channel": "",
    "Latitude": 33.64516909846938,
    "Longitude": -117.29959925865496,
    "TimeStamp": "2021-03-10 13:45:16.151",
    "DownloadSpeed": "8.00",
    "UploadSpeed": "3.43"
}

**Comment by a6wu** [comment]
Submit issue button sends the following in addition to the JSON above:

userId
userEmail

**Comment by c3bryant** [comment]
Notes:
- Package [i8wu/wifi_connection](https://github.com/i8wu/WifiConnection) requires Android min SDK 23 (previously 21)
- Min Android version will be 6.0 (previously 5.0)

**Comment by gmihir** [comment]
Testing on iOS FAIL -- see notes on spreadsheet

**Comment by p8gonzal** [comment]
Checked in w/ Mihir to take note of issues. Two problems and possible solutions:
Card available when not on wifi or cellular data -> Ensure Connectivity determines no connection before card stops loading
App becoming unresponsive and slow -> Verify that all data collection and api calls are as asynchronous as possible to avoid using the main thread.

**Comment by p8gonzal** [comment]
Addressed simulator crash error, now shows unavailable message:
https://images.zenhubusercontent.com/62921972/b9330347-ab01-43d6-a4ad-4f0f17e3bd70/simulationstate.mp4
Verified logs are encoded correctly:
![Screen Shot 2021-04-19 at 1.26.23 AM.png](https://images.zenhubusercontent.com/5ed09bee6aaada77327154ed/533226a5-4de8-41a2-bf37-9ecbc38904e4)
