### ISSUE TITLE
Create Mobile Logging API

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1128]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-114

This is complete when:
- [x] The API for logging WiFi stats is created in QA
- [x] The API for logging Availability stats is created in QA
- [x] The API for logging WiFi stats is created in Prod
- [x] The API for logging Availability stats is created in Prod
- [x] The API is integrated with AWS APIM

WiFi Analyzer repo: https://sourcecode.ucsd.edu/projects/WTS/repos/msm-wifianalyzer/browse

**Comment by a6wu** [comment]
Notes from meeting with Peter. Will use the following:

POST endpoint with query parameter "type"

1. /log?type=wifi
2. /log?type=advancedwayfinding

The flow will be: WSO2 -> APIM -> Lambda -> API

Lambda will
	- Check "type" query parameter
	- If Wifi, call API for logging Wifi data
	- If Advanced Wayfinding, call API for logging Advanced Wayfinding

**Comment by a6wu** [comment]
@p8gonzal Can you send the JSON data structure for iOS and Android?

**Comment by p8gonzal** [comment]
{

    "Platform": String,

    "SSID": String,

    "BSSID": String,

    "IPAddress": String,

    "MacAddress": String,

    "LinkSpeed": String,

    "SignalStrength": String,

    "Frequency": String,

    "NetworkID": String,

    "IsHiddenSSID": String,

    "RouterIP": String,

    "Channel": String,

    "Latitude": Double,

    "Longitude": Double,

    "TimeStamp": String,

    

}

Same structure for android and iOS. Will be distinguished by 'Platform'

**Comment by a6wu** [comment]
Submitted request for a setup to send WiFi logs to Service Now.

**Comment by a6wu** [comment]
[MobileAppLogger API](https://api-qa.ucsd.edu/store/apis/info?name=MobileAppLogger&version=v1.1.0&provider=a6wu#/default/post_log) will be called by the mobile app.

MobileAppLogger API will call [WiFiLogger](https://api-qa.ucsd.edu/store/apis/info?name=WiFiLogger&version=v1.0.0&provider=a6wu) if log type is "wifi"

MobileAppLogger API will call AdvancedWayfindingLogger if log type is "advancedwayfinding"

**Comment by a6wu** [comment]
@p8gonzal API in QA is now connected all the way to the final data logging destination. API to use is https://api-qa.ucsd.edu/store/apis/info?name=MobileAppLogger&version=v1.1.0&provider=a6wu

Parameter type values should be either "WiFi" or "Wayfinding". JWT token being checked.

Lambda source code at https://sourcecode.ucsd.edu/projects/WTS/repos/mobileapplogger/browse.

**Comment by a6wu** [comment]
Prod deployment request at [CS0441976](https://support.ucsd.edu/its?id=ticket&table=sn_customerservice_case&sys_id=b816a8b5dba2a850d4781c79139619e4)

**Comment by c3bryant** [comment]
MobileAppLogger v1.1.0 verified in PROD
