### ISSUE TITLE
Update Scandit SDK to v6.6

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1129]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:
- [x] The Android SDK is updated to v6.6
- [x] The iOS SDK is updated to v6.6
- [x] [PR 1185 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B6405AB22-AA02-4F2C-B176-F95BE9072789%7D&file=PR-1185-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (@lukedutta9)
- [x] [PR 1185 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B6405AB22-AA02-4F2C-B176-F95BE9072789%7D&file=PR-1185-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (@asg003)

Notes:
- Scandit SDK v6.6 allows for tap to focus on Android and iOS
- Double-tap outside of the scanner overlay area to focus the camera. User will see a white circle inside the scanner overlay area as an indicator that the camera is refocusing.
- https://docs.scandit.com/data-capture-sdk/android/release-notes/6.6.html
- https://docs.scandit.com/data-capture-sdk/ios/add-sdk.html

**Comment by lukedutta9** [comment]
New PR for the scandit updates sent to flutter_scandit repo: [https://github.com/UCSD/flutter_scandit/pull/1](https://github.com/UCSD/flutter_scandit/pull/1).

We actually do not need the raw archives for the scandit SDK to update them, scandit libraries are hosted on Maven and CocoaPods repos for Android and iOS respectively. 

To make changes to the scandit version on Android, need to change the versions of the scandit library in `android/build.gradle` towards the bottom of the file (~ line 36):

```
dependencies {
    implementation "com.scandit.datacapture:core:6.6.0-beta.2"
    implementation "com.scandit.datacapture:barcode:6.6.0-beta.2"
```

For iOS, need to change the dependencies in `ios/flutter_scandit_plugin.podspec` at around line 18:

```
s.dependency 'ScanditBarcodeCapture', '~> 6.6.0-beta.2'
```
