### ISSUE TITLE
Survey Card Options

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1134]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-81

This is complete when a technical options are presented that will allow users to:

- [x] Take the survey once
- [x] Take the survey once a day, week, quarter, etc.
- [x] Take the survey multiple times throughout the day
- [x] This setting is configurable per survey

**Comment by sramcode** [comment]
Here's a doc where I listed out some options for the survey card:

https://docs.google.com/document/d/1jM2GUS9ODyjgbgK47w4hYXYvuGLzdnH1bdpyIFVuo30/edit?usp=sharing

I'll keep adding as I think of some more!

**Comment by a6wu** [comment]
@sramcode I've added my comments to the doc. Thank you.
