### ISSUE TITLE
Test WebView Error Handling

### ISSUE THREAD

**Issue by vesp56** [UCSD/campus-mobile#1137]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-66

This is complete when a test is done where:

- [x] The HTML page loaded by the Webview throws an error
- [x] Verify if Flutter catches the thrown error or not

**Comment by c3bryant** [comment]
WebView Error Handling Test Results
- HTML pages loaded by the `webview_flutter` package do not inherently throw any errors
- HTML pages loaded by the `webview_flutter` package which fail to render in Flutter are caught by our Flutter card container try/catch to allow us to display a generic error
- Adding an ErrorChannel JS channel allows us to return custom-thrown JS errors back to Flutter
  - ErrorChannel will not fire off if there is a JS error in the code as the JS thread has been killed
  - JS Try/Catch will not fire off automatically. Errors can be thrown and then sent to Flutter via the ErrorChannel. What this means is that we can catch errors that we test for (i.e. when validating data/types), but not unknown errors, which is a problem.
- HTTP error codes cannot be caught/handled at this time ([\#39502](https://github.com/flutter/flutter/issues/39502))
- Top recommended third-party solution for webapp error monitoring is https://airbrake.io/
