### ISSUE TITLE
Integrate Login

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#114]
Implement UI and user flow for:

1. Student enters PID/PAC
2. Student taps submit
3. System connects to ECP
4. ECP returns token
5. Token securely stored on device

**Comment by i8wu** [comment]
The UI and login handling is mostly there already, hopefully mobile SSO demo next week goes well and we can start using it.

**Comment by a6wu** [comment]
Can some of the tasks be labeled for first timers?

**Comment by i8wu** [comment]
Probably not the tasks for this issue, will be keeping an eye out for others.

**Comment by woznaut** [comment]
![notloggedin](https://user-images.githubusercontent.com/19195410/27489531-be1485e0-57ef-11e7-8ea7-f38693bd5a68.png)
![loginscreen](https://user-images.githubusercontent.com/19195410/27489540-c6260164-57ef-11e7-9b96-d4e52db099c2.png)
![loggedin](https://user-images.githubusercontent.com/19195410/27489544-c94a7172-57ef-11e7-9bf2-ce7b1128f3d0.png)

**Comment by i8wu** [comment]
iOS screenshot for reference as well
![image uploaded from ios](https://user-images.githubusercontent.com/20545218/29226463-08f9c2a6-7e87-11e7-8120-a8ca6a5d6a62.jpg)

**Comment by c3bryant** [comment]
This has been initially completed on the `sso` branch. Remaining tasks will be handled with individual issues
