### ISSUE TITLE
Add Access Token to Info Cards

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1140]
ITS-Pro time category: MA-66

This is complete when:

- [x] The Student Info card receives the access token via a URI fragment (#token)
- [x] The Staff Info card receives the access token via a URI fragment (#token)
- [x] [PR 1158 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B8EAFC03C-AAA8-4329-B29C-495EDAF32C70%7D&file=PR-1158-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (Mihir @gmihir) 
- [x] [PR 1158 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B8EAFC03C-AAA8-4329-B29C-495EDAF32C70%7D&file=PR-1158-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (@lukedutta9)

**Comment by gmihir** [comment]
passes on iOS
