### ISSUE TITLE
Red X on Barcode Scanning

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1141]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The red X error does not appear when scanning, due to the app being opened for a least one hour
- [x] Refresh token code has been removed from the app
- [x] [PR 1152 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BEF15FDEF-2249-4512-AD7B-50B853FBFD24%7D&file=PR-1152-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (@kevdesilva01)
- [x] [PR 1152 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BEF15FDEF-2249-4512-AD7B-50B853FBFD24%7D&file=PR-1152-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (@kevdesilva01)

Current solution is to close out the app and reopen the app. Possible cause is the access token has expired when submitting the scan.

**Comment by kevdesilva01** [comment]
PR #1152 Passes, codes can be confirmed if needed.
