### ISSUE TITLE
Deploy DefaultCards V3

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1145]
Time Tracking: MA-80

This is done when:
- [x] AWS DefaultCards V3 deployed to Prod
- [x] APIM DefaultCards V3 deployed to Prod ([CS0359605](https://ucsdservicedesk.service-now.com/its?id=ticket&table=sn_customerservice_case&sys_id=e7ecb2b81b8d6c10df40ed7dee4bcb67))
- [x] APIM DefaultCards V3 verified in Prod

**Comment by c3bryant** [comment]
AWS DefaultCards V3 ready to deploy

- QA DefaultCards API Gateway: https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/rj786p8erh/resources/3ot0mt/methods/GET
- QA DefaultCardsList Lambda: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DefaultCardsList/aliases/v3?tab=configuration
- DefaultCardsList repo: https://sourcecode.ucsd.edu/scm/wts/defaultcardslist

**Comment by a6wu** [comment]
@c3bryant  Deployed v3 to prod
