### ISSUE TITLE
Push Notifications not received directly after fresh install

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#1146]
The Push notifications do not come in after installing the app and using it. The issue is resolved once the app is fully closed once and restarted. 

Steps to Reproduce:
1. Install TestFlight build 126
2. Log into the app as a Staff or Student
3. Minimize the app
4. Send a DM Push Notification. It will not be received
5. Close the app completely
6. Open the app
7. Minimize the app
8. Send a DM Push Notification. It will now be received from now on

This is complete when:

- [x] Push Notifications are received after installing, without having to restart the app

- [x] Intended Performance of Push Notifications on iOS and Android is not affected and they function correctly

**Comment by kevdesilva01** [comment]
Issue is only on iOS devices, not present on Android.

**Comment by lukedutta9** [comment]
Tried to reproduce this bug on both TestFlight build 124 and the experimental branch.

I was able to reproduce the bug on testflight, but on experimental, the push notifications are working as normal. I'm not having the issue where the notif doesn't appear before closing and reopening the app.

**Comment by c3bryant** [comment]
Resolved in #1186
