### ISSUE TITLE
SyntaxError for Android RN39

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#115]
The app builds and installs onto android, but on startup there is an error
`SyntaxError: Strict mode does not allow function declarations in a lexically nested statement`

Found a solution [here](https://github.com/facebook/react-native/issues/11389)

Basically:
open node_modules\react-native\Libraries\Core\InitializeCore.js line 112
change 
`function handleError(e, isFatal) `
to 
`var handleError = function(e, isFatal)`
then do npm start -- --reset-cache

This issue can probably be closed out after we update to RN40

**Comment by iancanderson** [comment]
Hi, I don't work on your app but I saw this issue because it was linked to the react-native issue. FYI this was fixed in `0.39.2`, so you don't have to upgrade to `0.40.0`: https://github.com/facebook/react-native/compare/v0.39.0...v0.39.2

**Comment by i8wu** [comment]
Oh cool, will have a look. Thanks for letting us know!

**Comment by c3bryant** [comment]
Upgrading to 0.42.2, closing
