### ISSUE TITLE
MyChart: Login timeout navigating user to MyChart springboard login

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1150]

**Comment by g9singh** [comment]
changed ios/Shared/Resources/SettingsForLibraryBuilds.plist
- EnableIdleTimer: false

changed /android/app/src/main/res/values/branding_config.xml
- Branding_Enable_Idle_Timer: false

Closing this issue because these changes made it so the user is not automatically taken to the MyChartLogin page.
