### ISSUE TITLE
Scanner Card Maintenance Deployment

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1151]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when the:

- [x] The scanner card is able to display a message about system maintenance in progress
- [x] The user cannot scan nor submit a scan during the system maintenance window

**Comment by kevdesilva01** [comment]
Scanner Downtime Screen link:

https://cwo-test.ucsd.edu/scanner-qa-kevin/scanner-downtime.html

**Comment by c3bryant** [comment]
- Dry run in QA has passed testing
- Ready to deploy on 2020-12-22 @ 8PM and revert at 2020-12-22 @ 9PM(tentative)

**Comment by c3bryant** [comment]
This is done when:
- [ ] Scanner maintenance page deployed to prod on 2020-12-22 @ 8PM
- [ ] Scanner maintenance page taken down in prod after 2020-12-22 @ 9PM (tentative)
