### ISSUE TITLE
Advanced Wayfinding Updates

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1153]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-86
 
- [x] Add DEVICE_CATEGORY to logged data (e.g. phone, headset, computer)
- [x] On device, log only data that is within X miles of Price Center (X miles is configurable outside of the app)
- [x] Log OS attribute for scanned device "iOS" or "non-iOS"
- [x] Explore the need for any supplemental debug/logging info (@p8gonzal)
<br>
- [x] PR branch pushed with AWS test API (@p8gonzal)
- [x] [PR 1239 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B49984266-741D-4116-B5C8-1039A9703B35%7D&file=PR-1239-Test-Plan-7.6.0-QA-1262.xlsx&action=default&mobileredirect=true) PASS on iOS (lukedutta9, gmihir) (TEST DB)
- [x] [PR 1239 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B49984266-741D-4116-B5C8-1039A9703B35%7D&file=PR-1239-Test-Plan-7.6.0-QA-1262.xlsx&action=default&mobileredirect=true) PASS on Android (lukedutta9, gmihir) (TEST DB)
<br>
- [x] PR branch pushed with QA API (p8gonzal)
- [x] [PR 1239 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B26EE5EC9-4BCD-4159-9286-9F3559950650%7D&file=PR-1239-Test-Plan-7.7.0-QA-1289.xlsx&action=default&mobileredirect=true) PASS on iOS (@kevdesilva01) (QA DB)
- [x] [PR 1239 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B26EE5EC9-4BCD-4159-9286-9F3559950650%7D&file=PR-1239-Test-Plan-7.7.0-QA-1289.xlsx&action=default&mobileredirect=true) PASS on Android (@asg003) (QA DB)

https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B26EE5EC9-4BCD-4159-9286-9F3559950650%7D&file=PR-1239-Test-Plan-7.7.0-QA-1289.xlsx&action=default&mobileredirect=true

**Comment by p8gonzal** [comment]
PR 1215
