### ISSUE TITLE
Spanish Scanner iPad App

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1156]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The iPad scanner app supports the Spanish language
- [x] [PR 41 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BCD839E86-E5DE-477D-826B-06158B9409DE%7D&file=Regression-Test-Plan-PR-41-QA.xlsx&action=default&mobileredirect=true&cid=59b41e16-e842-427d-96ca-395d29c51a72) PASS on iPad (@gmihir, @asg003, @c3bryant)

**Comment by a6wu** [comment]
@lukedutta9 Can you please provide an ETA on the PR? We want to get this out to the Store this month.

**Comment by lukedutta9** [comment]
PR [#41](https://github.com/a6wu/mobile-qr-scanner/pull/41) requested for mobile qr scanner.
