### ISSUE TITLE
Scan Confirmation Screen for Staff

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1159]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] Staff sees MyUCSDChart instead of MyStudentChart on the confirmation screen.
- [x] The confirmation screen content is loaded from the CMS
- [x] [PR 1162 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B80FCEDF5-37C7-4E8A-8292-F85E4BB78EC7%7D&file=PR-1162-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (@gmihir)
- [x] [PR 1162 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B80FCEDF5-37C7-4E8A-8292-F85E4BB78EC7%7D&file=PR-1162-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android

<img src="https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/7a09ab32-1eff-4959-91b5-f73371c70b5f" width="300">

**Comment by gmihir** [comment]
Both iOS and Android pass as per https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/doc2.aspx?sourcedoc=%7B80FCEDF5-37C7-4E8A-8292-F85E4BB78EC7%7D&file=PR-1162-Smoke-Test.xlsx&action=default&mobileredirect=true&cid=57c32a2f-66e8-40a8-a8cf-df2e30b3750b.

**Comment by g9singh** [comment]
iOS: Pass
android: Pass
results: https://ucsdcloud.sharepoint.com/:x:/s/WorkplaceTechnologyServices-CampusMobileBuilds/EaDoeY2G4tZDvP4c-pK9dDUBb3QueKb4w6ZOIWYPa9LBTg?e=D99lkE
