### ISSUE TITLE
COVID Test Kits Vending Machine Search

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1164]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-99

This is complete when:

- [x] The maps search has an icon shortcut for COVID test kits vending machines. Perhaps replacing "Mail" icon.
- [x] [PR 1174 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B2BF4B38E-4947-425D-9DC6-65564D162CF5%7D&file=PR-1174-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (@c3bryant)
- [x] [PR 1174 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B2BF4B38E-4947-425D-9DC6-65564D162CF5%7D&file=PR-1174-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (@c3bryant)

<img src="https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/1657e34c-b282-4fa8-8933-b1e73fb3f150" width="300">

**Comment by woznaut** [comment]
Does the data already exist for this filter?

**Comment by a6wu** [comment]
@woznaut  Yes
