### ISSUE TITLE
Card for COVID Test Kits Vending Machine Locations

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1165]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-99

This is complete when:
- [x] The `COVID-19 Info` card for Staff and Students includes a deep link to `COVID-19 Test Kit Vending Machines` on the Maps tab
- [x] [PR 1175 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B4B686702-2D4B-4FC0-9781-FDB1EB2E2409%7D&file=PR-1175-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on iOS (sramcode)
- [x] [PR 1175 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B4B686702-2D4B-4FC0-9781-FDB1EB2E2409%7D&file=PR-1175-Test-Plan.xlsx&action=default&mobileredirect=true) PASS on Android (lukedutta9)

References:
- Deep linking integration for iPad ([6647087](https://github.com/a6wu/mobile-qr-scanner/commit/6647087024c3ab6fe44efc811e2e2d34f316de3e), [fb1b25c](https://github.com/a6wu/mobile-qr-scanner/commit/fb1b25cd69d1914fbac296d30db74b81b18018d9))

**Comment by c3bryant** [comment]
`Self-Administered Testing Locations` link added to `campus_info`, `student_info`, `staff_info` cards in PROD/QA
