### ISSUE TITLE
iPad: Barcode Scan Verification

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1173]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:
- [x]  The scanner performs three scans, without user intervention
- [x]  If the three scans return the same barcode value, then the scan is valid
- [x]  If any of the three scans do not match in barcode values, then the scan is not valid
- [x]  If the scan is not valid, then the user sees the "red x" message
- [x] Tested successfully on iPad (@c3bryant)

References:
- Campus Mobile [Barcode Scan Verification PR 1172](https://app.zenhub.com/workspaces/campus-mobile-replatform-59791ae0251e9315c45be418/issues/ucsd/campus-mobile/1172)

**Comment by g9singh** [comment]
completed with commit hash: d4da3239f64d72e8be8f04df1d9e48a7dac7966e
PR submitted
