### ISSUE TITLE
Location Prompt Bug

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1178]
Time Tracking: MA-34

From a user:
> I discovered a bug in the mobile app. When I open the app it asks if I want to turn on my Location for a better experience. When I say No, it pops up again for a total of 5 times before the app crashes. My device is an Android – Moto Z Play Droid.

This is done when:
- [x] Shuttle location provider refactored
- [x] Wayfinding location provider refactored
- [x] FutureBuilder used inside Wayfinding StreamBuilder for local permission availability (@asg003)

- [x] PR 1405 Test Plan PASS on iOS
- [x] PR 1405 Test Plan PASS on Android

**Comment by g9singh** [comment]
Tried to reproduce on my nexus 5 using the following builds:
7.2.15 PROD
7.2.14 Prod
DEV build from experimental branch

Was unable to reproduce on any of the following branches. 
The device is running android version 6.0.1.

**Comment by a6wu** [comment]
@g9singh  Is there Moto Z Play Droid device on one of the device farms?

**Comment by gmihir** [comment]
Could not reproduce on Samsung Galaxy S6 on experimental or current production version from the Play Store. Currently running Android 8.0.0

**Comment by g9singh** [comment]
@a6wu I just ran it on [device farm](https://us-west-2.console.aws.amazon.com/devicefarm/home?region=us-west-2#/projects/e22a4579-3e1e-4fde-b696-2466513cc77b/runs/5468d412-fd2d-4fb6-a337-63fce008c524/jobs/00000). 

Unfortunately it does not reproduce the bug.

**Comment by g9singh** [comment]
From my initial research we have 4 options for other device farm like services:

- Firebase test labs: https://firebase.google.com/docs/test-lab/android/available-testing-devices
     - doesn’t support Moto Z
	
- Kobiton: https://docs.kobiton.com/devices-list/
     - supports Moto Z and many other devices

- Sauce labs: https://saucelabs.com/platform/supported-browsers-devices
     - does not support Moto Z
     - appears to be more expensive than Kobiton

- Xamarin Test Cloud (Now App Center Test)
     - does not Moto Z
     - supports many other devices

@c3bryant do you have any suggestions/preferences based on the CI/CD setup we have?

**Comment by asg003** [comment]
Reproduced on Samsung S7 running Android 8.0.0 using build 7.6.0 QA and 7.5.0 QA. App crashes in both instances whether accepting or declining to turn on device location. 

![Screenshot_20210218-151712_Google Play services](https://user-images.githubusercontent.com/49219707/108545618-df321c80-729c-11eb-9998-a3faa87e1e1b.jpg)

**Comment by g9singh** [comment]
Upon further investigation, it seems that the app is requesting permissions again from the wayfinding feature. We already have a LocationDataProvider that handles the permissions and returns a stream of coordinates. Please use that instead of a creating a new instance of the Location object.

Once the wayfinding feature is refactored to use the LocationDataProvider the permissions issue should be resolved.

**Comment by asg003** [comment]
Shuttle feature also creates another instance of the Location object and needs to be refactored to use stream from LocationDataProvider.

**Comment by kevdesilva01** [comment]
Test passed but Scans are being logged in the wrong folder in S3. I opened a new issue after speaking with Alex regarding this. #1422

**Comment by c3bryant** [comment]
Data logs going to the wrong folder has been resolved.

Ran into a bug when denying location permission. With location denied, a few areas in the app like location to dining eateries show a large distance (8000~mi). This distance matches the distance between the eatery and coordinates 0,0. It is likely that the location provider is reporting Lat:0 Lon:0 for the user's location when they have denied location access.

<img width="300" src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/8d57bb25-d4af-4892-b741-2933dff096d9">

**Comment by c3bryant** [comment]
Data logs going to the wrong folder has been resolved.
