### ISSUE TITLE
Update scanner code structure

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#1187]
ITS-pro time tracking: MA-74

This task is complete when:
- [x] There is a scanner data provider
- [x] State and data related functions are moved out of the UI file and put into the scanner data provider
- [x] [PR 1248 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BAD500B52-C4D5-433F-B5A6-313477685D95%7D&file=PR-1248-Test-Plan-7.7.0-QA-1283.xlsx&action=default&mobileredirect=true) PASS on iOS (c3bryant)
- [x] [PR 1248 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BAD500B52-C4D5-433F-B5A6-313477685D95%7D&file=PR-1248-Test-Plan-7.7.0-QA-1283.xlsx&action=default&mobileredirect=true) PASS on Android (asg003)

A good reference to use is the iPad scanner because it has the similar code but has the correct structure.
https://github.com/a6wu/mobile-qr-scanner

**Comment by gmihir** [comment]
Failed testing on iPhone, notes on test plan

**Comment by kevdesilva01** [comment]
Failed testing on Android, experienced same issues as Mihir ^^

**Comment by g9singh** [comment]
Updated code. Please try again.

**Comment by gmihir** [comment]
Passes on iPhone (TestFlight 1255)

**Comment by kevdesilva01** [comment]
passes on android
