### ISSUE TITLE
Video of Advanced Wayfinding Toggle

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1189]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-31

This is complete when:

- [x] A video shows the user enabling the Advanced Wayfinding feature

**Comment by a6wu** [comment]
@sramcode  Can you please combine the two videos and walk through the entire user flow.

1. Home view
2. Tap on Profile view
3. Then Advanced Wayfinding
4. Toggle on feature

Thank you.

**Comment by sramcode** [comment]
https://images.zenhubusercontent.com/62921972/aade960e-fedf-4321-91e1-6c8199b16792/advanced_wayfinding_flow.mov
