### ISSUE TITLE
WebCard to Not Reload Default URL

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1194]
ITS-Pro category: https://its-pro.ucsd.edu/browse/MA-66

Explore options and see why the default URL is reloading.
 
This is complete when:
- [x] The WebCard does not reload the default URL when submitting the web form, e.g. https://eforms.ucsd.edu/view.php?id=537412
- [x] [PR 1244 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B67E8F5DD-8E7F-481E-935B-D0AF29B9321F%7D&file=PR-1244-Test-Plan-7.6.0-QA-1265.xlsx&action=default&mobileredirect=true) PASS on iOS (sramcode)
- [x] [PR 1244 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B67E8F5DD-8E7F-481E-935B-D0AF29B9321F%7D&file=PR-1244-Test-Plan-7.6.0-QA-1265.xlsx&action=default&mobileredirect=true) PASS on Android (c3bryant)

**Comment by gmihir** [comment]
It seems that listening to a URL change is not possible, looked at quite a few things online (ex: https://github.com/flutter/flutter/issues/27729). Instead, I have an implementation where redirects are accomplished via a JS channel and actually executed on the flutter side (via WebViewController). The reload url is also set to the new url, so tapping 'reload' will not revert to the initial URL. I'm not sure if this is an adequate solution to the issue.
