### ISSUE TITLE
Last Successful Scan Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1196]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-42?filter=allissues

This is complete when:

- [x] The UI has been updated to be more intuitive. The goal is to display the last successful scan date to the user.
- [x] `COVID-19 Scan Status` card activated for Students and Staff
- [x] Testing PASS in QA [[Test Plan]](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120002D1EBB137A0D9A4AB18E3FD37624305E&id=%2Fsites%2FWorkplaceTechnologyServices%2DCampusMobileBuilds%2FShared%20Documents%2FCampus%20Mobile%20Builds%2FPull%20Request%20Testing%2FIssue%2D1196%2DLast%2DSuccessful%2DScan%2DCard%2DTesting%2Epdf&parent=%2Fsites%2FWorkplaceTechnologyServices%2DCampusMobileBuilds%2FShared%20Documents%2FCampus%20Mobile%20Builds%2FPull%20Request%20Testing) (evelynnelee)
- [x] Testing PASS in PROD

<img src="https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/7c2cc7e0-171e-443b-9e61-6a83378b8ec7" width="400">

**Comment by woznaut** [comment]
a couple options here, we could integrate it into the scanner card (cleaner, intuitive) or we could make it a stand alone at the top of the stack (more visible but less intuitive)

![LastScan_scanner](https://user-images.githubusercontent.com/19195410/106198190-93da9180-6168-11eb-9b2d-3257f672f37e.png)
![LastScan_standalone](https://user-images.githubusercontent.com/19195410/106198203-9806af00-6168-11eb-81c9-5ccc492936cc.png)

**Comment by a6wu** [comment]
Draft implementation on QA at https://mobile.ucsd.edu/replatform/v1/qa/webview/my-recent-scan.html

**Comment by c3bryant** [comment]
Activated in QA and PROD for Students and Staff in DefaultCards v4

Card ID: `ScanStatus`
Card Title: `COVID-19 Scan Status`
Card URL: `https://mobile.ucsd.edu/replatform/v1/(qa|prod)/webview/my-recent-scan.html`
