### ISSUE TITLE
Deploy DefaultCards v4 API

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1197]
Time Tracking: MA-80

Summary: DefaultCards v4 required for a breaking change in #1140 (completed in #1193) for Campus Mobile v7.5.0+

This is done when: 
- [x] DefaultCards v4 deployed to AWS Prod
    - [DefaultCardsList Lambda QA](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DefaultCardsList/aliases/v4?tab=configuration)
    - [DefaultCards v4 API QA](https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/rj786p8erh/resources/028fy5/methods/GET)
- [x] DefaultCards v4 deployed to APIM Prod
    - In Progress: [CS0408162](https://ucsdservicedesk.service-now.com/its?id=ticket&table=sn_customerservice_case&sys_id=7a84b5541b4a6050df40ed7dee4bcb0e)

**Comment by a6wu** [comment]
@c3bryant Lambda and API for v4 added. However, https://mobile.ucsd.edu/replatform/v1/prod/cards/visitor_cards-v4.json and others do not exist.
