### ISSUE TITLE
Allow Active Students and Staff Access to Scan

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1200]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The the scanner card is only available to active students and staff

**Comment by a6wu** [comment]
This is in place now. However, the affiliation code may not be updated in real-time in the system.

**Comment by c3bryant** [comment]
The Scanner card is only available for active students and staff, based on their returned affiliation code, which the mobile app updates at every login or silent login (re-authentication) attempt.
