### ISSUE TITLE
RTL Dashboard

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1208]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-99

This is complete when:
- [x] A WebCard displays the following dashboard
- [ ] [PR 1236 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B03D3EDA8-8296-430C-AF84-6EFA5E929F3B%7D&file=PR-1236-Test-Plan-7.6.0-QA-1256.xlsx&action=default&mobileredirect=true) PASS on iOS (@evelynnelee) (Failed)
- [ ] [PR 1236 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B03D3EDA8-8296-430C-AF84-6EFA5E929F3B%7D&file=PR-1236-Test-Plan-7.6.0-QA-1256.xlsx&action=default&mobileredirect=true) PASS on Android (@gmihir)  (Failed)

Resources:
- RTL Dashboard embed code
```html
<style>
  .embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object {position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}
</style>
<div class="embed-container">
  <iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Return to Learn: Wastewater Monitoring Dashboard" src="https://experience.arcgis.com/experience/bf6b605220284ef397fb95a9b046ea9e/"></iframe>
</div>
```

Note: some investigative work needed to get the correct style and formatting

**Comment by sramcode** [comment]
**Notes about known issues:**

- As a web card, the RTL Dashboard does not scroll

- The right half of the information that is on the actual RTL Dashboard website does not appear/fit on the web card

- RTL Dashboard map scrolls, but might interfere with the scrolling of the card to see all the info (if the scrolling of the whole card is possible)

**Comment by a6wu** [comment]
Thanks @sramcode. Let's figure out which portion of the dashboard would make sense on a WebCard. I'll connect with you on this.
