### ISSUE TITLE
App in Foreground Receives Push Notification Prompt 

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1209]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-60

This is complete when:
- [x] Push notifications are received when the app is in the foreground on iOS
- [x] Push notifications are received when the app is in the foreground on Android

- [x] [PR 1301 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BF6DD69B1-99A3-4041-95AB-0B87A59EDA33%7D&file=PR-1301-Test-Plan-7.8.0-QA-1317.xlsx&action=default&mobileredirect=true) PASS on iOS (@evelynnelee)
- [x] [PR 1301 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BF6DD69B1-99A3-4041-95AB-0B87A59EDA33%7D&file=PR-1301-Test-Plan-7.8.0-QA-1317.xlsx&action=default&mobileredirect=true) PASS on Android (@lukedutta9)

References:
- iOS: https://pub.dev/packages/flutter_local_notifications#-ios-setup
- Android: https://pub.dev/packages/flutter_local_notifications#-android-setup

https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by kevdesilva01** [comment]
Note: When foreground push notification comes in, the app automatically reroutes to the notifications tab no matter what screen it's on. There is logic to route to the maps tab on the background & app closed push notifications on-click, but foreground doesn't have that, so my thought is that it has to be something else.

**Comment by kevdesilva01** [comment]
The automatic rerouting has been disabled, now working on making the route to the notifications tab on click of the push notification.

**Comment by lukedutta9** [comment]
Android testing all PASS
