### ISSUE TITLE
Map: Directions button

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1211]
Time Tracking: MA-81

This is done when:
- [x] A 'Directions' icon is displayed in the lower-right corner of the map which links externally to provide walking directions from their current location to the destination.
- [x] [PR 1230 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B280EAF5A-66B0-4E70-8624-EBF966070AC9%7D&file=PR-1230-Test-Plan-7.6.0-QA-1258.xlsx&action=default&mobileredirect=true) PASS on iOS (sramcode)
- [x] [PR 1230 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B280EAF5A-66B0-4E70-8624-EBF966070AC9%7D&file=PR-1230-Test-Plan-7.6.0-QA-1258.xlsx&action=default&mobileredirect=true) PASS on Android (c3bryant)
- [x] Experimental branch updated and merged into PR 1230 (lukedutta9)

Web Directions via Address
    - https://maps.google.com/maps?saddr=Current+Location&daddr=${directionsAddr}&dirflg=w

Web Directions via Coords
    - https://www.google.com/maps/dir/?api=1&destination=${model.coordinates.lat},${model.coordinates.lon}&travelmode=walking

**Comment by lukedutta9** [comment]
Submitted PR #1230 for this issue
