### ISSUE TITLE
Advanced Wayfinding: SCANNED_DEVICE_ADVERTISEMENT_ID Format

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1213]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-86

This is complete when:
- [x] The SCANNED_DEVICE_ADVERTISEMENT_ID format corresponds to the format used by SOURCE_DEVICE_ADVERTISEMENT_ID, if applicable, e.g. 08506708-3068-0650-8008-0A82D0BB9C2E.

- [x] [PR 1419 Test Plan] (https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1419-Test-Plan-7.8.0-QA-1491.xlsx?web=1) PASS on iOS
- [x] [PR 1419 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1419-Test-Plan-7.8.0-QA-1492.xlsx?web=1) PASS on Android

**Comment by p8gonzal** [comment]
Scan from earlier this morning. 
Scanning device: iPhone 7 Plus running iOS 14.4
Scanned device: iPhone 11 Pro Max running iOS 14.5
First entry is SCANNED_DEVICE_ADVERTISEMENT_ID.
<img width="1367" alt="Screen Shot 2021-02-02 at 6 12 20 AM" src="https://user-images.githubusercontent.com/42155702/106616090-001b1380-6522-11eb-83eb-36fa5fba9402.png">

**Comment by a6wu** [comment]
Thanks @p8gonzal

**Comment by a6wu** [comment]
@p8gonzal Can you confirm if the value in the screenshot "08506708..." is for SCANNED_DEVICE_ADVERTISEMENT_ID and if it can be in the hyphenated format used by SOURCE_DEVICE_ADVERTISEMENT_ID?

**Comment by p8gonzal** [comment]
@a6wu Yes the value in the screenshot is for SCANNED_DEVICE_ADVERTISEMENT_ID. It can be hyphenated to match format used by SOURCE_DEVICE_ADVERTISEMENT_ID but it will require an app update. Let me know if we should move forward with that.

**Comment by a6wu** [comment]
@Yes, let's move forward. It'll help with analyzing the data.
