### ISSUE TITLE
Advanced Wayfinding Test

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1214]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-86

This is complete when:

- [x] Two phones running the campus mobile app submits a log. The expected results is that device A scans device B, and device B also scans device A, within the same time range. The log in prod should show that SOURCE_DEVICE_ADVERTISEMENT_ID and SCANNED_DEVICE_ADVERTISEMENT_ID have matching values.

**Comment by p8gonzal** [comment]
There seems to be an issue where iPhone 7 Plus cuts off last 2 digits for SCANNED_DEVICE_ADVERTISEMENT_ID when scanned a Pixel 2a. Pixel 2a reads in iPhone 7 Plus SCANNED_DEVICE_ADVERTISEMENT_ID correctly.
Android Pixel 2a: 
SOURCE_DEVICE_ADVERTISEMENT_ID: 08506708-3068-0650-8008-087B1CFA64E6
iPhone 7 Plus:
SOURCE_DEVICE_ADVERTISEMENT_ID: 08506708-3068-0650-8008-0BD8CA6FEEBD

Source: iPhone 7 Plus. Missing 'E6' for SCANNED_DEVICE_ADVERTISEMENT_ID
<img width="1291" alt="Screen Shot 2021-02-02 at 6 59 14 AM" src="https://user-images.githubusercontent.com/42155702/106619129-1c6c7f80-6525-11eb-8050-a3033449488a.png">

Source: Pixel 2a. Correct SCANNED_DEVICE_ADVERTISEMENT_ID
<img width="1379" alt="Screen Shot 2021-02-02 at 7 01 36 AM" src="https://user-images.githubusercontent.com/42155702/106619296-4c1b8780-6525-11eb-9836-6f7d2e92b334.png">

**Comment by a6wu** [comment]
Verified in the logs.
