### ISSUE TITLE
Migrate to new AWS Sandbox

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1218]
Time Tracking: MA-115

This is done when:
- [x] Tasks described in [https://go.ucsd.edu/31cyC82](https://go.ucsd.edu/31cyC82) completed

**Comment by a6wu** [comment]
@c3bryant  @techied  I will rework this and create more detailed document.

**Comment by c3bryant** [comment]
- DynamoDB migration completed
- API and Lambda migration on hold until 06/28/21
