### ISSUE TITLE
Staff ID overflow

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1224]
Time Tracking: MA-89

- Staff ID card information can overflow the card content area on smaller devices. The card can be scrolled to the right, which degrades app performance, making the app unusable for a time
- Reported in 7.5 regression testing

This is done when:
- [x] Staff ID card information renders within the card content area, and does not horizontally scroll
- [x] Testing PASS in QA
- [x] Testing PASS in PROD

**Comment by c3bryant** [comment]
Before:
<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/ffba8224-dcd4-4962-878b-7416ba449ace" width="400">

After:
<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/772def93-94cb-4779-988c-1163ec23c278" width="400">

Ready for testing

**Comment by gmihir** [comment]
Tested on QA and PROD on iPhone, Android, and iPad.

For PROD testing, I downloaded the app from the App Store/Play Store.

- iPhone: PASS (QA and PROD)
- Android: FAIL (QA good, PROD has old staff ID still)
- iPad : PASS (QA and PROD)

**Comment by c3bryant** [comment]
Thank you for testing, @gmihir 

Would you mind re-testing Android PROD on the new 7.5 (Build 1228)? Store rollout is underway for 7.5 but it looks like it wasn't available yesterday morning.

**Comment by kevdesilva01** [comment]
Tested on iOS and Android 

PROD: 
iOS: Pass
Android: Pass

QA:
iOS: Pass
Android: Pass

**Comment by gmihir** [comment]
Resolved on Android after latest update from Play Store
