### ISSUE TITLE
Standalone Scanner Occasionally Freezing Pixel 2a

### ISSUE THREAD

**Issue by p8gonzal** [UCSD/campus-mobile#1228]
Time Tracking: MA-74

Observed on Pixel 2a. 
Scanning on Standalone Scanner 3 times causes freezing, scans complete after a lapse of time.
Standalone scanner is opened from a third party app seems to cause this issue. 
It is not evident when Standalone Scanner is opened directly from browser.

**Steps to reproduce:**
On Pixel 2a, open link from Microsoft Teams.
Scan a barcode. 
Repeat 3 times.

This is done when:
- [ ] Pixel 2a freeze has been resolved

**Comment by c3bryant** [comment]
Open issue regarding MS Teams app crashing when using the camera:  https://answers.microsoft.com/en-us/msteams/forum/msteams_tfb-msteams_meeting-msteams_audio/ms-teams-crashes-when-using-a-camera/7b4252e3-5334-4bfb-9067-f3725eb50985?page=1

Launching the Standalone Scanner from a MS Teams app external link will not be supported until MS addresses the issue above. Deferred.
