### ISSUE TITLE
WiFi Survey Card Text Cutoff

### ISSUE THREAD

**Issue by p8gonzal** [UCSD/campus-mobile#1237]
Observed on iPhone 11 Pro Max.
A bug in dynamic height for the survey WiFi card causes 'Submit' button text to be cut off.

This is done when:
- [x] Student Survey card displays the full survey
- [x] Testing PASS in QA

https://user-images.githubusercontent.com/42155702/107805966-fc09a580-6d1a-11eb-9a95-3b89b64650f5.MP4

**Comment by c3bryant** [comment]
Ready for testing in QA
