### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#124]
Update screenshots to match March 2017 release.

**Comment by c3bryant** [comment]
Screenshots from March 2017 release to display:

[iPhone Screenshots.zip](https://github.com/UCSD/campus-mobile/files/862239/iPhone.Screenshots.zip)

[Android Screenshots.zip](https://github.com/UCSD/campus-mobile/files/862235/Android.Screenshots.zip)

Additional instruction:
- Image size should be similar to old screenshots 
- Align the images horizontally per device type
- Add corresponding iPhone/Android header text above image rows

**Comment by a6wu** [comment]
Completed.
