### ISSUE TITLE
Vending Machine Update Information

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1249]
ITS-Pro time tracking: https://its-pro.ucsd.edu/projects/MA/issues/MA-42?filter=allissues

This is complete when:

- [x] Options are presented for displaying the following information: Campus ID Needed for COVID Vending Machines Students and campus employees will soon be required to swipe their campus ID card when picking up a self-administered test kit from a vending machine.

**Comment by woznaut** [comment]
1. Notifications. A series of them spaced out over a few days or weeks.
2. Link on Covid-19 Info card - "Vending Machines" - links directly to the page/section about the Vending Machines on the RTL site.
3. Temporarily replace the promo banner from the current "Add CA Covid Notify" to a banner about the Campus ID requirement. Content to mimic whatever is created for RTL.

**Comment by a6wu** [comment]
@woznaut Confirmed to go with #3 option.

**Comment by c3bryant** [comment]
\#3 Done in QA (7.6 build 1270)
Link: https://go.ucsd.edu/2A9wdkI
Awaiting go-live direction

**Comment by c3bryant** [comment]
Live in prod
