### ISSUE TITLE
Staff ID WebCard Cutoff

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1250]
Time Tracking: MA-34

It was reported that the Staff ID card is rendering in a collapsed state, preventing the user from seeing their full Staff ID card.
Investigate and resolve.

This is done when:
- [x] Staff ID card handles the case of empty string/null data elements returned from the MyStaffProfile API

<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/f4310b1a-7411-4a38-8994-db1ac40f78a7" width="400">

**Comment by c3bryant** [comment]
- Unable to reproduce with p8gonzal on 2021-02-19
- Screenshots indicate data elements from MyStaffProfile API like Name, Dept, Emplid were not being returned on 2021-02-18
- Updating issue with instruction to handle the case where the MyStaffProfile API returns empty or invalid response with status code 200

**Comment by c3bryant** [comment]
Debugged a bit further. When the issue was reported, the API was in a broken state, where it was returning status code 200 (Success) but all data fields were empty strings `""`, which looked like this:
![Screen Shot 2021-02-25 at 11.45.44 AM.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/ed550576-8df6-42f9-8522-c0ce871f4c60)


Resolved a bug where the card height was only being set after rendering the barcode, which was only called if the barcode was not an empty string. If the API enters this broken state again, the card will now look like this:
![Screen Shot 2021-02-25 at 11.47.20 AM.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/ef1c7f51-c79b-4fe4-aeab-570c7d2ec33c)

Verified and deployed to QA & PROD

@woznaut Should we revisit which data elements are required in order to render the Employee ID card metadata vs. falling back to 'An error occurred, try again' user-facing message?

Currently the Staff ID card tries to render any data elements returned (Name, Dept, Emplid, Barcode) and will only show a user-facing error when the API returns a status code that is not 200

**Comment by woznaut** [comment]
Name, EmpID and Barcode should be required. Dept I'm on the fence about. 

Error message:
Unable to display Staff ID. 
If the problem persists, contact the [ITS Service Desk](http://blink.ucsd.edu/go/servicedesk).

**Comment by c3bryant** [comment]
Thanks woznaut
I have added issue #1277 for employee id validation
