### ISSUE TITLE
iPad Student name on ID Card

### ISSUE THREAD

**Issue by evelynnelee** [UCSD/campus-mobile#1254]
Time Tracking: MA-93

Student name on ID Card for iPad is having sizing issues where to name is smaller than the college and major. 

This is done when:
- [x] Student name on ID cards for iPad sized correctly with other text

![image](https://user-images.githubusercontent.com/46549895/108542606-cd4e7a80-7298-11eb-9233-f94ba1b9250c.png)

**Comment by keskinmbaha** [comment]
After testing on 3 different iPad simulations and on my own iPad with the app from the app store, the issue seems to have been resolved with a previous update.
