### ISSUE TITLE
Refactor Shuttle Location

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1261]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-102

This is complete when:

- [x] Shuttle has been broken up into appropriate model, service and provider files.
- [x] The shuttle data provider does not use its own location package
- [x] The shuttle data provider uses the locations data provider to access locations
- [x] The shuttle data provider does not prompt the user for location services directly
- [x] User profile tab reloading bug resolved
- [x] Testing PASS in QA

**Comment by g9singh** [comment]
pushed most recent changes to: https://github.com/g9singh/campus-mobile/tree/bugs/shuttle-provider-refactor%231261

There still seems to be an issue with the coordinates being null in the way finding data provider. (See the debug output for more detailed info)
