### ISSUE TITLE
Persistent Login Not Working

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1262]
ITS-PRO: MA-59

Problem: 
> Users seemed to be getting logged out of the UC San Diego app. They they have to remember the username and password. Is there a something trigger in the app. The seem to correlate it to when they go from from cellphone data to wifi.

Cause:
Prior to refresh token deprecation, the app would continue to retry requests in a `login->failed->refresh token->login` loop, even after the user has lost internet connectivity. When the user's internet connectivity was restored, this loop would generally re-authenticate the user with a new access token.

With the refresh token method now deprecated, if a user's access token expires while using the app offline, the app will attempt to login the user if an SSO authenticated request is made (i.e. Class Schedule, which will fail), causing them to be logging out.

This is done when:
- [x] Re-authentication mechanism with exponential backoff incorporated into SSO login
- [x] On re-authentication failure, display alert dialog "You have been logged out"
- [x] Testing PASS in QA

**Comment by a6wu** [comment]
@woznaut  Need a UI for "offline" notice to users.

**Comment by p8gonzal** [comment]
Here is a package to determine network connection, used for WiFi Speed Test Card: https://pub.dev/packages/connectivity
