### ISSUE TITLE
MyRecentScan QA API

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1265]
ITS-PRO: MA-74

Scan Status card in QA is pointing to MyRecentScan API in PROD. This is causing confusion and false-positives in development and testing.

This is done when:
- [x] ScanData V2 MyRecentScan QA API is available
- [x] ScanData V2 MyRecentScan QA API pulls scan data from QA

**Comment by a6wu** [comment]
@c3bryant  Updated QA API to point to QA instance, /qa/2.0.0/scanData/myrecentscan. Please verify.

**Comment by c3bryant** [comment]
@a6wu Thanks for the update.

In QA testing, we noticed an issue. Seeing a an empty-string response w/ status code 200
```json
{
    "Collection Date/Time": ""
}
```

**Comment by a6wu** [comment]
@c3bryant Verified working on QA build. Had to change from Node.js runtime from 14.x to 12.x.

**Comment by c3bryant** [comment]
Looks good here as well - thank you.
