### ISSUE TITLE
Deploy DefaultCards v5 & v6 API

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1266]
Time Tracking: MA-80

Summary: DefaultCards v5 & v6 ready to deploy
- v5 is a dependency for 7.7
- v6 is anticipatory for 7.8

This is done when:
- [x] DefaultCards v5 & v6 JSON deployed to CMS PROD (@c3bryant)
- [x] DefaultCards v5 & v6 deployed to AWS Prod (@a6wu)
    - [DefaultCardsList v5 Lambda QA](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DefaultCardsList/aliases/v5?tab=configuration)
    - [DefaultCardsList v6 Lambda QA](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DefaultCardsList/aliases/v6?tab=configuration)
    - [DefaultCards API QA](https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/rj786p8erh/resources/028fy5/methods/GET)

- [x] DefaultCards v5 & v6 deployed to APIM Prod (APIM)
    - Ticket: [CS0443121](https://ucsdservicedesk.service-now.com/its?id=ticket&table=sn_customerservice_case&sys_id=a036ed4e1b626c10df40ed7dee4bcb1d)

**Comment by a6wu** [comment]
@c3bryant Updated AWS Prod
