### ISSUE TITLE
Integrate Student Health & Wellbeing Information

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1276]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-116

This is complete when a WebCard has been add with the following:

- [x] Available to Visitor and Students, not for Staff
- [x] Card title is Student Health and Wellbeing (or use &)
- [x] Links:
Getting Started: https://caps.ucsd.edu/make-appointment/appointments.html
Tritons Flourish: https://caps.ucsd.edu/programs/flourish.html#Handouts-and-Flyers
Health Coaching: https://healthpromotion.ucsd.edu/services/health-coaching/index.html
Stress Management/Resilience: https://healthpromotion.ucsd.edu/services/resilience-lab/index.html
iFlourish: https://caps.ucsd.edu/resources/iflourish.html

**Comment by c3bryant** [comment]
Testing notes:
- Card title/id includes `Wellness` and not `Wellbeing`
- Card not yet activated for Students (student_cards-v4)
