### ISSUE TITLE
Android Splash Screen Incorrectly Sized

### ISSUE THREAD

**Issue by gmihir** [UCSD/campus-mobile#1293]
ITS-PRO: MA-34

The splash screen on Samsung Galaxy S7 is not correctly sized. 

This is done when:
- [ ] Splash screens correctly sized on Android

<img src="https://user-images.githubusercontent.com/13931192/112219476-461b5c00-8be2-11eb-9dc4-884c66c150bb.png" width="400">

**Comment by keskinmbaha** [comment]
The dpi range I can test on using android emulator is 420dpi - 560dpi.

Works on:
Pixel 2 API 30 is 108 x 1920: 420dpi.
Pixel 4 API 30 is 1080 x 2280: 440dpi.
Pixel 5 API 30 is 1080 x 2030: 440dpi.
Pixel XL API 30 is 1440 x 2560: 560dpi

Does not work on:
Samsung Galaxy S7 is 1440 X 2560: 577dpi.

**Comment by c3bryant** [comment]
Deferred until the next platform upgrade
