### ISSUE TITLE
Add Dining Location to Occuspace

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1295]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-83

This is complete when:

Dining locations are added into the Availability card by fall quarter

**Comment by c3bryant** [comment]
@a6wu Dining locations are not returned from the Occuspace busyness API. Should we open this ticket with the vendor?

**Comment by c3bryant** [comment]
This task is also a requirement for in progress #1465 - closing.
