### ISSUE TITLE
Package Upgrade: flutter_blue

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1303]
Time Tracking: MA-95

This is done when:
- [x] [UCSD/flutter_blue](https://github.com/UCSD/flutter_blue.git) upgraded from [flutter_blue:0.8.0](https://pub.dev/packages/flutter_blue/versions/0.8.0) to support Flutter 2
- [ ] ~~[UCSD/flutter_blue](https://github.com/UCSD/flutter_blue.git) testing PASS in QA~~

- [x] iOS compilation issues resolved [(debug)](https://github.com/UCSD/flutter_blue/pull/1#pullrequestreview-634852072)
- [x] [UCSD/flutter_blue](https://github.com/UCSD/flutter_blue.git) testing PASS in QA

References:
- Android `rawData` field added in [0b61d66](https://github.com/UCSD/flutter_blue/commit/0b61d66f1020b9a066c0de4da7876bceb9e3039e)
- Branch `flutter-2` err: ![Screen Shot 2021-03-31 at 9 35 19 AM](https://user-images.githubusercontent.com/15112294/113179435-74adbe00-9204-11eb-8de1-303e2f989036.png)

**Comment by lukedutta9** [comment]
PR for the 0.8.0 update is on the UCSD flutter_blue fork.

https://github.com/UCSD/flutter_blue/pull/1
