### ISSUE TITLE
Package Upgrade: wifi_connection

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1305]
Time Tracking: MA-110

This is done when:
- [x] [wifi_connection](https://github.com/i8wu/WifiConnection) has been moved to [github.com/UCSD/wifi_connection](github.com/UCSD/wifi_connection)
- [x] [github.com/UCSD/wifi_connection](github.com/UCSD/wifi_connection) has been [migrated to null safety](https://dart.dev/null-safety/migration-guide)
- [x] [github.com/UCSD/wifi_connection](github.com/UCSD/wifi_connection) null safety version published
- [x] [Compilation error](https://github.com/UCSD/campus-mobile/issues/1305#issuecomment-823524427) resolved
- [x] New wifi_connection version published to pub.dev
- [x] [github.com/UCSD/wifi_connection](github.com/UCSD/wifi_connection) null safety version incorporated into campus mobile
- [x] Testing PASS

**Comment by p8gonzal** [comment]
WifiConnection v0.0.3 published: https://pub.dev/packages/wifi_connection and package repo redirects to UCSD null-safety version: https://github.com/UCSD/wifi_connection

**Comment by c3bryant** [comment]
I encountered an error when building for iOS device
```
    Command CompileSwift failed with a nonzero exit code
    /.pub-cache/hosted/pub.dartlang.org/wifi_connection-0.0.3/ios/Classes/SwiftWifiConnect
    ionPlugin.swift:20:33: error: consecutive statements on a line must be separated by ';'
            let interfaces = CNCogit pySupportedInterfaces() as! [String]
                                    ^
                                    ;
```

@p8gonzal would you try to reproduce on your end?

**Comment by p8gonzal** [comment]
Yes. Just tried to reproduce it and got the error when trying to build the example app. Will investigate it @c3bryant
