### ISSUE TITLE
Custom App bar not consistently updating when routing to different views

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#1306]
Time Tracking: MA-78

Steps to reproduce:
1. Go into a dining hall menu through the dining card
2. Press back to go to the home page, and go to a different view (events detail)
3. It should show "Dining" as the title instead of "Events"

Alternative way with foreground push notifications:
1. Be in any view other than the notifications tab
2. Send push notification while app is in the foreground and click on the notification
3. The app bar should show the title of whatever the previous screen was, instead of "Notifications"

This is done when:
- [x] Custom App bar titles change with the corresponding view 

- [x] [PR 1384 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1384-Test-Plan-7.8.0-QA-1487.xlsx?web=1) PASS on iOS
- [x] [PR 1384 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1384-Test-Plan-7.8.0-QA-1488.xlsx?web=1) PASS on Android

**Comment by c3bryant** [comment]
Dining/events issue in the description is resolved, however, I encountered a few issues in testing here. 

I was able to reproduce the issue using Manage Shuttle Stops, Add Shuttle Stop, Manage Spots, and Manage Lots views.

Sending your way @kevdesilva01
