### ISSUE TITLE
Campus Info Card Layout Fix

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1307]
ITS-Pro time card: https://its-pro.ucsd.edu/browse/MA-66

This is complete when:

- [x] The video is extracted into its own WebCard
- [x] The Campus Info card layout retains the links

![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/35dde344-b427-4bd3-a157-376c33a2459f)

**Comment by asg003** [comment]
1. Copy testing_kit_video.html (https://mobile.ucsd.edu/replatform/v1/qa/webview/testing_kit_video.html) into webview folder of prod folder
2. In staff-cards-v5.json, student-cards-v5.json, and visitor-cards-v5.json, add the following parameter above "campus_info": 
"testing_kit_video": {
    "cardActive": true,
    "initialURL": "https://mobile.ucsd.edu/replatform/v1/prod/webview/testing_kit_video.html",
    "isWebCard": true,
    "requireAuth": false,
    "titleText": "Testing Kit Instructions"
  },
This will create a new card with just the video. Some builds may use v6 cards lists, update this as well if needed. 
3. Copy the code from campus_info-v4.html in QA and paste it into campus_info-v4.html in prod. This will remove the video from the campus info card and only contain the two buttons. 
4. Make sure all changes have been published
