### ISSUE TITLE
Profile Sign In button outline missing

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1326]
ITS-PRO: MA-95

The Sign In button on the Profile tab has lost some styling in the Flutter 2 migration

This is done when:
- [x] Sign In button renders as it did pre-Flutter 2 migration

Flutter 1.22.6
<img width="300" src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/2496e131-3f10-43f6-938c-ec688efce740">

Flutter 2 (current)
<img width="300" src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/501036fb-c7ed-484f-88eb-d76e23e1bec2">

**Comment by gmihir** [comment]
Resolved issue but the text color is still incorrect, complete fix depends on #1329
