### ISSUE TITLE
Migrate dependencies to null safety

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1327]
ITS-PRO: MA-95

This is done when:
- [x] Test and upgrade to null-safe `https://github.com/UCSD/liquid_progress_indicator`
- [x] Test and upgrade to null-safe `background_fetch: 1.0.0-nullsafety.2`
- [x] Test and upgrade to null-safe`beacon_broadcast: 0.3.0-nullsafety.0`

**Comment by p8gonzal** [comment]
Tested https://github.com/UCSD/liquid_progress_indicator with Campus Mobile Speed Test, continues to work as usual. 'dart migrate' verifies compatible with null-safety.
