### ISSUE TITLE
API Deployment: WiFiTest v1.0.0

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1333]
ITS-PRO: MA-31

This is done when:
- [x] WiFiTest v1.0.0 resource naming conventions follow [REST API Guidelines](https://collab.ucsd.edu/display/API/REST+API+Guidelines) ([swagger](https://api-qa.ucsd.edu/publisher/api-docs/p2gonzalez/WiFiTest/v1.0.0))
- [x] WiFiTest v1.0.0 deployed to AWS PROD

**Comment by c3bryant** [comment]
WiFiTest Deployment Steps

## AWS
1. Checkout code from ___ source code repository
2. Install node modules
3. Create a Lambda function in AWS PROD called ____
4. Upload zip file from source code repository
5. Export WiFiTest API swagger from AWS QA
6. Modify API swagger export for PROD import (replace API Gateway ID with *)
7. Import WiFiTest API swagger to AWS PROD
8. Add execution permission for Lambda <-> API Gateway WiFiTest

**Comment by a6wu** [comment]
@c3bryant 

All items except #7 have been completed. Please help verify before I submit a ticket for deployment.
