### ISSUE TITLE
Verify Path to Weather Icons

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1336]
ITS-Pro time entry: MA-88

This is complete when:

- [x] The source of the weather icons have been identified

**Comment by c3bryant** [comment]
Weather icons hosted on ucsdtest S3 (ucsd-its-wts)
- Console: https://s3.console.aws.amazon.com/s3/buckets/ucsd-its-wts?region=us-west-2&prefix=images/v1/weather-icons/&showversions=false
- Endpoint: https://s3-us-west-2.amazonaws.com/ucsd-its-wts/images/v1/weather-icons/
- Example: https://s3-us-west-2.amazonaws.com/ucsd-its-wts/images/v1/weather-icons/clear-day.png
