### ISSUE TITLE
Pressing tab for current view

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#134]
Pressing tab for current view sometimes re-renders the view. This is an issue with react-native-tabs/react-native-router-flux, will see if we can get a PR merged into the actual node_module before making forking/hacking a fix into the app.

Needs a fix to node_modules/react-native-tabs/index.js
```
onSelect(el){
        if (el.props.name === this.props.selected) {
            // do nothing
        }
        else if (el.props.onSelect) {
            el.props.onSelect(el);
        } else if (this.props.onSelect) {
            this.props.onSelect(el);
        }
    }
```
https://github.com/aksonov/react-native-tabs/pull/51

**Comment by c3bryant** [comment]
The pull request has stalled, and this isn't much of an issue since we disabled the tab bar on children views. We will be incorporating an alternative method for handling this behavior
