### ISSUE TITLE
Unhandled Exception: FCM onMessageOpenedApp

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1341]
ITS-PRO: MA-78

FCM exception seen in console when receiving a local push notification.

Also, we are seeing a bug when receiving local notifications while in the app. Steps:
- Build and run the app
- Send and receive one (1) local notification
- Send a second notification, receive two (2) local notifications back-to-back

This is done when:
- [x] FCM exception resolved
- [x] One local notification received per notification sent

- [x] [PR 1357 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BFAE35BAC-632E-40C4-94E1-24EB9EBC08BE%7D&file=PR-1357-Test-Plan-7.8.0-QA-1362.xlsx&action=default&mobileredirect=true) PASS on iOS
- [x] [PR 1357 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BF0E43983-EB9E-487C-AA93-C3BBBF888B7A%7D&file=PR-1357-Test-Plan-7.8.0-QA-1363.xlsx&action=default&mobileredirect=true) PASS on Android

Steps to reproduce:
1. Build and run campus-mobile `experimental` branch on a physical device
2. Send and receive a push notification with the app in the foreground

Error:
```
flutter: FCM: onMessageOpenedApp: background message:
flutter: Instance of 'RemoteMessage'
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3864:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3878:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3905:12)
#3      Provider._inheritedElementOf (package:provider/src/provider.dart:327:34)
#4      Provider.of (package:provider/src/provider.dart:284:30)
#5      PushNotificationDataProvider.initPlatformState.<anonymous closure> (package:campus_mobile_experimental/core/providers/notifications.dart:79:20)

```

**Comment by gmihir** [comment]
- steps to reproduce
 
1. get latest experimental
2. currently, latest commit (3b7bde359c93753acd49457759d13bcb4abb7797)
3. install and run app on physical iOS device (iPhone 12)
4. log in as student
5. send TM message using QA tool while app is in foreground
    - i'm seeing duplicate notifications for the first send
6. send DM message using QA tool while app is in foreground
    - same as step 5, seeing duplicate for first notification sent

- Notes

- getting duplicate on first notification even through flutter restart, phone reboot, etc.
- debug-wise, the Firebase.onMessage callback is called 4x for one notification
- cannot reproduce on Android, seems like an iOS-only issue for now
- only one message shows up in the notification view
- never got FCM error specified in issue

possible github issue:
- https://github.com/FirebaseExtended/flutterfire/issues/5986
- no response from firebase dev team yet
