### ISSUE TITLE
Surf Data Out of Date

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#135]
On March 10, 2017 the surf data feed is reporting surf information for Jan 24, 2017 at certain locations. Each location has a different reported date.

https://s3-us-west-2.amazonaws.com/ucsd-its-wts/now_ucsandiego/v1/surffeed.json

[{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=107951","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 10 ft. and poor to fair","title":"TORREY PINES STATE BEACH : 5-8 ft. - head high to 3 ft. overhead and poor to fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4245","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 8-12 ft. - 3 ft. overhead to double overhead + occasionally 14 ft. and fair","title":"BLACKS : 8-12 ft. - 3 ft. overhead to double overhead + and fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4246","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 10 ft. and fair","title":"SCRIPPS : 5-8 ft. - head high to 3 ft. overhead and fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4812","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 9 ft. and fair","title":"LA JOLLA SHORES : 5-8 ft. - head high to 3 ft. overhead and fair "},{"date":"Sat, 11 Mar 2017 00:00:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4247","description":"This is LOLA with the forecast for Saturday at 06:00 AM. Surf: 4-5 ft.","title":"HORSESHOE : Surf: 4-5 ft. "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4248","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 10 ft. and poor to fair","title":"WINDANSEA : 5-8 ft. - head high to 3 ft. overhead and poor to fair "},{"date":"Sat, 11 Mar 2017 00:00:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4803","description":"This is LOLA with the forecast for Saturday at 06:00 AM. Surf: 3-4 ft.","title":"PB POINT : Surf: 3-4 ft. "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4804","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 4-7 ft. - shoulder high to 2 ft. overhead occasionally 8 ft. and poor to fair","title":"OLD MAN'S/TOURMALINE : 4-7 ft. - shoulder high to 2 ft. overhead and poor to fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4250","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 10 ft. and poor to fair","title":"PACIFIC BEACH : 5-8 ft. - head high to 3 ft. overhead and poor to fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4252","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 6-10 ft. - head high + to double overhead occasionally none and poor to fair","title":"MISSION BEACH : 6-10 ft. - head high + to double overhead and poor to fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4253","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 6-10 ft. - head high + to double overhead occasionally 12 ft. and poor to fair","title":"OCEAN BEACH, SD : 6-10 ft. - head high + to double overhead and poor to fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4254","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 6-10 ft. - head high + to double overhead occasionally none and poor to fair","title":"SUNSET CLIFFS : 6-10 ft. - head high + to double overhead and poor to fair "},{"date":"Sat, 11 Mar 2017 00:00:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4816","description":"This is LOLA with the forecast for Saturday at 06:00 AM. Surf: 3-4 ft.","title":"CORONADO BEACH : Surf: 3-4 ft. "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4255","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 9 ft. and poor to fair","title":"IMPERIAL PIER NS : 5-8 ft. - head high to 3 ft. overhead and poor to fair "},{"date":"Tue, 24 Jan 2017 14:10:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4256","description":"Hey, Jonathan with the report for Tuesday afternoon at 2:10PM. 5-8 ft. - head high to 3 ft. overhead occasionally 10 ft. and poor to fair","title":"IMPERIAL PIER SS : 5-8 ft. - head high to 3 ft. overhead and poor to fair "},{"date":"Sat, 11 Mar 2017 00:00:00 PDT","link":"http://www.surfline.com/rss/rssredirect.cfm?id=4814","description":"This is LOLA with the forecast for Saturday at 06:00 AM. Surf: 4-5 ft.","title":"TIJUANA SLOUGH : Surf: 4-5 ft. "}]

**Comment by i8wu** [comment]
Maybe it's time to move on, [cough](https://github.com/UCSD/campus-mobile/issues/65)

**Comment by i8wu** [comment]
On a more serious note, the source we're pulling from is just providing extra/older data along with what we want. Might want the lambda to just parse those out to save our users some bytes.

**Comment by c3bryant** [comment]
While the problem started in the feed we consume back in March, this was never a problem for app users. The app handles this by filtering out entries that occurred in the past.

We have reached out to surfline multiple times with no response.

Options for moving away from our current feed are outlined in #65
