### ISSUE TITLE
Inaccurate HDH Dining locations

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#136]
The gps coordinates for all the HDH dining locations are wrong. Most of them are just slightly off, but some are far off.

Will be putting some manual fixes on the lambda for ones we find totally off, hoping to resolve this at the data source.

Manually fixing:
Village Market (32.887876,-117.242100)
Pines(32.878878,-117.242367)
Sixth Market(32.879096,-117.230939)

**Comment by i8wu** [comment]
@a6wu Lambda for dining-service needs to be updated

**Comment by c3bryant** [comment]
The dining-service lambda has been updated on production. This resolves the 3 manually fixed locations above.

**Comment by c3bryant** [comment]
We have fixed all incorrect locations we were able to find via extensive testing. I have requested that HDH verify all location coordinates again on their end.
