### ISSUE TITLE
Bad HDH Markets To Go Menu Link

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#137]
The menuWebsite url being fetched for Village and John's market is bad.

Comparing to other to go menu urls it isn't super wrong.

Bad: http://hdh.ucsd.edu/DiningMenus/MarketsToGo.pdf (This just goes to hdh menu website)
Good: https://hdh.ucsd.edu/DiningMenus/MarketsToGo.pdf (This actually goes to the pdf)

Fixing on gitlab

**Comment by i8wu** [comment]
@a6wu Lambda for dining-service needs to be updated

**Comment by a6wu** [comment]
Completed
