### ISSUE TITLE
Package upgrade: firebase

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1371]
ITS-PRO: MA-95

Package upgrade: firebase

firebase_core 1.1.1 --> 1.2.0
firebase_analytics 8.0.4 --> 8.1.0
firebase_crashlytics 2.0.3 --> 2.0.4
firebase_messaging 9.1.4 --> 10.0.0

This is done when:

- [x] [PR 1368 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1368-Test-Plan-7.8.0-QA-1382.xlsx?web=1) PASS on iOS
- [x] [PR 1368 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1368-Test-Plan-7.8.0-QA-1383.xlsx?web=1) PASS on Android

**Comment by gmihir** [comment]
Similar issue to previous test builds (may already be resolved), seeing two wifi test cards.

**Comment by c3bryant** [comment]
Thanks for reporting, gmihir. Duplicate wifi test card issue was resolved the day after this PR. We'll re-test post merge.
