### ISSUE TITLE
Parking Card: Implement Neighborhoods

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1373]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-84

This is done when:
- [x] The Parking card allows user to select lots based on neighborhoods, as implemented at https://xd.adobe.com/view/8e0f007c-1896-49bd-a562-60409a96111a-db5c/
- [x] [PR 1521 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1521-Test-Plan-7.12.0-QA-1674.xlsx?web=1) PASS on iOS
- [x] [PR 1521 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1521-Test-Plan-7.12.0-QA-1675.xlsx?web=1) PASS on Android

Resources:
- API at https://api-qa.ucsd.edu/store/apis/info?name=FIM-Portfolio&version=v0.0.3#/default/get_Neighborhood__id_

**Comment by sramcode** [comment]
[https://app.zenhub.com/files/62921972/b65f69d2-0647-4213-97ab-19901553b56c/download](https://app.zenhub.com/files/62921972/b65f69d2-0647-4213-97ab-19901553b56c/download)

In the Neighborhoods API, we can't seem to find any parking lots, only parking structures.

**Comment by sramcode** [comment]
[https://app.zenhub.com/files/62921972/35271d38-1b35-4b55-86b5-736e0e000222/download](https://app.zenhub.com/files/62921972/35271d38-1b35-4b55-86b5-736e0e000222/download)

/Neighborhood/(id)
For the La Jolla Campus, the ID = 129965164

**Comment by kwgong** [comment]
Neighborhoods UI Demo : 

https://images.zenhubusercontent.com/62921972/ac725898-17cc-40ed-818c-ff2d4c866eb2/final_demo.mov
