### ISSUE TITLE
Additional detail for map search results

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#139]
Would be good if we could display richer detail of a selected search result. We're using maplink api, so I'm not sure how rich our data can really be without an overhaul. But getting started on something would be nice. Having this slide up and down to reveal would be nice too.

Uses:
Parking Type Display
Dining Detail (hours?)
Labs (Printers/hours?)

![screenshot_20170314-115259](https://cloud.githubusercontent.com/assets/20545218/23917545/f38aab4c-08ac-11e7-9f44-7f7c88174e0e.png)
![screenshot_20170314-115357](https://cloud.githubusercontent.com/assets/20545218/23917551/f6380e34-08ac-11e7-9fde-14dd64aec9f1.png)

**Comment by c3bryant** [comment]
As mentioned above, MapLink does not support rich enough data to accommodate most of what is seen above in the screenshots. We will revisit when the VirtualMap API is available.
