### ISSUE TITLE
Restrict AWS Resource Access to Authorized Clients

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#14]
Look tokens with API gateway or cognito or other tools.

**Comment by c3bryant** [comment]
Adding some notes from last month-

Investigated a more rudimentary approach of checking the referrer to our various feeds upon request.
- Ran into a problem on Android in that no referrer is passed at all (possible workaround unknown)
- iOS referrer provides exact device type, app name, and other information

**Comment by c3bryant** [comment]
The three primary methods of doing this via AWS are:

- API keys
- IAM
- Amazon Cognito

Follow-up: Discuss which method would make the most sense to incorporate

**Comment by c3bryant** [comment]
Moving this issue to internal
