### ISSUE TITLE
Inaccurate non-HDH Dining locations

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#140]
Lots of non-HDH locations are off.

The current Dining-Service relies on a static JSON file for the non-HDH locations. This should changed to pull locations/info from Maplink, which can be updated to provide correct info directly to the app.

Steps:
Update maplink locations with accurate gps coords
Update gitlab to use maplink
Update lambda for dining-service

**Comment by c3bryant** [comment]
Many of the incorrect locations have been updated. Moving this issue to our internal list for final verification
