### ISSUE TITLE
Overflow in Events Card

### ISSUE THREAD

**Issue by gmihir** [UCSD/campus-mobile#1403]
Some events have a non-standard font (and possibly other elements) that result in an overflow exception. This is the error:

This is done when: 
- [x] RenderFlex error no longer thrown

Error:
`======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 4.0 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///Users/mihirgupta/Documents/work/campus-mobile/lib/ui/events/events_list.dart:95:20
: To inspect this widget in Flutter DevTools, visit: http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A60997%2Fk4yjm0Hxvcg%3D%2F&inspectorRef=inspector-569
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.`

**Comment by c3bryant** [comment]
Currently resolved, as the event causing this issue is now in the past and no longer in the API response.

Root cause was an event title and description were copied into the event submission form, likely from MS word, resulting in unsupported, non-text characters.

We will inform the client to add a note to the event submission form to encourage plain text title and descriptions.
