### ISSUE TITLE
Show shuttle arrival times on MapView

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#141]
Workout some logic to display shuttle arrivals on mapview.

Don't think there's an api call for shuttle arrivals for all stops, so might need to just do arrival to closest stop? Need to brainstorm. This could also be worked in with https://github.com/UCSD/campus-mobile/issues/139 if we consider each stop a location with details.

**Comment by c3bryant** [comment]
Need more info. Moving to our internal list to flesh out more before development can begin,
