### ISSUE TITLE
Package upgrade: package_info 2.0.0 --> 2.0.2

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1411]
ITS-PRO: MA-95

Package upgrade: package_info 2.0.0 --> 2.0.2

This is done when:
- [x] [PR 1400 Test Plan] (https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1400-Test-Plan-7.8.0-QA-1456.xlsx?web=1) PASS on iOS
- [x] [PR 1400 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1400-Test-Plan-7.8.0-QA-1457.xlsx?web=1) PASS on Android

**Comment by gmihir** [comment]
Not visible on TestFlight
