### ISSUE TITLE
Package upgrade: device_info 2.0.0 --> 2.0.2

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1413]
ITS-PRO: MA-95

Package upgrade: device_info 2.0.0 --> 2.0.2

This is done when:
- [x] [PR 1399 Test Plan] (https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1399-Test-Plan-7.8.0-QA-1454.xlsx?web=1) PASS on iOS (@kevdesilva01)
- [x] [PR 1399 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1399-Test-Plan-7.8.0-QA-1455.xlsx?web=1) PASS on Android

**Comment by kevdesilva01** [comment]
PASS on iOS
