### ISSUE TITLE
Route Mobile Logger data to its own folder within S3

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#1422]
Currently, mobile logs go into the s3 folder data_logs/availability_logs/. That path is the path where occuspace data goes. They are mixed together at the moment. A new path should be created for mobile app logs within data_logs. (WTSWTS account)

This is done when:

- [x] Mobile App logs when scanning for surrounding bluetooth devices are registered in its own folder.

**Comment by c3bryant** [comment]
Resolved and verified in QA, closing.
