### ISSUE TITLE
WiFi Speed Test Lambda/API Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1428]
Time Tracking: MA-110

This is done when:
- [x] The lambdas uses environment variables for the Bucket and Key, [source code](https://sourcecode.ucsd.edu/projects/WTS/repos/speed-test)
- [x] S3UploadUrl.index.js should just have root bucket name for the Bucket

- [x] WiFi Speed Test card testing PASS in QA

- [x] WiFi Speed Test API deployment plan created
- [x] WiFi Speed Test API deployment plan reviewed

- [x] WiFi Speed Test Lambdas deployed to PROD
- [x] WiFi Speed Test card testing PASS in PROD

**Comment by xxwwyytt1** [comment]
[deployment plan](https://docs.google.com/document/d/1973763itj3r1l8CINyK_uSltbIiMR6eG/edit?usp=sharing&ouid=101606588452279025783&rtpof=true&sd=true)
