### ISSUE TITLE
Wifi Speed Test Displaying inaccurate results

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#1431]
Wifi Speed Test card displays varying results with each test, these tests are also inaccurate most of the time. To test, run the speed test on the app a few times and make note of the results, then go to Ookla Speed test or google's speed test and run that. Compare results. 

It might be useful to consider whether the signal is coming from a multi-router mesh system, or a singular router. The Ookla speed test app has several parameters where users can specify, Test Server, and connection type (Multi/Single). 

This is done when:
- [ ] Speed Test upload results never displays 'Infinity Mbps'
- [ ] Speed Test download results are not capped to 100 Mbps
- [ ] Speed Test upload results are not capped to 20 Mbps

<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/a5ac6ec0-32ac-4ee1-ab40-bc624dc18508">
<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/c2f7e007-c678-49fc-8cf3-72289130ee55">
<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/bbdab6c8-0b25-4a1f-8591-e6d2dfebf7e9">
<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/8811eb3c-3d6b-43ec-be10-ae3f72e4c6b8">
<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/2d6fae2b-bed0-4b22-b93e-5eae816c2c06">
<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/a6260f99-14bb-4555-a75d-590b466abf84">
<img width="300" src="https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/65a7c615-5260-44f8-ac9b-84ed77b25a60">

**Comment by c3bryant** [comment]
Consolidating into #1525
