### ISSUE TITLE
Shuttle: City Shuttle (Ariba Nobel) route missing from feed

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#144]
The new Syncromatics API does not return the City Shuttle (Ariba Nobel) route (http://api.syncromatics.com/portal/routes)

This route should be active and is currently in use (verified via their old API used by https://www.ucsdbus.com/map)

![screen shot 2017-03-21 at 10 44 30 am](https://cloud.githubusercontent.com/assets/15112294/24162261/2df313a6-0e24-11e7-972f-08e3edbbf5fb.png)

**Comment by a6wu** [comment]
Completed.
