### ISSUE TITLE
Location: Distances incorrect when location permission denied

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1455]
Time Tracking: MA-87

Encountered a bug when location permission has been denied. Location to dining eateries show a large distance (8000~mi). This distance matches the distance between the eatery and coordinates 0,0. It is likely that the location provider is reporting Lat:0 Lon:0 for the user's location when they have denied location access.

This is done when:
- [x] Distance to dining locations shows `--` when the user has denied location permission
- [x] Directions buttons to dining locations still function with location permission denied

- [x] [PR 1456 Test Plan] (https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1456-Test-Plan-7.8.0-QA-1545.xlsx?web=1) PASS on iOS
- [x] [PR 1456 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1456-Test-Plan-7.8.0-QA-1546.xlsx?web=1) PASS on Android

**Comment by kevdesilva01** [comment]
The app needs to completely restart for the location permissions change to update the UI (render '--' or numbers), but I think that is expected. Android and iOS PASS.
