### ISSUE TITLE
FlatButton Deprecation

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1457]
Time Tracking: MA-95

This is done when:
- [x] `FlatButtons` have been converted to `TextButton`
- [x] TextButton styling problem resolved

- [x] PR 1464 Test Plan PASS on iOS
- [x] PR 1464 Test Plan PASS on Android

Info:
- TextButton with styleFrom style for dark mode support example:
https://github.com/UCSD/campus-mobile/blob/experimental/lib/ui/parking/parking_card.dart#L118

- Dart analyzer: ![Screen Shot 2021-06-21 at 11.11.34 AM.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/ac95bdb6-25ef-435c-933f-e5617e8df857)

**Comment by keskinmbaha** [comment]
The dismiss button on the report issue pop up is a dark blue color instead of white
