### ISSUE TITLE
UI Style Guide

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#146]
Guidelines and recommendations for UI elements and interactions.

**Comment by i8wu** [comment]
<img width="678" alt="colorpalette" src="https://cloud.githubusercontent.com/assets/20545218/25680017/3b7060f4-3004-11e7-9329-8d28f9a9f6bb.png">

**Comment by i8wu** [comment]
Could we get some Red/Green/Yellow? MapView is using some color that I copied from https://material.io/guidelines/style/color.html

**Comment by c3bryant** [comment]
The initial task has been resolved.

As far as supplementary colors there is no issue using other colors as needed where campus branding isn't the focus. Additional colors/themes/styles will be vetted by our user experience designer before implementation.
