### ISSUE TITLE
Occuspace Availability Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1465]
Time Tracking: MA-83

This is done when:

- [x] The Lambda function is updated to return only locations at [https://collab.ucsd.edu/display/WTS/Occuspace](https://collab.ucsd.edu/display/WTS/Occuspace)
- [x] Dining locations included in the API update
- [x] Availability locations displayed under their parent category
  - i.e. Libraries for the title and Geisel/Biomed underneath.
- [x] Add a title for child rows, above the `XX% Availability` text
i.e.
Libraries
  - Geisel
  - 60% Availability
  - ``<availability percentage bar>``

  - Biomed
  - 40% Availability
  - ``<availability percentage bar>``

This is done when:
- [x] API version 3 issues resolved
- [x] Parent locations with floors linked to Availability Detail view which displays floor availability
- [x] Remove arrow icon for parent locations with no floors
- [x] Single location failure returns 500 error fixed (#1830)
- [x] Floor availability percentage displayed, not that of its parent
- [x] Locations with no floors unlinked (tap ok, no navigation)

- [x] [PR 1829 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1829-Test-Plan-7.21.0-QA-2268.xlsx?web=1) PASS in iOS
- [x] [PR 1829 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1829-Test-Plan-7.21.0-QA-2269.xlsx?web=1) PASS on Android

**Comment by a6wu** [comment]
@woznaut Waiting on you for this.

**Comment by gmihir** [comment]
Encountered some issues, but actively working on it. Resolved all backend issues, only frontend issues remain (should have a PR soon).
