### ISSUE TITLE
Shuttle card - the "d" in "Arrived" drops to a new line in detail view on iPhone 6

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#147]
![img_6485](https://cloud.githubusercontent.com/assets/19195410/24301909/0a1a25ea-106e-11e7-91ad-3962c4e8dcfd.PNG)
### Issue Description

[FILL THIS OUT]

### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

### Additional Information

* React Native version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* Operating System (macOS, Linux, or Windows?): [FILL THIS OUT]

**Comment by c3bryant** [comment]
Done in dev [68d206a](https://github.com/UCSD/campus-mobile/commit/68d206a1a5d6572e6d8eca34bb9ecb64c28b2fee)
