### ISSUE TITLE
Package upgrade: location 4.1.1 --> 4.3.0

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1475]
Time Tracking: MA-95

This is done when:
- [ ] [PR 1446 Test Plan] (https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1446-Test-Plan-7.8.0-QA-1529.xlsx?web=1) PASS on iOS
- [ ] [PR 1446 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1446-Test-Plan-7.8.0-QA-1530.xlsx?web=1) PASS on Android

**Comment by keskinmbaha** [comment]
The location shows 7000 miles for the dining card upon onboarding login even though I choose location settings as "Allow while using the app" upon opening the app. In order for it to display the right distance, I have to hide/unhide the card or go to locations settings on my iPhone for the UCSD App then click "Always" then click "Allow while using the app" then reload the card in the app.

**Comment by c3bryant** [comment]
Deferred
