### ISSUE TITLE
Student Health and Well-Being Feed

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1488]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-116

Review use of the tockify feed with the current Student Health and Well-Being web card.

This is done when:
- [x] Student Health & Wellness card updated with links to:
  - CAPS - https://caps.ucsd.edu
  - Student Health Services - https://studenthealth.ucsd.edu/
  - Health Coaching - https://healthpromotion.ucsd.edu
- [x] Student Health & Wellness card is activated in QA
- [x] Student Health & Wellness card is activated in PROD

Process for updating and activating the Student Health & Wellness card in prod:

1. Add `student_health_wellbeing` JSON object to `student_cards-v6.json` after `student_info` card entry:
    CMS: https://cms.ucsd.edu/entity/open.act?id=f6257c670aaf69f57b25c95336fa869f&type=file
    Live: https://mobile.ucsd.edu/replatform/v1/prod/cards/student_cards-v6.json
    SH&WB Object:
        "student_health_wellbeing": {
            "cardActive": true,
            "initialURL": "https://mobile.ucsd.edu/replatform/v1/prod/webview/student-health-wellbeing.html",
            "isWebCard": true,
            "requireAuth": false,
            "titleText": "Student Health & Wellness"
        },
2. Submit and publish `student_cards-v6.json`
3. Load UC San Diego app from App Store, see 'Student Health & Wellness' card when logged in as a student

**Comment by woznaut** [comment]
Login to access the feed:
hps@health.ucsd.edu
!healthsys21

**Comment by woznaut** [comment]
![Screen Shot 2021-08-19 at 9.05.09 AM.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/f264ef8f-9149-4ee2-9a3c-106d4a5f078a)

**Comment by woznaut** [comment]
final wording, order and links:
CAPS - https://caps.ucsd.edu
Health Promotion Services -https://healthpromotion.ucsd.edu
Student Health Services - https://studenthealth.ucsd.edu/
