### ISSUE TITLE
Speed Test Card UI

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1495]
Time Tracking: MA-110

When not on a UCSD network, the WiFi Speed Test card allows user to Run Speed Test but then displays "Looks like you aren't on a UCSD network"

![8020CF4B-6560-49DC-8F08-EA7331626CD1.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/a50a0d96-ad80-4343-ab61-7d6f13819a68)

**Comment by c3bryant** [comment]
Resolved in #1525
