### ISSUE TITLE
Implement Navigator Experimental for Android

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#15]
Navigator module on Android is not currently working. Explore implementing Navigator Experimental module.

@i8wu noted that Navigator will not be supported going forward and that the RN team is moving towards Navigator Experimental (which will likely soon be called Navigator)

**Comment by i8wu** [comment]
We may want to consider an option that'll be web compatible too. So it'd be much easier to actually commonize code between native and desktop.

Possibilities:
[React Router](https://github.com/ReactTraining/react-router/blob/master/docs/Introduction.md)
Navigator Experimental - still under works, currently in CustomComponents of RN project

**Comment by i8wu** [comment]
Should we close this? Since we've moved on to react router flux, which seems to be pretty good rn. @c3bryant

**Comment by c3bryant** [comment]
Yes - thanks, closing
