### ISSUE TITLE
Update MyStudentProfile API

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1500]
Time Tracking: SAH Enrollment MyStudentProfile

This is done when:
- [x] Use column group "SAH Enrollment MyStudentProfile" for the [API](https://sourcecode.ucsd.edu/projects/WTS/repos/my-student-profile/browse)
- [x] Update sourcecode repository
- [x] [Testing PASS in QA (IOS)](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7BC5319C45-50D9-411C-B8E5-EEE3914CC124%7D&file=Regression-Test-Plan-7.26.0-QA-2749.xlsx&action=default&mobileredirect=true)
- [x] [Testing PASS on Android](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B3AE94E47-B18A-48BB-A596-3EDED08CBAF7%7D&file=Regression-Test-Plan-7.26.0-QA-2750.xlsx&action=default&mobileredirect=true)
- [x] [Create deployment plan](https://ucsdcloud-my.sharepoint.com/:w:/g/personal/vilohia_ucsd_edu/EbIB_1s-zChCjY_YeYaaUTsBaBSUq5caERVhD_wk78cC9g?e=d19Wdq)

Issues encountered during deployment. This is done when:
- [x] Diff MyStudentProfile QA schema and MyStudentProfile PROD response
- [x] Diagnose and resolve in QA to determine next steps

- [x] Deploy to PROD
- [x] Testing PASS in PROD

**Comment by a6wu** [comment]
Documentation at https://collab.ucsd.edu/display/WTS/MyStudentProfile

**Comment by virajl** [comment]
Updated documentation - https://ucsdcollab.atlassian.net/wiki/spaces/WTS/pages/112492581/MyStudentProfile

**Comment by a6wu** [comment]
@mliu6723  Could use your help to complete the iOS testing.
