### ISSUE TITLE
Integrate Gilman Parking API

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1501]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-84

Integrate Gilman parking availability vendor

https://collab.ucsd.edu/display/WTS/Parking

This is done when:
- [x] Gilman parking availability vendor integrated into ParkingAvailabilityVendors from mock response (branch: [vendor-indect](https://sourcecode.ucsd.edu/projects/WTS/repos/campusparkingservice/compare/commits?sourceBranch=refs%2Fheads%2Fvendor-indect&targetBranch=refs%2Fheads%2Fmaster))
- [x] Gilman parking vendor API whitelisting blocker resolved
- [x] Gilman parking vendor integration updated to fetch parking availability from whitelisted API
- [x] Gilman parking vendor deployed to CampusParkingService v1.3

- [x] Gilman vendor unknown spot types omitted from response
- [x] Gilman vendor spot type `Visitor` mapped to spot type `V`
- [x] Gilman parking neighborhood confirmed (Campus Services Complex)
- [x] Gilman Garage parking structure named `Gilman`
- [x] Gilman parking vendor function updated and deployed to CampusParkingService v1.3

**Comment by c3bryant** [comment]
Unable to query API - awaiting resolution of domain whitelisting request.

**Comment by a6wu** [comment]
Updated the collab page with additional data response information.

**Comment by gmihir** [comment]
The API url listed on the collab page does not return a response, even when on VPN.
