### ISSUE TITLE
App freeze when viewing Classes card for some students

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1511]
Time Tracking: MA-34

This is done when:
- [x] App no longer freezes for students viewing their Classes card

**Comment by a6wu** [comment]
For the following null values, let's use "TBD." It may be that the information is not known yet.

"date": null,
"time": null,
"days": null,
"building": null,
"room": null,

**Comment by c3bryant** [comment]
Adding some info on this issue

- The section ID in question, returning null values as shown above, is from a SSII section that is entirely asynchronous/remote, which has no days, time, building, or room.
- Adding TBD values will resolve `building` and `room` errors.
- The `time` and `days` fields are currently required to display on the Classes card, which only displays classes today, ordered by upcoming/ascending.
  Sections without `time` and `days` values should show up in 'View All Classes -> Other'. This is not currently happening. Looking into a possible fix.
