### ISSUE TITLE
Dining: Missing third party vendor information in data feed

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#152]
The dining feed is missing all third party vendor information from the primary data feed (i.e. Rubios, Burger King, etc). This has been problematic as we have to manually obtain this data from unofficial sources and then merge it with the main dining feed to get a comprehensive list of all dining establishments on campus.

We would like the dining feed to contain all dining establishments and markets on campus. This includes location, menu (if available), open hours, description, images, hours, and more.

**Comment by i8wu** [comment]
I don't think this is an HDH or internal issue, unless HDH is agreeing to help out with consolidating this info for us. Maybe we should be looking into Associated Students + Maplinks, or Google Maps/Business?

**Comment by c3bryant** [comment]
HDH will not provide and does not have third party vendor information, closing

**Comment by i8wu** [comment]
Are we just going to close this? Alex met with a CS student from AS today that wants to help with the app. Could have him work on this.

**Comment by c3bryant** [comment]
Yeah, this task was just to have HDH incorporate 3rd party vendor data into their feed which will not happen. We can create a new one to handle governance/managing the 3rd party vendor data via the CMS and to look at other options you mentioned above (Maplinks, Google Business etc)
