### ISSUE TITLE
Wifi Speed Test Card Issues

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#1525]
Time Tracking: MA-110

This is done when:
- [x] Speed Test card displays 'Test WiFi Speed' view when connected to UCSD WiFi
- [x] Speed Test card displays 'Connect to a UCSD Network' when not connected to WiFi
  - Scrolling up and down on the Home view can cause the Speed Test card to switch from the 'Connect to a UCSD Network' view to the 'Test WiFi' view
- [x] Speed Test results does not display 'Infinity Mbps' for download or upload results
- [x] Running speed test times out after 30 seconds.
  - In the event of a 30s timeout
    - a) Render completed test results. i.e. if Download test completed, display that result.
    - b) Render a red thumbs down icon for any timed out speed test as the result

- [x] [PR 1572 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1572-Test-Plan-7.13.0-QA-1835.xlsx?web=1) PASS on iOS
- [x] [PR 1572 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1572-Test-Plan-7.13.0-QA-1836.xlsx?web=1) PASS on Android

**Comment by kevdesilva01** [comment]
![IMG_8211.PNG](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/93db8189-cb88-43dc-aacd-c62f2f69ef00)

**Comment by kevdesilva01** [comment]
![IMG_8209.PNG](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/bf7a7edd-970b-4d1a-9874-fc06d678088f)

**Comment by kevdesilva01** [comment]
![IMG_8207.PNG](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/412303e2-de85-47e0-aae4-0b09554798d4)

**Comment by p8gonzal** [comment]
May be delayed due to account recovery.

**Comment by p8gonzal** [comment]
After Android test, follow up requested. @gmihir

**Comment by p8gonzal** [comment]
Handed off to Mihir to investigate reports from Android testing.

**Comment by gmihir** [comment]
Following up on this, Peter reported two issues:
* Needed to restart app to see Test WiFi 
    * This is expected behavior as the current infrastructure of the wifi card is to check network information on app start
     * Therefore, changing the wifi connection/state while the app is running does not reflect until the card is restarted/re-rendered
     * Verified on iOS as well

* Android test results look inaccurate
     * I was not able to reproduce this as my Android device kept timing out on the speed test
     * It is an older device, but the network I'm testing on is gigabit
     * A speedtest.net test on the device on this network shows 0.5 Mbps down and 0.1 Mbps up, so I'm not really sure how to replicate this issue with my current Android hardware.

**Comment by gmihir** [comment]
Next Steps: 

- [ ] Add "try again" button when WiFi speed test is not available
