### ISSUE TITLE
Card Shadows

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#153]
Add shadows to card components using react-native-elevated-views

Shadows were previously taken out because of performance issues, need to check if still an issue

**Comment by i8wu** [comment]
8eb7f1972b46290e6c6fd83bb154f9ece2773a2d

**Comment by c3bryant** [comment]
This seems to be working well everywhere except the Shuttle card. No shadow present
<img width="592" alt="screen shot 2017-05-05 at 10 06 10 am" src="https://cloud.githubusercontent.com/assets/15112294/25756238/dd00916a-317a-11e7-9db8-daa279a0ad17.png">

**Comment by i8wu** [comment]
oops, fixed c8d8d4047ebca839806a5a44bdcf97792fa18872
