### ISSUE TITLE
Parking Neighborhoods V2

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1533]
Time Tracking: MA-84

This is done when:
- [x] When there are no lots selected, display a message on the Parking card prompting the user to add a lot.
- [x] Order the lots alphabetically that way it can be easier to find a lot
- [x] Add a "Done" button to the top right nav on all selection pages so the user can go back to the home screen without tapping the back button 3 times.
- [x] On the Manage Lots lot selection view, allow the use to click anywhere on the row to activate or deactivate a lot.
- [x] Change parking card builder to render up to 3 spot types, omitting spot types 4-n from rendering

- [x] [PR 1649 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1649-Test-Plan-7.14.0-QA-1871.xlsx?web=1) PASS on iOS
- [x] [PR 1649 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1649-Test-Plan-7.13.0-QA-1848.xlsx?web=1) PASS on Android

**Comment by kevdesilva01** [comment]
needs new PR
