### ISSUE TITLE
Parking API Deployment

### ISSUE THREAD

**Issue by sramcode** [UCSD/campus-mobile#1534]
1. Checkout [parking-availibility source code repository](https://sourcecode.ucsd.edu/projects/WTS/repos/parking-availability/browse)
2. In [CampusParkingService on AWS](https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/4pefyt8qv7/resources/5fgx3c3me9), create v1.2 resource under the parking resource in prod
- under v1.2 create status resource and GET method pointing to parkingrouter lambda
3. Upload zip file with NeighborhoodMap.json and updated index.js file into the [ParkingAvailabilityRouter]( https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/ParkingAvailabilityRouter?tab=code) folder in AWS PROD 

This is done when:
- [x] Parking API (v1.2) deployed to AWS prod stage
- [x] Parking API (v1.2) deployed to APIM prod

**Comment by kwgong** [comment]
SNOW ticket: [CS0653687](https://support.ucsd.edu/nav_to.do?uri=sn_customerservice_case.do%3Fsys_id=6c1f22751b1e3050b8d255b5604bcbc2%26sysparm_stack=sn_customerservice_case_list.do%3Fsysparm_query=active=true)
