### ISSUE TITLE
Android App Icon Sharp Edges

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#155]
App icon on Android has sharp edges. Is this intended or should it be slightly rounded?

![screenshot_20170405-111637](https://cloud.githubusercontent.com/assets/4240132/24720663/bc633178-19f2-11e7-809f-f2394edc17e4.jpg)

**Comment by i8wu** [comment]
Rounded now
![screenshot_20170418-092702](https://cloud.githubusercontent.com/assets/20545218/25141865/ca027006-2419-11e7-85a9-f3fc9eb756e8.png)

**Comment by c3bryant** [comment]
thanks Ivan, closing this out
