### ISSUE TITLE
student_contact_info api endpoints  returning error

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#1554]
Time Tracking: MA-34

endpoints: https://api-qa.ucsd.edu:8243/student/my/student_contact_info/v1/barcode
https://api-qa.ucsd.edu:8243/student/my/student_contact_info/v1/photo
https://api-qa.ucsd.edu:8243/student/my/student_contact_info/v1/display_name

The student contact info api endpoints return this:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /StudentContactInfo/students/A15795955/display_name was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at academic-ws-qa.ucsd.edu Port 443</address>
</body></html>
```

SNOW Ticket: [CS0662932](https://ucsdservicedesk.service-now.com/its?id=ticket&table=sn_customerservice_case&sys_id=fceb03c81ba2f4d0b8d255b5604bcbcc)

**Comment by c3bryant** [comment]
Resolved by ATS
