### ISSUE TITLE
Dining: OceanView location is missing from app

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#156]
This location is now coming across the HDH feed but not making it into the feed consumed by the app. Investigate campus-eateries.json

**Comment by a6wu** [comment]
Emailed HDH group on how to handle this. Waiting to hear back.

**Comment by c3bryant** [comment]
@a6wu This turned out to be an issue on our end. This commit has been pushed and is ready for deployment to AWS Prod. The updated file in question is: campus-eateries.json

https://gitlab.com/ucsd-wts-services/dining-service/tree/521efe36e903daaceae80b5dc5db66e45adba2c2

**Comment by c3bryant** [comment]
Fix pushed to AWS Prod and verified, closed.
