### ISSUE TITLE
NTPLLN Mosaic Building

### ISSUE THREAD

**Issue by keskinmbaha** [UCSD/campus-mobile#1568]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-78

This is done when:
- [ ] Mosaic building's data is available from the vendor API
- [ ] Mosaic building data integrated into the BuildingStatus API
- [ ] Mosaic building available in Office Environment employee card

**Comment by c3bryant** [comment]
Revisit when customer has resolved BuildingStatus/NTPLLN API outage
