### ISSUE TITLE
NTPLLN Error in Ventilation Services

### ISSUE THREAD

**Issue by keskinmbaha** [UCSD/campus-mobile#1569]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-78
This is done when:
- [x] Fix the error that is being thrown in ventilation_services:
  - "flutter: type 'Null' is not a subtype of type 'Map<String, dynamic>'"
- [x] Make sure the building's real time data is shown in ventilation_card

**Comment by c3bryant** [comment]
An environment variable was missing in the MetasysData Lambda. This has been resolved in QA - please verify.

**Comment by keskinmbaha** [comment]
Issue has been resolved.
