### ISSUE TITLE
Improve user control when submitting feedback

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#157]
Investigate handling a feedback post in the background. Allow the user to continue using the app without having to wait a few seconds for the post request to be completed

**Comment by Gulci** [comment]
In my latest commit b12b39bc5003e25e1ef150eab8d6c82a9cbe1570 I moved the networking for making a POST request outside of the presentation component. I created a service, saga, and reducer for it. Now we store feedback in the global store until it's submitted. This should improve consistency when drafting a new feedback message and then navigating away from the app before sending it off.

I've also added a 10 second timeout. Any success or error messages are displayed globally in the app no matter where the user is, so the user can continue using the app and still receive feedback from the app on the status of their feedback submission.

**Comment by Gulci** [comment]
The last improvement I want to make for now is to make the view scrollable when the user has drafted a longer comment. Currently, it overflows and the user has to tap out of the keyboard before being able to see any other inputs. Additionally, the keyboard blocks the input once it is selected.

**Comment by Gulci** [comment]
I'm going to leave scrollable/keyboard adjusted views for another issue, as it potentially impacts other views in the app too, and it isn't related to this specific issue of improving user control when submitting feedback.

**Comment by Gulci** [comment]
This is done, commits are in branch 'feedback-submit'.

**Comment by c3bryant** [comment]
Verified & merged into v5.6-rc branch
