### ISSUE TITLE
Reorder Home Cards

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#159]
A good amount of people have requested having the ability to sort cards so I've begun working on the feature, it's mostly working but there's a small? bug holding things up

https://github.com/gitim/react-native-sortable-list/issues/40

**Comment by woznaut** [comment]
using the same control as the shuttle card re-order?

**Comment by i8wu** [comment]
pretty much. Here's a gif of the bug, but it also shoes functionality
https://gfycat.com/BonyHollowAnnashummingbird

**Comment by i8wu** [comment]
Explore pointing directly to fork/commit fix in package.json since release is coming soon.

**Comment by i8wu** [comment]
Syntax for pointing to fork for npm is pretty simple...
`"react-native": "github:i8wu/react-native",`

**Comment by i8wu** [comment]
Pointing to our fork of 0.42.3 with the switch fix 039f6e0a3643a8cad64e80969dbae67bd69575e8

**Comment by i8wu** [comment]
Oops, android doesn't like the react-native fork...

**Comment by i8wu** [comment]
Do inline fix for 5.2 release and revisit this issue.
