### ISSUE TITLE
Empty Search Query Bug

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#160]
### Issue Description

After a successful search with results returned, an empty search query " " will show the last search results.

### Steps to Reproduce / Code Snippets

Search for "books." Results appear.
Then search for " " (empty space). Last result for "books" displays.

#### Expected Results

Should show "No results found" message for empty query search. Maybe not do a search at all on bogus queries.

### Additional Information

* React Native version: 
* Platform(s) (iOS, Android, or both?): Tested on Android
* Operating System (macOS, Linux, or Windows?): N/A

**Comment by i8wu** [comment]
91ebafb6620d048d3ae2529401093dd0734f936e doesn't allow search for empty strings.

Nothing happens when an empty query is attempted to be submitted. Happy to discuss possible different behavior?

**Comment by a6wu** [comment]
The disconnect for me is that the search input is empty but the results from the previous search is still there. Maybe repopulate the search input with the previous query term to match the results shown?

**Comment by i8wu** [comment]
https://gfycat.com/SpicyGleefulAchillestang updated behavior
