### ISSUE TITLE
Office Environment Handling of Null Values

### ISSUE THREAD

**Issue by keskinmbaha** [UCSD/campus-mobile#1611]
Time Tracking: [MA-109](https://its-pro.ucsd.edu/browse/MA-109)

### Issue:
When Office Environment card is loading in a location, if the metasys api returns a value (in this case I believe it returned a null value) model/ventilation was not expecting, the card breaks and shows the following error.

![office_environement_null.png](https://images.zenhubusercontent.com/60c6eebbac3fd01e88c9b348/ce868422-d065-4b8e-a23a-5dfe1b2ef331)

### Finished when:
- [ ] Allow Office Environment/Ventilation to handle such errors gracefully
- [ ] Null error is resolved

**Comment by c3bryant** [comment]
Revisit when customer has resolved BuildingStatus/NTPLLN API outage
