### ISSUE TITLE
Accessibility: Card options menu verbiage changes

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1627]
Time Tracking: MA-126

This is done when:
- [x] Card option "reload" changed to "reload this card"
- [x] Card option "hide" changed to "hide this card"

- [x] [PR 1683 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1683-Test-Plan-7.15.0-QA-1986.xlsx?web=1) PASS on iOS
- [x] [PR 1683 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1683-Test-Plan-7.16.0-QA-2006.xlsx?web=1) PASS on Android

**Comment by a6wu** [comment]
@xxwwyytt1 Need your help on a failed testing on iOS.
