### ISSUE TITLE
SH&WB: Integrate Tockify Feed

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#1637]
Time Tracking: TBD

This is done when:
- [x] Tockify events feed integrated into [Student Health & Well-being card](https://mobile.ucsd.edu/replatform/v1/qa/webview/student-health/student-health-wellbeing.html)
- [x] Tockify events calendar feed (https://tockify.com/api/feeds/rss/hpsucsd) confirmed
- [x] Tockify events feed integration PASS in QA
- [x] Tockify events feed integration deployed to PROD
- [x] Tockify events feed integration PASS in PROD

**Comment by c3bryant** [comment]
Health & Well-Being card with 3 static links listed above deployed to Prod for Students in Oct '21

**Comment by woznaut** [comment]
https://tockify.com/i/docs/api/embed

the tockify calendar name is hpsucsd

**Comment by a6wu** [comment]
RSS option https://tockify.com/api/feeds/rss/hpsucsd

**Comment by c3bryant** [comment]
@woznaut To include in upcoming release 7.21 let us know by Sep 1. Release target date is Sep 5
This card is available for visitors on TestFlight 7.21 (2254)

**Comment by c3bryant** [comment]
Deployed.
Note: `Health & Well-Being` card is available for all logged-in students.

<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/6c227788-4e24-4faa-a516-d385552a69b3" width="400">
