### ISSUE TITLE
Remove location requirement from dining card

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#164]
The dining card fails to load when no location is available.

- Location should now be optional, and the initial fetch should not wait on location.
- If the user location does become available, display the distance below the Directions icon
- The Directions icon should always be shown regardless if location is available or not, as that location permission is handled by the users 3rd party navigation app

**Comment by i8wu** [comment]
c591074fd8ce5e2f408571900c7fa1a104ce46be
