### ISSUE TITLE
Notification Settings

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1648]
Time tracking: https://its-pro.ucsd.edu/browse/MA-60

User feedback:

The notification settings in the UC San Diego mobile app are not correctly saved. (Android 10)
Steps to reproduce:
1. Under Profile > Notifications, turn off all notifications.
2. Close the app so that it is not running in the background.
3. Open the app again and navigate to Profile > Notifications. All notifications have been re-enabled.

Note that notifications are pushed even if only steps 1 and 2 are followed. That is, it's not the act of manually opening the app again which re-enables the notifications.

**Comment by gmihir** [comment]
Unable to replicate this issue in PROD using both iOS and Android. I was not able to successfully run a simulator with Android 10 but my Samsung Galaxy S6 did not face the same issue. I have run into this issue a few times in QA but not sure why I can't reproduce it in PROD.
