### ISSUE TITLE
Load Links card icons locally

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#165]
The Links card currently loads link icons remotely. Move these icons to the local assets folder and load from there. This will alleviate an issue primarily seen on the View All Links view where the icons can take a few seconds to load in initially causing the view to look broken

**Comment by i8wu** [comment]
Can we save image assets without having it part of the build?

**Comment by i8wu** [comment]
Actually found super easy way to alleviate this issue. Loop thru all link icon urls and calls Image.prefetch https://github.com/UCSD/campus-mobile/commit/572032cef8ad5edee15d2a6931fe0348571e0876
