### ISSUE TITLE
Map Search: Distance to destinations is incorrect

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1663]
Time Tracking: MA-34

The distance to map search destinations is incorrect. Seeing `7.49e+3 mi` for most locations. Reproduced on 7.12 and 7.13

This is done when:
- [x] Distance to map search destinations is correctly rendered as `XX.X mi`

- [x] [PR 1685 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1685-Test-Plan-7.14.0-QA-1908.xlsx?web=1) PASS on iOS
- [x] [PR 1685 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1685-Test-Plan-7.14.0-QA-1909.xlsx?web=1) PASS on Android

References:
<img width="400" src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/4dce9e64-6630-4db9-82f3-81b2daa175f9">

**Comment by a6wu** [comment]
Investigate more_results_list.dart file
