### ISSUE TITLE
Package upgrade: flutter_local_notifications 6.1.1 --> 8.2.0

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1668]
Time Tracking: MA-95

This is done when:
- [x] Package flutter_local_notifications has been upgraded from 6.1.1 to 8.2.0

- PR 1560 testing round 1 failed (build out of date)

- PR 1560 testing round 2:

- [x] [PR 1560 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1560-Test-Plan-7.14.0-QA-1910.xlsx?web=1) PASS on iOS
- [x] [PR 1560 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1560-Test-Plan-7.14.0-QA-1911.xlsx?web=1) PASS on Android

**Comment by gmihir** [comment]
Failed iOS testing. Maybe worth retesting/discussing why, since the issues were not related to local notifications
