### ISSUE TITLE
Update Historical Parking Availability Data

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1690]
Time Tracking: MA-84

This is done when:
- [x] Ensure the historical data feed is up-to-date https://docs.google.com/spreadsheets/d/1nuXCIndvvk5a0F43E8I-_-dL790bUPROUPd6ZV8_A4M/edit#gid=1313940945

- [x] Historic parking data testing PASS in QA

- [x] Historic parking data deployed to PROD
- [x] Historic parking data testing PASS in PROD

**Comment by c3bryant** [comment]
Notes:
- Node utility function `update-historic-data` added to CampusParkingService > vendors > historic (repo: [CampusParkingService](https://sourcecode.ucsd.edu/projects/WTS/repos/campusparkingservice/browse/ParkingAvailabilityVendors/vendors/historic/update-historic-data.js))
  - Requirements: ParkingOccupancy.xlsx (exported from [Parking Occupancy sheet](https://docs.google.com/spreadsheets/d/1nuXCIndvvk5a0F43E8I-_-dL790bUPROUPd6ZV8_A4M/edit#gid=1313940945))
  - Usage: `node update-historic-data`
  - Output: `historic_data.json`
- Historical parking data/API _not_ updated - Missing data - Parking Occupancy data for Wed, Thu, Fri is missing on 2022-01-26

**Comment by c3bryant** [comment]
Update:
- Parking occupancy data is now available for Wed/Thu.
- Waiting for Fri data to be populated and then we will proceed with the update.

**Comment by c3bryant** [comment]
- Fri data populated.
- Historic data updated in QA and ready for testing
