### ISSUE TITLE
UCSD Scan: Add blood screen support

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1730]
Time Tracking: MA-74

This is done when:
- [x] Add support for barcode prefix `ZAP`
- [x] Successful scans for `ZAP` barcodes shows the following:
  - Proceed to the next step in the fingerstick blood collection process.
  - You can view your research test results in your MyChart in about 60 days.
- [x] Localize blood screen text for ES
- [x] UCSD Scan version 1.0.5 (13) on TestFlight
- [x] UCSD Scan 1.0.5 (13) testing PASS on iPad
- [x] UCSD Scan 1.0.5 (13) submitted for App Store Review
- [x] UCSD Scan 1.0.5 (13) released

**Comment by gmihir** [comment]
Submitted PR, does not provide accurate Spanish translation (shows English).
