### ISSUE TITLE
S3 Log Search Tool

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1733]
Time tracking: MA-99

This is complete when:

- [x] An AWS lambda accepts a string input
- [x] The lambda obtains object list from S3 bucket for files modified in the past 90 days
- [x] The lambda searches for the string input in a S3 bucket
- [x] Lambda returns the value in the S3 text file if there is match
- [x] Lambda returns "no match" if there is no match
- [x] LogSearch Lambda testing PASS in QA
- [x] LogSearch Lambda deployed to PROD
- [x] LogSearch Lambda testing PASS in PROD

- [x] LogSearch Lambda returns text line of file matching search criteria in the response

- [x] LogSearch Lambda testing PASS in QA

- [x] LogSearch Lambda deployed to PROD
- [x] LogSearch Lambda testing PASS in PROD

**Comment by c3bryant** [comment]
Notes:
- S3 log search capability added via function [LogSearch](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/LogSearch?tab=configure) (repo: [MobileAppLogger](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileapplogger/browse))
- Search bucket, path, and term configurable via env vars
- Search speed is approx 15 S3 obj/sec or 900/min
- Explored increasing search speed via 'start-after' filter option - not possible as filename objects are UUID format

Performance Improvement Options:
- Change log file paths or names to include date -- i.e. `22829e11-4da0-403c-...` --> `2022-01-26/22829e11-4da0-403c-...`
- [Amazon Athena](https://aws.amazon.com/athena/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc)
