### ISSUE TITLE
Integrate Shuttle Vendor

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1737]
Time tracking: Time Tracking: MA-102

This is done when:
- [x] The vendor API is implemented to CampusShuttles API version 2
- [x] Mobile app shuttle deprecation PR reverted
- [x] Mobile app shuttle service upgraded to version 2
- [x] Mobile app shuttle card integration completed
  - [x] Shuttle card can load indefinitely on initial app launch fixed.
    - Investigate: Shuttle card successful rendering criteria (https://github.com/UCSD/campus-mobile/blob/transloc-integration/lib/ui/shuttle/shuttle_card.dart#L38)

  - [x] Arrival times are not displaying in the UI
    - Investigate: Shuttle data provider fetching of arrival times (https://github.com/UCSD/campus-mobile/blob/transloc-integration/lib/core/providers/shuttle.dart#L65)
    - Is the data returned from the API call?
  - [x] Fix shuttle arrival icon when no shuttles en route

  - [x] Shuttle Stop list sorted alphanumerically
  - [x] Closest shuttle stop added and displayed on app launch
  - [x] Shuttle API endpoint points to APIM

- [x] [PR 1814 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1814-Test-Plan-7.21.0-QA-2241.xlsx?web=1) PASS on iOS
- [x] [PR 1814 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1814-Test-Plan-7.21.0-QA-2242.xlsx?web=1) PASS on Android

Refs:
- branch: transloc-integration
- https://collab.ucsd.edu/display/WTS/Campus+Shuttle

**Comment by c3bryant** [comment]
Waiting on endpoint access

**Comment by a6wu** [comment]
Updated documentation with API endpoint, https://collab.ucsd.edu/display/WTS/Campus+Shuttle.

**Comment by c3bryant** [comment]
Met with gmihir to resolve integration blocker relating to shuttle data model refactoring.
