### ISSUE TITLE
Use ColorConstants All Over

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#177]
Need to refactor code to use styles/ColorConstants.js

Coverage:
styles/
- css.js

views/
- ~[ ] banner~
- [x] card
- [x] common
- [x] conference (Pretty much done, needs a yellow constant for the stars though)
- [x] dining
- [x] events
- [x] news
- [x] preferences
- [x] quicklinks
- [x] schedule
- [x] shuttle
- [x] weather
- ~[ ] welcomeWeek~
- [x] FeedbackView
- [x] Home

**Comment by c3bryant** [comment]
Moving two entries from the list above down, these are what remain for the Meowth milestone
- [ ] mapsearch
- [ ] survey
