### ISSUE TITLE
ScanData API HA

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1774]
Time Tracking: IPPI-5293

This is done when:
- [x] ScanData API has been migrated to version ~3.0.0~ 2.0.0
- [x] [ScanData API 3.0.0 QA Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1777-Test-Plan-7.20.0-QA-2164.xlsx?web=1) PASS on iOS
- [x] [ScanData API 3.0.0 QA Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1777-Test-Plan-7.20.0-QA-2165.xlsx?web=1) PASS on Android

- [x] Scanner Logging Inconsistency resolved (#1797)

- [x] ScanData HA migrated to API version 2.0.0 in QA (c3bryant)
- [x] ScanData recent scan message updated in QA (c3bryant)
- [x] ScanData HA API version 2.0.0 testing PASS in QA (c3bryant)

- [x] S3 Covid Image to HANA completed in [IPPI-5411](https://its-pro.ucsd.edu/browse/IPPI-5411) (sshieh)
- [x] ScanData API 2.0.0 end-to-end testing PASS in QA
- [x] IPPI-5411 S3 Covid Image to HANA deployed to PROD
- [x] IPPI-5411 S3 Covid Image to HANA testing PASS in PROD
- [x] ScanData 2.0.0-HA deployed to PROD
- [x] ScanData 2.0.0-HA end-to-end testing PASS in PROD

Scan Process for HA Flow: [Updated Flow: B](https://lucid.app/lucidchart/02fe5777-fe61-4039-b3ba-539880366134/edit?beaconFlowId=2DE5BC9C2CF99059&invitationId=inv_c0d915e2-cce3-47ad-851d-0eae93f2d7f8&page=0_0#)

Testing
---
iOS Build: 2214
Android Build: 2215

**Comment by c3bryant** [comment]
1 & 2 ready for testing in BarcodeScanData branch [3.0.0-ha](https://sourcecode.ucsd.edu/projects/WTS/repos/barcodescandata/browse/postScanData?at=refs%2Fheads%2F3.0.0-ha)

**Comment by sshieh** [comment]
Data flow diagram:
https://lucid.app/lucidchart/052362fc-4a32-45cf-be20-5c19eb0fdf38/edit?viewport_loc=-11%2C-32%2C1795%2C1321%2C0_0&invitationId=inv_bbf67f05-ec36-4b67-b19b-a9a4934f6580
