### ISSUE TITLE
Parking: Add Hopkins

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1779]
Time tracking: Time Tracking: MA-84

This is complete when:
- [x] Hopkins Garage mapped to Hopkins
- [x] Function ParkingAvailabilityVendors deployed
- [x] Verify the app displays real-time data for Hopkins

**Comment by c3bryant** [comment]
Hopkins name mapping complete
Repo: CampusParkingService
Function: ParkingAvailabilityVendors
