### ISSUE TITLE
ESRI Integration Review

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1780]
Time tracking: https://its-pro.ucsd.edu/browse/MA-128

Review options for integrating [ESRI Quick Capture](https://campus-hazard-reporting-ucsd-admin.hub.arcgis.com/) with:

- [x] The Campus Mobile App
- [x] [ServiceNow](https://collab.ucsd.edu/display/ITSSMH/ServiceNow+Fundamentals)
- [x] [Maximo](https://collab.ucsd.edu/display/HDHIT/HDH+-+Maximo)

- [x] Level of Effort: Create a ArcGIS REST API Proxy with Find operation support

[Collab Documentation](https://collab.ucsd.edu/display/WTS/ESRI+ArcGIS)

**Comment by xxwwyytt1** [comment]
* Cannot use the QuickCapture app directly without downloading it
    * No directly API to call to use for the functionality and interface of QuickCapture
    * QuickCapture is a open source app tho (https://github.com/Esri/QuickCapture)
* ArcGIS has a REST API if we know what attribute we are passing into ArcGIS
    * https://developers.arcgis.com/rest/
    * Access to location and offline services
    * We can do similar function inside the mobile app with API?
        * https://pub.dev/packages/flutter_map_arcgis
        * Or https://pub.dev/packages/geolocator
* Nothing useful related to ServiceNow/Maximo IBM I can find
    * Stave Maps on ServiceNow store - used to visualize ServiceNow data. It doesn't seem to relate to our purpose though.

**Comment by c3bryant** [comment]
Create Esri Quick Capture with ArcGIS REST API?
https://community.esri.com/t5/arcgis-rest-api-questions/create-esri-quick-capture-with-arcgis-rest-api/m-p/1175774
