### ISSUE TITLE
Crash: wifi_connection: com.apple.main-thread

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1785]
Time Tracking: MA-114

This is done when:
- [ ] Crash: wifi_connection: com.apple.main-thread reproduced
- [ ] Crash: wifi_connection: com.apple.main-thread root cause determined
- [ ] Crash: wifi_connection: com.apple.main-thread resolved

Notes:
- Error: `Crashed: com.apple.main-thread: wifi_connection`
- [Crashlytics error report](https://console.firebase.google.com/project/uc-san-diego/crashlytics/app/ios:edu.ucsd.ucsandiego/issues/507f000da010b0b86156d901572245b2?time=last-seven-days&sessionEventKey=3b8fde02d2cf47ceb8c83547a8094482_1672596955769869796)
- flutter_error_exception
  - DioError [DioErrorType.response]: Http status error [404]
  - DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819) 
  - DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678) <asynchronous suspension>
  - DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586) <asynchronous suspension>
- flutter_error_reason
  - thrown DioError [DioErrorType.response]: Http status error [404]
  - DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
  - DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678) <asynchronous suspension>
  - DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586) <asynchronous suspension> . Error thrown null.

**Comment by p8gonzal** [comment]
Found all 404's occurring in the last QA build:

One occurs in weather.dart the service: 
flutter: DioError [DioErrorType.other]: SocketException: Failed host lookup: 'nq1dgvmtpe.execute-api.us-west-2.amazonaws.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
<asynchronous suspension>

Second one seems to be failing at  final String myAcademicHistoryApiEndpoint =
      'https://api-qa.ucsd.edu:8243/student/my/academic_history/v1/class_list';
As part of the classes service.

Unable to reproduce any WiFi crashes or exceptions, on and off campus wifi.

**Comment by c3bryant** [comment]
Resolved in 7.19, closing.
