### ISSUE TITLE
Flutter upgrade: 2.10.x --> 3.3.x

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1791]
Time Tracking: MA-95

This is done when:
- [x] Package [`gelolocator`](https://pub.dev/packages/geolocator) integrated and used to stream user coordinates to the Coordinates StreamProvider, replacing package `location`
- [x] Flutter upgraded from  2.10.x --> 3.3.x

- [x] [PR 1872 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1872-Test-Plan-7.23.0-QA-2394.xlsx?web=1) PASS on iOS
- [x] [PR 1872 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1872-Test-Plan-7.23.0-QA-2396.xlsx?web=1) PASS on Android

**Comment by c3bryant** [comment]
Test Result (Round 1):
- Round 1 testing failed on iOS
- Reason: User location not accessible after providing permission

Blocker:
- `location` package:
  - Latest version works as expected for Android but not iOS. Vice versa for the previous version
  - Lacks regular updates and testing

Next steps:
- Replace current `location` package with `geolocator` (#1793)

**Comment by c3bryant** [comment]
@gmihir Please provide an update here

**Comment by gmihir** [comment]
Sorry for the late update. I was dealing with a few local development issues that were finally resolved by deleting some caches that were on my machine. There were some other issues with the codebase that popped up when updating to Flutter 3.3.4, so I was working on resolving these so the project would compile without the behavior changing.

I started to update to the ```geolocator``` package and was running into a few issues; went back to the latest version of the ```location``` package to verify the issue. Notes on the issue show that the latest version did not work on iOS. I have verified that the location package is working on iOS on my branch. For the last few days, I was trying to test on my Android device but there seems to be an issue with the device as it is not booting up.

**Comment by gmihir** [comment]
Was able to get my Android test device to boot after soft reset. Compiling on Android gives these errors regarding the wifi_connection package, not sure how to resolve these.

```
e: /usr/local/Caskroom/flutter/2.0.2/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-4.1.0/android/src/main/kotlin/com/example/appsettings/AppSettingsPlugin.kt: (44, 25): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app_settings:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
