### ISSUE TITLE
Update JSON File for News Feed

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#18]
Currently in the News Feed (http://ucsdnews.ucsd.edu/rss/all) we are missing key information that is forcing us to link to an external website URL for the remaining parts of the story

What we are looking for in the feed is:
- The full story copy (currently we have the summary only)
- High quality image URLS and all image URLs available (currently we only get 1 low quality 'thumbnail' style image for most stories, which in many cases is too low-res to even use)

**Comment by c3bryant** [comment]
This request was sent a few times with no tangible response. We are reaching out to other contacts now and this issue is being tracked under our internal requests list.
