### ISSUE TITLE
S3 Object Life Cycle

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1808]
Time Tracking: MA-74

This is complete when the S3 bucket path have an object lifecycle applied:

- [x] barcode_scan_duplicate (delete after 3 months)
- [x] barcode_scan_success (delete after 1 day)
- [x] barcode_scan_invalid (delete after 1 month)
- [x] barcode_scan_ineligible (delete after 1 month)

- [x] S3 lifecycle operations verified

**Comment by morebytes** [comment]
Implementation done, closing out issue
