### ISSUE TITLE
Make Campus Lisa Card re-usable

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#181]
Make Conference more dynamic/re-usable (in particular for UCCSC)
Support multi-day
Needs an API to call that'll tell it what conference is running.
- [x] Set up master API to see what conference is running
- [x] Set up 2ndary API call that takes parameters from first API
- [x] Update app references to be more generic (get rid of clisa references)

**Comment by c3bryant** [comment]
The secondary API above is a Lambda behind an AWS API Gateway which returns the first active Special Event found if said event is within its activation window. If no active Special Events are found, nothing is returned.
