### ISSUE TITLE
Student ID Not Rendering

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1812]
Time Tracking: MA-34

Connect with the following students and gather more information for further troubleshooting.

https://collab.ucsd.edu/display/WTS/Student+ID+Card+Not+Loading

**Comment by c3bryant** [comment]
All reported issues on [Student ID Card Not Loading collab](https://collab.ucsd.edu/display/WTS/Student+ID+Card+Not+Loading) have been resolved.
