### ISSUE TITLE
Add path to shuttle map

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#182]
API: https://api.syncromatics.com/routes/{id}/shapes
This is undocumented by Syncromatics, but was obtained from their support team. Returns coordinates to draw polyline for a route.

**Comment by c3bryant** [comment]
Polylines for the routes we need are not available per Syncromatics. We will continue to push for this feature and reopen this issue when that happens in the future.

**Comment by celrak** [comment]
Polylines for base routes are now available.

From Kevin @ Syncromatics:

> The polyline information is now available via the API, but I'm still waiting on it to get documented in Apiary.  In the meantime, you should be able to start using the URL.  Here is the link:
> https://api.syncromatics.com/portal/routes/[[route_id]]/shapes
>  
> You put in the base route ID and will get back pattern ID's with lines.  Note that this will only return lines that are currently visible to the public.  If a route pattern is enabled for operations, but not public, you won't see it.
>  
> Let me know if you have any questions about base routes (containers) vs patterns (individual routes), etc.

Sample response from https://api.syncromatics.com/portal/routes/748/shapes:
```
[
    {
        "patternId": 3440,
        "line": "mrvgEvxqjUx@Rr@^h@RdANfCR`BBLAtKCb@QnBNxAB~FEfEB@yHDMLCbAA`@@^@zA@Bt@Jl@?~@DrJBPLPN@lC@tD@bBA~D]f@QX[XWZGRC\\B^FVXb@X`BDlH?p@Ob@i@PaA?m@?mCHyA?w@LaEGi@K]o@k@c@]O_@Wu@c@_@k@[u@_@w@sAi@TcDfBy@f@q@Pu@@kA]q@e@i@gAUkAI_A@gL?iEBiBXaCE]h@uBv@yFFiA?gAc@}Aq@aA[Wg@UoCe@_GaAyC[iBOm@@_@HgB~@lBvFJf@P\\~@rDTfBGbAc@bAaBiBm@Ck@VeBpBm@^qAdBsAfBQ|@?bAX`CFr@A|@{@jDy@vDGbCmCCs@Ao@?mFHyOd@SDMHIPEVD|CM~AA`@YZB|BAfB"
    }
]
```

**Comment by c3bryant** [comment]
Polylines for base routes are now available.

From Kevin @ Syncromatics:

> The polyline information is now available via the API, but I'm still waiting on it to get documented in Apiary. In the meantime, you should be able to start using the URL. Here is the link:
> https://api.syncromatics.com/portal/routes/[[route_id]]/shapes
> 
> You put in the base route ID and will get back pattern ID's with lines. Note that this will only return lines that are currently visible to the public. If a route pattern is enabled for operations, but not public, you won't see it.
> 
> Let me know if you have any questions about base routes (containers) vs patterns (individual routes), etc.

Sample response from https://api.syncromatics.com/portal/routes/748/shapes:
```
[
    {
        "patternId": 3440,
        "line": "mrvgEvxqjUx@Rr@^h@RdANfCR`BBLAtKCb@QnBNxAB~FEfEB@yHDMLCbAA`@@^@zA@Bt@Jl@?~@DrJBPLPN@lC@tD@bBA~D]f@QX[XWZGRC\\B^FVXb@X`BDlH?p@Ob@i@PaA?m@?mCHyA?w@LaEGi@K]o@k@c@]O_@Wu@c@_@k@[u@_@w@sAi@TcDfBy@f@q@Pu@@kA]q@e@i@gAUkAI_A@gL?iEBiBXaCE]h@uBv@yFFiA?gAc@}Aq@aA[Wg@UoCe@_GaAyC[iBOm@@_@HgB~@lBvFJf@P\\~@rDTfBGbAc@bAaBiBm@Ck@VeBpBm@^qAdBsAfBQ|@?bAX`CFr@A|@{@jDy@vDGbCmCCs@Ao@?mFHyOd@SDMHIPEVD|CM~AA`@YZB|BAfB"
    }
]
```

**Comment by Gulci** [comment]
Commit 7c01122 adds this functionality
![image](https://user-images.githubusercontent.com/8071536/41880825-0502b276-7895-11e8-9eaa-e36d37514f67.png)

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
