### ISSUE TITLE
Library link change

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#183]
Update link to point to new library website In campus-mobile and m.ucsd?

**Comment by i8wu** [comment]
library.ucsd.edu

**Comment by a6wu** [comment]
Good idea. There will be a redirect in place from libraries.ucsd.edu to library.ucsd.edu until we update it on our end.

**Comment by c3bryant** [comment]
Notes
- Initiated as a request from Library. They want to deprecate the old Libraries app at libraries.ucsd.edu/m/ by pointing this to their new responsive/mobile friendly site

Action Items
1) Redirect  libraries.ucsd.edu/m/* to library.ucsd.edu
2) Redirect  libraries.ucsd.edu/* to library.ucsd.edu
3) On http://m.ucsd.edu/, change the Library link to point to library.ucsd.edu
4) On UC San Diego mobile app, update Library link on Links card to point to library.ucsd.edu

*If m.ucsd.edu is going away in the near future, #3 could be skipped

**Comment by c3bryant** [comment]
It appears the new library site has launched with a few problems, one of which is affecting the Library link on the Link scard. Summary sent to Alex and Jeremy
