### ISSUE TITLE
Mobile Screenshots for iOS and Android

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1837]
Time Tracking: SVCOPS-408

Mobile app screenshots are required for a promotion video

This is done when the following screenshots are provided:

Tab Screenshots:
- [x] Home tab
- [x] Map tab
- [x] Notifications tab

Card Screenshots:
- [x] Shuttle card
- [x] Parking card
- [x] Classes card
- [x] News card
- [x] Events card
- [x] Dining card
- [x] Weather card
- [x] Speed Test card
- [x] Availability Card (Build 2268)

Other Screenshots:
- [x] Dining detail

**Comment by woznaut** [comment]
Hi - looks like we only need the Availability card shot. is that correct? if so, can I get an ETA?

**Comment by kwgong** [comment]
Hi! ios are all uploaded and the person uploading for android will finish up with the availability card around 5 PM tonight. So sorry for the delay!

**Comment by kwgong** [comment]
Hi! Claire was able to upload the last card. It should be all there now.

**Comment by woznaut** [comment]
sorry - where are they?

**Comment by c3bryant** [comment]
https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FWorkplaceTechnologyServices%2FShared%20Documents%2FCampus%20Mobile%2FScreenshots%2FMobile%20Promotion%20Video%20Sep%202022&FolderCTID=0x01200097B02543E8BEE14E9FA6BF4AC14CC4B4
