### ISSUE TITLE
Make Cards safer

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#187]
An issue with the events card's eventsData being a non-array caused the whole app to crash and be non-functional. We need to re-evaluate each card to make sure that is not possible.

Using Charles' test feeds below to test.

Cards:
- [x] Weather
- [x] Shuttle
- [x] Dining
- [x] Events
- [x] Quicklinks
- [x] News
- [x] Conference/Special Events

```
try {
    // finish by June 23
} catch (e) {
    // cry
 }
```

**Comment by c3bryant** [comment]
Test feed list for Events:
https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/feeds/events_invalid.json
https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/feeds/events_invalid_miscdata.json
https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/feeds/events_invalid_missing_eventlist.json
https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/feeds/events_invalid_text.json
https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/feeds/events_invalid_xml.json
https://s3-us-west-2.amazonaws.com/ucsd-mobile/dev/feeds/events_invalid_403.json

**Comment by i8wu** [comment]
We noticed the root causes of crashes were from array operations happening on non-arrays. We've remedied that problem by using Array.isArray before performing array operations (forEach, length)

Also, some of our services' fetches weren't catching errors which caused issues with invalid data or error codes. catches have been added.

**Comment by i8wu** [comment]
Also, we're using react-native-exception-handler to catch anything unexpected and clear AyncStorage to attempt and recover the app.
