### ISSUE TITLE
Integrate package device_info_plus

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1877]
Time Tracking: MA-95

Integrate package device_info_plus

This is done when:
- [x] Find the version of device_info_plus that has the same capabilities as device_info
- [x] Package [`device_info_plus`](https://pub.dev/packages/device_info_plus) integrated, replacing discontinued package `device_info`
- [x] Build information displays at the bottom of Profile tab

- [x] [PR 2029 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B2712095C-91B1-45D4-9448-DECF71D088F5%7D&file=PR-2029-Test-Plan-7.26.0-QA-2918.xlsx&action=default&mobileredirect=true) PASS on IOS
- [x] [PR 2029 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B8132F6D2-A75D-406F-93FD-7A49A6B5B7B7%7D&file=PR-2029-Test-Plan-7.26.0-QA-2919.xlsx&action=default&mobileredirect=true) PASS on Android

**Comment by morebytes** [comment]
Student ID card does not load on Android build. May have something to do w/ recent migrations in MyStudentProfile service

**Comment by c3bryant** [comment]
After review, Student ID not loading is related to a breaking change for MyStudentProfile service in #1500 as mentioned above.

**Comment by klortiz13** [comment]
The links to the spreadsheets for Android and IOS are mixed.
