### ISSUE TITLE
Use ms for TTLs

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#188]
Update AppSettings TTLs to milliseconds
Remove * 1000 from anywhere using TTL

**Comment by amneher** [comment]
i believe i've found the offending code. okay if i change and make a pr?

**Comment by c3bryant** [comment]
Hi Andrew, thank you for the PR! I think we may have a disconnect. To clarify, what we are trying to do is:

1) Convert all TTL values in AppSettings.js from Seconds to Milliseconds (i.e. WEATHER_API_TTL value would change from 1800 to 1800000)

2) Remove TTL conversion to Milliseconds throughout the rest of the /app/ code (anywhere you see a TTL being multiplied by 1000 (remove "* 1000"))

![screen shot 2017-06-30 at 8 30 39 am](https://user-images.githubusercontent.com/15112294/27742737-8b7cc44c-5d6e-11e7-9ef1-4d804496b57f.png)

**Comment by amneher** [comment]
whoops :smile:

**Comment by i8wu** [comment]
https://github.com/UCSD/campus-mobile/pull/190
