### ISSUE TITLE
Universal Search

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#19]
Provide a feature to search across cards and data feeds

**Comment by c3bryant** [comment]
Note: This will be very useful/used in the Nearby card to search for locations

**Comment by i8wu** [comment]
The way to do this would probably be to piecemeal the existing ListView items we have.(Dining, Events, News) As well as defining a search aggregate function for stuff that isn't stored on the app (Directory, Map, etc).

It should be fairly doable to search through the redux/store for the Events/News/Dining and compile a listview with mixed ListItems. This can be combined with some WebListItems for search relying on things outside of the app.

This can all be done with a TextInput and a ListView, but there are some libraries out there already. Haven't found a really good one, but this one seems to be popular. https://github.com/umhan35/react-native-search-bar

**Comment by c3bryant** [comment]
Moving this to our internal feature request board to flesh out the details before development begins.
