### ISSUE TITLE
Manage stops bug

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#191]
### Issue Description

Bug report from feedback form:
Unable to remove added stops
Manage stops will not allow removal, added stops are converted to closest stops and have no option to remove.

### Steps to Reproduce / Code Snippets

Adding a stop that's currently the closest stop will result in two closest stops being show in manage stops view.

#### Expected Results

There should only be one closest stop.

### Additional Information

* Platform(s) (iOS, Android, or both?): Both

**Comment by i8wu** [comment]
Partial fix https://github.com/UCSD/campus-mobile/commit/88c6193c7218a241539a564aea771723293f2079

Unable to reproduce being unable to remove stops.

**Comment by c3bryant** [comment]
We have not been able to reproduce being unable to remove stops if a second default stop has been added in the last two production builds. Closing until we are able to reproduce/verify that the issue still exists
