### ISSUE TITLE
Transition to Flutter Hooks/FQuery Part 1/3

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1918]
Time Tracking: MA-95

Working branch: [flutter_hooks](https://github.com/ucsd/campus-mobile/tree/flutter_hooks)

This is done when:
- [x] Availability card transitioned (morebytes)
- [x] Events card transitioned (xxwwyytt1)
- [x] News card transitioned (xxwwyytt1)
- [x] Employee ID card transitioned (zaashraf/declaire)

- [x] Parking card transitioned (morebytes)
- [x] Weather card transitioned (tkiyohar)
- [x] Student ID card transitioned (zaashraf)
- [x] Dining card transitioned (tkiyohar)

- [x] Investigate: Android: Dining card: Distance to locations not displaying on first load
  - Distances load successfully after closing and re-opening app
- [x] Reproduce: Grey screen below News card

- [x] PR submitted

- [ ] [PR 1973 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1973-Test-Plan-7.26.0-QA-2652.xlsx?web=1) PASS on iOS
- [ ] [PR 1973 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1973-Test-Plan-7.26.0-QA-2653.xlsx?web=1) PASS on Android

Flutter Hooks Migration Collab:
https://ucsdcollab.atlassian.net/wiki/spaces/WTS/pages/350192493/Flutter+Hooks+Migration

**Comment by xxwwyytt1** [comment]
[Meeting notes for hooks migration project](https://volcano-author-e16.notion.site/Provider-to-Hooks-Migration-7f8dadd6ada34915a1637873018c991d)

**Comment by c3bryant** [comment]
Please re-test when time allows

**Comment by morebytes** [comment]
Closing this out since we shut down the query hooks project and decided to go another direction with state management
