### ISSUE TITLE
v5.3.1 Hotfixes

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#192]
Hotfixes coming for after UCCSC

**Comment by c3bryant** [comment]
- [ ] Android Settings: Flicker when using toggle switches on Settings page
- [ ] Remove white border to the right of Date List on Special Events Schedule View
- [ ] Special Events Card: Filter button shown when pressing 'View My Schedule' from home tab
- [ ] Change double underline under applied Filters preview to single
- [x] Links Card: Can't do 'Hide Card' from home view
- [ ] Bolden the word 'Filter:' on the filter applied summary row seen on Special Events Schedule View
- [x] Links Card: Bookstore link is broken (deployed to prod)
- [x] Sort special events date array in ascending order (deployed to prod)
