### ISSUE TITLE
Package upgrade: firebase

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1921]
Time tracking: MA-95

This is done when:
- [ ] Firebase package firebase_analytics upgraded
- [ ] Firebase package firebase_core upgraded
- [ ] Firebase package firebase_crashlytics upgraded
- [ ] Firebase package firebase_messaging upgraded

**Comment by xxwwyytt1** [comment]
[Firebase Updating Notes](https://volcano-author-e16.notion.site/Firebase-Package-Upgrade-e9619017de184fc88375033cde49d466)

**Comment by c3bryant** [comment]
Blocked by [Google Play failed to upload artefacts#1931](https://github.com/UCSD/campus-mobile/issues/1931)
