### ISSUE TITLE
Firebase Upgrade Blocker / Google Play failed to upload artefacts

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1931]
Time Tracking: MA-78

Summary: Error when uploading build to Google Play after `firebase_analytics` version upgrade.
>Google Play failed to upload artefacts. This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.

This issue is blocking Flutter and Firebase upgrades:
- Unable to upgrade Flutter on current version of Firebase
- Unable to upgrade Firebase due to AD_ID requirement

This is done when:
- [x] Firebase analytics alternatives documented
- [x] Document implications of adding AD_ID permission to Android and IOS [Collab](https://ucsdcollab.atlassian.net/wiki/spaces/WTS/pages/1575911587/Firebase+AI_ID+Permission+Workaround)

- [x] AD_ID permission workaround implemented for Android
- [x] PR 2077 Testing PASS on Android

- [x] Upgrade package firebase_core
- [x] Upgrade package firebase_crashlytics
- [x] Upgrade package firebase_messaging
- [x] Upgrade package firebase_analytics

- [x] CI/CD build errors resolved on iOS
- [x] CI/CD build errors resolved on Android

---
**Android Test Plan**:
- [PR 2080 Regression Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B46B62A53-2660-40B8-BB90-EB1DB78A2DDD%7D&file=Regression-Test-Plan-PR-2080-7.28.0-Android-QA.xlsx&action=default&mobileredirect=true)

**Android Status**:
- Testing failed with one issue.

**Android TODO**:
- [x] Fix title bar text in dark mode and re-test
- [x] Regression test Scanner on build 3198 (c3bryant)

---
**iOS Test Plan**:
- [PR 2080 Regression Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B4E4C5A15-9597-4FBC-AE66-70544ADB188F%7D&file=Regression-Test-Plan-PR-2080-7.28.0-iOS-QA.xlsx&action=default&mobileredirect=true)

**iOS Status**:
- Testing failed with one issue.

**iOS TODO**:
- [x] Fix title bar text in dark mode and re-test (Same issue as Android)

**Comment by alien-traveler** [comment]
The first version of the Firebase Analytics Alternatives document is here: https://ucsdcollab.atlassian.net/l/cp/pheEsWa5

**Comment by morebytes** [comment]
Discovered and implemented a way to remove Android AD_ID from the build manifest. Needs to be tested to see if this solved the issue.
