### ISSUE TITLE
Weather Card Error

### ISSUE THREAD

**Issue by Jackyijun** [UCSD/campus-mobile#1942]
Time Tracking: MA-34

This is done when:
- [x] Reproduce issue in QA
- [x] Migrate AWS Lambda function to WeatherKit API
- [x] (WeatherKit API, Sourcecode/index.js) Create a mapping of WeatherKit "ConditionCode" values to existing icon names
  - Existing icon names:
    - clear-day.png
    - clear-night.png
    - cloudy.png
    - fog.png
    - partly-cloudy-day.png
    - partly-cloudy-night.png
    - rain.png
    - sleet.png
    - snow.png
    - wind.png
- [x] Translate new WeatherKit schema to previous WeatherService schema
  - Previous WeatherService response, tested on experimental:
    - https://mobile.ucsd.edu/replatform/v1/qa/integrations/mock/weather-forecast-2022.json

Because Forecast.io / DarkSky API has been deprecated since Mar 31. The Weather card in Production displays "An error occurred, please try again". We want to migrate to Apple's WeatherKit API

- [x] [PR 2023 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B95171DD1-B4D3-4CEF-852D-93BD907DD276%7D&file=PR-2023-Test-Plan-7.26.0-QA-2849.xlsx&action=default&mobileredirect=true) PASS on iOS
- [x] [PR 2023 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B00D21ADB-7C6A-4C0C-8894-D0133997784D%7D&file=PR-2023-Test-Plan-7.26.0-QA-2850.xlsx&action=default&mobileredirect=true) PASS on Android

- [x] [Deployment plan created](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FWorkplaceTechnologyServices%2FShared%20Documents%2FCampus%20Mobile%2FDeployments%2FWeatherForecast)
- [x] Weather service v1 deployed to PROD

**Comment by Jackyijun** [comment]
Blocker: Unable to create private key and service id for WeatherKit REST API

I was following the [documentation](https://developer.apple.com/documentation/weatherkitrestapi/request_authentication_for_weatherkit_rest_api#4042234) to make request to Apple's WeatherKit API but stuck on authentication. I did not find any button to create private key and service id in my Apple Developer Account's Certificates, Identifiers & Profiles page
![Image](https://user-images.githubusercontent.com/100548991/235552930-8fece7ca-42b4-48ab-943d-63dffc5afe65.png)

**Comment by Jackyijun** [comment]
<img width="710" alt="image" src="https://github.com/UCSD/campus-mobile/assets/100548991/aa436546-2937-4673-9782-7fcf097a3154">

<img width="679" alt="image" src="https://github.com/UCSD/campus-mobile/assets/100548991/ca0c6989-f0db-423e-afd3-4abf3647f07d">

https://www.youtube.com/watch?v=7mg42_Fix9k&t=2s

**Comment by a6wu** [comment]
@Jackkkkkkdzk  Still blocked?
