### ISSUE TITLE
Resolve APK Artifact Download

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1944]
Time Tracking:

https://api.codemagic.io/artifacts/01044934-0dc9-49d6-b36d-74affbc97a22/c0177b0f-3d28-42fa-96f5-6d63aa4ee91f/app-release.apk

For some users, a not authorized message displays. For others, a URL not found displays.

**Comment by c3bryant** [comment]
CI/CD settings updated. Artifacts are now saved for a longer period of time, which should resolve this issue.
