### ISSUE TITLE
Campus Branding Update

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1949]
Time Tracking: MA-42

This is done when:
- [x] App icon replaced with campus branding update icon
- [x] Remove app loading/onboarding animation
- [x] Replace Scanner Card trident icon with new scanner icon below
- [x] Update "Return to Learn" in Campus Information card to read "Covid-19 Resources/Guidelines" (Web card - deployed)
- [x] Replace Android silhouette french fry icons used for messaging and lock screen
- [x] Remove images/assets/TridentLogo.png
- [x] Update images/assets/UCSDMobile_banner.png 
- [x] Remove images/assets/UCSDMobile_rounded.png 
- [x] Update images/assets/UCSDMobile_sharp.png 
- [x] Verify no other uses of UCSD french fry icon/artwork in campus mobile

- [x] [PR 1961 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1961-Test-Plan-7.25.0-QA-2577.xlsx?web=1) PASS on iOS
- [x] [PR 1961 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1961-Test-Plan-7.25.0-QA-2578.xlsx?web=1) PASS on Android

**Comment by victor-thai** [comment]
app icon replaced, currently focused on replacing animation with new branding idea

**Comment by c3bryant** [comment]
Hi @victor-thai - I have updated the requirements to remove the loading animation.

@woznaut Please add a new issue for the creation of a new branded loading animation.

**Comment by victor-thai** [comment]
implemented removal of old french fry animations

**Comment by woznaut** [comment]
![UCSDMobile_scannerIcon](https://github.com/UCSD/campus-mobile/assets/19195410/f239624d-cbe2-4f21-a809-8b1207d6f71f)
@victor-thai updated scanner icon attached
