### ISSUE TITLE
Sign-in bug

### ISSUE THREAD

**Issue by mliu6723** [UCSD/campus-mobile#1950]
Time Tracking: MA-78

Students reporting they are unable to login to SSO on QA

Reproduction Test 1:
- A) Sign-in bug reproduced on Experimental as Student
- B) Sign-in bug reproduced on v7.24.0 as Student
- C) Sign-in bug reproduced on Experimental as Staff
- D) Sign-in bug reproduced on v7.24.0 as Staff

Notes:
- Checkout a tag:
git checkout v7.24.0 -b v7.24.0

**Comment by c3bryant** [comment]
Hi @Jackkkkkkdzk & @mliu6723,
Issue updated after review.
Please re-test and report your results here for Test 1 (A) and (B) above. Please include device type Android or iOS.

**Comment by tkiyohar** [comment]
Hi All,
I just tried running the build I got from "git checkout v7.24.0 -b v7.24.0" and I'm getting the following errors (see below). Note: I am able to run/build the regular experimental branch without issue, and I tried running both of these builds on both a "Pixel 2 API 30" and a "Pixel 6 API 31" emulator with same results/errors.

"
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:22:8: Error: The method 'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'.
  void createSync({bool recursive = false}) =>
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This is the overridden method ('createSync').
  void createSync({bool recursive = false, bool exclusive = false});
       ^
"

**Comment by c3bryant** [comment]
Hi @tkiyohar @mliu6723 @Jackkkkkkdzk 

Testing of the 7.24 tag requires Flutter 3.3.10. Here is how to go back to this version on OSX
```
cd <your-flutter-sdk>
git checkout 3.3.10
flutter --version
```


Here is one way to test the 7.24 tag:

```
git clone https://github.com/ucsd/campus-mobile campus-mobile-724-test
cd campus-mobile-724-test
git checkout v7.24.0 -b v7.24.0
flutter pub get
flutter run
```

**Comment by Jackyijun** [comment]
Hi Charles,
I encountered same error as Trent when testing 7.24. Following your instructions, I have now successfully tested both Experimental and v7.24.0 as Student and as Staff on both iOS simulator and Android emulator(Pixel 5). I have found **no problem** logging in to SSO.

**Comment by tkiyohar** [comment]
After downgrading my Flutter version to 3.3.10, I was also able to successfully log-in on both of my emulators ("Pixel 2 API 30" and a "Pixel 6 API 31") on my student and work accounts. 

However, I also experienced several graphical issues on the app home screen which included individual cards and sometimes the entire home screen itself not displaying. These error culminated in the app crashing on both my emulators on multiple occasions. 

In trying the 7.24v on my physical device (Pixel 6a android 13), I was also able to replicate these same graphical errors (screenshots below) but did not encounter a crash (the home screen froze several times though and had to be reloaded). 

Additionally, it is worth noting that across all devices (physical and emulated) both the employee ID card and student ID card either returned an error or displayed blank while I was purportedly logged in to my work or student account respectively.

![4fc72760-bd6b-4fbe-969b-295d68bbe3a4](https://user-images.githubusercontent.com/98426739/236565451-b81b2e56-538f-43ff-80d2-a9aa99b8af88.jpg)

![6c5f77e9-6bf3-4b0b-943b-1cc336c7cbf8](https://user-images.githubusercontent.com/98426739/236565484-3440a62f-d101-4edf-92f9-21d0d6c8083c.jpg)

**Comment by c3bryant** [comment]
Sign-in bug verified resolved in May, let's close this out.
@tkiyohar would you please create a new issue for the web card height problem if there is not one already. Student ID not rendering in QA is being worked on in a separate issue.
