### ISSUE TITLE
Student Profile Data Issue

### ISSUE THREAD

**Issue by zaashraf** [UCSD/campus-mobile#1951]
Time Tracking: MA-64

Check for translational errors in JSON Response.
Notes:

- Note any possible field name changes that can affect MyStudentProfile API
-  SAH Notes: https://ucsdcollab.atlassian.net/wiki/spaces/ACP/pages/265421048/2023-04+SAH+Release+Notes
-  Check if field is used in Campus Mobile App
-  Check if field is used MyStudentProfile JSON Response
- Look for translational error in source code: sourcecode.ucsd.edu

**Comment by zaashraf** [comment]
Following changes were made:
--deprecation of Student Legal Name fields

-  Student Legal Full Name replaced by Student Full Name
- Student Legal First Name replaced by Student First Name
- Student Legal Last Name replaced by Student Last Name
- Student Legal Middle Name replaced by Student Middle Name

**Comment by zaashraf** [comment]
- Can disregard name changes to Student Name fields, because Student Profile Model doesn't use name field.
- API-qa, source code, and student name model for campus mobile has no translational errors

**Comment by zaashraf** [comment]
The initial issue of studentProfile model not returning data was solved by renaming the following fields in the json response for the studentProfile model code:
 ID_Card_Number
ID_Card_Bar_Code
ID_Card_Classification_Type
ID_Card_Issue_Number
 in order to match the Json response and properly assign the values to the variables in the student profile model.

When checking the student profile source code there was discrepancy in the above field names, where the names of the fields do not match. This could possibly be an issue, however, the code is working fine right now. See picture of this below:
![image](https://github.com/UCSD/campus-mobile/assets/117619116/89524d35-7e82-404b-ad52-2c8aafbe8ea8)

![cdbe07dc-c28e-4433-8c2c-0bc7c66f87dd](https://github.com/UCSD/campus-mobile/assets/117619116/13e2eae9-52e2-41f2-a677-f075446b5f25)

**Comment by c3bryant** [comment]
Hi @zaashraf,
After review, the breaking change to MyStudentProfile in #1500 has been addressed on the back-end. Please revert any changes made to the hooks migration branch and verify the Student ID card renders as expected in QA as it does on experimental now.

**Comment by a6wu** [comment]
@zaashraf  Can you work with Claire (and reach out to Charles if needed) to reconcile this issue. Should it be closed?
