### ISSUE TITLE
PROD and QA Dining Locations Missing Location Data

### ISSUE THREAD

**Issue by tkiyohar** [UCSD/campus-mobile#1957]
The following restaurants are missing google maps location data in QA and PROD:
- Bird Rock
- Blue Bowl
- Copa Vida
- Cups Coffee
- Cups Outdoor Cafe
- Curry Up Now
- Dirty Birds
- Fairbanks Coffee
- Fan Fan
- Pinpoint Cafe
- Plant Power
- Ridge Walk Social
- Shake Smart
- Showa Ramen
- Street Corner
- Tahini
- Underbelly
- Volkan Coffee

The location data for these restraunts should be added to [https://api-qa.ucsd.edu:8243/dining/v3.0.0/locations](https://api-qa.ucsd.edu:8243/dining/v3.0.0/locations) and the prod data link if there is a seperate one

- [ ] Obtain coordinates for all dining locations missing location data
- [ ] Provide coordinates to WTS (Patricia) to add to data endpoint
- [ ] Once the coordinates have been purportedly updated, test locally on a device running an experimental/QA build to confirm that all dining locations now have their coordinates/location data

**Comment by a6wu** [comment]
The JSON data being returned from HDH source has breaking changes, https://hdh-web.ucsd.edu/diningmenuapi/api/DiningDataService/GetDiningInfo_V2/.

Also affects the web page, https://blink.ucsd.edu/facilities/services/general/personal/dining.html.

**Comment by a6wu** [comment]
Temporary fix in place by handling "special hours" attribute.
