### ISSUE TITLE
Dining Card: All HDH Vendors Are Missing From The Dining Card

### ISSUE THREAD

**Issue by tkiyohar** [UCSD/campus-mobile#1959]
All of the HDH dining vendors are missing from the dining card.
The data for all of the following restaurants is not included in the data returned to the app when fetching the dining vendors data:
- 64 Degrees
- 64 North
- Cafe Ventanas
- Canyon Vista
- Club Med
- Food Trucks
- Foodworx
- Johns
- Oceanview
- Pines
- Restaurants at Sixth
- Rogers
- Roots
- Seventh Market
- Sixth Market
- The Bistro

Debugging Steps
- [ ] Reproduce the bug
- [ ] Fix the bug
- [ ] Test locally on a device

**Comment by c3bryant** [comment]
Thanks for reporting, @tkiyohar 
I've created a ticket directed to the service owner internally. Closing.
