### ISSUE TITLE
Add Timezone config to AppSettings

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#196]
### Issue Description
Time conversions using moment.js library may reflect timezone of the phone instead of the timezone of UCSD. We've determined this is undesired behavior and will need to be addressed by specifying a timezone for moment.js to use during conversions
https://momentjs.com/timezone/

**Comment by c3bryant** [comment]
This problem which led to the creation of this issue is a result of one report from a user who had their timezone set incorrectly. The times displayed by the mobile app were correct based on this user's timezone setting. I propose we re-evaluate this issue in the future if the need arises.
