### ISSUE TITLE
Transition to Flutter Hooks/FQuery Part 2/3

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1960]
Time Tracking: MA-95

Working Branch: [flutter_hooks_2](https://github.com/UCSD/campus-mobile/tree/flutter_hooks_2)

This is done when:

**--- EASY HOOKS ---**
- [x]  Bottom Nav (NeuraByte-IT-Solutions & virajl)
- [ ] Connectivity (hellofatimad)
- [ ] Locations (alien-traveler & virajl)
- [x] Notices (alien-traveler)
- [x] Scanner Message (nathandelarosa & klortiz13 & virajl)
- [ ] Spot Types (rysakai22)

**--- MEDIUM HOOKS ---**
- [ ] Classes (declaire)
- [ ] Finals (tkiyohar)
- [ ] Map (Von-T)

**--- HARD HOOKS ---**
- [ ] Notifications Freefood (declaire)
- [ ] Parking (morebytes -- needs merge)
- [ ] Speed Test (morebytes)

**Comment by morebytes** [comment]
Closing this out since we shut down the query hooks project and decided to go another direction with state management
