### ISSUE TITLE
Student ID Card Error

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1965]
Time Tracking: MA-34

Might be caused by the this attribute in the JSON object returned from MyStudentProfile, "Student_Level_Current": null.

- [x] Pull from upstream to get the latest code
- [x] Checkout the feature branch
- [x] Compile and run the code
- [x] Reproduce the bug
- [x] Fix the bug
- [x] Test locally on a device
- [ ] Create Pull Request

**Comment by declaire** [comment]
ID Card issue in prod fixed by increasing the memory on Lambda Function: "ExtractPIDAuthorizer" 

ID Card issue in QA fixed by adding a mapping template to the Lambda function: "MyStudentProfile"
