### ISSUE TITLE
Android: Upgrade Android API target to level 33

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1971]
Time Tracking: MA-95

Review the Android 13 (API 33) migration guide and confirm compliance. https://developer.android.com/about/versions/13/migration

This is done when:
- [x] Android target API level 33 on experimental confirmed

**Comment by declaire** [comment]
Current SDK Versions on experimental branch:

compileSdkVersion: 33
minSdkVersion: 23
targetSdkVersion: 33

**Comment by c3bryant** [comment]
Resolved.
