### ISSUE TITLE
Add dSYMs to build and deploy process

### ISSUE THREAD

**Issue by mliu6723** [UCSD/campus-mobile#1976]
Time Tracking: MA-118

This is done when: 
- [x] dSYM upload is added to CI/CD pipeline
- [x] dSYM upload testing PASS in QA
- [x] dSYM upload added to all CI/CD workflows
- [x] dSYM upload testing workflows removed

**Comment by c3bryant** [comment]
Hi @mliu6723,
Ok to proceed on dSYM upload rollout to primary CI/CD workflows. See updated task list above.
