### ISSUE TITLE
Dynamic Type text change does not resize cells accordingly

### ISSUE THREAD

**Issue by alroman** [UCSD/campus-mobile#198]
### Issue Description

This is a UX/Accessibility issue for the conference card of the app, if you make the font size larger (as described here https://support.apple.com/en-us/HT202828), the list view cells don’t adjust their height accordingly, and text gets clipped inside the cell.  I did not test this on Android.

### Steps to Reproduce / Code Snippets

Follow instructions outlined here to change text size via Dynamic Type: https://support.apple.com/en-us/HT202828

#### Expected Results

I expect the text not to be clipped and cell to grow accordingly with content.

### Additional Information

* React Native version: n/a
* Platform(s) (iOS, Android, or both?): iOS 10.3.3
* Operating System (macOS, Linux, or Windows?): n/a

**Comment by i8wu** [comment]
![screenshot_20170811-110446](https://user-images.githubusercontent.com/20545218/29225974-274e9aee-7e85-11e7-8a26-a128992b4410.png)
Happens on Android as well. Never really thought about increasing font size affecting the app though. Will need to have our UX guy weigh in on it, but I don't think we've done much accessibility testing on the app yet. @woznaut

**Comment by i8wu** [comment]
iOS screenshot for reference as well
![image uploaded from ios](https://user-images.githubusercontent.com/20545218/29226463-08f9c2a6-7e87-11e7-8120-a8ca6a5d6a62.jpg)

**Comment by alroman** [comment]
Yeah, I never think to adjust Dynamic Type as a test either.  It was one of my former colleagues who noticed it and asked me if the app was 'broken' for me too.  I noticed it on at least one other phone (that I can recall) in the conference after that.

**Comment by c3bryant** [comment]
@vvp002 This feed has been updated to use for testing Special Events https://s3-us-west-1.amazonaws.com/ucsd-mobile-dev/special-events/campus-lisa.json

**Comment by vvp002** [comment]
- Bug was due to hardcoded row height for the Special Events Listview
- Removed hardcoded height and improved flexbox usage to stop text from getting cut off (in PR #225 )
- Tested with above Campus Lisa json

**Comment by c3bryant** [comment]
Branch dynamic-text has been used to generate TestFlight build 5.6 (4), which has the Campus LISA 2017 special event activated for testing purposes.

**Comment by c3bryant** [comment]
Issues found during the first round of testing have been resolved. Branch dynamic-text has been used to generate TestFlight build 5.6 (5).

**Comment by c3bryant** [comment]
Verified. Branch dynamic-text has been merged into v5.6-rc
