### ISSUE TITLE
Update Academic Calendar (2023-2024)

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1981]
Time Tracking: MA-62

This is done when:
- [x] AcademicTerm JSON updated to reflect [Academic and Administrative Calendar 2023–2024](https://blink.ucsd.edu/instructors/resources/academic/calendars/2023.html)
- [x] Testing PASS in QA
- [x] Deployed to PROD
- [x] Testing PASS in PROD

Notes:
- PROD Target Date: 2023-09-11

**Comment by a6wu** [comment]
Link top "Academic Calendar" goes to 404.
