### ISSUE TITLE
 Target Android API 33 or Higher

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1985]
Time Tracking Epic: https://its-pro.ucsd.edu/browse/MA-151

Review the Android 13 (API 33) migration guide and confirm compliance. https://developer.android.com/about/versions/13/migration

- [x] Campus Mobile targeting API 33

**Comment by c3bryant** [comment]
mliu6723 and I have verified we targeting API 33

We will likely need to disable older builds which may be active in other test tracks: https://stackoverflow.com/questions/76931031/warning-app-must-target-android-13-api-level-33-or-higher-it-does

**Comment by c3bryant** [comment]
Resolved
