### ISSUE TITLE
Evaluate Impact of Dart 3

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1986]
- [ ] Pull from upstream to get the latest code
- [ ] Checkout the feature branch
- [ ] Compile and run the code
- [ ] Develop the feature
- [ ] Test locally on a device
- [ ] Create Pull Request

**Comment by c3bryant** [comment]
Flutter+Dart upgrades blocked by #1931.

Let's revisit when this blocker has been resolved.
