### ISSUE TITLE
Update Barcode Source

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1988]
Time Tracking: MA-64

Use the barcode value from the MyStudentProfile API.

- [x] Pull from upstream to get the latest code
- [x] Checkout the feature branch
- [x] Compile and run the code
- [x] Develop the feature
- [x] Test locally on a device
- [x] Create Pull Request
- [x] deprecate the old barcodeModel 

- [x] [PR 1993 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1993-Test-Plan-7.26.0-QA-2755.xlsx?web=1) PASS on iOS
- [x] [PR 1993 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1993-Test-Plan-7.26.0-QA-2756.xlsx?web=1) PASS on Android

**Comment by c3bryant** [comment]
Example:
```
/lib/ui/student_id/student_id_card.dart: (line 239)

// BEFORE
barcodeModel.barCode.toString(),

// AFTER
profileModel.barcode.toString(),
```

**Comment by morebytes** [comment]
PR was merged, closing this issue
