### ISSUE TITLE
[Urgent] Recommendation request

### ISSUE THREAD

**Issue by 41y08h** [UCSD/campus-mobile#1994]
_I'm writing this here because of the urgency of the matter, I had also written an email yesterday for this to @c3bryant but didn't receive any response yet. I contacted Karen (karie on Discord) too but she's no longer working on the team. So, I had no option but to write it here._

Hi there, I'm Piyush, the main contributor to the open-source project [fquery](https://github.com/41y08h/fquery). I'm also a senior-year student at a high school in New Delhi, India, and have been doing computer programming for over 4 years now. I'm currently in the process of filling out my US college application (on the Common App).

As far as I can see on this GitHub repo, the integration of fquery into the codebase is in its final stages and I hope it is solving the project's needs. I'm coming up with new features and improvements on the next release in the not-too-distant future.

I'm writing this to humbly request the development team for a recommendation on my college application about how fquery helped the campus app's codebase. A recommendation from the development team would carry a lot of weight and make my college application stronger. This means a lot to me and would be highly appreciated.

I'm applying early to a university and hence **the deadline is 31st October**. If the team decides to recommend me, please provide me with the email I should use to invite the recommender to the Common App.

Thank you for your time and consideration.

**Comment by c3bryant** [comment]
Dear Piyush,

I have replied to your request via email.

Warm regards,
c3bryant
