### ISSUE TITLE
Making card re-ordering more discoverable

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#1996]
Time Tracking: MA-42

It is not immediately obvious to users that they can reorder the cards. 

Suggested fix:

- [x]  Rename "Cards" under Profile - s/b "Card Controls"

- [x] Add line of instruction to Cards Setting screen - "Press and hold to reorder" - ideal would be if this text appears at the top of the list but bottom would be acceptable
- [x]  Make borders between card titles more prominent - duplicate the slight 3D style used on the Profile screen to separate items

- [x] [PR 2032 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B220FE1AC-9E7E-422C-9F32-01064F9F2C26%7D&file=PR-2032-Test-Plan-7.27.0-QA-3082.xlsx&action=default&mobileredirect=true) PASS on iOS
- [x] [PR 2032 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B2F9DD164-C8C4-403C-9BD6-880E74C036F6%7D&file=PR-2032-Test-Plan-7.27.0-QA-3083.xlsx&action=default&mobileredirect=true) PASS on Android

**Comment by c3bryant** [comment]
Has iOS testing been completed?

**Comment by MaximPodgore** [comment]
I'll be in China from Tuesday till September 1st. I asked Timothy to follow
through with the testing on this one.

**Comment by Ishxn20** [comment]
I wasn't able to finish testing as I couldn't see the build on Test Flight. Max was suppose to ask Alex to rebuild it.

**Comment by morebytes** [comment]
@Ishxn20 Just messaged Max.

**Comment by morebytes** [comment]
Deployed
