### ISSUE TITLE
Transition to Flutter Hooks/FQuery Part 3/3

### ISSUE THREAD

**Issue by tkiyohar** [UCSD/campus-mobile#2004]
Time Tracking: MA-95

Working Branch: flutter_hooks_3 -- NEEDS TO BE CREATED

This is done when:

**--- HARD HOOKS --- **
- [ ] Messages ()
- [ ] Notifications ()
- [ ] Scanner ()
- [ ] Cards ()

**--- VERY HARD HOOKS --- **
- [ ] triton_media (TDB is the provider completed?)
- [ ] user
- [ ] Shuttle Hook ()

**Comment by morebytes** [comment]
Closing this out since we shut down the query hooks project and decided to go another direction with state management
