### ISSUE TITLE
 Implement GetX Prototype for News Card

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#2006]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-153

## Description
This issue aims to explore the use of GetX in our Flutter application, focusing on implementing a prototype for the News card component. The goal is to keep the effort minimal, aiming for a completion time of a few days.

## This is done when:
- [x] **Setup GetX Environment** (Assigned to: virajl)
- [ ] **Setup GetX Environment** (Assigned to: declaire)
  - Integrate GetX into the project.
  - Ensure compatibility with existing app setup.
- [x] **Setup GetX Environment** (Assigned to: Von-T)
- [x] **Setup GetX Environment** (Assigned to: Ishan)
- [x] **Setup GetX Environment** (Assigned to: klortiz13)
<br>

- [x] **Refactor News Card with GetX** (Assigned to: virajl)
- [ ] **Refactor News Card with GetX** (Assigned to: declaire)
  - Implement GetX Controllers for managing state.
- [x] **Refactor News Card with GetX** (Assigned to: Von-T)
- [x] **Refactor News Card with GetX** (Assigned to: Ishan)
- [x] **Refactor News Card with GetX** (Assigned to: klortiz13)
<br>

- [x] **Implement Business Logic with GetX** (Assigned to: virajl)
- [ ] **Implement Business Logic with GetX** (Assigned to: declaire)
  - Replace existing Provider logic with GetX.
  - Ensure data fetching and state updates work seamlessly.
- [x] **Implement Business Logic with GetX** (Assigned to: Von-T)
- [x] **Implement Business Logic with GetX** (Assigned to: Ishan)
- [x] **Implement Business Logic with GetX** (Assigned to: klortiz13)
<br>

- [x] **Testing and Debugging** (Assigned to: virajl)
- [ ] **Testing and Debugging** (Assigned to: declaire)
  - Test the News card in various scenarios.
  - Debug any issues related to GetX implementation.
- [x] **Testing and Debugging** (Assigned to: Von-T)
- [x] **Testing and Debugging** (Assigned to: Ishan)
- [x] **Testing and Debugging** (Assigned to: klortiz13)
<br>

- [ ] **Document and Present** (Assigned to: virajl, declaire, Von-T, Ishan, klortiz13)
  - Document the changes.
  - Present to the team.

## Resources
- [GetX Documentation](https://pub.dev/packages/get)
- [Flutter Official Documentation](https://flutter.dev/docs)

**Comment by morebytes** [comment]
Closing this due to change of direction
