### ISSUE TITLE
Document AH Column Groups in Use

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#2011]
Time Tracking: MA-57

This is done when:
- [x] Document AH column groups in use by the APIs on Collab.

**Comment by tkiyohar** [comment]
AH Column Sets Google Sheet: https://docs.google.com/spreadsheets/d/1aeEqhVa8sjxWg_soHjRvHK0PAK4zqrqbsmaRvhB-qXU/edit?gid=0#gid=0

**Comment by a6wu** [comment]
@tkiyohar Can you move the Google Docs to collab?

**Comment by tkiyohar** [comment]
@a6wu Done. Please see corresponding databases in Collab: [https://ucsdcollab.atlassian.net/wiki/spaces/SAH/database/1340702787](https://ucsdcollab.atlassian.net/wiki/spaces/SAH/database/1340702787)
[https://ucsdcollab.atlassian.net/wiki/spaces/SAH/database/1340702782](https://ucsdcollab.atlassian.net/wiki/spaces/SAH/database/1340702782)
