### ISSUE TITLE
Data Provider by Flutter Team

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#2036]
https://its-pro.ucsd.edu/browse/MA-175

**Comment by morebytes** [comment]
It may be worth looking into RiverPod again, the better version of Provider. It has hooks support now and would be a minimal effort retrofit on our existing codebase, allowing for better readability and performance to pave the way for the Campus Reactivation Project.

**Comment by morebytes** [comment]
Closing this because we are switching to Jira for task management and this has already been opened there.
