### ISSUE TITLE
Distance from dining locations is not showing up

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#204]
A recent update appears to have broken the distance to dining locations (if the user has location services enabled).

This information should appear under the directions/walk icon on the dining card, and dining full list view.

**Comment by c3bryant** [comment]
Recommend starting here:
campus-mobile/app/views/dining/DiningItem.js
<Text style={css.dl_dir_eta}>{data.distanceMilesStr}</Text>

**Comment by c3bryant** [comment]
https://github.com/UCSD/campus-mobile/commit/509eb4a8b7309498475766cd2dfe1e5b51ef4f8b#diff-bd2155e655b03def89a8962a3de1ff83

**Comment by vvp002** [comment]
Tested the rendering in home when scrolling with/without the pull statement in LocationSaga from commit 509eb4a. Averaging about 35-50 when just scrolling around for both cases, with both having about the same performance. Varies if stays on certain cards for too long.

**Comment by vvp002** [comment]
Fixed with PR: Uncomment Put statement in Location Saga to Update Dining Locations #205

**Comment by c3bryant** [comment]
Verified done in dev

**Comment by c3bryant** [comment]
Deployed with v5.5
