### ISSUE TITLE
Google Play Target API level requirements

### ISSUE THREAD

**Issue by mliu6723** [UCSD/campus-mobile#2040]
Time tracking: MA-95
- [ ] Pull from upstream to get the latest code
- [ ] Checkout the feature branch
- [ ] Compile and run the code
- [ ] Update the app to target Android 14 (API level 34) or higher.
- [ ] Test locally on a device
- [ ] Create Pull Request
- [ ] Publish a new version of the app to production by 8/31/2024

**Comment by c3bryant** [comment]
Dupe of #2043
