### ISSUE TITLE
Update Target SDK for Android

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#2043]
Due date Aug 31. https://developer.android.com/google/play/requirements/target-sdk

This is done when:
- [x] Target SDK for Android upgraded to 34
- [x] Build and test success locally
- [x] Build and test remotely (CodeMagic)

Blocker:
-  Android Experimental builds failing #2056

**Comment by a6wu** [comment]
@tkiyohar  updates?

**Comment by tkiyohar** [comment]
@a6wu No news to report as of now. I will be investigating this issue and touching base with Maxim in the coming days.

**Comment by tkiyohar** [comment]
Work on this issue is currently blocked pending the following:
- [ ] Charles investigating ad permissions with new firebase version
- [ ] New app builds are failing on code magic due to unrelated issue ([see issue 2056](https://github.com/UCSD/campus-mobile/issues/2056))
