### ISSUE TITLE
QA: COVID scanner malfunctioning

### ISSUE THREAD

**Issue by morebytes** [UCSD/campus-mobile#2045]
Based off reports from multiple testers, the COVID scanner does not seem to be working properly.

MA-191

- [x] Pull from upstream to get the latest code
- [x] Checkout the feature branch
- [x] Compile and run the code
- [x] Reproduce the bug
- [x] Fix the bug
- [x] Test locally on a device
- [x] Create Pull Request

**Comment by c3bryant** [comment]
Root cause traced to API slowness in the QA environment, and breaking changes to the authorizer.

The default timeout in QA has been increased to 60 seconds, and the authorizer has been restored.
