### ISSUE TITLE
Add 'no results' message when using map search and no locations are returned

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#206]
Currently, if a user performs a search on the Maps tab in the UC San Diego mobile app, they will see an animated loading icon for a few seconds, and then it will go away with no indication that no results were found.

Implement a message near the bottom of the map view that states 'No results found for your search.', similar to what Google Maps does in this same scenario.

![google-maps-no-results](https://user-images.githubusercontent.com/15112294/33569140-99f32346-d8dd-11e7-8c4e-a86ccbb75486.png)

**Comment by c3bryant** [comment]
One more addition for this task:

There is a 'No Results Found' placeholder text that shows up in the map search input field but there is a bug preventing it from displaying unless you click the 'back' arrow and then return to the search bar.

Rather than addressing this bug, please remove this functionality, we do not want to overwrite the user's inputted search text if no results are found

**Comment by vvp002** [comment]
Removed resetting of search input in searchTimeout function from NearbyMapView.js to keep original user search input. 

Added toast message instead to notify the user that no results were found.
![screen shot 2017-12-04 at 11 06 23 am](https://user-images.githubusercontent.com/13816146/33675023-284b166a-da66-11e7-8d13-a285571c17ee.png)

**Comment by woznaut** [comment]
please move the message to the bottom of the viewport. Too confusing to have it overlaid on top of the user's position. Also the original message was probably better - "No results found for your search."

**Comment by c3bryant** [comment]
Updated in dev

<img width="280" alt="screen shot 2017-12-06 at 9 33 20 am" src="https://user-images.githubusercontent.com/15112294/33676323-52b8ef68-da6a-11e7-8496-0b2aa59d7b5a.png">

**Comment by c3bryant** [comment]
Deployed with v5.5
