### ISSUE TITLE
Dismiss a Card from the View

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#21]
When a card is dismissed, log the user's action to determine preference:
- timestamp
- card metadata
- location

Dismiss action implemented with a swipe left to right, right to left, or an X icon on the card?

**Comment by i8wu** [comment]
I think card should be dismissible with swipe and button presses?
For alert cards and yes/no cards probably.
Will work on a demo.

**Comment by a6wu** [comment]
Demo of a swipe to dismiss card is at https://github.com/UCSD/now-mobile/blob/dev/app/views/card/DismissibleCard.js
