### ISSUE TITLE
OceanView Terrace Menu Items Missing

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#210]
We received a report that menu items are not displaying for the OceanView Terrace location in the app. The menu items appear to be coming across in the feed from HDH, so we suspect there may be an issue with the dining-service lambda.

The dining-service repo can be found here: https://sourcecode.ucsd.edu/projects/WTS/repos/dining-service/browse

**Comment by vvp002** [comment]
Investigated and discovered issue was because of a name mismatch between the HDH feed and our static feed. The menu items were under "OceanView" key name in HDH feed while the static feed was using the key name "Oceanview Terrace Restuarant". 

Resolved by editing the static feed to match the HDH's "OceanView" key name.

**Comment by c3bryant** [comment]
The oceanview-fix branch of the dining-service repo on bitbucket has been tested and is ready for deployment.

@a6wu When time allows please deploy the oceanview-fix branch from our bitbucket dining-service repo to AWS Prod

One additional commit was added to the oceanview-fix branch to update the coordinates for the Blue Pepper restaurant

**Comment by a6wu** [comment]
@c3bryant Will the oceanview-fix branch be merged into the master branch?

**Comment by c3bryant** [comment]
@a6wu Yes, we will do that as soon as possible. There was a breaking change made to the dining-service master branch which should only deploy with the dining V2 update. In the future we will use feature branches to avoid this scenario with the master branch.

**Comment by c3bryant** [comment]
This was deployed and has been verified - closing
