### ISSUE TITLE
Dining Service Inconsistencies / Simplification

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#211]
We would like to simplify the merging of the HDH and static feeds. Previously, custom logic was put in place to merge info from the static feed (which includes HDH locations now, but will not in the future) into the actual HDH feed. This is no longer required, and now may be causing inconsistencies in the data.

- Remove custom logic used to cherry-pick data from the HDH feed
- Perform a clean merge of the two feeds so that each location is one object inside of an array, removing the 'GetDiningInfoResult' key that all HDH data is housed under currently.
- Add try/catch for 'context' and remove the LAMBDA_ENABLED boolean

Dining Service Repo:
https://sourcecode.ucsd.edu/projects/WTS/repos/dining-service/browse

Final output sample:
[dining-service-update_output-sample.txt](https://github.com/UCSD/campus-mobile/files/1540179/dining-service-update_output-sample.txt)

**Comment by vvp002** [comment]
Dining service has been updated at same repo link:
https://sourcecode.ucsd.edu/projects/WTS/repos/dining-service/browse

Simplified now to remove custom logic, perform a clean merge, and added a try/catch for 'context'

**Comment by c3bryant** [comment]
The dining-v2 update is now at a point where this issue has been verified and can be closed
