### ISSUE TITLE
Partial search results not working in map view

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#213]
### Issue Description

Running a partial search won't return any results and show the "No results found for your search" toast.

### Steps to Reproduce / Code Snippets

Search "Student" and quite a few results will be displayed.

Search "Stu" and no results will be returned.

#### Expected Results

Searching "Stu" should return results that contain "Stu", such as the results of searching "Student".

**Comment by c3bryant** [comment]
With MapLink nearing end of life, we will instead be looking at migrating to the Campus Bird V2 API for map search.
