### ISSUE TITLE
Map Search Result Order

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#214]
### Issue Description

Map search result order does not appear to follow ABC or closest distance ranking. Hard to scroll through the result list to find what I'm looking for.

### Steps to Reproduce / Code Snippets

Search for "Stuart Collection" or "Lab." Results are not in ABC nor closest distance ranking.

**Comment by Gulci** [comment]
db2a9ec: Adds current location to map search query, allowing results to be sorted by distance from user. Results returned are now in closest distance ranking.

**Comment by c3bryant** [comment]
Verified. This has been merged into v5.6-rc
