### ISSUE TITLE
Special Event Data Handling

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#215]
There have been a few user reports of special event cards staying activated and showing up long after an event has ended.

To improve the user experience, wipe all special event data and hide the special event card immediately after the event has ended. In addition, ensure that the Special Events card on the User Settings tab is hidden from view.

**Comment by vvp002** [comment]
PR #228 : wiped special event data and hide card in Home view and User Settings once event is over

**Comment by vvp002** [comment]
PR #229: has updated Special Events function above. Tested with different null/active special events and working as expected to clear saved data and hide non active event, and otherwise not.

**Comment by c3bryant** [comment]
Verified & merge into v5.6-rc
