### ISSUE TITLE
Change Default Card Order

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#217]
Based on student feedback and data analysis, we will be changing the default card order in the app. The new order will be:
Emergency (upcoming)
Special Events
Finals (upcoming)
Shuttle
Class Schedule (upcoming)
Dining
Events
News
Links
Weather

Note: This change will not be made retroactively; only for new app users who have not loaded the app previously.

**Comment by Gulci** [comment]
Default card order has been changed. Only takes affect on a new installation of the application.

**Comment by c3bryant** [comment]
Verified. Branch new-order has been merged into v5.6-rc
