### ISSUE TITLE
UI Tests for Continuous Integration

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#218]
Using Jest and snapshots, setup four UI tests to verify component rendering. The tests should cover the main view for each of the follow tabs in the app:
- Home
- Map/search
- Feedback
- User Settings

**Comment by Gulci** [comment]
Basic test structure / setup and tests for Feedback have been added:  f4df5c7

**Comment by Gulci** [comment]
Tests have been added for NearbyMapView, Home, and PreferencesView: 3d7d23

**Comment by Gulci** [comment]
This is done for UI Components. To-dos include writing tests for our Sagas and for our Reducers. This can be done in a later issue.

**Comment by c3bryant** [comment]
Verified in testing branch, merged into v5.6-rc
