### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#22]
Define the process and flow of how a push notification will be initiated and displayed onto the device.

**Comment by i8wu** [comment]
Put this on hold for march? @a6wu @c3bryant

**Comment by a6wu** [comment]
@i8wu @c3bryant yes, let's hold on this.

**Comment by i8wu** [comment]
Probably a native push notification and a listview with previous notifications.

**Comment by i8wu** [comment]
https://github.com/UCSD/campus-mobile/pull/189

**Comment by c3bryant** [comment]
Push notification messages have been added to v5.4 with Firebase as the delivery method
Firebase -> Notifications -> New Message
