### ISSUE TITLE
Unable to disable shuttle selection in Map

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#224]
### Issue Description

You are unable to deselect a shuttle overlay on the map once one has been selected.

### Steps to Reproduce / Code Snippets

1. Go to Map
2. Click Shuttle button
3. Make any selection
4. Try to disable a shuttle

#### Expected Results

There should be a way to turn off the shuttle overlay, either by reselecting the previously selected option or by selecting a "None" option.

**Comment by c3bryant** [comment]
@vvp002 Thank you for your work on this issue outlined here: https://github.com/vvp002/campus-mobile/commit/8d86df658dcf8e89961d8b0522cdd8cb62768fb5

@Gulci We would like to continue moving forward on this issue as a secondary priority item. Sending your way to work towards the completion of this task when time allows.

**Comment by Gulci** [comment]
84db81a5 resolves this issue, and the user can now toggle a route by tapping on it again.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
