### ISSUE TITLE
Surf Service

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#230]
The get-surf-feed Lambda function on AWS QA has been recreated as SurfService and updated. This new Lambda has been mapped to the SurfService (/dev/v2/surf-service) API Gateway 

API Gateway:
 - SurfService v1: https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/0yi5xwy0v7/resources/bxldrd/methods/GET
- Endpoint: https://0yi5xwy0v7.execute-api.us-west-2.amazonaws.com/dev/v1/surf

Lambda ($LATEST):
 - https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/SurfService

Lambda Repo:
- Branch surf-service-v2
- https://sourcecode.ucsd.edu/projects/WTS/repos/surf-service/compare/commits?sourceBranch=refs%2Fheads%2Fsurf-service-v2&targetBranch=refs%2Fheads%2Fmaster

@a6wu - sending this your way for deployment to AWS Prod

**Comment by a6wu** [comment]
Completed.
https://kusyfng6mg.execute-api.us-west-2.amazonaws.com/prod/v1/surf

**Comment by c3bryant** [comment]
Verified and updated the endpoint in v5.6-rc here 03707ce
