### ISSUE TITLE
Upgrade Navigator

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#232]
With the upgrade to React Native .54, we will need to migrate our current navigator (react-native-router-flux) to V4. This is a good time to explore navigator options.

Based on community discussions, testing, and internal consensus the top 3 contenders are:
[React Navigation](https://facebook.github.io/react-native/docs/navigation.html)
[React Native Router Flux V4](https://github.com/aksonov/react-native-router-flux)
[React Native Navigation](https://github.com/wix/react-native-navigation)

Early testing results are showing React Navigation, the now-default navigation option for React Native applications, as the clear front-runner based on improved performance, screen transitions, and capability.

**Comment by Gulci** [comment]
Commits 19cb00e, e74c34e, and e6894f5 update React Native to version 0.54.2 and swap out React Native Router Flux v3 (deprecated) for React Navigation, which v4 of React Native Router Flux is based on and is officially endorsed by the React Native project.

These commits also merge in the latest changes in our v5.6 release candidate.

**Comment by c3bryant** [comment]
Verified & merged into v5.6-rc branch
