### ISSUE TITLE
Student AD Test Accounts for Mobile SSO

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#236]
Acquire student AD test accounts for ongoing development and testing of mobile SSO.

Notes:
- For all intents and purposes these accounts will need to be indistinguishable from a regular student AD account. The account will need a valid PID, current class schedule (ongoing) and finals schedule which is returned during appropriate finals windows.
- This request is for `5` student AD test accounts, with a mix of undergraduate and graduate students.

**Comment by a6wu** [comment]
Let's move forward onboarding more students as alpha/beta testers.

**Comment by c3bryant** [comment]
Sounds good. Let's revisit this in the future if/when it becomes feasible.
