### ISSUE TITLE
Dining Service Update

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#238]
There are two new lambda services ready for deployment to AWS Prod - DiningService and DiningMenuService.

**DiningService:**
 - API Gateway: https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/zbncpgqqj4/resources/w0wr5w
 - Lambda: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DiningService?tab=graph
 - Endpoint: https://zbncpgqqj4.execute-api.us-west-2.amazonaws.com/dev/v3/dining/locations
 - Repo: 
 	- Branch: dining-v2
 	- Location: https://sourcecode.ucsd.edu/projects/WTS/repos/dining-service/browse

**DiningMenuService:**
 - API Gateway: https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/zbncpgqqj4/resources/d3zbec
 - Lambda: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DiningMenuService?tab=graph
 - Endpoint Sample: https://zbncpgqqj4.execute-api.us-west-2.amazonaws.com/dev/v3/dining/menu/64
 - Repo:
 	- Branch: master
 	- Location: https://sourcecode.ucsd.edu/projects/WTS/repos/dining-menu-service/browse

@a6wu - Sending this your way for review and deployment to AWS Prod

**Comment by a6wu** [comment]
Completed.

https://pg83tslbyi.execute-api.us-west-2.amazonaws.com/prod/v3/dining/locations
https://pg83tslbyi.execute-api.us-west-2.amazonaws.com/prod/v3/dining/menu/64

**Comment by Gulci** [comment]
@a6wu Sending a request to the first endpoint with an Origin header of https://cms.ucsd.edu isn't creating the correct Access-Control-Allow-Origin header from the response.

**Comment by a6wu** [comment]
@Gulci Made some updates. Let me know if you run into other issues.

**Comment by Gulci** [comment]
@a6wu Thanks Alex, that fixed it.

One other quick thing: I made a change to the Dining Service Lambda to escape characters. Both the CMS and the HDH API were including the `&amp;` escape code in their responses which doesn't look good on the app. When you can, can you update the lambda on prod with the latest changes?

**Comment by c3bryant** [comment]
Aside from the note above, all testing of the two production endpoints listed above has passed (CMS & Mobile App)

**Comment by Gulci** [comment]
@a6wu @c3bryant I've made some changes to the Dining-Service lambda code that deals with processing entries from the CMS. In addition to fixes for HTML-escaped characters added in by the CMS, we now support adding gps coordinates to entries on the CMS, which means that distance estimates are now displayed by the app.

Changes are already pushed to the BitBucket repo.

**Comment by c3bryant** [comment]
@Gulci Changes confirmed and verified. @a6wu Ready to deploy

**Comment by c3bryant** [comment]
Verified and incorporated into v5.6-rc
