### ISSUE TITLE
Dining will show eatery as closed after midnight even if open

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#240]
### Issue Description

If an eatery closes at 1 a.m. and it's midnight, it will read "Closing soon" but the status will be displayed as closed.

#### Expected Results

The eatery should be displayed as open with a green dot.

**Comment by Gulci** [comment]
Additionally, the dining card and views don't update their statuses in real-time. Add an interval so that statuses update without the user having to reload the app.

**Comment by c3bryant** [comment]
Verified in `dev` and cherry-picked into `v5.6.1-hotfix`. Ready to deploy
