### ISSUE TITLE
SSO: Last updated time for Class/Finals schedules

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#242]
Add a small label to the Class Schedule and Finals cards which displays the last updated time.
Since Class and Finals schedules are returned from the same Academic History API call, any time this request returns a response, update the `last updated time` displayed on the Class Schedule and Finals cards

The format of the `last updated time` displayed on the Class Schedule and Finals cards should be a  human-friendly timestamp
Sample: `Last updated: Tuesday, May 1st at 3:30 p.m.`

**Comment by c3bryant** [comment]
Mockup approved for implementation on Classes and Finals card. Thanks @Gulci

**Comment by Gulci** [comment]
Using this from moment will make an easily readable string:
http://momentjs.com/docs/#/displaying/from/

**Comment by c3bryant** [comment]
Added a LastUpdated component to the Finals and Classes cards in these commits: e949f86, bbb36a0, d1cf973

**Comment by Gulci** [comment]
TODOS:
* Integrate warning if data is not able to sync or if there as authentication error.
* Give user reauthentication options when there is an error

**Comment by c3bryant** [comment]
TODOs added to an improvements list for future releases.
Verified in v6.0-rc, closing.
