### ISSUE TITLE
Messaging: Setup external datastore

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#243]
Setup an external datastore with AWS DynamoDB
From the mobile app will call the DynamoDB API to read/write information

Requirements:
- The data store should support a user that is logged in from multiple devices

**Comment by c3bryant** [comment]
For reference:
- [postDynamoDB Lambda](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/postDynamoDB?tab=graph)
- [firebaseNotifications DynamoDB](https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:selected=firebaseNotifications)

**Comment by Gulci** [comment]
Done.
