### ISSUE TITLE
Messaging: Setup Firebase SDK backend

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#245]
Setup a backend which will call Firebase SDK to send notifications
This backend should be accessible via API

**Comment by Gulci** [comment]
Here are the different parts of the backend that have to be set up:

1. Lambda that can send messages to topic(s) or user(s) **(Complete)**
2. Authorizer Lambda that verifies that the person sending the message has the correct permissions
3. Table(s) containing message-sending permissions
4. Firebase token registration API to associate user IDs with Firebase push tokens

**Comment by Gulci** [comment]
Done and ready for review.
