### ISSUE TITLE
Messaging: Restrict Firebase API access

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#246]
Only allow authorized access to Firebase APIs

**Comment by Gulci** [comment]
Currently the Messages API is restricted to people that fulfill the following criteria:

1) Have a valid access token with access to the Messages API on the WSO2 API Store
2) Have permission to send messages to the topics or users they specify

**Comment by c3bryant** [comment]
Thanks @Gulci this has been reviewed and is good to go.
