### ISSUE TITLE
Movie Show Times

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#25]
Add nearby and upcoming movie show times.

**Comment by c3bryant** [comment]
Making a note to discuss this at the feature meeting on 9/23

**Comment by i8wu** [comment]
Looking into using [Fandango API](https://developer.fandango.com)

[This](https://github.com/erunion/showtimes) looked promising, but it was powered by Google Movies which was discontinued about a month go. The maintainer is trying to move over to Fandango so maybe we could just wait.

**Comment by i8wu** [comment]
Alternatively we could work with [UCSD Box Office](https://ucsdboxoffice.com) for some sort of integration

**Comment by c3bryant** [comment]
I'd like to review this again to see if it's worth building and/or something people want.
If it is, let's turn it into a real task and flesh out the details.

**Comment by i8wu** [comment]
If it's only for movie times I don't think it'd be worth the effort. If it was something that integrated with the UCSD Box Office, I could see it being valuable.

**Comment by woznaut** [comment]
Adding this as a feature could be a good subject for a mobile poll question.

**Comment by c3bryant** [comment]
We will revisit this under our internal feature request board.
