### ISSUE TITLE
SSO: Finals Schedule: Setup auto activation/deactivation

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#254]
This task handles how the automatic activation and deactivation of the Finals Schedule card.
- Turn on 2 weeks leading up to finals week (turn on for all students)
- Turn off card at end of finals period for all students at midnight; e.g. June 16 at 12am (turn off for all students)

The AcademicTerm API is configured to return `true` starting exactly 2 weeks prior to the start of a Final, and to return false at exactly 12am (midnight) immediately after the term ends.

See https://blink.ucsd.edu/instructors/resources/academic/calendars/2017.html for term information

**Comment by Gulci** [comment]
Commit 776a499 now sets the Finals card `autoActivated` value to false. This card should be activated when finals are active _and_ user is authenticated, not on-login.

**Comment by Gulci** [comment]
Commit 8df6ab9 sets up auto-activation and auto-deactivation for the Finals card. The Finals card is displayed when the academic term API Finals endpoint returns true.

**Comment by Gulci** [comment]
Implementing this has brought up an issue: Cards maybe activated and made visible to the user even when they have previously opted to hide the card. We should implement this in a way that doesn't interfere with user choice (#261) . However, this issue itself has been completed.

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing.
