### ISSUE TITLE
SSO: Convert Finals and Schedule Card to new Flatlist view

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#257]
These cards were written before the React Native upgrade, so they are using old deprecated views. This results in the cards not rendering in certain situations where they should be rendered, such as when activating the finals card and switching to the home view.

**Comment by Gulci** [comment]
Commit a3d815 converts the FullScheduleListView to use the new SectionList. FinalsCard still has to be converted but should be trivial to convert.

**Comment by Gulci** [comment]
Commit ca5564c4 converts FinalsCard to use FlatList. This card still needs to be tested. Requires Student Test account / dummy finals data to continue testing.

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing.
