### ISSUE TITLE
SSO: Incorporate Academic Term API

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#258]
This task is to incorporate the Academic Term API

Dev endpoint: https://m9zc9vs4f1.execute-api.us-west-2.amazonaws.com/dev/v1/term/current
AppSettings: ACADEMIC_TERM_API_URL

Notes:
- The `name` returned from the API will ultimately be displayed somewhere on the Classes and Finals cards
- The `code` is the term code which should be used for all API calls pertaining to academic records
- Possible return values: https://sourcecode.ucsd.edu/projects/WTS/repos/academic-term/browse/Readme.md

**Comment by Gulci** [comment]
As of commit 4a55f95,  `code` from the API is now incorporated into the ScheduleAPI call.

**Comment by Gulci** [comment]
Waiting on potential refinements to Finals and Class cards. Where will we display the current term?

**Comment by Gulci** [comment]
Upon discussion with @c3bryant, @woznaut we are reconsidering / not moving forward with displaying the current term.

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing.

**Comment by Gulci** [comment]
Note to revisit functionality when the current term is over.

**Comment by a6wu** [comment]
The dates listed at https://blink.ucsd.edu/instructors/resources/academic/calendars/2017.html are when the classes start. The student may have already registered for classes weeks in advance. Need to confirm with students when they would like to see their class schedule.
