### ISSUE TITLE
Mutation of State

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#260]
Various operations within the app mutate state, creating unexpected behavior and usually are the source of various hard-to-diagnose bugs.

This has affected the implementation of SSO in relation to adding and removing cards. This issue includes both the fixes made for SSO as well as general fixes made to remove mutation of state from the app in general.

[redux-immutable-state-invariant](https://github.com/leoasis/redux-immutable-state-invariant) has been installed to help track down any actions and components that mutate state.

**Comment by Gulci** [comment]
8daca0a fixes all mutations of state as well as various bugs that would throw errors throughout the app.

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing.
