### ISSUE TITLE
SSO: Classes/Finals: Time formatting

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#262]
Where time is displayed on the Classes and Finals cards, do the following:
1. Convert the time from military time to standard (i.e. 15:30 -> 3:30)
2. Add `a.m.`/`p.m.` 

Samples:
Current format: `11:30 - 13:30`
New format: `11:30 a.m. - 1:30 p.m.`

**Comment by Gulci** [comment]
Commit 2e1f50a resolves this issue. However, times are now truncated in the class card:
<img width="145" alt="image" src="https://user-images.githubusercontent.com/8071536/39778800-32989286-52bc-11e8-9e82-c44125e6822f.png">

**Comment by Gulci** [comment]
This has been revised and times are now displayed in this section as [day] @ [start time]
![image](https://user-images.githubusercontent.com/8071536/39786407-58b591d0-52d5-11e8-8784-e6fb3174dda4.png)

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing
