### ISSUE TITLE
Create a dummy login to display mock Classes/Finals data

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#267]
This task is to create a dummy login to display mock Classes/Finals data

Notes:
- The dummy User ID/Password will be determined outside of this issue
- The mock data used to display Classes and Finals data should be completely scrubbed, and make no reference to any real information such as:
  - Student information of any kind
  - Class information of any kind
  - UCSD information of any kind

@a6wu Assigning this to you until if/when we are instructed to begin work on this. Note: This issue should be tied to the Kadabra milestone if no true AD test accounts w/ PID are to be provided prior to app submission.

**Comment by Gulci** [comment]
Commit 12eb479 adds internal test accounts. Username is studentdemo, and password is the same.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/8071536/40384982-0831817a-5dba-11e8-84ac-bdd85afeba8d.png">

Adds code that swaps between production and demo endpoints.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/8071536/40385016-22211028-5dba-11e8-8c4e-fbb05eb490ad.png">

**Comment by c3bryant** [comment]
API Gateway `MobileDemoMockData` has been setup and verified in dev and prod. v6.0-rc endpoints updated. closing.
