### ISSUE TITLE
React Native Update 0.55.4

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#268]
This issue is being created to keep track of our progress towards updating to React Native v0.55.4 as well as some dependency updates.

## Dependencies
| **Dependency**  | **Old Version**  | **New Version**  | **Notes** |
|---|---|---|---|
| moment  | 2.21.0  | 2.22.1  |   |
|  node-forge | 0.7.2  | 0.7.5  |   |
| react-native-device-info  | 0.21.2  |  0.21.5 |   |
| react-native-exception-handler | 2.7.1 | 2.7.5 | |
| react-native-fcm | 14.1.3 | 15.0.2 | |
| react-native-google-analytics-bridge | 5.6.2  |  5.6.3 | |
| react-navigation | 1.5.8 | 1.5.11 | Last working version |
| react-native-sortable-list | 0.0.21 | 0.0.22 | |
| react-native-popup-menu | 0.12.3 | 0.12.6 | Last working version |
| react-native-vector-icons | 4.5.0 | 4.6.0 | |
| react-navigation-header-buttons | 0.0.5 | 1.0.0 | |

## Dev Dependencies
| **Dependency**  | **Old Version**  | **New Version**  | **Notes** |
|---|---|---|---|
| babel-eslint | 8.2.2 | 8.2.3 | |
| babel-jest |22.4.3 | 22.4.4 | |
| enzyme-to-json | 3.3.3 | 3.3.4 |
| eslint-plugin-flowtype | 2.46.1 | 2.46.3 | |
| eslint-plugin-import  | 2.9.0 | 2.12.0 | |
| eslint-plugin-react | 7.7.0 | 7.8.2 | |
| jest | 22.4.3 | 22.4.4 | |

## Blocked updates
| **Dependency**  | **Old Version**  | **New Version**  | **Notes** |
|---|---|---|---|
| react-native  | 0.54.4 | 0.55.4 | Blocked by issues with compiling for android with react-native-maps |
| react-native-maps | refer to `package.json` | 0.21.0 | Blocked by pending react-native issue https://github.com/facebook/react-native/issues/16906 | 
| react-native-popup-menu | 0.12.3 | 0.13.1 | Requires rn v0.55.+ |

## Breaking updates
| **Dependency**  | **Old Version**  | **New Version**  | **Notes** |
|---|---|---|---|
| redux  | 3.7.2 | 4.0.0 | Makes us have to update redux-persist |
| redux-persist | 4.10.2 | 5.9.1 | Incompatible with previous states. Have to write custom experimental migrations or wipe all user data | 
| react-navigation | 1.5.8 | 2.0.1 | Breaking API changes. Requires refactoring |

**Comment by Gulci** [comment]
React native update is currently blocked by https://github.com/facebook/react-native/issues/16906

**Comment by Gulci** [comment]
Based on the state of things, we should hold off on updating to v55 of react native, as well as hold off on updating redux-persist, redux, and react-navigation. react-navigation made significant breaking changes that will drastically affect our Router setup. I think it's best to wait and see if some issues are resolved in the future.

**Comment by Gulci** [comment]
We will be staying on React Native 0.54.4 for now, but we should be able to upgrade in the next milestone. Will attempt again after the completion of Parking & Messaging projects.

**Comment by c3bryant** [comment]
React Native upgrade blocking issue https://github.com/facebook/react-native/issues/16906 has been resolved in RN 57.3+

**Comment by c3bryant** [comment]
Starting in March 2019, App Store Connect requires iOS builds be compiled with Xcode 10.1 or later.

App Center does not support Xcode 10.1 and RN 0.55 (our current version) - waiting on a response

App Center may support Xcode 10.1 and RN 0.57+ (TBD) - testing that this is correct

From Apple:

> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "UC San Diego". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> SDK Version Issue - This app was built with the iOS 11.4 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Best regards,
> The App Store Team

**Comment by c3bryant** [comment]
Issues #397 & #398 track the current progress of the react native platform upgrade. Closing
