### ISSUE TITLE
Messaging V1: Implement Notifications tab and UI

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#289]
This task is to:

1. Implement a Notifications tab, replacing the current Feedback tab
2. Relocate Feedback to User Settings
3. Build the Notifications tab UI view. Subsequent views will be addressed in V2.
4. Integrate the Firebase notifications UI/UX flow from #291
5. Add a notifications indicator overlaying the top-right portion of the Messaging tab icon as shown here:
![screen shot 2018-07-19 at 8 18 56 am](https://user-images.githubusercontent.com/15112294/42952043-6be21d7a-8b2c-11e8-9246-da0bd7b7eb98.png)

**Comment by c3bryant** [comment]
1 & 2 have been completed under 77d21499 on the `messaging` branch.

User Profile:
![user-profile](https://user-images.githubusercontent.com/15112294/42951791-de4dd5ee-8b2b-11e8-8314-6a28577caf4b.png)

Messaging Tab Shell:
![messaging](https://user-images.githubusercontent.com/15112294/42951814-eba5aeba-8b2b-11e8-88cb-5981bc7a004c.png)

**Comment by bethanybin** [comment]
e7e942b979f3fd9f86ff14b12b4641e2efd07bec still need to decide on what vector icons to put on the left

![simulator screen shot - iphone 6 - 2018-09-13 at 11 09 49](https://user-images.githubusercontent.com/24581206/45507234-56ffd280-b746-11e8-925e-a268a192be8b.png)

**Comment by bethanybin** [comment]
9b9c1a429fcca8e263c4ab10bf703f2df916535b badge alert shows number of unread messages 
![simulator screen shot - iphone 6 - 2018-09-21 at 13 03 29](https://user-images.githubusercontent.com/24581206/45903716-7e3a4d80-bd9f-11e8-81cb-22d8b3a04f16.png)

**Comment by c3bryant** [comment]
Nice job everyone! Any bugs found will be handled in separate issues. Verified & closing.
