### ISSUE TITLE
Parking structure notifications UI

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#293]
This task is to implement parking notification settings.

Topic notification settings have been added in Parking V1. Parking notification settings will appear below that and have a header labeled 'Parking' with available garages listed below.

Requirements:
1. Each garage can be enabled/disabled via a switch on the right of the row
2. The user will set their start time (which should default to 8:00 AM) and end time (default to 5:00 PM)
3. The user will select the days of the week they want to receive notifications. The default selection should include Mon thru Fri
4. If a parking notification switch is enabled, that lot should be expanded by default. If the switch is disabled, the lot should be collapsed.

Parking Notifications Final:
![parking-notifications-final](https://user-images.githubusercontent.com/15112294/46424295-9722f700-c6ed-11e8-9d4e-00bc24217604.png)

Parking Notifications - Set Dates:
![set-dates](https://user-images.githubusercontent.com/15112294/47038288-f0e7e000-d135-11e8-8313-cbf03041775a.png)

**Comment by atmartorana** [comment]
SetDates.js ready for review and styling has been moved to its respective file

**Comment by c3bryant** [comment]
Closing this out now as the RMP V2 direction has been revised. New issues will reference the work completed here such as the Set Dates and Set Time implementations which are needed to satisfy the new requirements.
