### ISSUE TITLE
Parking V1: Implement logging for Parking lot status API calls

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#296]
This task is to setup AWS CloudWatch logs for the ParkingAvailability Lambda which is accessed via the Parking API Gateway

We would like to have the following information logged:
- The parking lot ID being requested
- The User-Agent making the request
- The X-Forwarded-For IP address
- All errors and warning messages

**Comment by atmartorana** [comment]
Added logging parameters to CloudWatch in Parking API. Errors, parking lot ID, request ID, User Agent, and X-Forwarded-IP have are now logged. Commit to Bitbucket at: https://sourcecode.ucsd.edu/projects/WTS/repos/parking-availability/commits/6bc4d29ec5fcd6c42b50530ee13b0aecaabc03a5

**Comment by c3bryant** [comment]
Verified on AWS Dev. This work will be deployed with #270 so we can close this issue.
