### ISSUE TITLE
Special Events: CLISA 2018 Feed Verification

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#300]
This task is to verify that the CLISA 2018 agenda has been finalized, and to test the JSON feed in-app once completed. This feed should include all items from the [CLISA 2018 Agenda](http://campuslisa.ucsd.edu/agenda/index.html) page

**Comment by c3bryant** [comment]
We wil need to add a logo for CLISA 2018.
Sample logo from CLISA 2017:
![campus_lisa_2017_logo](https://user-images.githubusercontent.com/15112294/40559887-1df75a34-600d-11e8-8691-8cee037f97f7.png)
Dimension requirements: 1242x440

**Comment by Gulci** [comment]
Mostly complete. Logo has been added.

Logo needs to be reviewed in app, otherwise we are ready to go.

**Comment by Gulci** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/8071536/41171217-94281fca-6b04-11e8-8dc1-b082a56def48.png">
