### ISSUE TITLE
Messaging: Define API for Mobile Platform

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#302]
Define set of APIs for the messaging feature for the mobile platform. This definition is independent of  implementation specifics and will allow the mobile platform to utilize various messaging vendors.

**Comment by Gulci** [comment]
Proposed specification for Messages API as of June 20th. Includes being able to query for messages sent by a user to the mobile app and the ability to push messages to specific audiences on the mobile app.

API Endpoints
**POST**

    /messages
        Description: Schedules a message for delivery to the selected audience
        Parameters (application/x-www-form-urlencoded)

            audience (required)
                Which audience to deliver the message to
                Can be an audience or category / topic (student, staff, all, freeFood)
            message (required)
            time
                unix time stamp format;
                time the system will deliver the message
        Responses
            200
                Returns message ID: a unique identifier for the message in the system
            401
                Invalid authorization token provided

**GET**

    /messages
        Parameters
            ?dateSent
                standard ISO date
        Responses
            200
                Array of messages sent matching specified parameters
                If no parameters, returns all messages sent by user
            404
                Returned when there are no messages sent matching specified parameters

        /{message ID}
            Description
                Obtains message delivery status
            Responses
                200
                    Message delivery status, estimated time of delivery, metadata
                404
                    Message not found

**PUT**

    /messages/{message ID}
        Description
            Updates scheduled message
        Responses
            200
                Message updated
            401
                Unauthorized to access specific message
            404
                No message found matching ID
            405
                Message no longer available for editing (already sent)

**DELETE**

    /messages/{message ID}
        Description
            Cancels delivery of pending message
        Responses
            200
                Status of deletion
            401
                Unauthorized to access specific message
            404
                No message found matching ID
            405
                Message has already been delivered

**Comment by Gulci** [comment]
Messages: https://mobileplatform-messages-ucsd.docs.stoplight.io/
My Messages: https://mobileplatform-mymessages.docs.stoplight.io/
Token Registration: https://mobileplatform-registration-ucsd.docs.stoplight.io/
