### ISSUE TITLE
Error Report: Warning message/alert shown after logging out of student SSO account

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#306]
When students logs out of their SSO account, they are seeing the following message/alert:

![image uploaded from ios](https://user-images.githubusercontent.com/15112294/40813017-9c7a73ac-64ed-11e8-83b5-fc3f37e5935f.png)

Issue reported by Vivian
iOS 6.0 (5)

**Comment by Gulci** [comment]
This is related to an issue with how the app is handling pending requests, and ties in to some issues users are reporting with the class card getting stuck on "Updated x hours ago". I'm working on this right now.

**Comment by Gulci** [comment]
Commit cfbb732 should resolve this issue, as well as issues with auto-refreshing.

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing
