### ISSUE TITLE
Special Events: Session labels are not displaying on SpecialEventsListView

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#308]
Session labels (filters) are not displaying on SpecialEventsListView. This bug is present in 5.6+

**Comment by c3bryant** [comment]
Done on v5.6.1-hotfix 465c378

**Comment by Gulci** [comment]
3131c79 adds some fixes for missing information in talks.

Keynotes now show the keynote speaker's talk / topic:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/8071536/40866031-731ef244-65b0-11e8-9e2a-c2316d57fbf8.png">

Regular talks now show speaker information:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/8071536/40866040-82331bd4-65b0-11e8-836c-1af4ce8b834b.png">
