### ISSUE TITLE
Omit special meetings from the Classes card and full view

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#312]
The recent update to the My/AcademicHistory API in QA can now return sections which are not actual classes in the response. This task is to add the following criteria when evaluating whether or not a section returned by the API is a class or not.
New criteria:
- A section/class is only valid if its special meeting code is empty string `""`
- If the special meeting code is not an empty string, the section in question is not a class and therefore should be removed from the classes card and full view

**Comment by Gulci** [comment]
This should be resolved by a35d044

**Comment by c3bryant** [comment]
Added c311a41 to omit these classes from the full classes view as well

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing.
