### ISSUE TITLE
Running app on expo

### ISSUE THREAD

**Issue by odinscode** [UCSD/campus-mobile#314]
Hello everyone!

It is not an issue, just a question (sorry by the way if it is not in correct place): can we somehow connect that project to expo?

Thanks in advance,
Odin

**Comment by Gulci** [comment]
Hi @odinscode , this project contains custom native iOS and Android modules which I believe prevents this project from being connected to Expo. Is there something in particular you were wishing to get out of this project being connected to Expo?

**Comment by odinscode** [comment]
Hi @Gulci, I'm not really comfortable with Android Studio and I don't have any opportunity to use XCode. So I wanted to use Expo to navigate throw that application to get more experience in it. 

Due to inexperience in react native I don't know how to correctly configure expo in particular.

I would glad to hear any suggestions or advice, thanks!

**Comment by c3bryant** [comment]
Hi @odinscode, it sounds like you are on a PC, so Android Studio would be your best option for moving forward. To do this, follow the instructions [here](https://facebook.github.io/react-native/docs/getting-started.html) after selecting the 'Build Projects with Native Code' tab. If you need assistance with a particular step of the Android Studio setup, you can email me directly @ c3bryant@ucsd.edu

Expo out of the box will not work with our project for reasons Gulci mentions above. Expo does offer early Alpha support for working with native code, which you can learn about here: https://docs.expo.io/versions/latest/guides/expokit.html
