### ISSUE TITLE
SSO Login Screen Ambiguous for Staff

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#320]
There are multiple login systems for staff. Indicate which should be used: AD or business?

**Comment by c3bryant** [comment]
Adding screenshots of the both login areas for reference

Onboarding Login:
![v6-login-onboarding](https://user-images.githubusercontent.com/15112294/42113968-25e74dca-7ba2-11e8-944b-ba6844d8c9c3.png)

User Settings Login:
![v6-login-settings](https://user-images.githubusercontent.com/15112294/42113966-25c43772-7ba2-11e8-8ead-50459c0f30a5.png)

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
