### ISSUE TITLE
News and Events images do not load on iOS if referenced URL is HTTP

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#321]
We've already created some exceptions for endpoints that are HTTPS but do not have perfect forward secrecy. However, it seems that News in particular are now using plain HTTP image links for their images. An additional exception has to be added to iOS to allow loading images over HTTP from ucsd news and events urls.

We can also bypass this by manually rewriting those URLs to use HTTPS. @c3bryant 

Commit 8290a2d in dev adds the exceptions.

**Comment by c3bryant** [comment]
Verified in dev and merged into v6.1-rc, closing.
