### ISSUE TITLE
Parking Status Automated Messaging Service

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#324]
This task is to setup an automated messaging service will send push notifications to specific users/topics who have subscribed to parking status notifications.

This push notifications will act as `fuzzy messages` with general information about the parking availability for the lot in question. There will be three varieties of message:
1. Athena Parking Full
2. Athena Parking Almost Full
3. Athena Parking Available

**Comment by a6wu** [comment]
Are there other options other than use of topics for the details defined, e.g. Athena_B_M-F_0830? What if the user wants to be notified at 8:45am? Or when we get to event based notification that are not based on a predetermined time?

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
