### ISSUE TITLE
User Story for Use Case #2

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#327]
- Subscription based, like Shuttle Card 

- User subscribes to lots, times, types.  

- Card/messaging is updated hourly. 

- Subscriber only gets push messages for times subscribed. 

- Messaging is “fuzzy”, full, almost full, lots of parking. 

- Card design needed.  

- Message copy needed.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
