### ISSUE TITLE
Tab bar icon display issues on some iPad devices

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#329]
This issue covers two problems identified on some iPad devices. 
1. The tab bar icons at the bottom of the screen are not centered vertically.
2. The User Settings icon on the right is askew.

Screenshot from an iPad Pro 12.9":
![screen shot 2018-07-17 at 8 14 49 am](https://user-images.githubusercontent.com/15112294/42826858-49cee8dc-899a-11e8-9011-0bd0ad8636d1.png)

Screenshot from an iPhone 6+ showing the desired layout:
![screen shot 2018-07-17 at 8 18 25 am](https://user-images.githubusercontent.com/15112294/42826869-4cf4980e-899a-11e8-8d65-6ba787aaeeeb.png)

**Comment by atmartorana** [comment]
PR #333 submitted to dev branch.

**Comment by c3bryant** [comment]
Verified and merged into v6.1-rc, closing.
