### ISSUE TITLE
Messaging: Integrate react-native-firebase

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#330]
The `react-native-fcm` module we use currently for Firebase messaging is no longer in development. The maintainer evollu is pointing users to the newer, more robust `react-native-firebase` module located [here](https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0).

This issue is to deprecate `react-native-fcm` and implement `react-native-firebase`.

A sample project which covers transitioning from `react-native-fcm` to `react-native-firebase` is located [here](https://github.com/evollu/react-native-fcm/tree/firebase/Examples/firebase-migration).

**Comment by Gulci** [comment]
As of commit 4f9e8e2, react-native-firebase has been integrated. Some initial work getting the token has been done as well. Notifications are currently not handled locally in the app. Push certificates for Apple have to be tested and notifications need to be verified.

**Comment by Gulci** [comment]
Here are the remaining tasks for this issue:

1) Verify that react-native-firebase has been integrated correctly by receiving a test notification on both iOS and Android platforms (test by sending a push notification directly to a test device's firebase push token)
2) Handle push messages that are received when the app is open (for now logging to the console is sufficient)

**Comment by Gulci** [comment]
@bethanybin has verified that both platforms receive notifications.

**Comment by Gulci** [comment]
Verified and closing.
