### ISSUE TITLE
Parking V1: Implement Parking Card

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#335]
Step 1 of this task is to implement a barebones parking card which should make use of the common `ScrollCard` component (see ShuttleCard.js)

Here are parameters to use when setting up the card:
id: `parking`
active: `true`
component: `ParkingCard`
name: `Parking Availability`
title: `Parking Availability`
order: `before Shuttle`

When completed, the app should automatically display the Parking card titled `Parking Availability` in a barebones fashion as shown here:
![parkingcard_barebones](https://user-images.githubusercontent.com/15112294/44289000-42075080-a227-11e8-8868-6c008f285751.png)

The card should be able to be activated and deactivated from the card menu, and from the User Settings tab.

**Comment by c3bryant** [comment]
Step 2 of this task is to build out the inner parking card content.

Parking Card final mockups
One parking type:

![parkingcard-1-spot-type](https://user-images.githubusercontent.com/15112294/45113000-0b25ab80-b0fe-11e8-9b97-25d591acbda0.png)

Two parking types:
![parkingcard-2-spot-types](https://user-images.githubusercontent.com/15112294/45113009-0eb93280-b0fe-11e8-80e4-3ca147a952dc.png)

Three parking types:
![parkingcard-3-spot-types](https://user-images.githubusercontent.com/15112294/45113021-1547aa00-b0fe-11e8-97d8-5f0b73aea3a9.png)

**Comment by atmartorana** [comment]
<img width="396" alt="screen shot 2018-09-19 at 3 38 44 pm" src="https://user-images.githubusercontent.com/22435621/45785726-42c64480-bc22-11e8-8b71-785ff2e45671.png">
<img width="400" alt="screen shot 2018-09-19 at 3 39 02 pm" src="https://user-images.githubusercontent.com/22435621/45785729-44900800-bc22-11e8-9785-dcd9c7de5452.png">
<img width="406" alt="screen shot 2018-09-19 at 3 39 17 pm" src="https://user-images.githubusercontent.com/22435621/45785730-4659cb80-bc22-11e8-9ed7-f899425c3253.png">
<img width="392" alt="screen shot 2018-09-19 at 3 39 32 pm" src="https://user-images.githubusercontent.com/22435621/45785732-48238f00-bc22-11e8-9e28-8884f6bbd9b4.png">

**Comment by c3bryant** [comment]
Nice job everyone, we can close this out now. Any issues found in beta will be handled case by case
