### ISSUE TITLE
Parking V1: Implement Parking Spot Type View

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#336]
This task is to implement the Parking Spot Type view. From the Parking card, when the user clicks on `Edit parking spot type` they will be taken to the `ParkingSpotType.js` view which should reside in `app/views/parking/`

Desired Functionality:
When the user clicks on any area of a row, that row should reflect its highlighted state by applying the styles shown in the mockup (grey background, darkened checkmark, and an elevated look). For now, use state to keep track of if the row is active or not. This will later be tied into the app's persistent data store.

To leave this view, the user will click the Back arrow or swipe from the left side of the screen. These interactions should be handled by the navigator.

The first step is to build out the UI as shown below:
![parkingspottype](https://user-images.githubusercontent.com/15112294/44289680-2baec400-a22a-11e8-8f3e-00ea1ccbb150.png)

**Comment by c3bryant** [comment]
Step 2:  Add a `Max Selections` area to the bottom of this view, similar to the following, which will always be displayed:
![image](https://user-images.githubusercontent.com/15112294/44603216-de38d680-a796-11e8-9651-bf58aa8b2d42.png)

Step 3: Keep track of the users parking type selections using react-redux. The user should be able to force-close the app and still have their parking type selections persist upon a subsequent app load

**Comment by g9singh** [comment]
This is done
commit 63fa9c8 adds the styles to the css for the UI

**Comment by c3bryant** [comment]
Verified, closing.
