### ISSUE TITLE
Messaging: Handle Topic Subscriptions

### ISSUE THREAD

**Issue by Gulci** [UCSD/campus-mobile#340]
Handle back-end calls to subscribe and unsubscribe from topics.

Profile endpoint documentation: https://mobileplatform-registration-ucsd.docs.stoplight.io/

**Comment by Gulci** [comment]
This includes implementing a notifications "categories" UI where users can select / deselect categories of notifications they would like to receive.

**Comment by c3bryant** [comment]
Notifications UI Mockup from @bbenner2876:

![notification-settings-p103-expanded](https://user-images.githubusercontent.com/15112294/44926502-7cccb680-ad06-11e8-9c04-20039bc8a7a8.png)

**Comment by c3bryant** [comment]
Verified, closing
