### ISSUE TITLE
Dismiss Push Notification Icon

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#344]
### Issue Description

Push notification icon in the notification bar remains after the app has opened.

### Steps to Reproduce / Code Snippets

Receive push notification. 
Icon displays in the notification bar. 
Open the app. 
Icon remains.

#### Expected Results

Icon in the notification bar should dismiss once the app opens.

### Additional Information

* React Native version: Unknown
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): N/A

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
