### ISSUE TITLE
PID Messaging Support

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#345]
Support sending in-app messages to users by PIDs.

**Comment by a6wu** [comment]
API for use by SAH https://next.stoplight.io/ucsd/mobile-platform/version%2F1.0/SAH%20Messaging.oas2.yml?view=/

**Comment by a6wu** [comment]
Bring PID attribute to root level in user profile.

**Comment by c3bryant** [comment]
Completed with @vishant101

Repo: `mobileplatform-notificationmessages`
Branch: `feature/user-pid`

**Comment by c3bryant** [comment]
Deployed and verified on AWS Prod - thanks @a6wu, @g9singh
