### ISSUE TITLE
Add ability to star events on the Events card

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#354]
This user feedback driven enhancement is to allow `starring` of events on the Events card, much like how starring works for Special Events

Requirements:
1. The Events card and Event Detail view will have a star icon, which will highlight when checked.
2. Starred events should display at the top of the list of events, whether on the Events card or View All events view.

**Comment by vishant101** [comment]
@woznaut what do you think of the UI looking like this for V1?

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/f4f4224e-fc7a-4c6b-9304-c2e61ebaac2d)

**Comment by woznaut** [comment]
generally this is fine. 2 small points:

1) are these the same style stars we're using on the Special Event card? could just been the screenshots but the colors/star styles don't look quite the same to me.
2) on the detail view the star should be right aligned I think rather than at the end of the title. That way the placement will always be the same.

**Comment by vishant101** [comment]
1) The stars used in the special events page are from the same icon package but different star shapes. The ones used in the special events card are actually the iOS variants of the star, whereas here I used the default star shape. You're also correct about the color being slightly different. The special events card uses yellow, whereas here I've used  gold. Let me know if you would like me to change it too match the styling of the special events card. 

2) Good point. I've made the change. 

 ![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/7d74e5dd-6b6d-463f-a26e-9e2e92643d45)

**Comment by vishant101** [comment]
Here is how the reordering of the events works. @c3bryant @woznaut 

![6c6bb611b24fe6fb880c26e00a3b297c.gif](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/045ccbc1-d704-4481-97c7-e3d72dbce332)

**Comment by woznaut** [comment]
I think we should use the same yellow as on Special Events. The gold is a nice idea but the yellow is consistent the UCSD branding.

**Comment by vishant101** [comment]
Changed the color to match special events. Would you like the color for the outline for unselected events to be greyed just like special events as well? 

Only Yellow:
![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/8f2ab5d6-4f0f-4662-8eb4-bd4440b013bf)

Consistent with Special Events:
![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/8b4c11ba-6ca0-40f0-ad2d-8aad25e268bf)

**Comment by woznaut** [comment]
yes

**Comment by vishant101** [comment]
Implemented UI changes. Ready for testing on 8ecb0d1bcbb5090ec68591b7c0fb2dd700548ce8

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
