### ISSUE TITLE
Directions to classes from the Classes card

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#355]
This user feedback driven enhancement is to provide directions to classes from the Classes card.

Requirements:
1. Determine if directions are available for the selected course on the Classes card
2. If directions are available, under `Class Room Location` make the room/building/lecture a blue link, with a directions icon to the right, which will link out to Apple or Google maps for accurate walking/biking/driving directions.

![class-directions](https://user-images.githubusercontent.com/15112294/46761079-8263d780-cc88-11e8-8971-b5b7c2cd23ef.png)

**Comment by vishant101** [comment]
Navigating users in iOS and Android is simple. This can be done by opening a uri with either `maps:` or `geo:`  for iOS and Android respectively. The uri has to also include longitude and latitude parameters along with an option label (this would be the class name). This raises a problem as the data from the academic history API doesn't contain any geolocations. It only contains a building code and room number, as shown below:

`{
    "section": "938599",
    "section_code": "A00",
    "meeting_type": "Lecture",
    "date": null,
    "time": "13:00 - 13:50",
    "days": "WE",
    "building": "CENTR",
    "room": "119",
    "instructor_name": "Polikarpova, Nadezhda",
    "special_mtg_code": "",
    "enrollStatus": "EN"
},

{
    "section": "938627",
    "section_code": "A00",
    "meeting_type": "Lecture",
    "date": "2018-05-02",
    "time": "11:00 - 11:50",
    "days": "WE",
    "building": "WLH",
    "room": "2115",
    "instructor_name": "Saul, Lawrence",
    "special_mtg_code": "PB",
    "enrollStatus": ""
},`

We should seek to update the API to include geolocations before progressing any further with this task.

**Comment by a6wu** [comment]
Let's revisit use of Campus Bird API, https://collab.ucsd.edu/display/WTS/Visitor+Map+API.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
