### ISSUE TITLE
Push Notification Deep Link to Notifications Tab

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#365]
### Issue Description

Tapping on the push notification icon opens the app, but does not take the user to the notifications tab.

### Steps to Reproduce / Code Snippets

Receive push notification.
Tap on push notification icon.
App opens (to the last active tab or home view)

#### Expected Results

App should load and take the user to the notifications tab .

### Additional Information

* React Native version: 
* Platform(s) (iOS, Android, or both?): Android and iOS
* Operating System (macOS, Linux, or Windows?):

**Comment by g9singh** [comment]
ecf68af8667e7841d824242a9e38d04795235c0b

**Comment by c3bryant** [comment]
Verified on branch `deep-linking`

Routes available:
`Messaging` (default)
`Home`
`Map`
`Preferences` (User Profile)
`Notifications` (Topic Subscriptions)
`Feedback`
`ParkingSpotType`
`ManageParkingLots`
`SurfReport`
`CardPreferences`

Usage:
```
// Take user to the Home view
"data": {
	"routeName": "Home"
}```
