### ISSUE TITLE
Parking Lot Card Count Not in Sync with Managed Lots

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#366]
### Issue Description

The parking lot card on the home screens shows the number of lots selected by the circles at the bottom of the card. When four lots are selected, only three circles are shown on the home screen under the parking card. When five lots are selected, only four circles are shown. When six lots are selected, six circles are show. Deselecting a lot and going back to five lots, four circles are shown. Closing and re-opening the app does not fix the problem.

### Steps to Reproduce / Code Snippets

Add another parking lot in the Manage Parking Lots view, so two lots are selected. The Home view shows no circles under the parking card. Adding another lot in the Manage Parking Lots view, so three lots are selected. The Home view shows two circles under the parking card. This continues for four and five parking lots selected. Only when all six lots are selected does the Home view show six circles under the parking card.

From six lots, deselecting one lot, so that five lots are selected - the Home view shows four circles under the parking card.

#### Expected Results

The number of circles under the parking card in the Home view should match the number of parking lots selected in the Manage Parking Lots view.

### Additional Information

* React Native version: 
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?):

**Comment by c3bryant** [comment]
Verified in `rmp-v2` (fb71c59). Closing

**Comment by c3bryant** [comment]
Merged into `dev`
