### ISSUE TITLE
User Student Profile Logic

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#369]
### Issue Description

A user that has a PID is profiled as a student. An employee that was a student, and no longer a student, has a PID and is profiled as a student.

### Steps to Reproduce / Code Snippets

User this a former student, and a current employee, logs into the app. The user will be profiled as a student.

#### Expected Results

An employee, that was a former student, and no longer a student, should not be profiled as a student.

### Additional Information

* React Native version: all
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): NA

**Comment by c3bryant** [comment]
Adding these notes to the User Profile Transition milestone, closing
