### ISSUE TITLE
Smart Message Hub

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#371]
Allow more feature rich messaging hub:

- scheduling of messages to be sent
- read receipt
- cancel messages not yet sent
- rate limiting of number of messages sent
- others

Reference for review: https://www.nngroup.com/articles/push-notification/?utm_source=Alertbox&utm_campaign=b276aeacb3-push_notifications_digital_noise_2018_11_19&utm_medium=email&utm_term=0_7f29a2b335-b276aeacb3-24386589

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
