### ISSUE TITLE
Parking Card: Implement "Powered by <Service>" Detail

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#379]
For the parking card, show that the data is powered by a particular service. E.g. For parking lot 406, show that the data is powered by Visionful.

**Comment by woznaut** [comment]
suggest we're more specific regarding that it's the data that the vendor is supplying, not the parking card technology. Suggested options:

"Data provided by <Service>"
"Data supplied by <Service>"
"Data courtesy of <Service>"

**Comment by a6wu** [comment]
Discussed putting in an "about" reference in the mobile app and the content resides in the CMS.

**Comment by c3bryant** [comment]
Closing in favor of #481
