### ISSUE TITLE
Update Login Promotion Screen

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#380]
Review the login prompt to showcase benefits.

**Comment by c3bryant** [comment]
Here are screens of what we have now:

Onboarding - Welcome
![mobile_onboarding_5s_1](https://user-images.githubusercontent.com/15112294/48730646-dd75dc00-ebef-11e8-8cdf-6add60a48a98.png)

Onboarding - Login
![mobile_onboarding_5s_2](https://user-images.githubusercontent.com/15112294/48730653-e1096300-ebef-11e8-8baf-74cbe34f0a55.png)

**Comment by c3bryant** [comment]
@woznaut sending this your way for review

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
