### ISSUE TITLE
Mobile Client: Update Affiliation Attribute on Re-auth

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#381]
If a current undergrad student (affiliation `U`) graduates, they will currently retain their `U` affiliation unless they were to log out and log in to the mobile app again.

This task is to handle the client-side updating of the user profile on a recurring basis.

#### Success Criteria

On API token re-authentication, user affiliation should reflect the current affiliation from the SSO.

**Comment by g9singh** [comment]
commit 217d73d594c0af22c665ae8cadd6d3c1fdc3f362

**Comment by c3bryant** [comment]
Verified, closing
