### ISSUE TITLE
Shuttle stops not resetting after changing routes

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#394]
### Issue Description

On the Maps tab, when a user is toggling between shuttle routes, some stops are not fully resetting. This is causing shuttle stops to show up when they should not.

### Steps to Reproduce / Code Snippets

1) Load the campus mobile app, and navigate to the Maps tab
2) Click the Shuttle icon and select a route
3) Once the first route is populated with Stops and shuttle busses, select a different shuttle route
4) Stops from the first activated route may show up when they should not

![polyline-reset](https://user-images.githubusercontent.com/15112294/51415679-82972d00-1b2b-11e9-9ec7-5ac20c808ccb.png)

### Additional Information

* App Build: 6.0-6.2
* Platform(s) (iOS, Android, or both?): Both

**Comment by vvp002** [comment]
Shuttles stops were not removing stops from the toggled route correctly. Changed it so it was checking the correct route to remove the stops from that corresponding route. Fix should be in bugs/shuttle-service.

Tested it and app was able to update stops correctly when toggling between shuttle routes. But found a new bug where map stops working when you try to toggle on and off the same shuttle route.

**Comment by vishant101** [comment]
Some of the issue appears to be arising from the toggle list. The view shown to the end user is not perfectly indicative of the underlying states.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
