### ISSUE TITLE
Faulty rendering after removing parking lot

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#395]
### Issue Description
When two parking lots are added and the second lot is removed the parking lot card becomes blank.

### Steps to Reproduce / Code Snippets

1) Add both Lot406 and Osler to the parking card
2) Make sure parking card is currently viewing the Osler parking lot
3) Then deselect Osler from Manage lots view
4) Go back to home view

#### Expected Results

We expect the Parking Card to show Lot406 instead of a blank card

![screenshot_20190116-162832](https://user-images.githubusercontent.com/13146131/51417501-2e904680-1b33-11e9-90aa-ffd8e383ac7b.png)

* Build version: 6.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by g9singh** [comment]
This is a known issue with ReactNative Flatlists. 

https://github.com/facebook/react-native/issues/13316

From the comments on the post it seems as if the issue was resolved in an older update of ReactNative but then later reappeared and started to only affect android devices. 

removeClippedSubviews={false} does not solve the issue as it did for many other people in the post above

**Comment by c3bryant** [comment]
Let's revisit this after the next React Native upgrade

**Comment by a6wu** [comment]
Reproduced behavior on Android for v6.6 updated on May 10, 2019.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
