### ISSUE TITLE
Migrate RN Dev Dependencies

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#397]
To support RN v0.57, migrate node modules to the latest stable and compatible version for development environment.

**Comment by c3bryant** [comment]
Done on branch `react-native-57-upgrade-v1` in 2420bca

**Comment by c3bryant** [comment]
#### Dev Dependency Updates:
| **Dependency**  | **Old Version**  | **New Version** |
|---|---|---|
| @babel/core | n/a | ^7.0.0-0 |
| babel-eslint | 8.2.2 | 9.0.0 |
| babel-jest | 22.4.3 | 24.1.0 |
| metro-react-native-babel-preset | n/a | 0.51.1 |
| flow-bin | 0.65.0 | 0.92.1 |
| husky | 1.1.4 | 1.3.1 |
| jest | 22.4.3 | 24.1.0 |
| react-test-renderer | 16.2. | 16.6.3 |

**Comment by c3bryant** [comment]
Ready for testing on branch `react-native-57-upgrade`

**Comment by c3bryant** [comment]
Initial testing has passed. Future problems encountered will be logged as separate issues.
