### ISSUE TITLE
Migrate RN Prod Dependencies

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#398]
To support RN v0.57, update node modules to the latest and stable version for production environment.

**Comment by c3bryant** [comment]
#### Dependency Updates:
| **Dependency**  | **Old Version**  | **New Version** |
|---|---|---|
| @babel/runtime | n/a | 7.3.1 |
| moment | 2.21.0 | 2.24.0 |
| react | 16.3.0-alpha.1 | 16.6.3 |
| react-native | 0.54.4 | 0.57.8 |
| react-native-animatable | 1.2.4 | 1.3.1 |
| react-native-gesture-handler | n/a | 1.0.15 |
| react-native-maps | <0.21.0 | 0.23.0 |
| react-native-popup-menu | 0.12.3 | 0.15.0 |
| react-native-sortable-list | 0.0.21 | 0.0.22 |
| react-navigation | 1.5.8 | 3.0.9 |

**Comment by c3bryant** [comment]
Ready for testing on branch `react-native-57-upgrade`

**Comment by c3bryant** [comment]
Initial testing has passed. Issues encountered in beta will be logged separately.
