### ISSUE TITLE
Move parking notification settings

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#405]
### Issue Description

Move the parking notification screen from the user profile screen and place it in the notification settings under the title: "Parking"
![Simulator Screen Shot - iPhone XS Max - 2019-01-25 at 14.36.03.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/0fd7b18c-a1fa-4b79-9352-aec1f6c10b3c)

#### Expected Results
refer to issue #293

* Platform(s) (iOS, Android, or both?): both

**Comment by c3bryant** [comment]
RMP V2 requirements have changed, closing
