### ISSUE TITLE
Web Link from Notifications Feed

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#406]
Allow for web links to be used in notifications feed that opens up the installed web browser on the device.

**Comment by vishant101** [comment]
@c3bryant  A few questions

1) Can a notification contain more then one hyperlink? If a notification can only contain one url, do we want the onClick event to be on the message container or localized to the url.

2) do we want to change the formatting of the url to be changed, i.e. underlined and blue, to show that it is clickable?

**Comment by c3bryant** [comment]
Thanks Vishant, great questions:
1. No
2. Yes
3. Yes

**Comment by c3bryant** [comment]
Android passes initial testing.

iOS failed with one issue:

1) The clickable link area appears to be above the link, making it difficult to click on. The area outlined in red is where the actual clickable area seems to be:

![Screen Shot 2019-02-13 at 11.31.21 AM.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/f815841f-878c-42cf-afe5-f193f0d704c3)

**Comment by vishant101** [comment]
@c3bryant  I've identified the issue and implemented a fix and documented the problem and solution, see #428. I've not been able to test the messages however due to lack of an iOS simulator. 

Please test and let me know if the issue has been resolved.

**Comment by c3bryant** [comment]
Fix verified and testing has passed. Merged into `refresh-2`.
