### ISSUE TITLE
Profile Sync

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#408]
### Issue Description
In userSaga.js the method which syncs the user profile only runs once every hour. 
This is an issue in some cases where the user changes a profile attribute and then decides to logout. Depending on the last sync time the user's changes might not be saved in the remote server.

#### Expected Results

When the user changes any profile attribute the changes should reflect immediately in the remote server.
The sync method should use a column called "lastSynced" in the remote server to decide whether the profile on the local state should be pushed or if the remote server profile should be pulled to overwrite the local state. 
* App version: 6.2
* Platform(s) (iOS, Android, or both?): Both

#### Success Criteria

Remove one hour interval for syncing
Sync for any attribute changes in the profile object
Sync on app startup
Sync on app login

**Comment by g9singh** [comment]
Removal of the one hour constraint has been completed in: 4eed98d8b526fb4137db19cbf241f60d716f22c8

**Comment by c3bryant** [comment]
Verified & deployed in 6.4
