### ISSUE TITLE
Flatten Remote Profile Data

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#409]
### Issue Description
The profile column in dynamoDB saves all the attributes connected to each user. 

#### Expected Results
DynamoDB should store each (group of) attribute(s) in a separate column of its own. 
Still want to keep the JSON which is stored in profile column to allow for a seamless transition from previous data structure

* React Native version: 6.2
* Platform(s) (iOS, Android, or both?): both

#### Success Criteria
Data in the current user profile json structure to be pulled up one level. Each data attribute will be on the root level.

**Comment by c3bryant** [comment]
Done on branch `feature/flatten-profile`
