### ISSUE TITLE
Allow parking lots to be reordered in the manage parking lots view

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#410]
### Issue Description
As of now the manage parking lots view is static (there is no way of allowing the user to reorder the lots).
![IMG_3147.jpg](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/7f96de10-f09a-4f10-8cd7-ce84370c2950)
#### Expected Results
We want to allow the parking lots in the manage parking lots view to be reordered by the user.
A good example of this is in the manage shuttle stops view or the Cards view in the profile tab. 
![IMG_3145.PNG](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/2b1a87ef-7512-421c-8ed1-84b2530e5c4a)

![IMG_3146.jpg](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/7260edff-06e3-46df-810a-2be36fa2f3ca)

* App version: 6.2
* Platform(s) (iOS, Android, or both?): both

**Comment by c3bryant** [comment]
Verified on `feature/reorder-parking-lots` and merged into `refresh-2`
