### ISSUE TITLE
Free Food and Shuttle Notification Preferences Turning Off

### ISSUE THREAD

**Issue by vvp002** [UCSD/campus-mobile#411]
### Issue Description

When logging out and logging back into the app, notifications for Shuttles and Free Food are turned off in the User Profile.

![img_5200](https://user-images.githubusercontent.com/13816146/52006695-9de62e80-2481-11e9-93f3-09c6d7c0088e.PNG)

### Steps to Reproduce / Code Snippets

Check Notification Preferences in User Profile and log out. Log into the app and check Notification Preferences again.

#### Expected Results

Expected results would be for the app to save Notifications Preferences for each user. In my case, all of the notifications should've been kept on.

![img_5201](https://user-images.githubusercontent.com/13816146/52006864-00d7c580-2482-11e9-976d-2a3575c824ec.PNG)

### Additional Information

* Platform(s) (iOS, Android, or both?): iOS

**Comment by g9singh** [comment]
@sssaiya narrowed down the issue to the login portion of the code. The preferences are being reset upon login and seem to be consistent with dynamoDB when logging out.

**Comment by sssaiya** [comment]
Completed in:
bea184fcbeeaa28f56a776ed59854c8c4e7ec4ae
Sending to @g9singh and @c3bryant for review.

**Comment by c3bryant** [comment]
Verified & merged into branch `6.5`

**Comment by c3bryant** [comment]
Verified on branch `6.5` - thanks @sssaiya & @g9singh, closing
