### ISSUE TITLE
Support Shuttle Alerts

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#412]
Integrate notifications with https://www.ucsdbus.com/alerts#login.

**Comment by a6wu** [comment]
Twilio does not support receiving text from a short code, which the ucsdbus service uses.

https://support.twilio.com/hc/en-us/articles/223181668-Can-Twilio-numbers-receive-SMS-from-a-short-code-

**Comment by a6wu** [comment]
Was able to link a Google voice phone number to Twilio. Need to review filtering of ucsdbus sms to forward to the campus mobile app.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
