### ISSUE TITLE
Empty Notification Tab Message

### ISSUE THREAD

**Issue by sssaiya** [UCSD/campus-mobile#413]
### Issue Description

After disabling all the notifications from settings, when the user navigates to the notifications tab,
there is a message saying, 
"There was a problem fetching your messages.
   Please try again soon."
![Screenshot_20190131-111157.jpg](https://images.zenhubusercontent.com/5c479bf58d88074ab2c6a60f/51cb00be-b6b9-4db7-a73f-34c859d8fc37)
### Steps to Reproduce / Code Snippets

1) Go to user settings, 
2) Disable all notifications,
3) Go back to the notifications tab.

### Expected Behavior
We want the text to display the following if there are no messages:

"You aren't subscribed to any notification topics.

You can add topics in the User Profile."

The error message should still appear if something went wrong while the messages were being fetched.

### Additional Information
* Platform(s) (iOS, Android, or both?): both

**Comment by sssaiya** [comment]
After fixing the Error message to display
"You aren't subscribed to any notification topics.
You can add topics in the User Profile."
Now when the user unsubscribes to topics, that message is displayed

However, even when there is no network connection, the same error message is displayed
The issue is that this.props.myMessageStatus is initially null and is changed by the messaging saga

**Comment by sssaiya** [comment]
Added an additional checker for this.props.myMessageError and now can successfully display 
You aren't subscribed to any notification topics.
You can add topics in the User Profile."
when there are no topics subscribed to and there is no network connection

and will also display 
There was a problem fetching your messages.
Please try again soon.
When there is a network connection problem.

**Comment by sssaiya** [comment]
Github Commit hash:
0dff9ffbaad00e61fb34c078cdb040bf4f8d3dc1

**Comment by c3bryant** [comment]
Hi @sssaiya, nice job on this so far.

I made a few updates in commit c1ed178, please review when you have a chance.

**Comment by g9singh** [comment]
tested and verified: 64f18d53107d0ebf9a668ffac40c3a31e427f715

**Comment by c3bryant** [comment]
Merged into `refresh-2`
