### ISSUE TITLE
Direct Message Restriction

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#414]
Internal issue at https://its-pro.ucsd.edu/projects/MA/issues/MA-39?filter=allopenissues

**Comment by vishant101** [comment]
Implemented changes see ```feature/direct-messages```  on ```mobileplatform-notifications``` 

Hash: ```f196094fe09db706418854ebcba230427f7f2b16```

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
