### ISSUE TITLE
Integrate MTS Bus Tracking

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#422]
Allow users to track MTS buses.

https://www.sdmts.com/business-center-developers/real-time-data

**Comment by a6wu** [comment]
QA API, https://api-qa.ucsd.edu/store/apis/info?name=CampusShuttles&version=v1.0.0&provider=a6wu&tenant=carbon.super#!/default/get_mts_positions

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
