### ISSUE TITLE
ListView is going to be removed 

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#429]
### Issue Description

react-native-implementation.js:65 ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information

### Additional Information
We need to change the components which use ListView because it will removed soon and may also be causing slow rendering of various components.

It has already been deprecated however it will soon be removed completely 
https://facebook.github.io/react-native/docs/listview

the following files are affected by this issue:
specialEvents/MultiSelect.js
specialEvents/SpecialEventsListView.js

* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both

**Comment by g9singh** [comment]
Data was processed and passed into ListView using a certain format. The format had to be restructured to fit into an array because FlatList requires that as an input. The MultiSelect component was affected by this change.

Completed in 1a1f42d2a61dd0e3d83a54dc4cd15e4b06cd6ff2

**Comment by c3bryant** [comment]
Fixes made in 78986bd
Verified on branch `feature/depreciate-listview`

**Comment by c3bryant** [comment]
Merged into `refresh-2`
