### ISSUE TITLE
Crash: Android KitKat 4.4

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#438]
### Issue Description
Users have reported crashing on Android KitKat 4.4
Reproduced by @a6wu on campus mobile 6.2.1 and 6.3

```Name: Nexus_4_Kitkat
CPU/ABI: Google APIs Intel Atom (x86)
Path: /Users/a6wu/.android/avd/Nexus_4_Kitkat.avd
Target: google_apis [Google APIs] (API level 19)
hw.device.name: Nexus 4
hw.initialOrientation: Portrait
image.androidVersion.api: 19
avd.ini.displayname: Nexus 4 Kitkat
```

### Steps to Reproduce / Code Snippets
1) Install campus mobile 6.2.1 or 6.3 on an Android device running KitKat 4.4
2) Crash with the message "Unfortunately, UC San Diego has stopped".

### Additional Information
* React Native version: 54.4 & 57.8
* Platform(s) (iOS, Android, or both?): Android KitKat 4.4, others?

**Comment by a6wu** [comment]
Release 6.0, version code 453 Jun 21, 2018, 2:53 PM runs ok on KitKat. 

App versions from 6.1 (version code 290) to the 6.3 does not run on KitKat. App crashes on startup as reported.

**Comment by c3bryant** [comment]
AWS Device Farm testing confirms the startup crash on Android 4.4.2 and 4.4.4

Err: `android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0001`

![Screen Shot 2019-03-13 at 10 32 46 AM](https://user-images.githubusercontent.com/15112294/54301197-b6b32b00-457b-11e9-9565-0ea78d7996b2.png)

**Comment by c3bryant** [comment]
We will be upping the Android API requirement to 21. In turn, this crash experienced on API 17 and 19 will not be addressed at this time.
