### ISSUE TITLE
Schedule card showing all discussion sections

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#439]
### Issue Description
The schedule card is currently showing all discussions available for a certain class. 

### Steps to Reproduce / Code Snippets
 Log in and view schedule card. You can also see this problem persist on the View All classes screen.
![Screenshot_1551984269.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/1131cd14-ed96-44ce-9f42-d5e914ebee84)
![Screenshot_1551984436.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/9b96df90-3085-4e5c-8378-c3cc880123cc)
#### Expected Results
We want to only display the discussion section the student is currently signed up for.
(This is up for debate because many professors have open discussion sections, meaning students are free to attend any discussion section regardless of which section they are actually enrolled in)

### Additional Information

* App version: 6.3
* Platform(s) (iOS, Android, or both?): both

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
