### ISSUE TITLE
Invalid ScrollCard list item

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#440]
### Issue Description

The most reported event in Bugsnag is `Invalid ScrollCard list item`. This task is to Investigate and find a solution

### Steps to Reproduce / Code Snippets

The steps to reproduce this error being thrown is unknown

From a users perspective, we are not aware of any in-app bugs caused by this thrown error

### Additional Information
* React Native version: All
* Platform(s) (iOS, Android, or both?): both

**Comment by c3bryant** [comment]
Done on branch `refresh-2`. @g9singh sending your way for review.

**Comment by g9singh** [comment]
@c3bryant I could not recreate the issue. I believe the issue has been resolved by the changes you made.
