### ISSUE TITLE
Integrate Occuspace UI

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#442]
Build out UI from issue #465

**Comment by g9singh** [comment]
A working prototype is on the feature/occuspace branch 
commit hash: 198cdfa451649cb7d83a6b6b47e68294788ad610

**Comment by g9singh** [comment]
Updates:
- fixed scrolling issue on android 
- updated height on progress bar
- automatically store users added locations to DB (if signed in)
- updated error reporting for more information on Bugsnag

branch: feature/occuspace
commit: 248cae0d01608a12001faab79bb510dc01c3f845
