### ISSUE TITLE
Student ID Card: UI mockup

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#447]
UI mockup for Student ID Card

**Comment by woznaut** [comment]
![UserID_Home.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/787fc1cf-8ea8-4a77-b18d-b71dbe26c704)

**Comment by woznaut** [comment]
![UserID_Home_notLoggedIn.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/1f512eca-15b4-41f1-99f8-f8384f57fab5)

**Comment by c3bryant** [comment]
Ready for implementation, closing

**Comment by c3bryant** [comment]
Completed on branch `student-id-card`, closing

**Comment by c3bryant** [comment]
This work has been completed, closing.
