### ISSUE TITLE
Integrate P782 Parking Lot

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#452]
https://collab.ucsd.edu/display/WTS/Internal+Team+Documents

**Comment by c3bryant** [comment]
* Added Parking Logix integration to Parking Availability API
* Lot P782 activated in QA

Repo: https://sourcecode.ucsd.edu/projects/WTS/repos/parking-availability/branches
Branch: v1.2-qa

Ready for Beta testing in QA env on branch `refresh-2`

**Comment by c3bryant** [comment]
Parking API 1.1 update with Parking Logix integration and Lot 782 deployed to prod independently of refresh-2 on 3/27/19
