### ISSUE TITLE
Refactor FlatList Component

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#453]
### Issue Description

We have components in the code base that use FlatList. Many of these components depend on external data. 

Right now we conditionally render a message that tells the user there is no data available or if the app ran into an error while trying to fetch data. (An example of this is the Notifications tab). In some cases we do not even render a message, Yikes!

We can reduce the number of conditionals checks by using FlatList's argument named ListEmptyComponent.

ListEmptyComponent: Rendered when the list is empty. Can be a React Component Class, a render function, or a rendered element.

Here is a list of files that may need to be updated:

campus-mobile/app/views/common/ScrollCard.js
campus-mobile/app/views/dining/DiningListView.js (not in prod yet)
campus-mobile/app/views/dining/DiningListViewAll.js (not in prod yet)
campus-mobile/app/views/messaging/Messaging.js
campus-mobile/app/views/schedule/FinalsCard.js
campus-mobile/app/views/shuttle/ShuttleOverviewList.js
campus-mobile/app/views/shuttle/ShuttleSmallList.js
campus-mobile/app/views/weather/SurfReport.js

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
