### ISSUE TITLE
Student ID Card: Increase brightness to 75% or greater

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#455]
Increase screen brightness when barcode screening is needed.

**Comment by a6wu** [comment]
Or is it instructions for users to take?

**Comment by c3bryant** [comment]
Done on branch `feature/barcode-brightness`

**Comment by c3bryant** [comment]
Initial testing passes on iOS and Android. Merged into `student-id-card`

**Comment by c3bryant** [comment]
This work has been completed, closing.
