### ISSUE TITLE
Student ID Card: UX for Barcode Use

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#456]
Mockups for user interaction when needing to scan the barcode. Screen brightness increase temporarily and then back to user's original brightness level.

**Comment by a6wu** [comment]
Do we need a full-size barcode?

**Comment by woznaut** [comment]
![HomeStudentID_scan1.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/d44b9201-5c41-425a-b814-a17215f85af5)![HomeStudentID_scan2.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/0315e60c-25bc-46e8-ac7f-a4911902a9ba)

**Comment by woznaut** [comment]
![HomeStudentID_scan1.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/529e9a7d-8f10-46c4-84f9-0aed6f113d22)

user taps on homescreen student ID, barcode overlay displays and device brightness goes to 100%. To dismiss, user clicks away from overlay or clicks "Close" and brightness goes back to user's preferred setting.

**Comment by woznaut** [comment]
![HomeStudentID_scan2.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/9ecc0bbd-c177-44da-a380-17af58ce5aeb)

Cllicking "Expand" produces even larger, vertically displayed barcode. Programmatically hide/show "Expand" based on device screensize?

**Comment by c3bryant** [comment]
All set here, closing

**Comment by c3bryant** [comment]
This work has been completed, closing.
