### ISSUE TITLE
New messages are not reflected in the app without refresh 

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#457]
### Issue Description
When a user receives a push notification and does NOT click on it, but rather opens the app via the icon on the home screen, the user does not receive any indication that a new message is available. The user will have to manually go to the notifications tab and pull to refresh in order to load the new message. (The user will only need to pull to refresh if the app was minimized rather than completely closed or "force closed")

### Steps to Reproduce / Code Snippets
Close app
Get notification
Open app via the home page

#### Expected Results
We want the app to reflect any new messages regardless of how the app was opened.
The badge icon should update correctly as well as the messages in the notification tab.

* app version: 6.3
* Platform(s) (iOS, Android, or both?): Both

**Comment by c3bryant** [comment]
Ready for beta on branch `bugs/messages-loading`

**Comment by c3bryant** [comment]
Added to branch `6.5`
