### ISSUE TITLE
Handle Unavailable API for Parking Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#458]
When an API is unavailable for a particular parking lot, display a message to indicate status.

**Comment by c3bryant** [comment]
When a parking lot API is down, the lot in question should remain displayed in the app on the Parking Card and also in Manage Lots.

This will Parking Availability API will need to be updated to always return a response for unresponsive lots. `parking-lots-master.js` can help facilitate this.

Adding @woznaut to assist with UI for what to display when a lot is down.

We should be able to display the following information regardless of lot API state:
- Lot Name
- Lot Context (location/intersection)
- Spot Type Selection

The following information will be unavailable when a lot is down:
- ~X Spots Available
- Availability percentage

![Screen Shot 2019-04-03 at 2.42.30 PM.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/29c24a6b-e8cd-41ba-b156-d38b88c83f96)

**Comment by vishant101** [comment]
![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/0265604e-da33-435f-8568-64d83989e4d4)

When a parking lot is unavailable the message "Data unavailable. Please try again later" is displayed. 

If a parking data returned does not contain a lot, the lot is removed from the list of available lots on the app.

**Comment by g9singh** [comment]
completed in: 1dcd96ab9ea9f5043b128ea136ea8760e1f8cdf8
Tested and verified on feature/unavailible-parking-lots branch

**Comment by c3bryant** [comment]
The parking-availability Lambda is ready for deployment on branch `v1.1`

**Comment by c3bryant** [comment]
Branch `feature/unavailible-parking-lots branch` merged into 6.6 and ready to deploy.

The `parking-availability` Lambda update to v1.1 can deploy at any time.
