### ISSUE TITLE
Waitz UI/UX Flow

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#465]
This task is to flesh out the UI/UX flow for mobile integration with [Waitz](https://www.ucsdwaitz.com/)

**Comment by woznaut** [comment]
![BusyCard.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/de18d566-869b-4409-85d0-3149c8def3a3)

interface and management follow Shuttle card paradigms

**Comment by c3bryant** [comment]
The two remaining questions will be handled in separate issues:
- Locations enabled by default
- Final card name

The UI has been reviewed and is ready for implementation, closing.
