### ISSUE TITLE
Student Radio Card

### ISSUE THREAD

**Issue by atmartorana** [UCSD/campus-mobile#466]
Integrate KSDT's live feed into the mobile app

**Comment by a6wu** [comment]
https://ksdt.ucsd.edu/stream.mp3

**Comment by woznaut** [comment]
![RadioPlay.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/89745a44-79d8-4bf3-9ad0-a538f5e58e42)
basically replicates the player on the https://ksdt.ucsd.edu site. The animated "live" dot and the "Coming up next" both important for fit and finish imo. I presume the animated dot is easy, "Coming up next" is a nice to have assuming we can grab it from their schedule.

![RadioPause.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/d7c5d7d6-783f-473b-8108-706102fa7c25)

**Comment by c3bryant** [comment]
Mocks available in #471

**Comment by atmartorana** [comment]
I switched between several other libraries such as react-native-video but this failed after getting an RTC{something}.prepare error, but decided on react-native-audio-toolkit:

https://github.com/react-native-community/react-native-audio-toolkit

**Comment by atmartorana** [comment]
<img width="907" alt="Screen Shot 2019-05-21 at 10 38 44 AM" src="https://user-images.githubusercontent.com/22435621/58117981-ba36e400-7bb4-11e9-8b8e-41af86a8e236.png">

**Comment by atmartorana** [comment]
That might be the source of the error?

**Comment by c3bryant** [comment]
Next Steps:

1. Setup the `react-native-audio-toolkit` example app for iOS and test start, stopping, and resuming of the KSDT stream (https://github.com/react-native-community/react-native-audio-toolkit/tree/master/ExampleApp/ios)

2. Setup the `react-native-audio-toolkit` example app for Android and test start, stopping, and resuming of the KSDT stream (https://github.com/react-native-community/react-native-audio-toolkit/tree/master/ExampleApp/android)

3. Determine if the following is available and/or feasible from KSDT:
a) A programatic way to determine when the KSDT stream is active (on air) and inactive (off air)
b) A programatic way to determine the name of the current song or show playing and related information
c) A programatic way to determine the next upcoming song or show and related information

4. When 1, 2, and 3a are complete, proceed with the Student Radio card integration to campus mobile.
Final UI available here: https://app.zenhub.com/workspaces/campus-mobile-app-59791ae0251e9315c45be418/issues/ucsd/campus-mobile/471

**Comment by a6wu** [comment]
Need support from KSDT to continue on with this feature. @a6wu to reach out to KSDT.

**Comment by a6wu** [comment]
Version 1 of the radio card will have play/pause feature only. We'll continue to contact the radio station for future support.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
