### ISSUE TITLE
extra empty sections in student class schedules 

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#467]
### Steps to Reproduce / Code Snippets
![Screen Shot 2019-04-11 at 10.30.23 AM.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/9e881f7b-1fbc-407f-a264-48964d36d8dc)

If we navigate to the "View All" screen for the classes card some weekdays appear even though they have no class data inside.

#### Expected Results

Only days of the week with actually classes on that day should be displayed

**Comment by g9singh** [comment]
completed in: a84ba5c321664446f92322fec2826e47c41b3341
@c3bryant sending your way for review

**Comment by c3bryant** [comment]
Merged into branch `6.6`, ready for beta

**Comment by c3bryant** [comment]
Ran into a Finals card bug when testing 6.7 in production which we traced back to this issue. The current plan is to revert these commits and re-evaluate this task in a future milestone

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
