### ISSUE TITLE
Add Lot 386 (Gliderport)

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#468]
Add parking lot data for through Parking Logix API:
- P386 (Gliderport): S only

**Comment by c3bryant** [comment]
Lot 386, Campus Point East, and Sports Deck have been activated in QA

Branch: `v1.1`
Lambda: `parking-availability:v2`

Previews:
![Screen Shot 2019-04-17 at 9 09 01 AM](https://user-images.githubusercontent.com/15112294/56303827-a994d900-60f1-11e9-8645-27d7554be8e7.png)
![Screen Shot 2019-04-17 at 9 08 35 AM](https://user-images.githubusercontent.com/15112294/56303828-a994d900-60f1-11e9-98f2-e433725d138f.png)
![Screen Shot 2019-04-17 at 9 07 56 AM](https://user-images.githubusercontent.com/15112294/56303829-aa2d6f80-60f1-11e9-82dc-78b2f8f55aa1.png)
![parking-logix-new-lots](https://user-images.githubusercontent.com/15112294/56303838-ae598d00-60f1-11e9-8cbc-2fef07bb5229.png)

**Comment by c3bryant** [comment]
Deployed & verified on 4/17/19
