### ISSUE TITLE
Classes with Multiple Professors in Schedule Showing Multiple Times

### ISSUE THREAD

**Issue by vvp002** [UCSD/campus-mobile#470]
### Issue Description

Classes that have multiple professors assigned to it will show up multiple times in students' schedule card. The same will also apply to their finals as well. 

### Steps to Reproduce / Code Snippets

1. Log in with student credentials
2. Go to Class Schedule Card and see full schedule 

![Simulator Screen Shot - iPhone X - 2019-04-09 at 17 29 41](https://user-images.githubusercontent.com/13816146/56226727-b8fc1f80-6028-11e9-909d-116155b9f929.png)

#### Expected Results

Expected result should just be to display the class and the final once. It's the same course, just with multiple professors teaching it so it doesn't make sense to have it appear multiple times in the schedule.

### Additional Information

* Platform(s) (iOS, Android, or both?): both

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
