### ISSUE TITLE
UI/UX Mockup for KSDT Live Radio Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#471]
UI/UX for radio card

**Comment by woznaut** [comment]
![RadioPlay.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/89745a44-79d8-4bf3-9ad0-a538f5e58e42)
basically replicates the player on the https://ksdt.ucsd.edu site. The animated "live" dot and the "Coming up next" both important for fit and finish imo. I presume the animated dot is easy, "Coming up next" is a nice to have assuming we can grab it from their schedule.

![RadioPause.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/d7c5d7d6-783f-473b-8108-706102fa7c25)

**Comment by c3bryant** [comment]
Implementation is underway on branch `feature/ksdt`, we can close this out. Thanks @woznaut
