### ISSUE TITLE
Integrate Mock Occuspace Data

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#472]
Use mock data from https://s3-us-west-1.amazonaws.com/ucsd-mobile-dev/mock-apis/occuspace/waitzv1.json until API is complete

Since we already have the data for Waitz in prod we can begin the development process.

This issue will involve a few tasks:
1) fetch the correct data from the endpoint (services/occuspaceService.js)
2) parse the data  (sagas/occuspaceSaga.js)
3) store data into state (reducers/occuspace.js) (should be stored under: state.occuspace.data)

In order to accomplish these tasks at least the following files will need to be created or modified.

Create:
app/services/occuspaceService.js
app/reducers/occuspace.js
app/sagas/occuspaceSaga.js

Modify:
app/reducers/index.js
app/sagas/rootSaga.js
app/AppSettings.js

**Comment by sssaiya** [comment]
completed in [bfb81db](https://github.com/UCSD/campus-mobile/commit/bfb81db03bba93429c0c02ccbc459e8e3b8d93ae)
