### ISSUE TITLE
Add parking lot context on Manage Lots view

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#473]

**Comment by woznaut** [comment]
had a thought about this - instead of trying to figure out what to call these lots to make them more human meaningful what if we let the user name the lot for themselves? 

Instead of "lot name" we could add a "nickname" data type that defaults to the lot name but the user can edit.

**Comment by woznaut** [comment]
Upon further discussion it was decided that the solution here is:

for lots that are only named by a lot number we will introduce logic to switch the lot name with the lot context data. ex. Lot 386/Gliderport will instead read Gliderport/Lot 386

long context entries may need to be truncated.

**Comment by c3bryant** [comment]
Done in `parking-availability` on branch `qa`

Manage lots:
![image.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/6e557170-9c8a-4025-9689-e37b12e22e4e)

Parking card longest character lot name example:
![image.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/eacb507d-27c5-419f-b191-7908389ae13d)

**Comment by c3bryant** [comment]
Explore adding the Lot # back to the Manage Lots view

**Comment by c3bryant** [comment]
After review, we will be reverting this change on the back-end and implementing the context<->lot number swap on the client side

**Comment by vishant101** [comment]
Completed in e5bb5ad08c0027a46843247214fd162c7148ef00 

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/f806a237-3a45-4009-a726-7d7697c8263b)

However I think for lots with only numbers we should just switch the context and lot name on the server. This way the name would stay consistent across the different screens.

**Comment by vishant101** [comment]
Just had a chat with @woznaut we want to display only the contextual name on the manage parking lots screen not the lot number. We also want the contextual name to appear as the heading on the parking card on the main screen and the lot number as the sub heading for all lots.

**Comment by c3bryant** [comment]
Closing this in favor of issues #545, #546, #547

**Comment by vishant101** [comment]
Decided to make server side improvements #546 and #547 to deal with this. #545 will take care of the  necessary changes to the client side for this to occur.
