### ISSUE TITLE
Login button not working and causing app crash

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#475]
### Issue Description
User's have reported that the login button becomes unusable.
Investigate and try to recreate issue.

### Additional Information
We think the issue is related to line 109 in AccountLogin.js 
"disabled={Boolean(this.props.requestStatus))}"
Boolean(this.props.requestStatus) maybe defaulting to false because (this.props.requestStatus) is null

* App version: <6.2
* Platform(s) (iOS, Android, or both?): Both

**Comment by g9singh** [comment]
First attempt to fix on branch: bugs/login-button
commit: 37f8ea5de5f84063e965c98ba86279e6424f4206

**Comment by c3bryant** [comment]
Verified with @g9singh and merged into `6.6`

**Comment by g9singh** [comment]
Extra notes: During initial implementation I ran into some issues running the badge indicator icon on android. 

The firebase library used to set badge icon in react native uses a library to set the indicator on android. However this library is only compatible with certain devices.

Knowing this we would like to move forward with the implementation by having an if check before we make the call to set badge icons just to see if the device is android or iOS. If it is iOS then we can make the call to set the badge number, otherwise do nothing. 

These links may help: 
https://github.com/leolin310148/ShortcutBadger
https://rnfirebase.io/docs/v3.3.x/messaging/reference/messaging

**Comment by c3bryant** [comment]
Ran into issues during testing - this was backed out from the 6.6 release. We are not receiving any new crash reports for this as of v6.5. Let's investigate again when time permits.

**Comment by c3bryant** [comment]
We are not seeing any bugsnag or user reports for this as of 6.5. Closing for now and adding additional steps to our regression test plan surrounding the login button
