### ISSUE TITLE
Create Occuspace API 

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#476]
Create API for Occuspace data
Prod API at https://collab.ucsd.edu/display/WTS/Occuspace

**Comment by c3bryant** [comment]
This API is ready to deploy
@g9singh will you add a note with the ITS-PRO ticket link when available?

**Comment by g9singh** [comment]
The request was completed but needs to be edited once more because the header_sequence.xml file was not put into the PROD api. Currently waiting on a response.

**Comment by g9singh** [comment]
The api has been deployed to production

**Comment by c3bryant** [comment]
Verified, closing
