### ISSUE TITLE
Combine ParkingLogix JSON Data

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#478]
ParkingLogix API is returning two separate JSON object for the same parking structure. Combine the following into one object, conforming to our mobile app parking API.  

Source code at: https://sourcecode.ucsd.edu/projects/WTS/repos/parking-availability/browse.

{
	"location_name": "Campus Point East Structure",
	"default_free": "0",
	"location_address": "304 Medical Center Dr",
	"timezone": "-8:00",
	"data": [{
			"total_spaces": "426",
			"free_spaces": "91",
			"level": "0",
			"date_time": "2019-02-20 09:15:07  -8:00"
		},
		{
			"total_spaces": "426",
			"free_spaces": "91",
			"level": "10",
			"date_time": "2019-02-20 09:15:07  -8:00"
		},
		{
			"total_spaces": "426",
			"free_spaces": "91",
			"date_time": "2019-02-20 09:15:07 -8:00"
		}
	]
}

{
	"location_name": "Sports Deck (Campus Pt East Structure Roof)",
	"default_free": "0",
	"location_address": "304 Medical Center Dr",
	"timezone": "-8:00",
	"data": [{
			"total_spaces": "264",
			"free_spaces": "FULL",
			"level": "0",
			"date_time": "2019-03-19 11:07:27  -8:00"
		},
		{
			"total_spaces": "264",
			"free_spaces": "FULL",
			"level": "10",
			"date_time": "2019-03-19 11:07:27  -8:00"
		}
	],
	"total_spaces": "264",
	"free_spaces": "FULL",
	"date_time": "2019-03-19 11:07:27 -8:00"
}

**Comment by sssaiya** [comment]
completed in [83dd4b9b042](https://sourcecode.ucsd.edu/projects/WTS/repos/parking-availability/commits/83dd4b9b04238d26a4e686e5daf89ebbc08b1656)

**Comment by c3bryant** [comment]
I'm unable to move forward with testing. Let's get together to discuss

**Comment by c3bryant** [comment]
One issue found and corrected in `ca690aa`

ParkingAvailabilityRouter v4 alias has been created and deployed to the CampusParkingService API v1.1 in QA

Tests passing on device. Ready for final review and deployment.

**Comment by c3bryant** [comment]
Deployed and verified on Prod, thanks @a6wu
