### ISSUE TITLE
Use SystemID from JWT

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#483]
Use SystemID from JWT

https://collab.ucsd.edu/api/api-documentation/information-for-api-developers/accessing-authentication-details-via-jwt

**Comment by a6wu** [comment]
To Do:

1. Investigate if the SystemID attribute is available from the JWT from ECP

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
