### ISSUE TITLE
Investigate the feasibility of Integrated WebViews

### ISSUE THREAD

**Issue by vishant101** [UCSD/campus-mobile#486]
### Issue Description

React-Native has a high setup and learning cost. We want to investigate a natural way of integrating WebViews that feel organic and is easier to develop for as we ramp up number of features in the app.  Integrating Web Views poses many challenges both known and unknown.

#### Expected Results

A working demonstration of an integrated WebView. 
Identify constraints to implementing WebViews. 

* Platform(s) (iOS, Android, or both?): both

**Comment by vishant101** [comment]
## Overview
This task was broken down into two components. The first was an investigation into obtaining the user app token and passing it into the webview. The second was the performance and restrictions on the webview UI

## Communication between React-Native and the Webview
The purpose behind passing the user token is so the webview may consume the token and make API calls using the token to obtain the same level of functionality as native component. 

The auth util has a very easy method called ```retrieveAccessToken``` that allows us to retrieve the mutated user app token that has the required to access all the necessary subscriptions. Note this token is different from the user token which has limited subscriptions.

Once the token is retrieved we are able to pass the token to the webview using the method outlined in https://medium.com/@azharuddin31/react-native-pass-data-to-webview-and-get-data-out-of-webview-792ffbe7eb75 . Although there are other ways that were explored to communicate between react-natve and webviews this way has the least overhead and appears safe from a security point of view.

The webview can obtain the token using an ```eventListener``` where the token is stored inside an object as a string. Note the communication method explored only allows for transfer of items as strings. Once the token is obtained the webview can make API calls using the token to obtain items such as a students academic history.

If the website is built using React a range of advanced communication features would be possible. However stipulating that webviews for the app be built using React would defeat the purpose of building webviews in the first place.

## WebView UI
![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/8255387a-5ca2-4380-bb47-f1286228445b) 

The scrollview system that allows for the speedy implementation works by calculating the size of components before rendering. What this means is that a fixed size must be declared for the webview card rather then the webview dictating it's own size. In the demo produced above a height of 400, similar to the other cards was used for the webview. 

The webview itself allows for interactivity but caution is advised due to limited size and lack of navigation buttons on the webview. For example the webview iteself can be used to link a youtube video, however after the video finishes and if autoplay is enabled a subsequent video will play. From this video it is impossible to navigate to the original video due to the lack of back button that users are accustomed to on a normal webpage. 

The webview created above was generated as a visual example of rendered html in a card for the app. Performance of the card seemed on par with the remaining app.

## Conclusions
Building cards with webviews that have the same functionality as native components is possible. Although certain challenges such as the predetermined size requirement and navigation interactions are present, webviews can be effectively integrated into the overall application

 @a6wu

**Comment by vishant101** [comment]
Another potential use of webviews could be having a promo video banner that simply shows a youtube video. It could function similarly to the promo banner where instead of passing in an image URL we pass in a youtube URL. Something like this would be helpful at the start of a semester where we could show a video tour of the campus or throughout the year if we want to highlight a particular event or piece of news. Most of the underlying work has already been completed as part of the investigation and previous work on promo banners.

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/4e8203a4-7847-4f21-96a2-8caff504b2b1)

@a6wu

**Comment by c3bryant** [comment]
Nice work and writeup, @vishant101
This update has been added to Collab under Projects -> Web Cards
