### ISSUE TITLE
Validate Lambda Functions for AmazonLinux1803

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#487]
Related to #480 but this issue can move forward independently

https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/

This task is complete when:
1. each Lambda function has been tested successfully under the new AmazonLinux1803 system.

**Comment by c3bryant** [comment]
All Node.js functions in the QA env have been upgraded to v10.x. Initial tests have passed but more end user testing is recommended.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
