### ISSUE TITLE
Emergency Alert: CMS Event

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#490]
From the CMS application server, in the emergency website, when content is published, have an event triggered and call an HTTP endpoint.

This is complete when
1. A trigger is created and added to the CMS application server. See documentation at:

https://www.hannonhill.com/cascadecms/latest/content-management/workflows/workflow-triggers/publish-trigger.html

2. An HTTP endpoint that accepts a POST from the CMS application. This endpoint will accept a JSON value passed in the body to include at minimum: the site name, CMS event type

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
