### ISSUE TITLE
Integrate Commencement 2019 Event

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#493]
For June 15 and June 16 dates

**Comment by c3bryant** [comment]
The June 15/16 commencement feed is up - https://mobile.ucsd.edu/feeds/commencement.json

The next steps are we need the banner image dimensions corrected and re-added, and the date for the QA env feed start-date set to today for testing - Cristian is helping out with this.

**Comment by c3bryant** [comment]
The `Commencement 2019` June 15/16 event has been activated on all QA builds and sent to the client for completion and review.
