### ISSUE TITLE
Security: Base64 is an encoding and not encryption

### ISSUE THREAD

**Issue by srri** [UCSD/campus-mobile#494]
### Issue Description

In: https://github.com/UCSD/campus-mobile/commit/9cd578ebc9abc4d973373248d23f6b43be2a5cd9

You add "base64 encryption". While base64 might obfuscate the passwords, they are easily reversed, this is not encryption. Storing passwords as base64 is equivalent to storing them as plaintext.

**Comment by srri** [comment]
Nevermind, looks like you encrypt with a pub key first, the commit itself (wording) sounds inaccurate though.

**Comment by a6wu** [comment]
@srri Thank you for the note. Please let us know if anything else catches your attention.
