### ISSUE TITLE
Parking: Dynamic Spot Types

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#496]
This task is allow for the adding, removing, and updating of spot types dynamically

**Comment by vishant101** [comment]
Completed as of c7edfc0351b32714a78092105524ffd5398050e2

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/28421db0-5e95-46ac-bb59-ec9e46c02c10)

Potential Improvements Identified:  The availability endpoint returns data with the keys being a spot types short name or the type if it is an Accessible spot type (Accessible does not have a short name) we should ideally use the spot types id instead when returning data.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
