### ISSUE TITLE
Parking: Spot Types: Dynamic UI

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#500]
Modify the Spot Types view to support a dynamic number of spot types

Tasks:
1) Convert the Spot Types view to a Flatlist, which will enable scrollability
2) Work with @woznaut to convert the 'Max Selection (3)' pop-up to a temporary (toast?) message to avoid UI blocking interactions as shown here:
![Screen Shot 2019-05-31 at 1 35 35 PM](https://user-images.githubusercontent.com/15112294/58824903-14db3180-85f2-11e9-951a-8fde29a1c9b4.png)

**Comment by vishant101** [comment]
Talked to @woznaut and replaced warning message with a toast message. @woznaut let me know what you would like for the message text. 

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/a8eef641-3f6a-4bc8-a401-e13eec1c3400)

**Comment by vishant101** [comment]
The parking spot types already used a flat list as of 6.7, scrolling was however not enabled. I've now enabled it in 6e1f815baca91e8713405ec20cee8b75dfc18ed3 See gif with mock data below.

![daa97a2a1b7cf74b9d4e3e45f388fec8.gif](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/1f6e6a90-5d77-429e-80d8-f4aa7b094ed7)

@c3bryant @g9singh

**Comment by g9singh** [comment]
iOS results: 
- spot types appear: PASS
- scroll functionality: PASS
- too many spot types selected modal: PASS
- deselecting spot type: FAIL
![error_ios.PNG](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/f86181e7-ddba-436b-bd4f-6c58c954a34b)
Android results: 
- spot types appear: PASS
- scroll functionality: PASS
- too many spot types selected modal: PASS
- deselecting spot type: FAIL
![error_android.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/b79d23e6-8d11-469e-9b9c-03ce3d52d84c)

Notes: 
- On Android and iOS the app crashes when trying to deselect spot type
- On Android the build (674) from AppCenter causes a crash on app launch, however the build succeeds if I compile locally

**Comment by vishant101** [comment]
@g9singh thanks identifying the error. I believe I've now fixed it in 433fe600495c96bd429f8061a54e21fb7d37c232 The error was caused due to me factoring out unused methods, I missed removing a reference to the method I removed. Please test and  confirm that this works now. Thanks.

**Comment by c3bryant** [comment]
Issues resolved on iOS/Android. Merged into `6.9-beta`

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
