### ISSUE TITLE
Webreg: Implement course search

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#501]
This task is complete when:

- [x] 1. User is able to enter text into the search input field
- [ ] 2. Results displays beneath the search input field as the user types
- [ ] 3. Each search result item is linked to the detailed course view

UI flow for Course Search is currently unavailable.

Blockers for 2 & 3: Need API for Student Access Token. currently we must get access token manually to get courses info.

**Comment by c3bryant** [comment]
@EnqiZhang99 sending your way to review/update

**Comment by EnqiZhang99** [comment]
@chrisqz95 Could you please update the figma for search view? Thanks!

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
