### ISSUE TITLE
Webreg: Implement Term selection

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#502]
This task is complete when:

1. The current term and future available terms are available for selection
2. The user can select a term
3. On term selection, the user is taken to the calendar view for that term

See UI Flow at https://www.figma.com/proto/hUluYT2dbw4VormTKyluEl/WebReg-shared?redirected=1&scaling=min-zoom&node-id=40%3A2423

**Comment by c3bryant** [comment]
@EnqiZhang99 @Priceincoding @woznaut @chrisqz95 sending your way to discuss/review

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
