### ISSUE TITLE
Webreg: Implement Calendar view for a specific term

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#503]
This task is complete when:

1. The view displays the current week from Sunday to Saturday
2. The view displays the enrolled and waitlisted courses within the time range of the specific course

See UI Flow at https://www.figma.com/proto/hUluYT2dbw4VormTKyluEl/WebReg-shared?redirected=1&scaling=min-zoom&node-id=40%3A2423

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
