### ISSUE TITLE
Webreg: Create Mock API for Calendar Service

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#504]
This task is complete when mock APIs have been created on APIM QA for:

1. Get calendar event
2. Add calendar event
3. Update calendar event

See https://collab.ucsd.edu/display/WTS/WebReg for documentation.

**Comment by c3bryant** [comment]
Looking to get real data format/schema to base mock API structure around

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
