### ISSUE TITLE
Integrate TLC SI Summer Schedule

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#506]
https://docs.google.com/spreadsheets/d/1MmIKjgLCbtk2Py38a9pP2IkLv6fXod1WeheOfpag7Hg/edit#gid=1091060376

**Comment by g9singh** [comment]
There is an issue with the data provided on google docs because many of the professors are labeled as staff. On the client side we use the name of the professor to distinguish different SI sessions for different students.

**Comment by c3bryant** [comment]
All professor names have been updated by TLC
TLC JSON updated by and deployed - thanks @g9singh, @a6wu
