### ISSUE TITLE
Webreg: Create Mock APIs for Course Plan Service

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#507]
This task is complete when mock APIs have been created on APIM QA for:

1. Get planned courses
2. Get courses for a specific Plan
3. Get list of Plans
4. Delete a course from a Plan
5. Delete a Plan

See https://collab.ucsd.edu/display/WTS/WebReg for documentation.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
