### ISSUE TITLE
Feedback extra info

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#51]
Update eform to include extra information, such as, device platform and app version.
Update FeedbackView to send extra info
Look into ways to identify app version

**Comment by c3bryant** [comment]
https://github.com/rebeccahughes/react-native-device-info

**Comment by c3bryant** [comment]
Done in dev 132aadb

**Comment by c3bryant** [comment]
Add location (if available) and user preferences

**Comment by c3bryant** [comment]
Add location / GPS info is now handled under issue #179 
Preferences to be added as a separate issue later if the need arises
