### ISSUE TITLE
Webreg: Solve Conflicting Class in Calendar

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#520]
Create and implement UI/UX for the calendar when a user has multiple classes on the same day/time.

**Comment by c3bryant** [comment]
Sending your way @chrisqz95 

Reference:
![update.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/2838ccd0-3e9b-4f8a-8dae-cc80a9911225)

**Comment by qidian99** [comment]
I tested the new build 698 in TestFlight, and it seems like we also need to deal with animations in conflicting classes. Currently the animation shows some discontinuity despite the code looks good.

[Link](https://drive.google.com/file/d/1DPWban4p7v5KLF1Kj9fyO4Df4ZNQajnO/view?usp=sharing) to demo video.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
