### ISSUE TITLE
Webreg: Implement Course Detail from Search Results

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#522]
This task is complete when:

1. The user taps on a search result
2. The user sees the course details

**Comment by c3bryant** [comment]
@chrisqz95 sending your way to finalize/attach the updated B version of this UI

**Comment by chrisqz95** [comment]
![Course detail (section expanded).png](https://images.zenhubusercontent.com/5d1120a505116729f96c9eb1/92fe01a9-7dc6-4ad5-a26d-a4dc05fa8805)

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
