### ISSUE TITLE
Webreg: Implement Course Search Filter

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#523]
This task is complete when:

1. User can set the filters for lower, upper, and graduate division
2. User types in the textfield and taps search
3. The search results only displays courses matching the filter values

See https://www.figma.com/proto/hUluYT2dbw4VormTKyluEl/WebReg-shared?node-id=60%3A804&scaling=scale-down&redirected=1

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
