### ISSUE TITLE
Webreg: Implement Search Results Filter

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#524]
This task is complete when:

1. After a search is done 
2. User can set the filters for lower, upper, and graduate division
3. The search results is updated to only show filtered courses

See https://www.figma.com/proto/hUluYT2dbw4VormTKyluEl/WebReg-shared?node-id=60%3A804&scaling=scale-down&redirected=1

**Comment by c3bryant** [comment]
@EnqiZhang99 sending your way for UI implementation

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
