### ISSUE TITLE
Webreg: UI/UX for Active Search Filter

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#525]
Review how to indicate that filters are active for course search.

See https://www.figma.com/proto/hUluYT2dbw4VormTKyluEl/WebReg-shared?node-id=60%3A804&scaling=scale-down&redirected=1

**Comment by chrisqz95** [comment]
![Search results (filtered).png](https://images.zenhubusercontent.com/5d1120a505116729f96c9eb1/b945da88-8402-4147-95ea-bc6e27f335ab)

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
