### ISSUE TITLE
Webreg: Implement Class List View

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#527]
This task is complete when:

1. The user sees the classes in a list view
2. The user can expand on each class
3. The class card height should accommodate various numbers of meeting types
4. The "Note" feature TBD

UI screen to be linked here.

**Comment by qidian99** [comment]
[Here](https://drive.google.com/file/d/1Ap4oblhnBlrgruwPfVQerAoLE1YuozQU/view?usp=sharing) is the demo to course list view.
I am refactoring the code for CourseTableView.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
