### ISSUE TITLE
Integrate occuspace live data using wso2 end point

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#529]
Right now the app is using mock data which has been uploaded to S3

This task is complete when:
1. The app can fetch and parse live occusapce data
2. The app uses the flowing endpoint for occuspace data: https://api-qa.ucsd.edu:8243/occuspace/v1.0
3. https://its-pro.ucsd.edu/browse/MA-53 is completed

**Comment by g9singh** [comment]
This task has been completed on the feature/occusapce branch and is ready to be tested on devices.

**Comment by c3bryant** [comment]
Verified on branch `feature/occuspace`
