### ISSUE TITLE
Webreg: Implement Card Component for Different Class Status

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#530]
This task is complete when:

1. Each class status has its own card component (enrolled, waitlist, planned)
2. Each class status component is visually distinct

UI screen to be added https://www.figma.com/proto/hUluYT2dbw4VormTKyluEl/WebReg-shared?node-id=206%3A217&scaling=scale-down&redirected=1

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
