### ISSUE TITLE
Classes Card not rendering on HomeScreen

### ISSUE THREAD

**Issue by qidian99** [UCSD/campus-mobile#532]
### Issue Description

Currently the Classes Card on HomeScreen is always loading. For now, the Saga, updateSchedule, returns nothing. The required condition to render the course data is that all three of "coursesToShow", "coursesToShow[activeCourse]", "currentTerm.term_code" are not null. However, for now they are "[]", "undefined", and "inactive", respectively.

### Steps to Reproduce / Code Snippets

Login with an arbitrary account, and go to HomeScreen

#### Expected Results

The Classes Card should be render with the student's course, if any, after the Saga, updateSchedule, has succeeded in fetching course data.

### Additional Information
* Build Environment: QA
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by c3bryant** [comment]
This has been resolved

If no term is active in QA, we now return Spring 2019 data
