### ISSUE TITLE
Webreg: Resuable Class Section Component

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#533]
This task is complete when:

1. The class section component accommodates various number of meeting types
2. The component can be reused across various webreg features

**Comment by c3bryant** [comment]
Class section self adjust to varying configurations
Requires real data for final implementation

**Comment by hanyt08** [comment]
<img width="371" alt="Screen Shot 2019-08-26 at 8 35 47 PM" src="https://user-images.githubusercontent.com/35383611/63705328-76144900-c85f-11e9-9359-fd61f55ff27f.png">
<img width="371" alt="Screen Shot 2019-08-26 at 8 35 47 PM" src="https://user-images.githubusercontent.com/35383611/63705336-77457600-c85f-11e9-8399-a5b6792537f3.png">
Here is the newest course search list and the course detail page with new header. Remaining content in the course detail page is still in progress.

**Comment by hanyt08** [comment]
<img width="384" alt="Screen Shot 2019-08-29 at 11 59 20 PM" src="https://user-images.githubusercontent.com/35383611/63956499-1dd88380-cab9-11e9-8871-89450799cd4e.png">
Here is the screenshot of course view.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
