### ISSUE TITLE
save user's occuspace location(s) once logged in

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#534]
This task is complete when:
1) users' occuspace locations are stored on DynamoDB
2) users' occuspace locations are retrieved from DynamoDB upon login
3) users' occuspace locations are synced every time a change is made on the client side

**Comment by g9singh** [comment]
completed on branch feature/occuspace
commit hash: bb6b67f6b45cb8ff15e1ba859331ea898911ff09

**Comment by c3bryant** [comment]
Verified on branch `feature/occuspace`
