### ISSUE TITLE
Occuspace Data not loading properly in QA build

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#536]
### Issue Description
The Occuspace card has an endless loading indicator

### Steps to Reproduce / Code Snippets
Use test flight or google play to get builds 595 and 661 respectively.
Launch app

#### Expected Results
We should see a the loading indicator for a maximum of 15 seconds. 
After which, either an error message should appear with a try again button or the Geisel Library data should appear.

### Additional Information
This issue requires that the source maps be uploaded for version 6.7 of the app. Without the source maps it becomes difficult to debug when testing on device.

**Comment by g9singh** [comment]
Issue was caused by a mismatch in the replacement script and the variable being replaced in the code base. This has been resolved.

**Comment by c3bryant** [comment]
Fix verified
