### ISSUE TITLE
Bugsnag android builds

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#537]
### Issue Description

On the Bugsnag dashboard all the builds for android seem to be coming from production. This causes some confusion when trying to filter bugs that are just in production vs bugs that are in development.

The task is complete when we Bugsnag is successfully able to distinguish production and development builds on the dashboard.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
