### ISSUE TITLE
Android: Target API level 28

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#539]
We received the following warning from Google Play regarding the target API level. This task is to investigate and resolve

> Your app currently targets API level 27 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.
> 
> From August 2019, new apps must target at least Android 9.0 (API level 28).
> From November 2019, app updates must target Android 9.0 (API level 28).
> 
> Change your app's target API level. Learn how.
> https://developer.android.com/distribute/best-practices/develop/target-sdk.html

**Comment by vishant101** [comment]
Had significant issues once I updated the target SDK to API 28 with it being no longer able to communicate with the metro blunder. Followed solution outlined at https://github.com/facebook/react-native/issues/22024 to fix the problem. Also updated gradle and build tools. 

4edff38039325d63a8d758d600c0ca534608da1b

**Comment by c3bryant** [comment]
Thanks for the update Vishant. We are going to explore the RN 0.59 upgrade first and revisit this after that conversation.

**Comment by c3bryant** [comment]
Completed in #541
