### ISSUE TITLE
Upgrade React Native Firebase to 5.2.5

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#542]
This task is to upgrade React Native Firebase to 5.2.5

https://github.com/invertase/react-native-firebase/releases/tag/v5.2.5

**Comment by vishant101** [comment]
Attempted to upgrade to version 5.0.0 outlined in https://rnfirebase.io/docs/v5.x.x/releases/v5.0.0 it failed due to version mismatches.  Will investigate at a later date.

**Comment by c3bryant** [comment]
Thanks for looking into this @vishant101 - we're moving forward with the FIrebase upgrade in #541 which is running the latest React Native version 60
