### ISSUE TITLE
Parking: Use LocationId over LocationName for client-side operations

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#545]
In some cases, Parking logic in campus mobile references LocationName for purposes other than rendering.

This task is to ensure LocationName is only used for displaying a parking location name, and LocationId is used for all other client-side operations like sorting, initialization, etc.

**Comment by vishant101** [comment]
completed in c765592b79144a966347283b3e97f988fe2398be

**Comment by vishant101** [comment]
minor error with default selected lot. Need to add in Osler locationId

**Comment by c3bryant** [comment]
Verified on branch `feature/parking-lot-ids`
Merged into `6.9-beta`

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
