### ISSUE TITLE
Parking API: Swap LocationName and LocationContext for numbered parking lots 

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#546]
This task is to swap LocationName and LocationContext for numbered parking lots in `parking-lots-master.json`

This is a breaking change, so we will be looking to create a new version (1.2) in qa, and point the mobile app client this new version

**Comment by vishant101** [comment]
Completed the changes on f85e3e464364164bb7089d93a06b30f4791afd19 on the parking repository.

Uploaded the functions to AWS lambda. New endpoint is https://4pefyt8qv7.execute-api.us-west-2.amazonaws.com/dev/parking/v1.2/status

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
