### ISSUE TITLE
Parking: Upgrade Parking API to version 1.2

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#547]
This task is to upgrade the Parking API version on the campus-mobile client to version 1.2, from it's current version, 1.1.

**Comment by vishant101** [comment]
Completed in 8b78d033ced8b3f1fdfde04bacdce06a747c89e2

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/91e1e639-9d37-4110-8b79-5eaab9c19db5)

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/128743de-334e-49d2-8dab-93d871058be4)

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
