### ISSUE TITLE
Link Reddit Bot with Slack Channel

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#549]
Link Reddit bot #479 to our team Slack channel, "reddit-bot"

**Comment by c3bryant** [comment]
Sending this your way @atmartorana

Please work with myself and Alex to complete this task

**Comment by atmartorana** [comment]
Added @a6wu and @c3bryant as collaborators to the app on Slack. Updated the webhook URL to send messages to reddit-bot slack channel.

**Comment by c3bryant** [comment]
Hi @atmartorana - thanks for setting this up

We'd like to have the bot send some test messages to the new slack channel to ensure everything is working as expected. Please setup a time with myself and @a6wu to discuss this and next steps

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
