### ISSUE TITLE
Use Continuous Integration

### ISSUE THREAD

**Issue by alexhwu** [UCSD/campus-mobile#55]
For code commits

**Comment by srkirkland** [comment]
@alexhwu To start the discussion, I've heard good things about www.bitrise.io.  Basically CI for mobile apps.  They have some RN support.  Free for small projects & I'd be happy to help set it up.

**Comment by alexhwu** [comment]
@srkirkland Thanks. Please do.

**Comment by alexhwu** [comment]
How does bitrise compare to bamboo or travis ci?

**Comment by srkirkland** [comment]
@alexhwu It's similar to travis or bamboo except it is geared toward mobile development so they have specialized containers w/ XCode and Android SDKs already installed and steps for signing keys and provisioning profiles. They also natively have React Native build step support.  Also unlike bamboo, bitrise has a free tier that we can use to get started.

**Comment by srkirkland** [comment]
@a6wu All the PR does is update the unit test to search for the text "Feedback" (which is in your footer) instead of the text "Welcome to React Native" which is only in the initial react native sample.  That PR has nothing to do with bitrise itself, and even if you run the tests in XCode it'll fail until this PR is merged as well.

However, merging that PR will allow the tests to run and then I could do forward w/ setting up bitrise, which I am most of the way done with except it properly is failing on that bad test.

**Comment by srkirkland** [comment]
@a6wu Also does UCSD have a bamboo license?  I don't think we do over there but that's another option you might want to look at

**Comment by a6wu** [comment]
@srkirkland Gotcha. Thanks for the info. We do have a bamboo license and it's used in other projects. @c3bryant is looking into it.

**Comment by c3bryant** [comment]
https://hanno.co/blog/bitrise-deployment-workflow-react-native/

**Comment by c3bryant** [comment]
This main issue is being broken into multiple tasks, the first of which is #218

**Comment by c3bryant** [comment]
The initial CI implementation for Android has been completed via VS App Center. Passing builds can now be deployed directly to the Google Play Alpha, Beta, or Production stores with one click. 

![appcenter-android-alpha](https://user-images.githubusercontent.com/15112294/37415630-1e680e50-2769-11e8-913c-0d6452a5c899.png)

![googleplayconsole-android-alpha2](https://user-images.githubusercontent.com/15112294/37415629-1e4356d2-2769-11e8-852e-d85ae41581e6.png)

![googleplayconsole-android-alpha1](https://user-images.githubusercontent.com/15112294/37415628-1e1ac06e-2769-11e8-8ec3-aa0f34447e77.png)

Special thanks to @Gulci and @a6wu 🎉

**Comment by c3bryant** [comment]
Android and IOS builds are both passing and set to automatically build `dev` on code commit.
The plan going forward is to setup each `-rc` branch to be built as well, whenever a `-rc` branch is created.
