### ISSUE TITLE
Parking Card Lot Name

### ISSUE THREAD

**Issue by vishant101** [UCSD/campus-mobile#556]
The parking card doesn't center text for lot names if the lot takes up multiple lines.

![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/17dd851f-09b8-4f7d-9d88-e50ac603c162)

* Platform(s) (iOS, Android, or both?): Both

**Comment by vishant101** [comment]
Completed on c6a643dad386088aac973052911eb33e9a4df432

**Comment by c3bryant** [comment]
Testing passed on iOS/Android. Merged into `6.9-beta`

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
