### ISSUE TITLE
Availability: Info not displaying correctly 

### ISSUE THREAD

**Issue by g9singh** [UCSD/campus-mobile#558]
### Issue Description
Some time after the initial load of the card it tries to reload again and then gets stuck on the error message even if you tap retry.

### Steps to Reproduce / Code Snippets
Load app and wait for card to error out
Tap on retry 
The old data will flash for a second and then error message will reappear 

#### Expected Results

After hitting retry we should see either the loading indicator (or the error message if no network is available)

### Additional Information
V 6.8 +

**Comment by g9singh** [comment]
Could not reproduce the bug.
May have been solved by the fix implemented in issue #557

Next steps:  test thoroughly and try to reproduce

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
