### ISSUE TITLE
Student Authentication

### ISSUE THREAD

**Issue by alexhwu** [UCSD/campus-mobile#56]
Explore OpenID or ECP for authentication

**Comment by srkirkland** [comment]
@alexhwu BTW our central campus just announced they were adding OpenID (OIDC) support to our UCD authentication system, and since it's a pretty popular standard I think that'd be a good direction to support

**Comment by a6wu** [comment]
@srkirkland Can you forward along the announcement so I can share with the other teams here? Thanks.

**Comment by srkirkland** [comment]
@alexhwu Sure, probably the best place would be http://developers.ucdavis.edu/events/2016/11/08/duo-cas/, which links to the PDF presentation our central campus tech unit gave about changes to campus auth in the works (http://developers.ucdavis.edu/media/meetings/7/duo-with-cas.pdf).  OAuth 2.0/OIDC announcement on page 8.

**Comment by a6wu** [comment]
@srkirkland Thanks. Shared it with others. OAuth2/OpenID is on the roadmap and also looking at SAML-to-JWT as alternative to OIDC. Estimated completion of a dev env for SSO ECP is end of 2016.

**Comment by a6wu** [comment]
@srkirkland We have a test ECP setup and @i8wu is able to get a SAML token from it. Working on getting an OAuth access token from the API manager using the SAML token.

**Comment by srkirkland** [comment]
@a6wu awesome.  I'd like to try something similar w/ OIDC/OAuth directly from a local provider too once you get the scaffolding working.  Are you using the Linking library to open a webpage and then using that to callback to the app?  Also, I'm assuming you are going to just create a redux user store and store the user info in there, right?

**Comment by i8wu** [comment]
@srkirkland We're probably going to just use fetch/request instead of the Linking library. I think storing the SAML and or OAuth tokens in a redux store would be good, but for the username/password I'm looking into using this [react-native-keychain](https://github.com/oblador/react-native-keychain).

**Comment by srkirkland** [comment]
@i8wu the tokens sound like a good idea, but why would you ever want to store the username/pass?  Seems like a recipe for future security issues.  Instead you could just have the oauth token last a long time, or keep the token as well as a refresh token and just refresh it as needed.

**Comment by i8wu** [comment]
I don't think we can refresh the token if the user is out of app. And if they have to re-login every time the app might feel a bit clunky? The module seems to use iOS keychain natively and Android's account manager natively I think, so it should be fairly secure. Although, if this method really is insecure we can explore options with the tokens.

**Comment by srkirkland** [comment]
@i8wu Ok so this must be something with the AWS API manager that I've just never seen before?  When you use OAuth via something like GitHub or Facebook, you just store the token and then that's it, no need for passwords or refreshing or anything.

**Comment by i8wu** [comment]
@srkirkland The UCSD APIs we want to use aren't on AWS, they're managed by [WSO2](https://docs.wso2.com/display/AM190/About+API+Manager)

**Comment by srkirkland** [comment]
@i8wu I thought I read you got a SAML token from your UCSD APIs and then were going to get an "OAuth access token from the API manager using the SAML token".  Then all you'd need to do is to store that oauth access token and not worry about refreshing or passwords.

**Comment by i8wu** [comment]
@srkirkland The SAML is from our SSO authentication, do oauth tokens not need to be refreshed? I actually don't know much about them, but I was led to believe that they do need to be refreshed once in a while.

**Comment by srkirkland** [comment]
@i8wu depends on how the OAuth tokens are setup, but most providers these days don't bother with refreshing oauth tokens.  GitHub and Twitter for example has them never expire, other providers might have them expire after a few years.

**Comment by i8wu** [comment]
@srkirkland I try double checking with out API middleware guys then, thanks for the heads up!

**Comment by a6wu** [comment]
@srkirkland Our API OAuth access token expires at about 20 minutes. SAML assertion also is set to expire, though at a much longer timeframe. On premise API manager is from WSO2 which currently is planned to house the student data API. We're using AWS API Gateway currently but hope to reduce it to just one API product.

**Comment by c3bryant** [comment]
Going with ECP for authentication. If a more straightforward method with OpenID presents itself we will be exploring that option.
