### ISSUE TITLE
Implement Single Sign-On

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#567]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-59

**Comment by c3bryant** [comment]
Updates for V1
- [ ] Disable refresh token authorization flow
- [ ] On app launch/[app resumed](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html), silently reauthenticate the user

**Comment by c3bryant** [comment]
Passed initial review, signing off
