### ISSUE TITLE
Implement Student ID Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#573]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-64

This is done when:
- [x] Student ID card displays on the Home view after student login as shown in the mockup
- [x] Student ID card barcode can be clicked to display an enlarged, horizontal version of the barcode

Resources
- Mockup:
<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/62a93329-a0ce-49d4-9da0-50200f9b4bf2" width="300">

- Core setup: https://github.com/c3bryant/campus-mobile/tree/feature/student-id-card

**Comment by c3bryant** [comment]
TODO:
- [ ] Real world id card scanner testing on physical Android devices
- [ ] Real world id card scanner testing on physical iOS devices
