### ISSUE TITLE
Implement Dining Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#596]
Time category: https://its-pro.ucsd.edu/browse/MA-82

- [x] Dining Card - Make title larger and change color to primary color
- [x] Dining Card - Change color of walk man to primary color
- [x] Dining Card - Change color of distance to primary color
- [x] Dining View All - Change title color to the primary color and bump size up
- [x] Dining View All - Move hours back to middle of screen and fix dot color
- [x] Dining View All - Add directions back in
- [x] Dining View All - Add sorting back (vegan vegetarian etc)
- [x] Dining View All - Figure out how to add more filters (spacing issue)
- [x] Dining View All - Change color of menu items
- [x] Dining Nutrition - Add primary color to title
- [x] Dining Nutrition - Add category after title
- [x] Dining View All - Add padding between sections
- [x] Dining Card - Change time format to match the original app
- [x] Dining View All - Add padding to content overall

**Comment by c3bryant** [comment]
Merged to `experimental`, thanks @Atreto76

**Comment by c3bryant** [comment]
Theme conflicts surfaced after merging into 7.2-rc. Resolved in #739. Verified and merged into `experimental`
