### ISSUE TITLE
Implement QR Scanner Feature

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#598]

**Comment by a6wu** [comment]
1. Scan card appears on the home view
2. If user is logged in, tapping the Scan Now button takes the user to the scan feature
3. If the user is not logged in, a Log in button takes the user to the login form on the Settings view
4. After log in, the user is taken to the scan feature

**Comment by c3bryant** [comment]
Latest build of `UCSD Scan` app
https://github.com/a6wu/testscan/tree/v1.0.0.15

**Comment by i8wu** [comment]
@a6wu You mentioned that we might be sending geolocation data as well, should that be done as a part of this issue since #602 is complete?

**Comment by i8wu** [comment]
I can copy over the submit implementation from testscanner, but it does not include first/last/geolocation. Also `AuthenticationModel` does not contain first/last
Can we confirm:
- What API we'll be using to submit
- If access-profile API has first/last available

**Comment by c3bryant** [comment]
2. access-profile does not have first/last

**Comment by c3bryant** [comment]
Updates - 
1. iOS build on device is having trouble, may be crashing on 'scan' button which navigates to the QR scanner. no logs available
2. Gagan noticed a few issues with provider setup and ui and jumped in, (https://github.com/UCSD/campus-mobile/commit/3d5ac5bcf8023d2d409ef484f8705390bb6a3b8b) need to test and merge this in

**Comment by a6wu** [comment]
Updated values sent to the API above. Date timestamp populated by API itself. First/Last Name will be joined against another DB table during GET call.

**Comment by c3bryant** [comment]
Tests passing. Anything left here? Closing
