### ISSUE TITLE
Implement 3 Notice Banners

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#600]
This task is to implement 3 Notice banners

Feature Reqs:
- A Notice banner should appear when its corresponding endpoint has been published (200 resp)
- When a Notice banner endpoint is not present (non-200 resp), hide the banner
- Notice banners should not be dismissable
- When clicked, link out to browser using `notice-banner-link`
- Notice banners should remain locked to the top of the Home view, in order, 1-3

JSON fields:
```
notice-title
notice-banner-image
notice-banner-link
```

JSON for Notice Banner 1
```json
{
    "notice-title": "Coronavirus Information",
    "notice-banner-image": "https://mobile.ucsd.edu/feeds/_resources/media/promo-banners/covid-19-app-20-03-04.png",
    "notice-banner-link": "https://go.ucsd.edu/38nb0Pf"
}
```

Please configure Notice Banner 2 and 3 using mock data with a placeholder banner.

Notice banner JSON (x3) to reside on AWS QA: https://s3.console.aws.amazon.com/s3/buckets/ucsd-its-wts-dev/now_ucsandiego/v1/notices/?region=us-west-1&tab=overview

Example actual Notices card from UC San Diego app in prod:
![image](https://user-images.githubusercontent.com/15112294/80929705-0d248f80-8d63-11ea-9520-8fd04d34063f.png)

**Comment by i8wu** [comment]
Not exactly sure why it needs to be a 3 banner implementation, the PR I have up allows any number of notices and the order is determined by the order of the array. Let me know if that's an issue and we can change it.

**Comment by c3bryant** [comment]
Next up
- [ ] Deploy AWS QA [mobile-app-notice-banners.json](https://ucsd-its-wts-dev.s3-us-west-1.amazonaws.com/replatform/v1/notices/mobile-app-notice-banners.json) to [AWS Prod](https://ucsd-its-wts.s3-us-west-2.amazonaws.com/replatform/v1/notices/mobile-app-notice-banners.json)
- [ ] Update NoticesService endpoint to AWS Prod (https://github.com/UCSD/campus-mobile/blob/experimental/lib/core/services/notices_service.dart#L15)
- [ ] Fetch remote data via NetworkHelper.fetchData (https://github.com/UCSD/campus-mobile/blob/experimental/lib/core/services/notices_service.dart#L24)
