### ISSUE TITLE
Implement Maps

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#601]
Time category: https://its-pro.ucsd.edu/browse/MA-81

Do not include Shuttle

**Comment by c3bryant** [comment]
- [ ] Merge https://github.com/c3bryant/campus-mobile-experimental/tree/feature/android-google-maps

**Comment by c3bryant** [comment]
TODO:
- [ ] Complete Map tab integration
- [ ] Activate Map tab

Testing
iOS
- [ ] Test map search
- [ ] Test map quick search icons
- [ ] Test map search history
- [ ] Test map search pins pop up when expected
- [ ] Test location tracking on device

Android
- [ ] Test map search
- [ ] Test map quick search icons
- [ ] Test map search history
- [ ] Test map search pins pop up when expected
- [ ] Test location tracking on device
