### ISSUE TITLE
Lab Barcode Reader App

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#604]
A separate app from campus mobile app.

Barcode Reader App will:

Iteration 1:

1. Scan the barcode
2. Query the API with the barcode as the key
3. Display all the data from the API
4. No data is persisted on the device

**Comment by i8wu** [comment]
No work to be done per @a6wu message about this being completed in testscan repo

**Comment by a6wu** [comment]
@i8wu Please use this repo for the Barcode Reader App, https://github.com/a6wu/QRScanLab.

**Comment by i8wu** [comment]
We need the API endpoint and maybe app icons to close out this issue.

**Comment by c3bryant** [comment]
Looking good here. Let's use #627 for the remainder
