### ISSUE TITLE
Backend Services: Implement APIs/Services in Prod Environment

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#605]
- [x] In AWS Prod account, create API that will accept POST for scanned barcode data, use JWT authorizer (Student PID, barcode id, datetime of scan, user ID/email, **first and last name not in current API**)
- [x] In AWS Prod account, create API that will read scanned barcode data based on Student ID, auth method is API Key on AWS, "QRScannerAPIKey"

- [x] In AWS Prod account, create Lambda in the UCSD Campus VPC that will call the HANA Stored Procedure, PUT_SCAN_DATA, use JWT authorizer
- [x] In AWS Prod account, create Lambda in the UCSD Campus VPC that will call the HANA Stored Procedure, GET_SCAN_DATA, auth method is API Key on AWS, "BarcodeScanDataAPIKey"

- [x] Migrate exsiting WSO2 API to Prod

**Comment by ryanrose** [comment]
Just waiting on DIS to migrate to Prod.
