### ISSUE TITLE
Update AH.GET_SCANCODE_DATA to return First and Last Name

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#607]
- [x] Verify with Health if this is legal name, preferred name, etc
- [x] Update Lambda to return FIRST_NAME, LAST_NAME
- [ ] Update stored procedure to join with SAH on PID or EID

**Comment by ryanrose** [comment]
The stored procedure was updated. I think we need to check with Judy and/or Vince to see why employee names don't populate. Maybe it's looking for very specific format on employee id? We are getting the numeric version from SSO/JWT (no leading 0's).

The API will return FULL_NAME, where
    FULL_NAME = STUDENT_FULL_NAME if IDENTITY_TYPE contains "student"
   else  FULL_NAME = EMPLOYEE_FULL_NAME if IDENTITY_TYPE contains employee
    else FULL_NAME = null otherwise (this shouldn't happen)
