### ISSUE TITLE
Prepare UCSD Scan for Public Store

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#610]
Point to prod APIs (dynamodb)
Submit for approval
Queue up and be ready for public release for Android/iOS

**Comment by c3bryant** [comment]
- [ ] Deploy AWS [QRScanner DynamoDB](https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:selected=QRScanner)
- [ ] Deploy AWS [QRScanner API Gateway](https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/f0qqgvpdp4/resources/62ws6pb4x4)
- [ ] Deploy [APIM QRScanner API 1.0.0](https://api-qa.ucsd.edu/store/apis/info?name=QRScanner&version=1.0.0)
- [ ] Demo login video (iOS)
- [ ] Determine if Android app renaming is required (is Back to School Kit shown on Play Store?)
- [ ] Submit for App Store Review
- [ ] Submit for Play Store Review
