### ISSUE TITLE
Remove Cards from Home View

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#611]
Remove the following card from the Home view, so users do not see it.

- [x] Weather
- [x] Availability
- [x] Parking
- [x] Dining
- [x] News
- [x] Events
- [x] Links

Update the Settings -> Cards View to reflect above deletions.
Ensure corresponding services are not called.

**Comment by i8wu** [comment]
I don't think i can assign this to myself bc I don't have permission but I'm working on this.

**Comment by c3bryant** [comment]
Verified, thanks @i8wu
