### ISSUE TITLE
Scanner Card: Finalize V1 title and content

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#623]
Current:
![image.png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/28ac79d1-24dc-46e5-8a54-5b2d72667358)

**Comment by woznaut** [comment]
![Screen Shot 2020-05-04 at 9.22.09 AM.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/b3aa84fd-bc9c-471e-b68f-8f9a2f5c01bd)

**Comment by a6wu** [comment]
Empty menu options for ellipses option.
