### ISSUE TITLE
Finalize Lab Barcode Reader App

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#627]
Dev
- [x] Call Prod API on WSO2 that connects with GET method, https://lemqls3u03.execute-api.us-west-2.amazonaws.com/prod/scanData/{barcode}
- [x] Displays all information returned from the API, API may return additional values later
- [x] Allow user to rescan and see data with additional barcode scan
- [x] Displayed data should be cleared out on app launch
- [x] Add camera permission message for user

Release Prep
- [x] Finalize app name (UCSD Lab Scan)
- [x] Get it ready for TestFlight ([Build 6](https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1511986933/testflight?section=build&subsection=testers&id=92636057-6375-4011-826f-f9df547c5f86))
- [x] Run on iPad sitting on a stand
Barcode will be moved into the camera view
App scans the barcode

This app likely will not go to public Store

**Comment by c3bryant** [comment]
Completed. Thanks @i8wu
