### ISSUE TITLE
MyChart Card UI

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#631]
An image or Text to display for the card that will take users to MyChart.

**Comment by woznaut** [comment]
![Screen Shot 2020-05-04 at 4.12.40 PM.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/9d7d878b-adc8-439c-8345-c0aecca1d6ee)
![MyUCSDChartIcon.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/7fee9f1b-e444-4bdd-a403-43a1a47a6f31)

**Comment by woznaut** [comment]
![MyUCSDChartIcon.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/e87c71e8-c62d-46a6-9a27-13e4a2715a1b)
