### ISSUE TITLE
Bug: Classes and Finals cards loading forever for some students

### ISSUE THREAD

**Issue by ally1250** [UCSD/campus-mobile#636]
Time category https://its-pro.ucsd.edu/browse/MA-78

Logged in with my account:
![image](https://user-images.githubusercontent.com/35356954/81034064-be522500-8e4a-11ea-9f79-0ebf8907ca5b.png)

Logged in with Jadie's and Ethan's account:
![image](https://user-images.githubusercontent.com/35356954/81034030-9ebafc80-8e4a-11ea-9e95-2c3a57b51270.png)

Error Message:
![image](https://user-images.githubusercontent.com/35356954/81034326-9ca56d80-8e4b-11ea-9929-3ec5d8da571c.png)

**Comment by c3bryant** [comment]
Verified on 7.2-rc, closing
