### ISSUE TITLE
Bug: Scanner Integration

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#641]
Steps to reproduce

1. Log in as staff
2. Log out
3. Tap the scanner
4. See a blank screen

Steps to reproduce:

1. Existing prod app (react native) on phone
2. Upgrade from TestFlight
3. Skip the login from onboarding
4. Tap the Sign In on scanner card
5. Gray full screen displays
6. Cannot get back to home without closing app

**Comment by g9singh** [comment]
This error was caused when removing the maps tab. Fixed and test on iOS and android. Going to test flight soon.

committed on "experimental-rc" branch: d357154b0effe747667237407616800b94d6cd02
