### ISSUE TITLE
Update Refresh Token Changes in Prod

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#647]
Time category https://its-pro.ucsd.edu/browse/MA-24

Promote the mobile-user-profile-access lambda from QA to prod

**Comment by g9singh** [comment]
Tried to promote from QA to prod but the attempt was unsuccessful. 
The error we got back was:
`{
 "errorMessage": "orchestration failed(Error: Invalid response from ECP [*IDP_URL*)"
}`
Next steps:

- [ ] Ensure that code on branch "[qa](https://sourcecode.ucsd.edu/projects/WTS/repos/mobile-authentication-service/browse)" is synced up with [MobileAuthenticationService](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/MobileAuthenticationService?tab=configuration) lambda
- [ ] Debug by redeploying MobileAuthenticationService lambda in production on a different endpoint

**Comment by c3bryant** [comment]
Closing in favor of #831
