### ISSUE TITLE
Bug: Campus Mobile Scan Barcode Not Saved

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#649]
From the campus mobile app, the scan feature does not saved barcode data in the HANA db.

**Comment by a6wu** [comment]
Need to use https://api.ucsd.edu:8243/scandata/1.0.0/scanData

**Comment by g9singh** [comment]
merged into experimental-rc branch: a5624f50e1b6a4945294be4da61045268e8acf0f
