### ISSUE TITLE
Bug: UI/UX Updates

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#650]
1. Scan code value is not updating when scanning a new code.
2. Button stays on Received

**Comment by i8wu** [comment]
Unable to reproduce on Android 5/8/2020
Steps tried:
Scan code
Submit
Scan another code
Submit
....etc

**Comment by g9singh** [comment]
can not reproduce on latest build in experimental-v2 branch

**Comment by a6wu** [comment]
Cannot reproduce
