### ISSUE TITLE
Notifications tab - momentary blank screen on reload 

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#651]
Time category https://its-pro.ucsd.edu/browse/MA-78

Low impact 
when a user pulls down to refresh Notifications list, the screen goes blank for a second or 2 on redraw

**Comment by g9singh** [comment]
merged into experimental-v2: 37a9f956cb7decd2bb90db41f56dd41f6e2e8db2

**Comment by c3bryant** [comment]
Verified on `experimental`
