### ISSUE TITLE
Scanner state freezes - unable to scan new QR codes

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#653]
Severity - High

**Case 1**
Steps to reproduce:

Hold camera up to QR code
Move camera away from QR code 
Navigate back to home - Go back to scanner
Result: Scanner still has value from previous QR code, Submit button is inactive and scanner won’t read any new codes

**Case 2**
Steps to reproduce:

Hold camera up to QR code
Hit Submit - Get “Received” message
Move camera away from QR code 
Navigate back to home - Go back to scanner
Result: Scanner still says “Received”, button is disabled, scanner not reading new QR codes

I have seen this hard crash the whole app but have not yet reproduced consistently. I'm on iOS v13.3 on an iPhoneX

**Comment by woznaut** [comment]
video 1
[IMG_9134.MP4.zip](https://github.com/UCSD/campus-mobile/files/4584100/IMG_9134.MP4.zip)

**Comment by woznaut** [comment]
video 2
[IMG_9135.MP4.zip](https://github.com/UCSD/campus-mobile/files/4584108/IMG_9135.MP4.zip)

**Comment by g9singh** [comment]
merged into experimental-v2 branch: 956956e4c89bf87d7d44e2a4d8e99dc703511cda

**Comment by c3bryant** [comment]
Please verify on TestFlight Build 51, thanks @woznaut @g9singh

**Comment by c3bryant** [comment]
This fix is also included in Build 53 and 54 (798 and 799 for Android)
