### ISSUE TITLE
Bug: Button is stuck at "Try again"

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#657]
Campus mobile app, scan feature.

Steps to reproduce:

- [ ] Simulate an API POST failure
- [ ] Button is stuck at "Try again."
- [ ] Need to log in again.

**Comment by i8wu** [comment]
So, pretty sure this has been addressed by Gagan. https://github.com/UCSD/campus-mobile/blob/50afad2f58c1a64d8e3bdbefbf16c30963e1b927/lib/core/data_providers/barcode_data_provider.dart#L76

Can't reproduce anymore, even with failing the post for the first time one purpose.

**Comment by g9singh** [comment]
can not reproduce on latest build in experimental-v2 branch

**Comment by a6wu** [comment]
Bug fixed
