### ISSUE TITLE
Bug: UCSD Lab Scan

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#660]
Tapping Scan Another brings up the scan view
The view is white and appears stuck for a few seconds
Then the camera view is active and can scan

**Comment by i8wu** [comment]
https://github.com/a6wu/QRScanLab/pull/9 Seems to address a similar issue in Android. Can someone verify before merging this?

**Comment by g9singh** [comment]
Issue still exists on iPad

**Comment by i8wu** [comment]
Unassigning from myself bc I can't reproduce.

**Comment by i8wu** [comment]
@g9singh @c3bryant Can we see if this is still an issue with the continuous scan implementation and close if no longer needed?

**Comment by c3bryant** [comment]
I am not seeing this issue on TestFlight Build 8 w/ Continuous Scan. Let's close and revisit if needed.
