### ISSUE TITLE
Bug: iOS Dark Mode

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#662]
Time category https://its-pro.ucsd.edu/browse/MA-78

Campus mobile app, scan feature.

The "Please scan a test kit" label in iOS dark mode is displayed in white color. Hard to see against a white background.

Either:
1. Disable dark mode
2. Have text be black against white on dark mode

**Comment by g9singh** [comment]
merged into experimental-v2: 377925c120a3a0889e2f0d2a0fa48014f9e54797

**Comment by c3bryant** [comment]
Verified and deployed
