### ISSUE TITLE
Bug: UCSD LabScan - error handling

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#665]
Need better user feedback if user tries to Submit a code that does not exist in the db. Currently it appears to the user that they are stuck in a Submit/Try Again loop.

if db field is null, user should get a message saying something like, "Test Kit Code does not exist."

**Comment by g9singh** [comment]
merged into master: 822cf51871c374a0dc215799fa7d3a43be86509a

**Comment by c3bryant** [comment]
On TestFlight Build 8 w/ Continuous Scan, when an invalid barcode is scanned, a message is displayed to the technician:
`Scan data with barcode <YOUR BARCODE> could not be found.`
