### ISSUE TITLE
BarcodeScanData Lambda Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#666]
HANA version for POST.

- [ ] Create a version for existing Lambda that is used by the API
- [ ] Associate this versioned Lambda with the AWS API on Prod
- [ ] Test on $latest Lambda

**Comment by ssekar14** [comment]
The APIM URL to the version 2 of the ScanData API is https://api.ucsd.edu:8243/scandata/2.0.0

Updated features :

**POST ScanData**
1. Returns 409 when scanning a duplicate barcode that exists for a different user
2. Returns 201 with the same data when scanning a duplicate barcode for the same requester
3. Returns 400 when barcode is empty string or null.

**GET ScanData**

no changes

**Comment by a6wu** [comment]
Completed
