### ISSUE TITLE
Bug: UCSD Lab Scan: Crash after 'Scan Another'

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#669]
To reproduce:

 UCSD Lab Scan TestFlight Build 6
1. Install UCSD Lab Scan
2. Scan a valid QR code, see results
3. Click 'Scan Again'
4. Lock device
5. Unlock device
6. UCSD Lab Scan frozen on QRScan/Camera view
7. Force close and restart returns the app to a working state

**Comment by g9singh** [comment]
merged into master: a5add5e6b74af4f8654d0d6c415beb5768c5c507

**Comment by c3bryant** [comment]
Verified on TestFlight Build 7 and 8
