### ISSUE TITLE
Campus Mobile App Unexpected Authentication Call

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#678]
Time category, Single Sign-On, https://its-pro.ucsd.edu/browse/MA-59
Time category, Refresh token, https://its-pro.ucsd.edu/browse/MA-24

Campus mobile app unexpectedly goes through the authentication flow on non-200 response from barcode scan API (POST method). @c3bryant  Please fill in details.

**Comment by g9singh** [comment]
addressed in pr #694

**Comment by c3bryant** [comment]
Verified and deployed
