### ISSUE TITLE
UI/UX: Auth Flow on Launch

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#680]
Time category https://its-pro.ucsd.edu/projects/MA/issues/MA-42?filter=allissues

Mobile app appears logged out on app launch

1. "Sign In" on QR Scanner card changes to "Scan Now" after a few seconds
2. If user taps "Sign In" quickly, the user goes to the Settings page to log in
3. As user types in the username/password, the app becomes logged in and the form disappears
4. And displays "You are logged in as:"

**Comment by c3bryant** [comment]
Moving to New pipeline for further review

**Comment by c3bryant** [comment]
Deployed in 7.0
