### ISSUE TITLE
Barcode Scan Value Persistent

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#682]
Time category https://its-pro.ucsd.edu/browse/MA-74

On Android, v7.0.0 updated May 8. 

Steps to reproduce:
1. Tap on Scan Now
2. Scan barcode
3. Value displays above the Submit button
4. Go back to Home
5. Tap Scan Now
6. Previous barcode value is above the Submit button

**Comment by c3bryant** [comment]
Verified and deployed
