### ISSUE TITLE
Lab Scan App: Generate QR Code

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#683]
Time category https://its-pro.ucsd.edu/browse/MA-76

1. On barcode scan from the testkit,
2. Generate a QR code that has the MRN_ID value
3. Display the QR code along with the other text data

**Comment by i8wu** [comment]
Do we still want to still display the MRN_ID as text too?

**Comment by c3bryant** [comment]
This was completed, thanks i8wu. MRN QR available in LabScan Build 8. ORD for Build 9+
