### ISSUE TITLE
Verify Push Notification Behavior

### ISSUE THREAD

**Issue by its-webtech** [UCSD/campus-mobile#693]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-60

Verify that push notification behaves as described below.

On push notification sent from the server, user will receive a push notification alert with sound (OS permitting) on the device when:
1. App is in the background
2. App is closed and not running
3. ~~App is in the foreground~~ Enhancement. Hold off for V1

**Comment by g9singh** [comment]
Test the following while user is logged in and while user is logged out in QA env:

iOS:
- [ ] Notification settings are synced upon login
- [ ] Notification settings are persistent through app launches
- [ ] Push notification to a topic subscriber is delivered within 3 seconds
- [ ] Push notification to an individual user is delivered within 3 seconds 
- [ ] Push notification received when the app has been completely closed out and not in the background 
- [ ] Push notification received when the app is in the background (not completely closed out) 

Android:
- [ ] Notification settings are synced upon login 
- [ ] Notification settings are persistent through app launches 
- [ ] Push notification to a topic subscriber is delivered within 3 seconds 
- [ ] Push notification to an individual user is delivered within 3 seconds 
- [ ] Push notification received when the app has been completely closed out and not in the background 
- [ ] Push notification received when the app is in the background (not completely closed out)

**Comment by c3bryant** [comment]
Verified. Merged into `experimental`
