### ISSUE TITLE
Basic Needs Free Food Availability Integration

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#700]
Time category: https://its-pro.ucsd.edu/browse/MA-70

### Issue Description
This issue is to document the flow process and development effort involved in Free Food Availability Integration. Include resource links for AWS, WSO2, and Lucidchart, Collab, and any supplemental documentation in comments below.

This is done when:
- [x] Flow Diagram (Lucidchart) included
- [x] API Resources included
- [x] Database Resources included
- [x] I'm going button shows up for free food events
- [x] Tapping the button increments count on server-side and change UI on button
- [x] Tapping the button again decrements the count and change UI on button
- [x] Re-launching app will show last button state

Remaining:
- [x] DynamoDB table name change (basic-needs-events -> campus-events)
- [x] Update all Lambda's to point to new table name
- [x] Add Lambda code and project resources to 'basic-needs' repo (https://sourcecode.ucsd.edu/projects/WTS/repos/basic-needs/browse)
- [x] Update documentation
- [x] Submit PR (take PR out of Draft mode)

Example repo: https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse

Example structure: 
basic-needs/src/getEventsCount
basic-needs/src/getEventsCount/index.js
basic-needs/src/getEventsCount/package.json
basic-needs/src/getEventsCount/node_modules/...

Repeat for Lambdas:
- createCampusEvent
- decrementCounter
- incrementCounter
- getMaxCount

**Comment by ally1250** [comment]
**Flow diagram**
https://app.lucidchart.com/invitations/accept/cf7fa000-f503-419b-8e39-b62600fc64c0

**API Resources** (messageId is the id of the notification message for the event)
1. Fetch the current number of students signed up for the event:
https://9tqs71by9h.execute-api.us-west-2.amazonaws.com/dev/v1/count/{messageId}
2. Fetch maximum food offerings for the event:
https://9tqs71by9h.execute-api.us-west-2.amazonaws.com/dev/v1/maxcount/{messageId}
3. Set the maximum food offerings for the event (all free food events need to specify a maximum number):
https://9tqs71by9h.execute-api.us-west-2.amazonaws.com/dev/v1/setmaxcount/{messageId}
4. Decrement the number of students signed up for the event:
https://9tqs71by9h.execute-api.us-west-2.amazonaws.com/dev/v1/decrement/{messageId}
5. Increment the number of students signed up for the event:
https://9tqs71by9h.execute-api.us-west-2.amazonaws.com/dev/v1/increment/{messageId}

**Database Resources**
DynamoDB table for basic-needs-events:
https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:selected=basic-needs-events;tab=overview
This database needs to be manually populated when adding a new free food notification in the messaging-center database.

**Collab**
TODO

**Deployment Process (QA to PROD)**
TODO

**Comment by c3bryant** [comment]
Remaining:
1. Server: Deployment to Prod (WSO2 & AWS)
2. Client: Configure Free Food Service endpoint for Prod
3. Client: Deployment to Prod

**Comment by ally1250** [comment]
Checklist:

> server:

1. Lambda source code: https://sourcecode.ucsd.edu/projects/WTS/repos/basic-needs/browse/src
2. API Gateway: https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/9tqs71by9h/resources/kyv9cr39il
3. Dynamo DB: https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:selected=campus-events;tab=overview
4. WSO2: https://api-qa.ucsd.edu/publisher/info?name=MobilePlatform-BasicNeedsEvents&version=1.0.0&provider=daw001

> client:

1. https://github.com/ally1250/campus-mobile/tree/experimental-freefood
