### ISSUE TITLE
Link to YouTube Video

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#701]
Add link to YouTube video between the COVID banner and QR Scanner.

https://www.youtube.com/watch?v=yf1ez9bVzss&feature=youtu.be

**Comment by c3bryant** [comment]
[QA mobile-app-notice-banners.json](https://ucsd-its-wts-dev.s3-us-west-1.amazonaws.com/replatform/v1/notices/mobile-app-notice-banners.json)

Notes:
- notice-banner-link analytics

Ready to deploy

![preview-ios](https://user-images.githubusercontent.com/15112294/82488050-23855780-9a94-11ea-8cca-10a006090737.png)
![preview-dest](https://user-images.githubusercontent.com/15112294/82488037-1ec0a380-9a94-11ea-87d2-ee295492a77c.png)

**Comment by c3bryant** [comment]
Deployed & verified
