### ISSUE TITLE
Use Shorter Text In Place of UUID Code

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#708]
Time category: https://its-pro.ucsd.edu/browse/MA-78

When the user scans the barcode, the UUID code displays. Use a shorter text in place of the UUID to indicate the scan was successful.

**This is done when:**
- [x] When the user successfully scans a barcode, display the text `Ready to submit` in place of the scanned UUID barcode ID

Resources:
- https://mobile.ucsd.edu/replatform/v1/qa/cardActivationControl-qr-scanner-enabled.json

**Comment by woznaut** [comment]
"Ready to submit"
