### ISSUE TITLE
Add Survey Card

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#71]
### Issue Description

Add a Survey Card to the app. The card should:
- Dynamically pull in boolean questions from an internal CMS/json feed
- Manage and ask survey questions at appropriate times (limited to a certain frequency i.e. 48 hours)
- Be dismissible in some way
- Store survey results remotely
- Store some information locally in AsyncStorage (i.e. QuestionID to not ask the same question again)

**Comment by i8wu** [comment]
Only going to be focused on non-recurring general population yes/no survey questions for Blastoise release.

**Comment by i8wu** [comment]
Possible new survey vendor, need more details on availability. @a6wu

**Comment by woznaut** [comment]
![surveycard](https://cloud.githubusercontent.com/assets/19195410/25682002/5bcbd9d0-300b-11e7-8b5d-46b6a2d004dd.png)

**Comment by woznaut** [comment]
![surveycardpressed](https://cloud.githubusercontent.com/assets/19195410/25682020/667f14d2-300b-11e7-9dfb-c1ac704a5fb2.png)
button depressed

**Comment by i8wu** [comment]
^ could the card just fade/dismiss itself after an option is chosen?

**Comment by woznaut** [comment]
thought about that. seems to me there should be a confirmation of some kind. 
Now that you mention it though, we should use the popup confirmation we've been using for the shuttle card instead

**Comment by woznaut** [comment]
something else to think about for the future is that we'll want the option to expose the question results to users to increase their engagement with campus and the app. just a bit of game-ification.
![surveyresults](https://cloud.githubusercontent.com/assets/19195410/25686333/46d39a24-3022-11e7-8e6e-28543a6e805b.png)
the popup notification could be the default for now.
note to self: consider other graphical data display types and animation.

**Comment by i8wu** [comment]
TODO: Figure out push-based survey delivery

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
