### ISSUE TITLE
Hyperlink URLs found in News/Event description

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#711]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-33

#### Summary
Many Events and some News articles now include URLs in the description and location which cannot be copied or clicked

See flutter_linkify https://github.com/UCSD/campus-mobile/blob/experimental/lib/ui/views/notifications/notifications_list_view.dart#L116

#### This is done when:
- [x] News Detail and Event Detail descriptions are hyperlinked and open in a web browser
- [x] Event Detail location is hyperlinked and open in a web browser

<img src="https://user-images.githubusercontent.com/15112294/83565896-0315be00-a4d4-11ea-90ba-fe5e6c90a659.png" width="300">

<img src="https://user-images.githubusercontent.com/15112294/83565920-0ad56280-a4d4-11ea-9f2e-0e3113b3d084.png" width="300">

@Atreto76 assigned.

**Comment by a6wu** [comment]
Do we want to make the hyperlinks live? Are the links causing a problem?

**Comment by c3bryant** [comment]
Feature enhancement
Many Events and some News articles now include URLs in the description which cannot be copied or clicked

![image](https://user-images.githubusercontent.com/15112294/83565896-0315be00-a4d4-11ea-90ba-fe5e6c90a659.png)

![image](https://user-images.githubusercontent.com/15112294/83565920-0ad56280-a4d4-11ea-9f2e-0e3113b3d084.png)

**Comment by Atreto76** [comment]
A bug with the flutter_linkify package was detected. The issue has been found and there a few options to remedy it.

The issue has do with the regular expression used in locating links in the string provided. It does not account for the "\r" escape character and that causes the regular expression to not detect any links found after the character is written.

Solution 1: Contact persons responsible for the events API and remove the "\r" escape characters as they are not needed (just newlines "\n" will suffice).
Solution 2: Remove all "\r" escape characters ourselves when the data is returned.
Solution 3: Figure out a fix for the regular expression in the flutter_linkify package ourselves or wait for developer (that might take awhile; least time-viable option).

Regardless of which way we go, I'll be creating an issue on the [flutter_linkify GitHub page](https://github.com/Cretezy/flutter_linkify) with my findings anyway so no one else runs into the same issue.

**Comment by c3bryant** [comment]
@Atreto76 Mock Events endpoints to test with below (\r removed). Please verify all are functional. Hyperlinks included in `location` and `description`

  - 0 Events: https://ucsd-mobile-dev.s3-us-west-1.amazonaws.com/mock-apis/events/events-test-0.json
  - 2 Events: https://ucsd-mobile-dev.s3-us-west-1.amazonaws.com/mock-apis/events/events-test-2.json
  - 4 Events: https://ucsd-mobile-dev.s3-us-west-1.amazonaws.com/mock-apis/events/events-test-4.json
  - 10 Events: https://ucsd-mobile-dev.s3-us-west-1.amazonaws.com/mock-apis/events/events-test-10.json

**Comment by Atreto76** [comment]
@c3bryant All mock event endpoint tests successful. I created a pull request with the code that works for \r-less strings for now #765
