### ISSUE TITLE
Multiple loading spinners on Notifications tab

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#713]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-34

This is done when:
- [x] A single loading spinner renders for the user when in-app messages are being fetched
- [x] Loading spinner renders as expected in Light and Dark mode

**Comment by sramcode** [comment]
![IMG_2753.png](https://images.zenhubusercontent.com/5ed55224796b708b6bb1cbd1/d642a2b0-ff11-4744-aec1-a298d8393e94)![IMG_2754.png](https://images.zenhubusercontent.com/5ed55224796b708b6bb1cbd1/9e87a0c2-f07e-4ba0-8bd6-864829c9e4fe)

The loading spinner in the notifications tab is clearly visible in both light and dark mode, but there is a subtle ring/shadow surrounding it and I am not sure if this still is "transparent".

**Comment by sramcode** [comment]
![IMG_2783.PNG](https://images.zenhubusercontent.com/5ed55224796b708b6bb1cbd1/506893da-6981-421e-9eb6-1ce069220ccc)![IMG_2782.PNG](https://images.zenhubusercontent.com/5ed55224796b708b6bb1cbd1/a6741e22-fd43-4d3e-b163-bb5d55fdd986)

I now see two loading spinners in the notifications tab in both light and dark mode. The transparent spinner now exists and is clearly visible. The spinner was a little cut off and not fully on the screen, so I added some padding (not seen in screenshots).
