### ISSUE TITLE
Notification tab loading text is taking up space below the top nav

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#714]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-34

- [x] Loading indicator and label slides Notification messages down, as if the user were pulling down to refresh
- [x] When user messages are done loading, slide the user's messages up, while fading out the loading indicator and label

**Comment by g9singh** [comment]
resolved in pr #720

**Comment by c3bryant** [comment]
Verified. Merged into `experimental`
