### ISSUE TITLE
Reddit Bot Teams Integration

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#716]
Time category: https://its-pro.ucsd.edu/browse/SVCOPS-407

### Issue Description
Transition the Reddit Bot integration from Slack to Teams
[https://sourcecode.ucsd.edu/projects/WTS/repos/reddit-bot/browse](https://sourcecode.ucsd.edu/projects/WTS/repos/reddit-bot/browse)

**Comment by c3bryant** [comment]
@sssaiya Follow-ups from the initial test on Jun 1 @ 8:30AM
- Debug the webhook and lambda/trigger mechanism failure
- Apply necessary fixes
- Schedule a re-test

**Comment by sssaiya** [comment]
There were a few problems
1 -  The regex was not whitespace insensitive (Fixed now)
2 - The Lambda was timing out in a lot of occurrences (Timeout increased from 3s to 10s)
There is scope for improvement in this, 
 - If it is worth the time we could find more keywords that we want to watch out for
- We could add functionality that posts a message such as "No new posts found" Just so we know that the lambda is triggering even though theres no new posts on reddit

**Comment by c3bryant** [comment]
Thanks for this update @sssaiya 

Update the internal repo from the Reddit-bot-trigger Lambda and we can close this out.

**Comment by sssaiya** [comment]
I have updated the internal Repo with most recent code from the lambda, We can close this ticket.
