### ISSUE TITLE
Integrate MyChart

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#758]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-79

### Issue Description

Integrate MyChart via SDK

### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

### Additional Information

* React Native version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
* Operating System (macOS, Linux, or Windows?): [FILL THIS OUT]

This is done when:

- [x] MyChart push notification received on iOS
- [x] MyChart push notification received on Android
- [x] Screen #1 and #2 implemented from https://xd.adobe.com/view/0fa4c630-7662-4b40-b994-93e15804ddb6-5af7/

**Comment by c3bryant** [comment]
- Successful push notification test on iOS and Android with Jeff on 12/11/2020
- Project source: https://sourcecode.ucsd.edu/projects/WTS/repos/campus-mobile-mychart
- Project branch: mychart (default)
- Old branches tagged and cleaned up
- Remaining TODO's to be logged in separate issues
