### ISSUE TITLE
Implement Availability Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#759]
ITS-Pro Time Category: https://its-pro.ucsd.edu/browse/MA-83

This is done when:
- [x] Availability card displays for all users after app install on the Home view as shown in the adobe XD prototype below
- [x] Availability card displays all available locations by default
- [x] App users can scroll horizontally between enabled locations
- [x] App users can add and remove locations from the Manage Locations button view
- [x] App users can reorder locations from the Manage Locations button view

To activate the current Availability card on the `experimental` branch:
1. Uncomment line https://github.com/UCSD/campus-mobile/blob/experimental/lib/core/data_providers/cards_data_provider.dart#L29
2. Uncomment lines https://github.com/UCSD/campus-mobile/blob/experimental/lib/ui/views/home/home.dart#L88-L90

**Comment by woznaut** [comment]
link to screens: https://xd.adobe.com/view/e210ea76-23f5-48e0-9c82-b4dbaeeb401f-b743/

I have an interactive prototype as well that better illustrates the functionality, just ping me for an invite.
