### ISSUE TITLE
MyStudentProfilev1 returns incorrect response

### ISSUE THREAD

**Issue by p8gonzal** [UCSD/campus-mobile#767]
**Issue Description**
Calling authorizedFetch() on https://api-qa.ucsd.edu:8243/student/my/v1/profile does not return any information pertaining to the student. The response received is: 
 {"errorType":"object","errorMessage":"[object Object]","trace":[]}

**This is done when\:**

- [x] Returns the profile of a student: College Current Current Primary Major Code Current Primary Major Department Code Current Primary Major Department Name Current Primary Major Division Current Primary Major Division ID Current Primary Major Name Current Primary Major Short Name Is Athlete Current Flag Student Level Student Level ID

@c3bryant added a mock endpoint QA \:
https://ucsd-mobile-dev.s3-us-west-1.amazonaws.com/mock-apis/academic/MyStudentProfile_mock.json

**Comment by c3bryant** [comment]
Verified, thanks Alex
