### ISSUE TITLE
Add static shuttle information

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#77]
### Issue Description

A few scenarios exist where we are unable to present shuttle information to the user:
- User disallows us to access their location
- Shuttle feed is down/having difficulties

Investigate adding static shuttle information to alleviate these issues

**Comment by i8wu** [comment]
#34 for reference

**Comment by i8wu** [comment]
Branch static-shuttle-demo has an implementation, but shouldn't be merged in until we actually get the static shuttle schedule from Transportation.

**Comment by i8wu** [comment]
Waiting on transportation so removing for milestone for now.

**Comment by c3bryant** [comment]
Static shuttle data does not exist in a consumable format. This issue has been added to our feature request board if said data should become available down the road.
