### ISSUE TITLE
QA: ScanData API

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#773]
Time category: https://its-pro.ucsd.edu/browse/MA-78

ScanData API V1 & V2 in QA are not working. Investigate and resolve

This is done when:
- [ ] ScanData API in QA has been synced from Prod and is operational

**Comment by c3bryant** [comment]
[ScanData QA API](https://api-qa.ucsd.edu/publisher/info?name=ScanDataAPI&version=2.0.0&provider=ssekar) exists, but points to AWS Prod, resulting in `Error 401: Unauthorized`

RFI - How to proceed in regard to Campus VPC and SAP HANA security groups utilized by [postScanData](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/postScanData?tab=configuration), [getScanData](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/getScanData?tab=configuration) Lambda's on AWS Prod for AWS QA env

**Comment by a6wu** [comment]
QA version of ScanData at the DB level is in the works.
