### ISSUE TITLE
Survey Notice Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#774]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-85

Add a notice survey which links out to Qualtrics.

This is done when:
UI/UX
- [ ] A survey banner image has been provided (1242x440)
- [ ] A survey link has been provided

Dev
- [ ] Notices json has been updated and verified in QA
- [ ] Notices json has been updated and verified in PROD

**Comment by woznaut** [comment]
prototype link: https://xd.adobe.com/view/ad9082c8-38ed-4ee7-b4f2-c12d99b62bc4-f8c3/

interactive version is available as well
