### ISSUE TITLE
CMS Web Page Survey with SSO

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#776]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-85

A student visits https://mobile.ucsd.edu/cards/student_survey.html.
Student logs in to SSO with their AD account.
The web page saves to the browser local storage the student PID.
Student reviews the survey content and selects from predefined choices, e.g. Yes or No.
The web page POST to an API, sending along the student PID.

**Comment by c3bryant** [comment]
Integrate eForm with Survey WebCard #1011 slated for release in 7.5
