### ISSUE TITLE
Update Occuspace API

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#781]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-83

Update Occuspace API to use the latest data format.

This is done when:

- [x] V2 of the API is created in WSO2
- [x] V2 of the API is configured in AWS API Gateway
- [x] AWS Lambda updated to accept the latest data format
- [x] Mobile client successfully consumes the API

**Comment by sssaiya** [comment]
Completed in #934 
No changes were made on AWS Lambda, but mobile client can successfully consume the updated api data.
