### ISSUE TITLE
Create Debug APK of Prod Release

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#782]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-69

'Create a debug APK of the production release for security scanning.

This is done when:

- [x] A process is defined and implemented for creating a debug APK for each prod release
- [x] The APK is save to a shared folderd

**Comment by c3bryant** [comment]
- Shared folder created which will contain debug APK's for all future releases.
- Added #790 to automate this effort in the CI pipeline for each release.
