### ISSUE TITLE
Implement Bluetooth Scanning in Foreground

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#785]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-86

This is done when:

- [x] App scans and detects surround bluetooth devices
- [x] App identifies count of bluetooth devices
- [x] App logs scanned bluetooth IDs to device
- [x] On app foreground event, make a scan and log every 15 minutes if app is being used
- [x] GPS location changes at least 200 meters, make a scan and log
- [x] Logs are stored in secure storage

**Comment by p8gonzal** [comment]
Items 1 -3 are currently checked off. Periodic scans wip.

**Comment by gmihir** [comment]
PR #811 also includes an application-wide update to the location package (issue #808). These issues should be linked. This is done in order to upgrade the entire package in one PR to minimize version conflicts.

**Comment by p8gonzal** [comment]
Logs are stored in secure storage. Testing location based scan trigger.
