### ISSUE TITLE
Implement Bluetooth Key Rotation

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#788]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-86

This is done when:

- [x] Document iPhones and Android devices that supports BT LE
- [x] Bluetooth key broadcasted by the app is rotated every 24 hours
- [x] Bluetooth key is prefix with "ucsdapp"

**Comment by lukedutta9** [comment]
This doc lists out all the devices that support beacon transmission. Information for iOS devices is pulled from Apple's site: [https://support.apple.com/en-us/HT202880](url). Information for Android devices is pulled from the Android Beacon Libary: [https://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html](url).
