### ISSUE TITLE
UI/UX Flow for Enabling/Disabling Bluetooth/GPS Feature

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#789]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-42?filter=allissues

This is done when:

- [x] The user flow for enabling/disabling Bluetooth/GPS within the app is mocked
- [x] The supporting content presented and reviewed by the user is drafted

**Comment by woznaut** [comment]
Alert window copy below:

**“UCSD Mobile” Would Like to Use Bluetooth**
This will allow “UCSD Mobile” to find and connect to Bluetooth devices. This app may also use Bluetooth to know when you’re nearby.”

Don’t Allow - Allow When App is in Use - Always Allow


**“UCSD Mobile” Would Like to Use GPS**
This will allow “UCSD Mobile” to identify your location via GPS.

Don’t Allow - Allow When App is in Use - Always Allow

**Comment by woznaut** [comment]
alert style/language can be found here: https://xd.adobe.com/view/013e92df-116c-4452-801c-6de5808f78e6-546d/

Thinking these alerts would appear after the user has entered credentials on splash screen. If user chooses to skip, alerts would appear on subsequent load. Thoughts?
