### ISSUE TITLE
Enable all cards to work without GPS location

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#79]
### Issue Description

Make the app fully functional without needing location permissions

How things are setup now:

Location Required
- Shuttle
- Nearby
- Dining

Location Not Required
- Weather
- Surf
- Events
- News

Ways to accomplish this:
1. For the Shuttle card, when location permissions are disabled, show static data of the general shuttle route times/eta's (this is currently in the works for when the Shuttle API goes down like it did today)
2. For the Nearby card, possibly rename the card entirely or just for users with permissions disabled. List locations not by nearest but based on a simple ranking system (most prominent first, i.e. Geisel Library, Price Center, etc)
3. For the Dining card - disable the distance in miles to destination; order results not by closest but by alphanumeric

The Nearby and Dining cards (and ultimately the Shuttle card) have buttons that link to 'walking directions' which take you out to your native mapping application (Apple Maps, Google Maps) and they can handle the permissions from there

See [#63](https://github.com/UCSD/now-mobile/issues/63) for the full discussion to this point

**Comment by jpknoll** [comment]
I'd agree with a good fallback functionality. The cards themselves should handle how they want to degrade.

**Comment by i8wu** [comment]
- Nearby - Card has been removed
- Shuttle - Displays error message on card. No static shuttle schedule currently available #77 
- Dining - Defaults to alphabetic

Issue okay to close? @c3bryant

**Comment by c3bryant** [comment]
yes, thanks Ivan
