### ISSUE TITLE
Shuttle Routes JSON incomplete

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#80]
`app/json/shuttle_routes_master.json`
Does not contain all shuttle routes. Is missing Sanford Consortium, City Shuttle, East Campus.

This is probably because SC and CS is missing from, not sure about East Campus. `http://api.syncromatics.com/portal/routes/?api-key=`

We probably need to contact Synchromatics/Transportation office to figure out why.

**Comment by a6wu** [comment]
I can help forward this to our transportation contact at UCSD working with syncromatics .

**Comment by i8wu** [comment]
@a6wu did syncromatics ever reply?

**Comment by i8wu** [comment]
This was due to improper configuration on syncromatics admin console. Should be fixed.
