### ISSUE TITLE
Upgrade Location Package

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#808]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-86

This is done when:
- [x] The [`location`](https://pub.dev/packages/location/versions/3.0.2) package has been upgraded to v3.0.2
- [x] Breaking changes from v2->v3 have been resolved
- [x] Maps, Dining, and Bluetooth/GPS are able to access location as expected

**Comment by gmihir** [comment]
work is done, in PR #811

**Comment by c3bryant** [comment]
Verified, thanks @gmihir
