### ISSUE TITLE
Update campus logo

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#812]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-42

This is done when:
- [ ] An updated UC San Diego branded logo with underline has been provided ([current](https://github.com/UCSD/campus-mobile/blob/experimental/assets/images/UCSanDiegoLogo-nav.png))
- [ ] The updated logo has been incorporated into `experimental`

**Comment by woznaut** [comment]
![ucsdLogo_wht_underlined.png](https://images.zenhubusercontent.com/5a68da944b5806bc2bc42863/ab4eb9c2-b96e-4bc3-b4cb-bc16a8a23d9e)

**Comment by woznaut** [comment]
note that this logo needs to be updated both on the app header and the splash screen

**Comment by lukedutta9** [comment]
Just updated the app logo on splash screen and app header. Tested on Android Emulator (Pixel XL API 29).

Onboarding Screen
![image.png](https://images.zenhubusercontent.com/5ed06a8f9b11fd221d012097/f29e6830-7681-417a-8601-f4ee0cc4cf4c)

Onboarding Login
![image.png](https://images.zenhubusercontent.com/5ed06a8f9b11fd221d012097/15b052af-1715-49c8-8259-ee4c1fe48aa9)

App Header
![image.png](https://images.zenhubusercontent.com/5ed06a8f9b11fd221d012097/4a61d115-f70f-467e-aa08-a11c6461534a)
