### ISSUE TITLE
Error fetching notification when logged in

### ISSUE THREAD

**Issue by ally1250** [UCSD/campus-mobile#821]
**Notification Center error message:** 
![image](https://user-images.githubusercontent.com/35356954/87101433-f20f4980-c203-11ea-9e65-1456d364ce7e.png)

**Cause:**
The response of the myMessages/message API in qa is missing the audience field.

**Current incorrect response format:**
`{
  "messages": [
    {
      "sender": "a6wu@ucsd.edu",
      "message": {
        "data": {},
        "message": "Test",
        "title": "Test"
      },
      "messageId": "eaohyv8kcavql9j",
      "timestamp": 1594062640422
    },
    {
      "sender": "g1singh@ucsd.edu",
      "message": {
        "title": "Direct TEST 25",
        "message": "Direct message test 25"
      },
      "messageId": "a38k9ti7qzj",
      "timestamp": 1588658436703
    },
    {
      "sender": "c3bryant@ucsd.edu",
      "message": {
        "data": {},
        "title": "[TEST] This is a test message only",
        "message": "This is a test message only -rp106"
      },
      "messageId": "a38k9ti07tv",
      "timestamp": 1588658085283
    }
  ],
  "next": 1593632581781
}`

**Expected response format with the audience field** (taken from [MyMessages/topics](https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/bvgjvzaakl/resources/azfctr/methods/GET) aws API):
`{
  "messages": [
    {
      "sender": "g1singh@ucsd.edu",
      "message": {
        "data": {},
        "message": "servings of pastries available [Test]",
        "title": "Sandwiches [Test]"
      },
      "messageId": "uzjmm7kcdznnng",
      "audience": {
        "topics": [
          "freeFood"
        ]
      },
      "timestamp": 1594250620539
    },
    {
      "sender": "daw001@ucsd.edu",
      "message": {
        "data": {},
        "message": "test",
        "title": "test-freefood"
      },
      "messageId": "15lduj7kcdyvhz3",
      "audience": {
        "topics": [
          "freeFood"
        ]
      },
      "timestamp": 1594249306814
    }
  ]
}`

**This is done when:**
The response format of notifications matches the format above.

**Comment by c3bryant** [comment]
Verified in #764
