### ISSUE TITLE
Implement 2D Matrix Barcode Support

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#823]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The campus mobile app is able to scan 2D matrix barcode
- [x] The scanner feature is tested on smaller and smaller barcode sizes, until failure

**Comment by gmihir** [comment]
2d matrix barcode is already supported, and scans.

size threshold for scanning:
- 460x508 px for iPhone XS (roughly 65% of the scanner view)
- also works all the way down to 200x220 px when you add a slight upward movement after scanning (not sure why this happens)

**Comment by a6wu** [comment]
Moving to Firebase ML kit.
