### ISSUE TITLE
Extract UCPath Employee ID and Preferred Name from JWT

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#825]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-89

This is complete when:

- [x] The mobile auth service returns the UCPath employee ID and preferred name, extracted from the JWT

**Comment by c3bryant** [comment]
Done in QA

Added fields:
- employee id (`emplid`)
- preferred name (`name`)

Branch: [qa](https://sourcecode.ucsd.edu/projects/WTS/repos/mobile-authentication-service/compare/commits?sourceBranch=refs%2Fheads%2Fqa&targetBranch=refs%2Fheads%2Fmaster)
Tag: [v1.2](https://sourcecode.ucsd.edu/projects/WTS/repos/mobile-authentication-service/browse?at=refs%2Ftags%2Fv1.2)
API: https://3hepzvdimd.execute-api.us-west-2.amazonaws.com/dev/v1.2/access-profile
Lambda: [MobileAuthenticationService:v3](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/MobileAuthenticationService/aliases/v3?tab=configuration)

**Comment by c3bryant** [comment]
@a6wu sending this one your way. These fields were added primarily for Staff ID card use, which is now handled by the MyStaffProfile API and corresponding webapp. We can proceed with the deployment or close this out to be revisited at a later date.

**Comment by a6wu** [comment]
We will use the API.
