### ISSUE TITLE
Default Card List per User Affiliation

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#834]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-80

This is complete when:

- [x] On app launch, the app sends the user affiliations to an API
- [x] The API returns the list of cards available to the user

**Comment by i8wu** [comment]
@gmihir, @a6wu updated the visitor(logged out) and staff json to include MyChart and Scanner

**Comment by a6wu** [comment]
Deployed to AWS Prod, https://xn9j5n5nph.execute-api.us-west-2.amazonaws.com/prod/defaultcards?ucsdaffiliation=U

**Comment by c3bryant** [comment]
Verified on 7.2.6 - phased rollout underway
