### ISSUE TITLE
Student Survey Web Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#840]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-85

This is complete when:

- [ ] ~~Only when a student is logged in, the app displays a link to the student survey at https://ucsd.co1.qualtrics.com/jfe/form/SV_4O3FqInkiyS1qsJ~~

**Comment by a6wu** [comment]
prototype link: https://xd.adobe.com/view/ad9082c8-38ed-4ee7-b4f2-c12d99b62bc4-f8c3/

**Comment by c3bryant** [comment]
Notes:
- Survey Card slated to deploy (dormant) in 7.2.15
- Survey Card functionality update required before enabling. Outlined in #1011
