### ISSUE TITLE
Notifications Settings State Persistence Issue

### ISSUE THREAD

**Issue by evelynnelee** [UCSD/campus-mobile#841]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-60

When closing and restarting the app, all the notifications are turned off and the user will have to go into the Notification's Settings to manually turn them back on.

**Comment by i8wu** [comment]
Unable to reproduce on Pixel 2 with latest experimental branch

**Comment by i8wu** [comment]
Actually, I'm able to reproduce. 
_loadSavedUserProfile() in user_data_provider.dart is unsubscribing from all topics on app start.
Looks like fetchUserProfile() has logic to add to override subscribedTopics everytime. Is this intended? We may be able to add a hook there to do the actual subscription if it's on purpose.

**Comment by i8wu** [comment]
Sometimes on android the in app messages are actually unsubscribed from even though the toggle state is on. Toggling it off makes in app messages for that topic to show up...still investigating
