### ISSUE TITLE
Hidden personalized cards reactivate after app restart

### ISSUE THREAD

**Issue by sramcode** [UCSD/campus-mobile#848]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-34

On complete closure and reopening of the app, the finals, classes, and student ID cards show up even if they were hidden by the user.

This is done when:
- [x] Personalized cards stay hidden after the user completely closes and reopens the app

- [x] [PR 1291 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B2E94B57E-BCFC-4793-8E54-43784EE52704%7D&file=PR-1291-Test-Plan-7.8.0-QA-1316.xlsx&action=default&mobileredirect=true) PASS on iOS (@evelynnelee)
- [x] [PR 1291 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B2E94B57E-BCFC-4793-8E54-43784EE52704%7D&file=PR-1291-Test-Plan-7.8.0-QA-1316.xlsx&action=default&mobileredirect=true) PASS on Android (@lukedutta9)

**Comment by p8gonzal** [comment]
Progress:
Debugged and found issue. Persistent data is overwritten before sign-in completes.

Current Fix:
Commented out all other writes to HiveBox -> currently personalized cards stay hidden after the user completely closes and reopens the app

Issues:
Student cards are toggled off as default. 
Staff cards states are not preserved.

Next steps:
Explore a possible restructure for state re-instantiation.
Maybe save to a user data api?

**Comment by lukedutta9** [comment]
Android testing all PASS
