### ISSUE TITLE
Home View jumps

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#85]
When the app starts up most things load pretty quickly, but if you start scrolling down before ShuttleStop loads..and ShuttleStop loads in, it will push the components down and you'll lose focus of what you were looking at or misclick.

Possible fix, scroll view by the height of loaded components?

**Comment by c3bryant** [comment]
Sounds good, if we can get it working reliably well

ScrollView has the following props that should be able to get us close:
onContentSizeChange 
onScroll
scrollEventThrottle

View also has an onLayout prop that could come in handy

Other ideas discussed a while back:
- Animate anything that would expand or contract in the home view
- Have a set height for each home view component (this was proven to not be ideal, even moreso now that the app is much more dynamic than it used to be)

**Comment by i8wu** [comment]
Possible solutions:
-Have set heights for dynamic cards using [slider cards](https://github.com/LIU9293/react-native-cards-slider)
-Lazy load and not render content until everything is loaded
-Redesign dynamic sized cards

**Comment by i8wu** [comment]
Need to test if this is still an issue for March release.

**Comment by c3bryant** [comment]
With the redesign of the shuttle card and other adjustments made this hasn't been as much of an issue, but let's keep this in mind as we design and implement new cards
