### ISSUE TITLE
Update Barcode Confirmation UI

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#868]
Revisit implementation of additional cues for successful scan.

**Comment by woznaut** [comment]
adding a green checkmark icon (check_circle from Google Icons) and "Scan Successful" message will better convey that scan worked. Timestamp might be a nice addition as well but it optional depending on level of effort.

![ScanSuccess](https://user-images.githubusercontent.com/19195410/88968643-759ce300-d264-11ea-9a5f-45501276a16c.PNG)

**Comment by kevdesilva01** [comment]
![IMG_6625.PNG](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/488290b2-8de5-43e8-b3ad-ac46b36e8995)![IMG_6626.PNG](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/ae2363cb-b02e-44d2-a9ee-c996cc06d410)![IMG_6627.PNG](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/5680b195-a016-47b5-8dc0-56faa5f30cbf)

**Comment by c3bryant** [comment]
Closing in favor of #930
