### ISSUE TITLE
Verify Staff ID Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#877]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-89

This is complete when the following have been verified:

- [x] The staff ID card works in QA, with https://api-qa.ucsd.edu
- [x] The user's "personal" access token is passed from the mobile app to the Staff ID WebCard

Prod is throwing a 403 error when calling the API.

**Comment by c3bryant** [comment]
Resolved in QA
Ticket submitted for deployment to Prod (CS0200577)
