### ISSUE TITLE
Basic Needs Free Food Fix

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#882]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-70

- [ ] This is complete when each item in the following checklist is done, https://go.ucsd.edu/39ZsJyr

**Comment by ally1250** [comment]
**QA and Prod comparison:**

**notify.js:**
- line11: add
`this.state = {servings: '' };`
- line 18: add
`this.updateServings = this.updateServings.bind(this);`
- line 33: replace with
`url: 'https://api-qa.ucsd.edu:8243/mp-basic-needs/1.0.0/create-event',`
- line 37: replace with
`"freeFood"`
- line 43: replace with
`    "data": {}
    },
    "servings": this.state.servings`
- line 51: add
`if (data.statusCode != 200) {
  f = '<div class="alert alert-warning">Could not send the message. Please contact <a href="mailto:mobile@ucsd.edu">mobile@ucsd.edu</a>.</div>';
}`
- line 62: replace with
`f = '<div class="alert alert-warning">You are not allowed to send notifications. Please contact <a href="mailto:mobile@ucsd.edu">mobile@ucsd.edu</a>.</div>';`
- line 78: add
`updateServings(e) {
    this.setState({ servings: e.target.value });
}`
- line 107: add
```
<div className="form-group">
  <label htmlFor="servings">Servings</label>
  <input type="text" className="form-control" id="servings" name="msg_servings" placeholder="50" onChange={this.updateServings} />
</div>
```

**notify.html**
- line 39 & 40: replace with
```
<link rel="stylesheet" href="https://cdn.ucsd.edu/cms/decorator-4.5/styles/bootstrap.css" />
<link rel="stylesheet" href="https://cdn.ucsd.edu/cms/decorator-4.5/styles/base-min.css" />
```
- line 41: add
`<link href="../_resources/css/themes/white.css" media="all" rel="stylesheet" type="text/css"/>`
- line 60: replace with
`<script src="https://cdn.ucsd.edu/cms/decorator-4.5/scripts/modernizr.js"></script>`
- line 80: add
```
<script src="https://use.typekit.net/zqx2vjc.js"></script>
<script>try{Typekit.load();}catch(e){}</script>
```
- lines 83 - 108: replace with
```
<header class="layout-header" role="banner">
    <a class="sr-only" href="#maincontent">Skip to main content</a>
    <div id="uc-emergency"></div>
    <section aria-label="Logout" class="layout-login" role="complementary">
        <div class="layout-container"></div>
    </section>
    <!-- title section -->
    <section aria-label="Site name and Mobile Nav" class="layout-title">
        <div class="layout-container">
            <button class="btn-nav">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="title-header" href="/">
              Basic Needs
            </a>
            <a class="title-header title-header-short" href="/">
              Basic Needs
            </a>
            <a class="title-logo" href="http://www.ucsd.edu">UC San Diego</a>
        </div>
    </section>
</header>
<nav class="navdrawer-container layout-navbar">
    <div class="layout-container">
        <div class="search" role="search">
            <button class="search-toggle btn-default">
                <span class="glyphicon glyphicon-search"></span>
                <span class="caret"></span>
            </button>
            <div class="search-content">
```
- lines 115-122: delete
- lines 141,142: delete
- lines 155 - 512: delete
- line 512: add lines 134-247 in qa
- line 539: add
`</article>`
- lines 561-591 replace with
```
        <section aria-label="Sidebar" class="col-xs-3 main-section" role="complementary">
            <article aria-label="Logo" id="site-logo" role="complementary">
                <logo/>
            </article>
            <article aria-label="Sidebar Nav" class="main-content-nav" role="navigation">
                <h2>
                    Basic Needs
                </h2>
                <ul class="navbar-list">
                    <li class="active">
                        Free Food
                    </li>
                </ul>
            </article>
            <custom/>
        </section>
    </div>
</main>
<footer class="layout-footer">
```
- lines 598 - 629 replace with lines 329 - 353 in qa
- lines 646 - 654: replace with
`<script src="https://cdn.ucsd.edu/cms/decorator-4.5/scripts/decorator.js" type="text/javascript"></script>`
