### ISSUE TITLE
Card Updates on Home View

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#885]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-97

The following should be completed as a set. This is complete when:

- [x] The covid banner on the home view is removed
- [ ] ~~The Student Info and Staff Info card default order is at the top of the card list~~

**Comment by c3bryant** [comment]
Student - top cards order
1. Notice banners (none enabled)
2. Scanner card (disabled)
3. MyStudentChart
4. Student Info (renamed to COVID-19 Info)
5. Remaining authenticated cards (Finals, Classes, Student ID)

Staff - top cards order
1. Notice banners (none enabled)
2. Scanner card (disabled)
3. Staff Info (renamed to COVID-19 Info)
4. Remaining authenticated cards (Staff ID)

Completed on 7.2.6
