### ISSUE TITLE
Change "MyStudentChart" to "MyChart"

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#903]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-79

This is complete when:

- [ ] The cards.json is updated to use "MyChart"
- [ ] The project code data provider uses "MyChart"
- [ ] The card title on the Home view uses "MyChart"

**Comment by gmihir** [comment]
Changing title to MyUCSDChart instead of MyChart.

**Comment by gmihir** [comment]
Completed on feature/mychart branch (I think it's better to make it one PR with the rest of MyChart). Not sure what is meant by the project code data provider.

**Comment by c3bryant** [comment]
Hi @gmihir,
When time allows, please also also incorporate your changes on the campus-mobile repo here and submit a PR.

The project code data provider I believe is referring to the four instances of 'MyStudentChart' found in cards_data_provider.dart.

**Comment by gmihir** [comment]
PR submitted, needs slight rename in Default Cards JSONs to function (change "MyStudentChart" to "MyUCSDChart" in all cards that enable the card).

**Comment by c3bryant** [comment]
Closing in favor of #943
