### ISSUE TITLE
HiveError when restarting app

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#904]
Time Tracking: MA-34

> [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 34. Did you forget to register an adapter?

Suggested fix:
Move Hive.registerAdapter functions from providers into main.dart

Might be related to:
https://github.com/UCSD/campus-mobile/issues/826

**Comment by g9singh** [comment]
Pr submitted from: g9singh:bugs/904-hive-error
