### ISSUE TITLE
Fix Android Push Notification/In-App Message

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#908]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-60

This is complete when:

- [x] Android receives a push notification and in-app message for "freeFood" topic

The Android build was logging the following:

E/FlutterFcmService(20682): Fatal: failed to find callback
E/FlutterFcmService(20682): Fatal: failed to find callback
E/FlutterFcmService(20682): Fatal: failed to find callback

**Comment by lukedutta9** [comment]
The "failed to find callback" error is related to background message handling. However, we don't do any background message handling so these errors are safe to ignore.

**Comment by c3bryant** [comment]
Included in 7.2.7
