### ISSUE TITLE
HTML entities on news card show up as text instead of reserved character

### ISSUE THREAD

**Issue by sssaiya** [UCSD/campus-mobile#921]
![Screenshot_20200827-210554](https://user-images.githubusercontent.com/29939574/91464127-d93d1f00-e8a9-11ea-9855-06c325526382.jpg)

When fixed, entities like &Amp; and &Apos; should be displayed as their associated reserved characters 
ie: & (ampersand) or ' (single quote)

**Comment by c3bryant** [comment]
Tested and verified in QA. Ready to deploy.

**Comment by c3bryant** [comment]
Verified in Prod
