### ISSUE TITLE
Add Photo to Staff ID Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#933]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-89

This is complete when:

- [x] Staff ID card integrates the "Photo" attribute from the JSON call from https://api-qa.ucsd.edu/store/apis/info?name=MyStaffProfile&version=v1&provider=a6wu#/default/get_profile
- [x] The photo URL is https://hollerith.ucsd.edu/emp-image/[Photo value]", e.g. https://hollerith.ucsd.edu/emp-image/sLppoe.jpg
- [x] The photo displays for the Staff ID card
- [x] If photo does not exist, then keep the generic silhouette icon

- [ ] [PR 1934 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1934-Test-Plan-7.25.0-QA-2511.xlsx?web=1) ~~PASS~~ failed on iOS
- [x] [PR 1934 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1934-Test-Plan-7.25.0-QA-2512.xlsx?web=1) PASS on Android

**Comment by gmihir** [comment]
Unsure where "Identity_Photo_File" field is located, GET request from https://api-qa.ucsd.edu:8243/staff/my/v1/profile returns a field named "Photo" which is null for me. Currently, implementation is complete assuming this is the correct field. Otherwise, need to add another ajax for the API this uses.

**Comment by a6wu** [comment]
Need authoritative photo source.

**Comment by c3bryant** [comment]
Failed in testing. Reason: Staff photos are no longer accessible outside of campus VPN.

**Comment by c3bryant** [comment]
Closing due to lack of progress. Let's revisit in the future.
