### ISSUE TITLE
Verify Scandit Demo Settings and Mobile Scan Settings

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#937]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

The mobile web scan settings mirrors the Scandit web demo settings
The mobile web scan is consistent with the Scandit web demo scan
One of the mobile web scan settings have Code 128, QR, DataMatrix, and color inversion set

Question: From the websdk.scandit.com demo, does "Use Extended Symbol Counts" affect speed?

**Comment by gmihir** [comment]
Verified current version in Prod with Scandit Web SDK settings by running diff command on settings shown in console. Identical except for a reduced scan area, which we found helped performance.
![image.png](https://images.zenhubusercontent.com/5ecf51f81b04ffcb6094acce/bf04c3d3-f75f-4713-93da-8a9812627158)
