### ISSUE TITLE
Open tool-tip when user clicks a map search result

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#94]
On the new Map Search card, after the user submits a search query, have the Name/Description/Directions bubble automatically show up above the Marker without the user having to physically click on the marker location

**Comment by i8wu** [comment]
Bug with react-native-maps not allowing this to be possible right now...investigating

**Comment by c3bryant** [comment]
This is a nice to have, so I am removing the milestone

**Comment by i8wu** [comment]
onMapReady callback seems to have just been added, no release yet..but we should keep an eye out https://github.com/airbnb/react-native-maps/pull/1369

**Comment by i8wu** [comment]
onMapReady has been released in v0.16.0 of react-native-maps
However, we will not be able to upgrade and take advantage of it until react-native has be upgraded as well https://github.com/airbnb/react-native-maps/issues/1473

**Comment by c3bryant** [comment]
@Gulci sending this your way, will you take a look when time permits?

**Comment by Gulci** [comment]
76f34a5 adds functionality to display a tool-tip when a map search result is selected.

**Comment by Gulci** [comment]
Commit 7c01122 resolves an issue with the previous commit where stops would not show up properly when toggling between routes in the map view.

**Comment by c3bryant** [comment]
Merged & verified in dev, closing.
