### ISSUE TITLE
Shuttle Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#946]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-102

This is complete when the Home view contains a shuttle card where:

- [x] User can view the closest shuttle stop information
- [x] User can manage their shuttle stops preference: select, add, remove shuttle stops
- [x] Each shuttle stop information displays upcoming bus arrival times
- [x] Uses the API endpoint https://api-qa.ucsd.edu/store/apis/info?name=CampusShuttles&version=v1.0.0&provider=a6wu#tab1
- [x] Create an API endpoint for SHUTTLE_ROUTES_MASTER: 'https://s3-us-west-2.amazonaws.com/ucsd-its-wts/now_ucsandiego/v1/shuttle_routes_master_map.json',
- [x] Create an API endpoint for SHUTTLE_STOPS_MASTER: 'https://s3-us-west-2.amazonaws.com/ucsd-its-wts/now_ucsandiego/v1/shuttle_stops_master_map.json',
- [x] Create an API endpoint for SHUTTLE_STOPS_MASTER_NO_ROUTES: 'https://s3-us-west-2.amazonaws.com/ucsd-its-wts/now_ucsandiego/v1/shuttle_stops_master_map_no_routes.json',

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561376338393530346235383036626332626336326333342f36393836326139612d393631332d343663662d383061652d323965663339636663343761 (1).png](https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/1758ef33-bfa6-40a5-b714-e671d7fc0fa3)

**Comment by a6wu** [comment]
@gmihir  Is this API in use? https://api-qa.ucsd.edu/store/apis/info?name=ShuttleStops&version=v1.0.0&provider=m9gupta#/default/get__variant_

**Comment by a6wu** [comment]
@gmihir  Can you list out the APIs that were created?

**Comment by c3bryant** [comment]
Added #1016 for shuttle API deployment

**Comment by gmihir** [comment]
API's Used: 

ShuttleStops API (not migrated to WSO2) : https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/3aibfzk3na/resources/g1b462knmf

- This API is also dependent on the grabShuttleInfo lambda: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/grabShuttleInfo?tab=configuration

Also using following endpoint in WSO2: 
https://api-qa.ucsd.edu:8243/shuttles/v1.0.0
