### ISSUE TITLE
Student Home View Bug

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#952]
ITS-Pro time category: MA-34

This is complete when:
- [x] Students do not see the gray box on the home view, which may be an infinite height

<img src="https://user-images.githubusercontent.com/15112294/93350964-05372a80-f7ee-11ea-858f-a96add972b2d.jpg" width="300">

**Comment by c3bryant** [comment]
Resolved on the back-end and reinforced on the mobile app client in #964
