### ISSUE TITLE
iOS 14 Regression Test

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#953]
ITS-Pro time category: MA-38

This is complete when:
- [x] [7.2.8 iOS 14 Regression Test Checklist](https://ucsdcloud-my.sharepoint.com/:x:/r/personal/c3bryant_ucsd_edu/_layouts/15/Doc.aspx?sourcedoc=%7BE7D02BE3-AB07-461B-BCC5-CDA6A8AB70A4%7D&file=7.2.8%20iOS%2014.xlsx) has been completed for iPhone w/ iOS 14
- [x] [7.2.8 iOS 14 Regression Test Checklist](https://ucsdcloud-my.sharepoint.com/:x:/r/personal/c3bryant_ucsd_edu/_layouts/15/Doc.aspx?sourcedoc=%7BE7D02BE3-AB07-461B-BCC5-CDA6A8AB70A4%7D&file=7.2.8%20iOS%2014.xlsx) has been completed for iPad w/ iOS 14

**Comment by c3bryant** [comment]
Notes:
- iOS 14 introduced a default browser setting, which is not supported by Flutter's url_launcher package (https://github.com/flutter/flutter/issues/65936)
- The url_launcher package canLaunch method is only supported on Safari
- The url_launcher package canLaunch method is used to open all external URLs
- The url_launcher is used in several areas: web scanner, info cards, dining, notices, events, news, onboarding, and user profile
- With a default browser other than Safari selected, clicking any external URL does nothing
- Fix applied in PR #963
