### ISSUE TITLE
Web Scanner UI/UX Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#956]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The scan process is optimize for a single hand operation
- [x] The scan is submitted to the API when a scan is recognized
- [x] The user does not need to tap on the Submit button
- [x] The UI presents clear messaging on each step

**Comment by woznaut** [comment]
"The user does not need to tap on the Submit button" - definitely would like to discuss this requirement
