### ISSUE TITLE
MobilePlatform-Messages API Cleanup

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#971]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-60

This is complete when:

- [x] MobilePlatform-Messages API in Prod and QA are in sync
- [x] Have apps subscribe to v1.0.0 in QA
- [x] MobilePlatform-Messages API v2.0.0 in QA is deleted

**Comment by c3bryant** [comment]
A few applications to unsubscribe from MobilePlatform-Messages API v2.0.0 - @g9singh / @i8wu when time permits.
g1singh	DefaultApplication
icwu	MobileReminders
icwu	MobileReminders2

**Comment by i8wu** [comment]
Unsubbed MobileReminders
