### ISSUE TITLE
Info Card Content Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#984]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-97

This is complete when:

- [ ] The info cards display a link to Shuttle, https://ucsdbus.com/map
- [ ] The info cards display a link to Parking, https://maps.ucsd.edu/map/?id=1005#!ce/17201?ct/25239,29254,29255,29256,29257,29258,29263,29264,29265,29266,25238?mc/32.868485887539286,-117.24128723144533?z/14?lvl/0

**Comment by c3bryant** [comment]
Shuttle and Parking links have been added to the Campus Information card for Visitors

Shuttle and Parking links were _not_  added to `COVID-19 Info` cards for Students and Staff. Please advise
