### ISSUE TITLE
MessagingTrigger Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#992]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-60

This is complete when:

- [x] the Firebase Admin SDK and other packages are updated
- [x] the trigger processes only one Record attached to the event
- [x] message send throttled to 20K messages per 15 minutes

See https://sourcecode.ucsd.edu/scm/wts/mobileplatform-notificationmessages.git, /src/messagingCenterTrigger/index.js

**Comment by c3bryant** [comment]
Done on branch `qa`, ready to deploy
- https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse/src/messagingCenterTrigger

Notes:
- Upgraded all packages in `mobileplatform-notificationmessages` on branch `qa`
- Deprecated unused/old code
- Cleaned up mobileplatform-notificationmessages repo
  - Branch `v2` moved to `qa` (default)
  - Branch `master` moved to `prod`
