### ISSUE TITLE
Parking black screen on scroll

### ISSUE THREAD

**Issue by kevdesilva01** [UCSD/campus-mobile#994]
Scrolling through the parking card produces a black/white blank screen and has a delay before rendering the content.[https://app.zenhub.com/files/62921972/8e75fa4d-3759-45a2-83c9-182822073078/download](https://app.zenhub.com/files/62921972/8e75fa4d-3759-45a2-83c9-182822073078/download)

**Comment by a6wu** [comment]
@kevdesilva01  Is this still present in v7.2.12?

**Comment by kevdesilva01** [comment]
@a6wu Im not sure about android, but the issue is not present anymore on iOS devices.

**Comment by c3bryant** [comment]
Resolved in 7.2.12
